-- LEGHEVO v0.62.31
-- Barriera causale certificata dell'avvio competizione provider.
-- Migrazione interna: database/135_provider_competition_start_causal_barrier_safety.sql
-- Eseguire dopo database/134_provider_new_season_bootstrap_barrier_safety.sql.
--
-- L'avvio della competizione viene legato atomicamente al bootstrap provider
-- certificato, all'impronta immutabile del calendario e alla giornata iniziale.
-- Le RPC storiche non possono aggirare la barriera: un trigger ENABLE ALWAYS
-- autorizza il passaggio a started soltanto nel contesto della RPC v4.
-- Eventuali regressioni successive non riaprono la stagione e non riscrivono
-- il certificato: la testa viene marcata affected e la Direzione viene avvisata.

begin;

-- PRE-FLIGHT: la v0.62.30 deve essere installata e integralmente valida.
do $preflight$
declare
  v_integrity jsonb;
  v_missing text[] := array[]::text[];
  v_required text;
begin
  if to_regprocedure('public.get_provider_season_bootstrap_integrity_v1()') is null then
    raise exception
      'Preflight v0.62.31 non superato: manca la diagnostica v0.62.30.';
  end if;

  v_integrity := public.get_provider_season_bootstrap_integrity_v1();
  if (select count(*) from jsonb_each(v_integrity)) <> 20
    or exists(
      select 1
      from jsonb_each(v_integrity) check_row
      where jsonb_typeof(check_row.value) is distinct from 'boolean'
         or check_row.value is distinct from 'true'::jsonb
    ) then
    raise exception
      'Preflight v0.62.31 non superato: la v0.62.30 non è integra.';
  end if;

  foreach v_required in array array[
    'public.leagues',
    'public.fantasy_teams',
    'public.fantasy_fixtures',
    'public.matchdays',
    'public.league_competition_events',
    'public.provider_season_bootstrap_certificates',
    'public.provider_season_bootstrap_heads',
    'public.provider_season_bootstrap_events'
  ] loop
    if to_regclass(v_required) is null then
      v_missing := array_append(v_missing, 'table ' || v_required);
    end if;
  end loop;

  foreach v_required in array array[
    'public.compute_provider_season_bootstrap_gate_v1(uuid)',
    'public.reconcile_provider_season_bootstrap_v1(uuid,boolean)',
    'public.compute_league_calendar_fingerprint(uuid)',
    'public.get_league_competition_integrity_v1(uuid)',
    'public.start_league_competition_guarded_v3(uuid)',
    'public.get_league_season_state_v8(uuid)',
    'public.get_league_management_state_v18(uuid)',
    'public.get_league_provider_sync_health_v29(uuid)',
    'public.is_league_admin(uuid)',
    'public.is_league_member(uuid)'
  ] loop
    if to_regprocedure(v_required) is null then
      v_missing := array_append(v_missing, 'function ' || v_required);
    end if;
  end loop;

  if coalesce(array_length(v_missing, 1), 0) > 0 then
    raise exception 'Preflight v0.62.31 non superato. Dipendenze mancanti: %',
      array_to_string(v_missing, '; ');
  end if;
end;
$preflight$;

create table if not exists public.provider_competition_start_certificates (
  id bigint generated by default as identity primary key,
  league_id uuid not null unique
    references public.leagues(id) on delete restrict,
  bootstrap_certificate_id bigint not null
    references public.provider_season_bootstrap_certificates(id) on delete restrict,
  provider text not null,
  competition_code text not null,
  season integer not null,
  bootstrap_hash text not null,
  provider_fixture_fingerprint text not null,
  calendar_fingerprint text not null,
  opening_matchday_id uuid not null
    references public.matchdays(id) on delete restrict,
  opening_matchday_number smallint not null,
  fantasy_fixture_count integer not null,
  fantasy_matchday_count integer not null,
  fantasy_team_count integer not null,
  competition_started_at timestamptz not null,
  start_hash text not null,
  certified_by uuid references public.profiles(id) on delete set null,
  certified_at timestamptz not null default now(),
  result_payload jsonb not null default '{}'::jsonb,
  constraint provider_competition_start_cert_provider_check
    check(char_length(trim(provider)) between 1 and 100 and provider !~ E'[\r\n]'),
  constraint provider_competition_start_cert_competition_check
    check(competition_code = 'IT-SA'),
  constraint provider_competition_start_cert_season_check
    check(season between 2000 and 2200),
  constraint provider_competition_start_cert_bootstrap_hash_check
    check(bootstrap_hash ~ '^[0-9a-f]{32}$'),
  constraint provider_competition_start_cert_provider_hash_check
    check(provider_fixture_fingerprint ~ '^[0-9a-f]{32}$'),
  constraint provider_competition_start_cert_calendar_hash_check
    check(calendar_fingerprint ~ '^[0-9a-f]{32}$'),
  constraint provider_competition_start_cert_start_hash_check
    check(start_hash ~ '^[0-9a-f]{32}$'),
  constraint provider_competition_start_cert_matchday_check
    check(opening_matchday_number > 0),
  constraint provider_competition_start_cert_counts_check
    check(fantasy_fixture_count > 0 and fantasy_matchday_count > 0
      and fantasy_team_count >= 2),
  constraint provider_competition_start_cert_payload_check
    check(jsonb_typeof(result_payload) = 'object')
);

create table if not exists public.provider_competition_start_heads (
  league_id uuid primary key references public.leagues(id) on delete restrict,
  certificate_id bigint unique
    references public.provider_competition_start_certificates(id) on delete restrict,
  start_status text not null,
  reason_code text not null,
  observed_season integer,
  observed_bootstrap_certificate_id bigint,
  observed_bootstrap_hash text,
  observed_provider_fixture_fingerprint text,
  observed_calendar_fingerprint text,
  observed_opening_matchday_id uuid,
  observed_opening_matchday_number smallint,
  observed_fantasy_fixture_count integer not null default 0,
  observed_fantasy_matchday_count integer not null default 0,
  observed_fantasy_team_count integer not null default 0,
  ever_affected boolean not null default false,
  first_affected_at timestamptz,
  last_assessed_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint provider_competition_start_heads_status_check
    check(start_status in ('waiting','ready','official','affected')),
  constraint provider_competition_start_heads_reason_check
    check(char_length(trim(reason_code)) between 3 and 180),
  constraint provider_competition_start_heads_season_check
    check(observed_season is null or observed_season between 2000 and 2200),
  constraint provider_competition_start_heads_bootstrap_hash_check
    check(observed_bootstrap_hash is null
      or observed_bootstrap_hash ~ '^[0-9a-f]{32}$'),
  constraint provider_competition_start_heads_provider_hash_check
    check(observed_provider_fixture_fingerprint is null
      or observed_provider_fixture_fingerprint ~ '^[0-9a-f]{32}$'),
  constraint provider_competition_start_heads_calendar_hash_check
    check(observed_calendar_fingerprint is null
      or observed_calendar_fingerprint ~ '^[0-9a-f]{32}$'),
  constraint provider_competition_start_heads_matchday_check
    check(observed_opening_matchday_number is null
      or observed_opening_matchday_number > 0),
  constraint provider_competition_start_heads_counts_check
    check(observed_fantasy_fixture_count >= 0
      and observed_fantasy_matchday_count >= 0
      and observed_fantasy_team_count >= 0),
  constraint provider_competition_start_heads_affected_check
    check((not ever_affected and first_affected_at is null)
      or (ever_affected and first_affected_at is not null)),
  constraint provider_competition_start_heads_state_check
    check(
      (start_status in ('waiting','ready') and certificate_id is null)
      or (start_status = 'official' and certificate_id is not null)
      or (start_status = 'affected')
    )
);

create table if not exists public.provider_competition_start_events (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete restrict,
  certificate_id bigint
    references public.provider_competition_start_certificates(id) on delete restrict,
  event_type text not null,
  start_status text not null,
  reason_code text not null,
  observed_season integer,
  observed_bootstrap_certificate_id bigint,
  observed_bootstrap_hash text,
  observed_provider_fixture_fingerprint text,
  observed_calendar_fingerprint text,
  observed_opening_matchday_id uuid,
  observed_opening_matchday_number smallint,
  observed_fantasy_fixture_count integer not null,
  observed_fantasy_matchday_count integer not null,
  observed_fantasy_team_count integer not null,
  event_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint provider_competition_start_events_type_check
    check(event_type in ('waiting','ready','certified','affected','revalidated')),
  constraint provider_competition_start_events_status_check
    check(start_status in ('waiting','ready','official','affected')),
  constraint provider_competition_start_events_reason_check
    check(char_length(trim(reason_code)) between 3 and 180),
  constraint provider_competition_start_events_season_check
    check(observed_season is null or observed_season between 2000 and 2200),
  constraint provider_competition_start_events_bootstrap_hash_check
    check(observed_bootstrap_hash is null
      or observed_bootstrap_hash ~ '^[0-9a-f]{32}$'),
  constraint provider_competition_start_events_provider_hash_check
    check(observed_provider_fixture_fingerprint is null
      or observed_provider_fixture_fingerprint ~ '^[0-9a-f]{32}$'),
  constraint provider_competition_start_events_calendar_hash_check
    check(observed_calendar_fingerprint is null
      or observed_calendar_fingerprint ~ '^[0-9a-f]{32}$'),
  constraint provider_competition_start_events_counts_check
    check(observed_fantasy_fixture_count >= 0
      and observed_fantasy_matchday_count >= 0
      and observed_fantasy_team_count >= 0),
  constraint provider_competition_start_events_payload_check
    check(jsonb_typeof(event_payload) = 'object')
);

create index if not exists provider_competition_start_certificates_created_idx
  on public.provider_competition_start_certificates(league_id, certified_at desc);
create index if not exists provider_competition_start_heads_status_idx
  on public.provider_competition_start_heads(start_status, updated_at desc);
create index if not exists provider_competition_start_events_league_idx
  on public.provider_competition_start_events(league_id, created_at desc, id desc);

alter table public.provider_competition_start_certificates enable row level security;
alter table public.provider_competition_start_heads enable row level security;
alter table public.provider_competition_start_events enable row level security;
alter table public.provider_competition_start_events replica identity full;

revoke all on public.provider_competition_start_certificates
from public, anon, authenticated, service_role;
revoke all on public.provider_competition_start_heads
from public, anon, authenticated, service_role;
revoke all on public.provider_competition_start_events
from public, anon, authenticated, service_role;
grant select on public.provider_competition_start_certificates to authenticated;
grant select on public.provider_competition_start_heads to authenticated;
grant select on public.provider_competition_start_events to authenticated;

drop policy if exists provider_competition_start_certificates_member_select
on public.provider_competition_start_certificates;
create policy provider_competition_start_certificates_member_select
on public.provider_competition_start_certificates
for select to authenticated
using(public.is_league_member(league_id) or public.is_league_admin(league_id));

drop policy if exists provider_competition_start_heads_member_select
on public.provider_competition_start_heads;
create policy provider_competition_start_heads_member_select
on public.provider_competition_start_heads
for select to authenticated
using(public.is_league_member(league_id) or public.is_league_admin(league_id));

drop policy if exists provider_competition_start_events_member_select
on public.provider_competition_start_events;
create policy provider_competition_start_events_member_select
on public.provider_competition_start_events
for select to authenticated
using(public.is_league_member(league_id) or public.is_league_admin(league_id));

create or replace function public.prevent_provider_competition_start_immutable_v1()
returns trigger language plpgsql security definer set search_path = '' as $function$
begin
  raise exception 'Registro certificato dell''avvio competizione immutabile.';
end;
$function$;
revoke all on function public.prevent_provider_competition_start_immutable_v1()
from public, anon, authenticated, service_role;

create or replace function public.guard_provider_competition_start_writes_v1()
returns trigger language plpgsql security definer set search_path = '' as $function$
begin
  if coalesce(current_setting('leghevo.provider_competition_start_context', true), '') <> 'on' then
    raise exception 'Scrittura avvio provider consentita solo alle RPC certificate.';
  end if;
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$function$;
revoke all on function public.guard_provider_competition_start_writes_v1()
from public, anon, authenticated, service_role;

drop trigger if exists provider_competition_start_certificates_immutable
on public.provider_competition_start_certificates;
create trigger provider_competition_start_certificates_immutable
before update or delete on public.provider_competition_start_certificates
for each row execute function public.prevent_provider_competition_start_immutable_v1();
alter table public.provider_competition_start_certificates
  enable always trigger provider_competition_start_certificates_immutable;

drop trigger if exists provider_competition_start_events_immutable
on public.provider_competition_start_events;
create trigger provider_competition_start_events_immutable
before update or delete on public.provider_competition_start_events
for each row execute function public.prevent_provider_competition_start_immutable_v1();
alter table public.provider_competition_start_events
  enable always trigger provider_competition_start_events_immutable;

drop trigger if exists provider_competition_start_certificates_insert_guard
on public.provider_competition_start_certificates;
create trigger provider_competition_start_certificates_insert_guard
before insert on public.provider_competition_start_certificates
for each row execute function public.guard_provider_competition_start_writes_v1();
alter table public.provider_competition_start_certificates
  enable always trigger provider_competition_start_certificates_insert_guard;

drop trigger if exists provider_competition_start_heads_write_guard
on public.provider_competition_start_heads;
create trigger provider_competition_start_heads_write_guard
before insert or update or delete on public.provider_competition_start_heads
for each row execute function public.guard_provider_competition_start_writes_v1();
alter table public.provider_competition_start_heads
  enable always trigger provider_competition_start_heads_write_guard;

drop trigger if exists provider_competition_start_events_insert_guard
on public.provider_competition_start_events;
create trigger provider_competition_start_events_insert_guard
before insert on public.provider_competition_start_events
for each row execute function public.guard_provider_competition_start_writes_v1();
alter table public.provider_competition_start_events
  enable always trigger provider_competition_start_events_insert_guard;

create or replace function public.compute_provider_competition_start_hash_v1(
  p_league_id uuid,
  p_bootstrap_certificate_id bigint,
  p_bootstrap_hash text,
  p_provider_fixture_fingerprint text,
  p_calendar_fingerprint text,
  p_opening_matchday_id uuid,
  p_opening_matchday_number smallint,
  p_fantasy_fixture_count integer,
  p_fantasy_matchday_count integer,
  p_fantasy_team_count integer,
  p_competition_started_at timestamptz
)
returns text language sql immutable set search_path = '' as $function$
  select md5(concat_ws('|',
    p_league_id::text,
    p_bootstrap_certificate_id::text,
    p_bootstrap_hash,
    p_provider_fixture_fingerprint,
    p_calendar_fingerprint,
    p_opening_matchday_id::text,
    p_opening_matchday_number::text,
    p_fantasy_fixture_count::text,
    p_fantasy_matchday_count::text,
    p_fantasy_team_count::text,
    to_char(p_competition_started_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US')
  ));
$function$;
revoke all on function public.compute_provider_competition_start_hash_v1(
  uuid,bigint,text,text,text,uuid,smallint,integer,integer,integer,timestamptz
) from public, anon, authenticated;
grant execute on function public.compute_provider_competition_start_hash_v1(
  uuid,bigint,text,text,text,uuid,smallint,integer,integer,integer,timestamptz
) to service_role;

create or replace function public.compute_provider_competition_start_gate_v1(
  p_league_id uuid,
  p_ignore_missing_certificate boolean default false
)
returns jsonb language plpgsql stable security definer set search_path = '' as $function$
declare
  v_league public.leagues%rowtype;
  v_bootstrap jsonb;
  v_bootstrap_certificate public.provider_season_bootstrap_certificates%rowtype;
  v_certificate public.provider_competition_start_certificates%rowtype;
  v_fixture_count integer := 0;
  v_matchday_count integer := 0;
  v_team_count integer := 0;
  v_scope_issue_count integer := 0;
  v_opening_matchday_id uuid;
  v_opening_matchday_number smallint;
  v_opening_matchday_valid boolean := false;
  v_calendar_fingerprint text;
  v_status text := 'waiting';
  v_reason text := 'provider_competition_start.waiting';
  v_applicable boolean := false;
  v_bootstrap_ready boolean := false;
  v_calendar_ready boolean := false;
  v_model_ready boolean := false;
  v_started boolean := false;
  v_healthy boolean := true;
  v_affected boolean := false;
  v_expected_hash text;
begin
  select league.* into v_league
  from public.leagues league
  where league.id = p_league_id;

  if not found then
    return jsonb_build_object(
      'available', false,
      'applicable', false,
      'protected', true,
      'healthy', false,
      'affected', true,
      'status', 'affected',
      'reasonCode', 'provider_competition_start.league_missing'
    );
  end if;

  v_started := v_league.competition_started_at is not null;
  v_bootstrap := public.compute_provider_season_bootstrap_gate_v1(p_league_id);
  v_applicable := coalesce((v_bootstrap ->> 'applicable')::boolean, false);

  if not v_applicable then
    return jsonb_build_object(
      'available', true,
      'applicable', false,
      'protected', true,
      'healthy', true,
      'affected', false,
      'status', case when v_started then 'official' else 'ready' end,
      'reasonCode', 'provider_competition_start.not_required',
      'started', v_started,
      'certified', false,
      'certificateId', null,
      'bootstrap', v_bootstrap
    );
  end if;

  select certificate.* into v_bootstrap_certificate
  from public.provider_season_bootstrap_certificates certificate
  where certificate.league_id = p_league_id;

  select certificate.* into v_certificate
  from public.provider_competition_start_certificates certificate
  where certificate.league_id = p_league_id;

  select
    count(*)::integer,
    count(distinct fixture.matchday_id)::integer
  into v_fixture_count, v_matchday_count
  from public.fantasy_fixtures fixture
  where fixture.league_id = p_league_id;

  select count(*)::integer into v_team_count
  from public.fantasy_teams team
  where team.league_id = p_league_id;

  select count(*)::integer into v_scope_issue_count
  from public.fantasy_fixtures fixture
  join public.matchdays matchday on matchday.id = fixture.matchday_id
  where fixture.league_id = p_league_id
    and (
      matchday.competition_code <> 'IT-SA'
      or matchday.season is distinct from v_league.calendar_season
    );

  if v_started then
    select event.matchday_id,
      nullif(event.payload ->> 'matchdayNumber', '')::smallint
    into v_opening_matchday_id, v_opening_matchday_number
    from public.league_competition_events event
    where event.league_id = p_league_id
      and event.dedupe_key = 'competition-opening:v1'
    limit 1;
  end if;

  if v_opening_matchday_id is null then
    select matchday.id, matchday.number
    into v_opening_matchday_id, v_opening_matchday_number
    from public.fantasy_fixtures fixture
    join public.matchdays matchday on matchday.id = fixture.matchday_id
    where fixture.league_id = p_league_id
    group by matchday.id, matchday.number, matchday.starts_at
    order by matchday.number, matchday.starts_at, matchday.id
    limit 1;
  end if;

  v_opening_matchday_valid := v_opening_matchday_id is not null
    and exists(
      select 1
      from public.fantasy_fixtures fixture
      join public.matchdays matchday on matchday.id = fixture.matchday_id
      where fixture.league_id = p_league_id
        and fixture.matchday_id = v_opening_matchday_id
        and matchday.number = v_opening_matchday_number
        and matchday.competition_code = 'IT-SA'
        and matchday.season = v_league.calendar_season
    );

  v_calendar_fingerprint := public.compute_league_calendar_fingerprint(p_league_id);
  v_bootstrap_ready := coalesce((v_bootstrap ->> 'certified')::boolean, false)
    and coalesce(v_bootstrap ->> 'status', 'waiting') = 'ready'
    and coalesce((v_bootstrap ->> 'healthy')::boolean, false)
    and not coalesce((v_bootstrap ->> 'affected')::boolean, false)
    and v_bootstrap_certificate.id is not null
    and v_bootstrap_certificate.bootstrap_hash = v_bootstrap ->> 'bootstrapHash';

  v_model_ready := not v_started or (
    v_league.competition_model_closed_at is not null
    and v_league.competition_opening_verified_at is not null
    and v_league.competition_calendar_fingerprint = v_calendar_fingerprint
  );

  v_calendar_ready := v_fixture_count > 0
    and v_matchday_count > 0
    and v_team_count >= 2
    and v_scope_issue_count = 0
    and v_opening_matchday_valid
    and v_calendar_fingerprint ~ '^[0-9a-f]{32}$'
    and coalesce(v_league.calendar_expected_fixture_count, v_fixture_count) = v_fixture_count
    and coalesce(v_league.calendar_expected_matchday_count, v_matchday_count) = v_matchday_count
    and (
      v_league.competition_calendar_fingerprint is null
      or v_league.competition_calendar_fingerprint = v_calendar_fingerprint
    )
    and v_model_ready;

  if not v_bootstrap_ready then
    v_status := case
      when coalesce((v_bootstrap ->> 'affected')::boolean, false)
        then 'affected'
      else 'waiting'
    end;
    v_reason := case
      when coalesce((v_bootstrap ->> 'affected')::boolean, false)
        then 'provider_competition_start.bootstrap_affected'
      else 'provider_competition_start.bootstrap_not_ready'
    end;
  elsif not v_calendar_ready then
    v_status := case when v_started then 'affected' else 'waiting' end;
    v_reason := case
      when v_scope_issue_count > 0
        then 'provider_competition_start.calendar_scope_mismatch'
      when not v_opening_matchday_valid
        then 'provider_competition_start.opening_matchday_invalid'
      when not v_model_ready
        then 'provider_competition_start.competition_model_not_closed'
      when v_league.competition_calendar_fingerprint is not null
        and v_league.competition_calendar_fingerprint <> v_calendar_fingerprint
        then 'provider_competition_start.calendar_fingerprint_changed'
      else 'provider_competition_start.calendar_not_ready'
    end;
  elsif not v_started then
    v_status := 'ready';
    v_reason := 'provider_competition_start.ready';
  elsif v_certificate.id is null then
    if p_ignore_missing_certificate then
      v_status := 'ready';
      v_reason := 'provider_competition_start.historical_start_adoptable';
    else
      v_status := 'affected';
      v_reason := 'provider_competition_start.certificate_missing';
    end if;
  else
    v_expected_hash := public.compute_provider_competition_start_hash_v1(
      p_league_id,
      v_certificate.bootstrap_certificate_id,
      v_certificate.bootstrap_hash,
      v_certificate.provider_fixture_fingerprint,
      v_certificate.calendar_fingerprint,
      v_certificate.opening_matchday_id,
      v_certificate.opening_matchday_number,
      v_certificate.fantasy_fixture_count,
      v_certificate.fantasy_matchday_count,
      v_certificate.fantasy_team_count,
      v_certificate.competition_started_at
    );

    if v_certificate.start_hash <> v_expected_hash then
      v_status := 'affected';
      v_reason := 'provider_competition_start.certificate_hash_invalid';
    elsif v_certificate.bootstrap_certificate_id <> v_bootstrap_certificate.id
      or v_certificate.bootstrap_hash <> v_bootstrap_certificate.bootstrap_hash then
      v_status := 'affected';
      v_reason := 'provider_competition_start.bootstrap_lineage_changed';
    elsif v_certificate.provider_fixture_fingerprint
      <> v_bootstrap_certificate.fixture_fingerprint then
      v_status := 'affected';
      v_reason := 'provider_competition_start.provider_scope_changed';
    elsif v_certificate.calendar_fingerprint <> v_calendar_fingerprint then
      v_status := 'affected';
      v_reason := 'provider_competition_start.calendar_fingerprint_changed';
    elsif v_certificate.opening_matchday_id <> v_opening_matchday_id
      or v_certificate.opening_matchday_number <> v_opening_matchday_number then
      v_status := 'affected';
      v_reason := 'provider_competition_start.opening_matchday_changed';
    elsif v_certificate.fantasy_fixture_count <> v_fixture_count
      or v_certificate.fantasy_matchday_count <> v_matchday_count
      or v_certificate.fantasy_team_count <> v_team_count then
      v_status := 'affected';
      v_reason := 'provider_competition_start.competition_structure_changed';
    elsif v_certificate.competition_started_at <> v_league.competition_started_at then
      v_status := 'affected';
      v_reason := 'provider_competition_start.started_at_changed';
    else
      v_status := 'official';
      v_reason := 'provider_competition_start.certified';
    end if;
  end if;

  v_affected := v_status = 'affected';
  v_healthy := not v_affected;

  return jsonb_build_object(
    'available', true,
    'applicable', true,
    'protected', true,
    'healthy', v_healthy,
    'affected', v_affected,
    'status', v_status,
    'reasonCode', v_reason,
    'started', v_started,
    'certified', v_certificate.id is not null and v_status = 'official',
    'certificateId', v_certificate.id,
    'startHash', v_certificate.start_hash,
    'season', case when coalesce(v_league.calendar_season, '') ~ '^[0-9]{4}$'
      then v_league.calendar_season::integer else null end,
    'bootstrapCertificateId', v_bootstrap_certificate.id,
    'bootstrapHash', v_bootstrap_certificate.bootstrap_hash,
    'provider', v_bootstrap_certificate.provider,
    'providerFixtureFingerprint', v_bootstrap_certificate.fixture_fingerprint,
    'calendarFingerprint', v_calendar_fingerprint,
    'openingMatchdayId', v_opening_matchday_id,
    'openingMatchdayNumber', v_opening_matchday_number,
    'fantasyFixtureCount', v_fixture_count,
    'fantasyMatchdayCount', v_matchday_count,
    'fantasyTeamCount', v_team_count,
    'calendarScopeIssueCount', v_scope_issue_count,
    'openingMatchdayValid', v_opening_matchday_valid,
    'bootstrapReady', v_bootstrap_ready,
    'calendarReady', v_calendar_ready,
    'competitionModelReady', v_model_ready,
    'competitionStartedAt', v_league.competition_started_at,
    'bootstrap', v_bootstrap
  );
end;
$function$;
revoke all on function public.compute_provider_competition_start_gate_v1(uuid,boolean)
from public, anon, authenticated;
grant execute on function public.compute_provider_competition_start_gate_v1(uuid,boolean)
to service_role;

create or replace function public.certify_provider_competition_start_v1(
  p_league_id uuid
)
returns jsonb language plpgsql security definer set search_path = '' as $function$
declare
  v_gate jsonb;
  v_existing public.provider_competition_start_certificates%rowtype;
  v_bootstrap_certificate public.provider_season_bootstrap_certificates%rowtype;
  v_certificate_id bigint;
  v_start_hash text;
  v_payload jsonb;
begin
  if auth.uid() is not null and not(
    public.is_league_admin(p_league_id)
    or exists(
      select 1 from public.leagues league
      where league.id = p_league_id and league.owner_id = auth.uid()
    )
  ) then
    raise exception 'Solo la Direzione può certificare l''avvio competizione.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'league-season-rollover-lineage:' || p_league_id::text, 0));
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'provider-new-season-bootstrap:' || p_league_id::text, 0));
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'competition:' || p_league_id::text, 0));
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'provider-competition-start:' || p_league_id::text, 0));

  select certificate.* into v_existing
  from public.provider_competition_start_certificates certificate
  where certificate.league_id = p_league_id;

  if found then
    return public.compute_provider_competition_start_gate_v1(p_league_id, false);
  end if;

  v_gate := public.compute_provider_competition_start_gate_v1(p_league_id, true);
  if not coalesce((v_gate ->> 'applicable')::boolean, false) then
    return v_gate;
  end if;
  if not coalesce((v_gate ->> 'started')::boolean, false)
    or coalesce(v_gate ->> 'status', 'waiting') <> 'ready'
    or not coalesce((v_gate ->> 'bootstrapReady')::boolean, false)
    or not coalesce((v_gate ->> 'calendarReady')::boolean, false) then
    raise exception 'Avvio competizione non certificabile [%].',
      v_gate ->> 'reasonCode';
  end if;

  select certificate.* into strict v_bootstrap_certificate
  from public.provider_season_bootstrap_certificates certificate
  where certificate.id = (v_gate ->> 'bootstrapCertificateId')::bigint
    and certificate.league_id = p_league_id;

  v_start_hash := public.compute_provider_competition_start_hash_v1(
    p_league_id,
    v_bootstrap_certificate.id,
    v_bootstrap_certificate.bootstrap_hash,
    v_bootstrap_certificate.fixture_fingerprint,
    v_gate ->> 'calendarFingerprint',
    (v_gate ->> 'openingMatchdayId')::uuid,
    (v_gate ->> 'openingMatchdayNumber')::smallint,
    (v_gate ->> 'fantasyFixtureCount')::integer,
    (v_gate ->> 'fantasyMatchdayCount')::integer,
    (v_gate ->> 'fantasyTeamCount')::integer,
    (v_gate ->> 'competitionStartedAt')::timestamptz
  );

  v_certificate_id := pg_catalog.nextval(pg_catalog.pg_get_serial_sequence(
    'public.provider_competition_start_certificates', 'id')::regclass);
  v_payload := v_gate || jsonb_build_object(
    'status', 'official',
    'reasonCode', 'provider_competition_start.certified',
    'certified', true,
    'certificateId', v_certificate_id,
    'startHash', v_start_hash,
    'certifiedAt', now()
  );

  perform set_config('leghevo.provider_competition_start_context', 'on', true);
  insert into public.provider_competition_start_certificates(
    id, league_id, bootstrap_certificate_id, provider, competition_code,
    season, bootstrap_hash, provider_fixture_fingerprint,
    calendar_fingerprint, opening_matchday_id, opening_matchday_number,
    fantasy_fixture_count, fantasy_matchday_count, fantasy_team_count,
    competition_started_at, start_hash, certified_by, result_payload
  ) values(
    v_certificate_id,
    p_league_id,
    v_bootstrap_certificate.id,
    v_bootstrap_certificate.provider,
    v_bootstrap_certificate.competition_code,
    v_bootstrap_certificate.season,
    v_bootstrap_certificate.bootstrap_hash,
    v_bootstrap_certificate.fixture_fingerprint,
    v_gate ->> 'calendarFingerprint',
    (v_gate ->> 'openingMatchdayId')::uuid,
    (v_gate ->> 'openingMatchdayNumber')::smallint,
    (v_gate ->> 'fantasyFixtureCount')::integer,
    (v_gate ->> 'fantasyMatchdayCount')::integer,
    (v_gate ->> 'fantasyTeamCount')::integer,
    (v_gate ->> 'competitionStartedAt')::timestamptz,
    v_start_hash,
    auth.uid(),
    v_payload
  );

  insert into public.provider_competition_start_heads(
    league_id, certificate_id, start_status, reason_code,
    observed_season, observed_bootstrap_certificate_id,
    observed_bootstrap_hash, observed_provider_fixture_fingerprint,
    observed_calendar_fingerprint, observed_opening_matchday_id,
    observed_opening_matchday_number, observed_fantasy_fixture_count,
    observed_fantasy_matchday_count, observed_fantasy_team_count,
    ever_affected, first_affected_at, last_assessed_at, updated_at
  ) values(
    p_league_id, v_certificate_id, 'official',
    'provider_competition_start.certified',
    (v_gate ->> 'season')::integer,
    v_bootstrap_certificate.id,
    v_bootstrap_certificate.bootstrap_hash,
    v_bootstrap_certificate.fixture_fingerprint,
    v_gate ->> 'calendarFingerprint',
    (v_gate ->> 'openingMatchdayId')::uuid,
    (v_gate ->> 'openingMatchdayNumber')::smallint,
    (v_gate ->> 'fantasyFixtureCount')::integer,
    (v_gate ->> 'fantasyMatchdayCount')::integer,
    (v_gate ->> 'fantasyTeamCount')::integer,
    false, null, now(), now()
  ) on conflict(league_id) do update set
    certificate_id = excluded.certificate_id,
    start_status = 'official',
    reason_code = 'provider_competition_start.certified',
    observed_season = excluded.observed_season,
    observed_bootstrap_certificate_id = excluded.observed_bootstrap_certificate_id,
    observed_bootstrap_hash = excluded.observed_bootstrap_hash,
    observed_provider_fixture_fingerprint = excluded.observed_provider_fixture_fingerprint,
    observed_calendar_fingerprint = excluded.observed_calendar_fingerprint,
    observed_opening_matchday_id = excluded.observed_opening_matchday_id,
    observed_opening_matchday_number = excluded.observed_opening_matchday_number,
    observed_fantasy_fixture_count = excluded.observed_fantasy_fixture_count,
    observed_fantasy_matchday_count = excluded.observed_fantasy_matchday_count,
    observed_fantasy_team_count = excluded.observed_fantasy_team_count,
    last_assessed_at = now(),
    updated_at = now();

  insert into public.provider_competition_start_events(
    league_id, certificate_id, event_type, start_status, reason_code,
    observed_season, observed_bootstrap_certificate_id,
    observed_bootstrap_hash, observed_provider_fixture_fingerprint,
    observed_calendar_fingerprint, observed_opening_matchday_id,
    observed_opening_matchday_number, observed_fantasy_fixture_count,
    observed_fantasy_matchday_count, observed_fantasy_team_count,
    event_payload
  ) values(
    p_league_id, v_certificate_id, 'certified', 'official',
    'provider_competition_start.certified',
    (v_gate ->> 'season')::integer,
    v_bootstrap_certificate.id,
    v_bootstrap_certificate.bootstrap_hash,
    v_bootstrap_certificate.fixture_fingerprint,
    v_gate ->> 'calendarFingerprint',
    (v_gate ->> 'openingMatchdayId')::uuid,
    (v_gate ->> 'openingMatchdayNumber')::smallint,
    (v_gate ->> 'fantasyFixtureCount')::integer,
    (v_gate ->> 'fantasyMatchdayCount')::integer,
    (v_gate ->> 'fantasyTeamCount')::integer,
    v_payload
  );
  perform set_config('leghevo.provider_competition_start_context', '', true);

  return v_payload;
end;
$function$;
revoke all on function public.certify_provider_competition_start_v1(uuid)
from public, anon;
grant execute on function public.certify_provider_competition_start_v1(uuid)
to authenticated, service_role;

create or replace function public.reconcile_provider_competition_start_v1(
  p_league_id uuid,
  p_auto_certify boolean default true
)
returns jsonb language plpgsql security definer set search_path = '' as $function$
declare
  v_gate jsonb;
  v_head public.provider_competition_start_heads%rowtype;
  v_status text;
  v_reason text;
  v_certificate_id bigint;
  v_event_type text;
  v_changed boolean := true;
  v_ever_affected boolean;
  v_first_affected_at timestamptz;
  v_candidate jsonb;
begin
  if p_auto_certify then
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
      'league-season-rollover-lineage:' || p_league_id::text, 0));
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
      'provider-new-season-bootstrap:' || p_league_id::text, 0));
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
      'competition:' || p_league_id::text, 0));
  end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'provider-competition-start:' || p_league_id::text, 0));

  v_gate := public.compute_provider_competition_start_gate_v1(p_league_id, false);
  if not coalesce((v_gate ->> 'applicable')::boolean, false) then
    return v_gate;
  end if;

  if p_auto_certify
    and coalesce((v_gate ->> 'started')::boolean, false)
    and nullif(v_gate ->> 'certificateId', '') is null then
    v_candidate := public.compute_provider_competition_start_gate_v1(
      p_league_id, true);
    if coalesce(v_candidate ->> 'status', 'waiting') = 'ready' then
      return public.certify_provider_competition_start_v1(p_league_id);
    end if;
  end if;

  v_status := coalesce(v_gate ->> 'status', 'waiting');
  v_reason := coalesce(v_gate ->> 'reasonCode',
    'provider_competition_start.waiting');
  v_certificate_id := nullif(v_gate ->> 'certificateId', '')::bigint;

  select head.* into v_head
  from public.provider_competition_start_heads head
  where head.league_id = p_league_id
  for update;

  if found then
    v_changed := v_head.start_status is distinct from v_status
      or v_head.reason_code is distinct from v_reason
      or v_head.certificate_id is distinct from v_certificate_id
      or v_head.observed_bootstrap_certificate_id is distinct from
        nullif(v_gate ->> 'bootstrapCertificateId', '')::bigint
      or v_head.observed_bootstrap_hash is distinct from v_gate ->> 'bootstrapHash'
      or v_head.observed_provider_fixture_fingerprint is distinct from
        v_gate ->> 'providerFixtureFingerprint'
      or v_head.observed_calendar_fingerprint is distinct from
        v_gate ->> 'calendarFingerprint'
      or v_head.observed_opening_matchday_id is distinct from
        nullif(v_gate ->> 'openingMatchdayId', '')::uuid
      or v_head.observed_opening_matchday_number is distinct from
        nullif(v_gate ->> 'openingMatchdayNumber', '')::smallint
      or v_head.observed_fantasy_fixture_count is distinct from
        coalesce((v_gate ->> 'fantasyFixtureCount')::integer, 0)
      or v_head.observed_fantasy_matchday_count is distinct from
        coalesce((v_gate ->> 'fantasyMatchdayCount')::integer, 0)
      or v_head.observed_fantasy_team_count is distinct from
        coalesce((v_gate ->> 'fantasyTeamCount')::integer, 0);
  end if;

  if not v_changed then
    return v_gate || jsonb_build_object(
      'everAffected', v_head.ever_affected,
      'firstAffectedAt', v_head.first_affected_at
    );
  end if;

  v_ever_affected := coalesce(v_head.ever_affected, false)
    or v_status = 'affected';
  v_first_affected_at := case
    when coalesce(v_head.ever_affected, false) then v_head.first_affected_at
    when v_status = 'affected' then now()
    else null
  end;

  v_event_type := case
    when v_status = 'affected' then 'affected'
    when coalesce(v_head.start_status, '') = 'affected'
      and v_status in ('ready','official') then 'revalidated'
    when v_status = 'official' then 'certified'
    when v_status = 'ready' then 'ready'
    else 'waiting'
  end;

  perform set_config('leghevo.provider_competition_start_context', 'on', true);
  insert into public.provider_competition_start_heads(
    league_id, certificate_id, start_status, reason_code,
    observed_season, observed_bootstrap_certificate_id,
    observed_bootstrap_hash, observed_provider_fixture_fingerprint,
    observed_calendar_fingerprint, observed_opening_matchday_id,
    observed_opening_matchday_number, observed_fantasy_fixture_count,
    observed_fantasy_matchday_count, observed_fantasy_team_count,
    ever_affected, first_affected_at, last_assessed_at, updated_at
  ) values(
    p_league_id, v_certificate_id, v_status, v_reason,
    nullif(v_gate ->> 'season', '')::integer,
    nullif(v_gate ->> 'bootstrapCertificateId', '')::bigint,
    v_gate ->> 'bootstrapHash',
    v_gate ->> 'providerFixtureFingerprint',
    v_gate ->> 'calendarFingerprint',
    nullif(v_gate ->> 'openingMatchdayId', '')::uuid,
    nullif(v_gate ->> 'openingMatchdayNumber', '')::smallint,
    coalesce((v_gate ->> 'fantasyFixtureCount')::integer, 0),
    coalesce((v_gate ->> 'fantasyMatchdayCount')::integer, 0),
    coalesce((v_gate ->> 'fantasyTeamCount')::integer, 0),
    v_ever_affected, v_first_affected_at, now(), now()
  ) on conflict(league_id) do update set
    certificate_id = excluded.certificate_id,
    start_status = excluded.start_status,
    reason_code = excluded.reason_code,
    observed_season = excluded.observed_season,
    observed_bootstrap_certificate_id = excluded.observed_bootstrap_certificate_id,
    observed_bootstrap_hash = excluded.observed_bootstrap_hash,
    observed_provider_fixture_fingerprint = excluded.observed_provider_fixture_fingerprint,
    observed_calendar_fingerprint = excluded.observed_calendar_fingerprint,
    observed_opening_matchday_id = excluded.observed_opening_matchday_id,
    observed_opening_matchday_number = excluded.observed_opening_matchday_number,
    observed_fantasy_fixture_count = excluded.observed_fantasy_fixture_count,
    observed_fantasy_matchday_count = excluded.observed_fantasy_matchday_count,
    observed_fantasy_team_count = excluded.observed_fantasy_team_count,
    ever_affected = excluded.ever_affected,
    first_affected_at = excluded.first_affected_at,
    last_assessed_at = now(),
    updated_at = now();

  insert into public.provider_competition_start_events(
    league_id, certificate_id, event_type, start_status, reason_code,
    observed_season, observed_bootstrap_certificate_id,
    observed_bootstrap_hash, observed_provider_fixture_fingerprint,
    observed_calendar_fingerprint, observed_opening_matchday_id,
    observed_opening_matchday_number, observed_fantasy_fixture_count,
    observed_fantasy_matchday_count, observed_fantasy_team_count,
    event_payload
  ) values(
    p_league_id, v_certificate_id, v_event_type, v_status, v_reason,
    nullif(v_gate ->> 'season', '')::integer,
    nullif(v_gate ->> 'bootstrapCertificateId', '')::bigint,
    v_gate ->> 'bootstrapHash',
    v_gate ->> 'providerFixtureFingerprint',
    v_gate ->> 'calendarFingerprint',
    nullif(v_gate ->> 'openingMatchdayId', '')::uuid,
    nullif(v_gate ->> 'openingMatchdayNumber', '')::smallint,
    coalesce((v_gate ->> 'fantasyFixtureCount')::integer, 0),
    coalesce((v_gate ->> 'fantasyMatchdayCount')::integer, 0),
    coalesce((v_gate ->> 'fantasyTeamCount')::integer, 0),
    jsonb_build_object('assessment', v_gate,
      'everAffected', v_ever_affected,
      'firstAffectedAt', v_first_affected_at)
  );
  perform set_config('leghevo.provider_competition_start_context', '', true);

  return v_gate || jsonb_build_object(
    'everAffected', v_ever_affected,
    'firstAffectedAt', v_first_affected_at
  );
end;
$function$;
revoke all on function public.reconcile_provider_competition_start_v1(uuid,boolean)
from public, anon, authenticated;
grant execute on function public.reconcile_provider_competition_start_v1(uuid,boolean)
to service_role;

create or replace function public.get_league_provider_competition_start_v1(
  p_league_id uuid
)
returns jsonb language plpgsql stable security definer set search_path = '' as $function$
declare
  v_gate jsonb;
  v_head public.provider_competition_start_heads%rowtype;
begin
  if not(public.is_league_member(p_league_id) or public.is_league_admin(p_league_id)) then
    raise exception 'Non puoi consultare la certificazione di avvio di questa lega.';
  end if;

  v_gate := public.compute_provider_competition_start_gate_v1(p_league_id, false);
  select head.* into v_head
  from public.provider_competition_start_heads head
  where head.league_id = p_league_id;

  return v_gate || jsonb_build_object(
    'status', coalesce(v_gate ->> 'status', v_head.start_status, 'waiting'),
    'reasonCode', coalesce(v_gate ->> 'reasonCode', v_head.reason_code),
    'certificateId', coalesce(nullif(v_gate ->> 'certificateId', '')::bigint,
      v_head.certificate_id),
    'everAffected', coalesce(v_head.ever_affected, false),
    'firstAffectedAt', v_head.first_affected_at,
    'lastAssessedAt', v_head.last_assessed_at
  );
end;
$function$;
revoke all on function public.get_league_provider_competition_start_v1(uuid)
from public, anon, service_role;
grant execute on function public.get_league_provider_competition_start_v1(uuid)
to authenticated;

create or replace function public.guard_provider_competition_activation_v1()
returns trigger language plpgsql security definer set search_path = '' as $function$
begin
  if old.competition_started_at is null
    and new.competition_started_at is not null
    and (
      new.previous_league_id is not null
      or exists(
        select 1
        from public.provider_season_bootstrap_heads head
        where head.league_id = new.id
      )
      or exists(
        select 1
        from public.provider_season_bootstrap_certificates certificate
        where certificate.league_id = new.id
      )
    )
    and coalesce(current_setting('leghevo.provider_competition_start_context', true), '') <> 'on' then
    raise exception
      'Avvio bloccato: usa start_league_competition_guarded_v4.';
  end if;
  return new;
end;
$function$;
revoke all on function public.guard_provider_competition_activation_v1()
from public, anon, authenticated, service_role;

drop trigger if exists provider_competition_start_activation_guard
on public.leagues;
create trigger provider_competition_start_activation_guard
before update of competition_started_at on public.leagues
for each row execute function public.guard_provider_competition_activation_v1();
alter table public.leagues
  enable always trigger provider_competition_start_activation_guard;

create or replace function public.start_league_competition_guarded_v4(
  p_league_id uuid
)
returns jsonb language plpgsql security definer set search_path = '' as $function$
declare
  v_bootstrap jsonb;
  v_gate jsonb;
  v_base jsonb;
  v_certification jsonb;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;
  if not public.is_league_admin(p_league_id) then
    raise exception 'Solo la Direzione può avviare la competizione.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'league-season-rollover-lineage:' || p_league_id::text, 0));
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'provider-new-season-bootstrap:' || p_league_id::text, 0));
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'competition:' || p_league_id::text, 0));
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'provider-competition-start:' || p_league_id::text, 0));

  v_bootstrap := public.reconcile_provider_season_bootstrap_v1(p_league_id, true);
  if coalesce((v_bootstrap ->> 'applicable')::boolean, false)
    and (
      coalesce(v_bootstrap ->> 'status', 'waiting') <> 'ready'
      or not coalesce((v_bootstrap ->> 'certified')::boolean, false)
      or coalesce((v_bootstrap ->> 'affected')::boolean, false)
    ) then
    raise exception 'Avvio bloccato dal bootstrap provider [%].',
      v_bootstrap ->> 'reasonCode';
  end if;

  v_gate := public.compute_provider_competition_start_gate_v1(p_league_id, false);
  if coalesce((v_gate ->> 'applicable')::boolean, false)
    and coalesce(v_gate ->> 'status', 'waiting') not in ('ready','official') then
    raise exception 'Avvio competizione non pronto [%].', v_gate ->> 'reasonCode';
  end if;

  perform set_config('leghevo.provider_competition_start_context', 'on', true);
  v_base := public.start_league_competition_guarded_v3(p_league_id);

  if coalesce((v_gate ->> 'applicable')::boolean, false) then
    v_certification := public.certify_provider_competition_start_v1(p_league_id);
  else
    v_certification := public.compute_provider_competition_start_gate_v1(
      p_league_id, false);
  end if;
  perform set_config('leghevo.provider_competition_start_context', '', true);

  return v_base || jsonb_build_object(
    'providerCompetitionStartProtected', true,
    'providerCompetitionStartApplicable',
      coalesce((v_certification ->> 'applicable')::boolean, false),
    'providerCompetitionStartStatus',
      coalesce(v_certification ->> 'status', 'ready'),
    'providerCompetitionStartReason', v_certification ->> 'reasonCode',
    'providerCompetitionStartCertified',
      coalesce((v_certification ->> 'certified')::boolean, false),
    'providerCompetitionStartCertificateId',
      nullif(v_certification ->> 'certificateId', '')::bigint,
    'providerCompetitionStartHash', v_certification ->> 'startHash'
  );
end;
$function$;
revoke all on function public.start_league_competition_guarded_v4(uuid)
from public, anon;
grant execute on function public.start_league_competition_guarded_v4(uuid)
to authenticated, service_role;

-- Le vecchie RPC restano disponibili al proprietario delle funzioni, ma non
-- possono essere invocate direttamente dai client o dai worker di servizio.
revoke all on function public.start_league_competition_guarded_v3(uuid)
from public, anon, authenticated, service_role;
revoke all on function public.start_league_competition_guarded_v2(uuid)
from public, anon, authenticated, service_role;
revoke all on function public.start_league_competition_guarded(uuid)
from public, anon, authenticated, service_role;
revoke all on function public.start_league_competition(uuid)
from public, anon, authenticated, service_role;

create or replace function public.reconcile_provider_competition_start_from_bootstrap_v1()
returns trigger language plpgsql security definer set search_path = '' as $function$
begin
  perform public.reconcile_provider_competition_start_v1(new.league_id, false);
  return new;
end;
$function$;
revoke all on function public.reconcile_provider_competition_start_from_bootstrap_v1()
from public, anon, authenticated, service_role;

drop trigger if exists provider_bootstrap_reconcile_competition_start
on public.provider_season_bootstrap_heads;
create trigger provider_bootstrap_reconcile_competition_start
after insert or update on public.provider_season_bootstrap_heads
for each row execute function public.reconcile_provider_competition_start_from_bootstrap_v1();
alter table public.provider_season_bootstrap_heads
  enable always trigger provider_bootstrap_reconcile_competition_start;

create or replace function public.get_league_season_state_v9(p_league_id uuid)
returns jsonb language plpgsql stable security definer set search_path = '' as $function$
declare
  v_state jsonb;
  v_gate jsonb;
begin
  v_state := public.get_league_season_state_v8(p_league_id);
  v_gate := public.compute_provider_competition_start_gate_v1(p_league_id, false);
  return v_state || jsonb_build_object(
    'providerCompetitionStartProtected', true,
    'providerCompetitionStartApplicable',
      coalesce((v_gate ->> 'applicable')::boolean, false),
    'providerCompetitionStartHealthy',
      coalesce((v_gate ->> 'healthy')::boolean, true),
    'providerCompetitionStartAffected',
      coalesce((v_gate ->> 'affected')::boolean, false),
    'providerCompetitionStartStatus', coalesce(v_gate ->> 'status', 'waiting'),
    'providerCompetitionStartReason', v_gate ->> 'reasonCode',
    'providerCompetitionStartReady',
      coalesce(v_gate ->> 'status', 'waiting') in ('ready','official'),
    'providerCompetitionStartCertified',
      coalesce((v_gate ->> 'certified')::boolean, false),
    'providerCompetitionStartCertificateId',
      nullif(v_gate ->> 'certificateId', '')::bigint,
    'providerCompetitionStartHash', v_gate ->> 'startHash',
    'providerCompetitionStart', v_gate
  );
end;
$function$;
revoke all on function public.get_league_season_state_v9(uuid)
from public, anon, service_role;
grant execute on function public.get_league_season_state_v9(uuid)
to authenticated;

create or replace function public.get_league_management_state_v19(p_league_id uuid)
returns jsonb language plpgsql stable security definer set search_path = '' as $function$
declare
  v_state jsonb;
  v_season jsonb;
  v_checks jsonb;
  v_start_ready boolean;
begin
  v_state := public.get_league_management_state_v18(p_league_id);
  v_season := public.get_league_season_state_v9(p_league_id);
  v_checks := coalesce(v_state -> 'checks', '{}'::jsonb);
  v_start_ready := not coalesce(
      (v_season ->> 'providerCompetitionStartApplicable')::boolean, false)
    or coalesce(v_season ->> 'providerCompetitionStartStatus', 'waiting')
      in ('ready','official');

  return v_state || v_season || jsonb_build_object(
    'canStart', coalesce((v_state ->> 'canStart')::boolean, false)
      and v_start_ready,
    'checks', v_checks || jsonb_build_object(
      'providerCompetitionStartProtected', true,
      'providerCompetitionStartReady', v_start_ready,
      'providerCompetitionStartCertified',
        coalesce((v_season ->> 'providerCompetitionStartCertified')::boolean, false),
      'providerCompetitionStartHealthy',
        coalesce((v_season ->> 'providerCompetitionStartHealthy')::boolean, true)
    )
  );
end;
$function$;
revoke all on function public.get_league_management_state_v19(uuid)
from public, anon, service_role;
grant execute on function public.get_league_management_state_v19(uuid)
to authenticated;

create or replace function public.get_league_provider_sync_health_v30(p_league_id uuid)
returns jsonb language plpgsql stable security definer set search_path = '' as $function$
declare
  v_base jsonb;
  v_gate jsonb;
  v_healthy boolean;
begin
  v_base := public.get_league_provider_sync_health_v29(p_league_id);
  v_gate := public.compute_provider_competition_start_gate_v1(p_league_id, false);
  v_healthy := coalesce((v_base ->> 'healthy')::boolean, false)
    and coalesce((v_gate ->> 'healthy')::boolean, true)
    and not coalesce((v_gate ->> 'affected')::boolean, false);

  return v_base || jsonb_build_object(
    'protected', coalesce((v_base ->> 'protected')::boolean, false)
      and coalesce((v_gate ->> 'protected')::boolean, false),
    'healthy', v_healthy,
    'status', case when v_healthy then coalesce(v_base ->> 'status', 'idle')
      else 'attention' end,
    'providerCompetitionStart', v_gate
  );
end;
$function$;
revoke all on function public.get_league_provider_sync_health_v30(uuid)
from public, anon, service_role;
grant execute on function public.get_league_provider_sync_health_v30(uuid)
to authenticated;

-- Backfill non distruttivo: le competizioni esistenti non vengono riaperte,
-- fermate o modificate. Viene soltanto certificato lo stato osservabile.
do $backfill$
declare
  v_league_id uuid;
begin
  for v_league_id in
    select league.id
    from public.leagues league
    where exists(
      select 1
      from public.provider_season_bootstrap_heads head
      where head.league_id = league.id
    )
  loop
    perform public.reconcile_provider_competition_start_v1(v_league_id, true);
  end loop;
end;
$backfill$;

do $realtime$
begin
  if not exists(
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'provider_competition_start_events'
  ) then
    alter publication supabase_realtime
      add table public.provider_competition_start_events;
  end if;
end;
$realtime$;

create or replace function public.get_provider_competition_start_integrity_v1()
returns jsonb language plpgsql stable security definer set search_path = '' as $function$
declare
  v_certify text := coalesce(pg_catalog.pg_get_functiondef(
    to_regprocedure('public.certify_provider_competition_start_v1(uuid)')), '');
  v_reconcile text := coalesce(pg_catalog.pg_get_functiondef(
    to_regprocedure('public.reconcile_provider_competition_start_v1(uuid,boolean)')), '');
  v_start text := coalesce(pg_catalog.pg_get_functiondef(
    to_regprocedure('public.start_league_competition_guarded_v4(uuid)')), '');
  v_activation_guard text := coalesce(pg_catalog.pg_get_functiondef(
    to_regprocedure('public.guard_provider_competition_activation_v1()')), '');
begin
  return jsonb_build_object(
    'predecessor_ready',
      to_regprocedure('public.get_provider_season_bootstrap_integrity_v1()') is not null
      and (select count(*) from jsonb_each(
        public.get_provider_season_bootstrap_integrity_v1())) = 20
      and not exists(
        select 1
        from jsonb_each(public.get_provider_season_bootstrap_integrity_v1()) check_row
        where jsonb_typeof(check_row.value) is distinct from 'boolean'
           or check_row.value is distinct from 'true'::jsonb
      ),
    'certificate_table_ready',
      to_regclass('public.provider_competition_start_certificates') is not null,
    'head_table_ready',
      to_regclass('public.provider_competition_start_heads') is not null,
    'event_table_ready',
      to_regclass('public.provider_competition_start_events') is not null,
    'columns_ready',
      not exists(
        select 1
        from (values
          ('provider_competition_start_certificates','id'),
          ('provider_competition_start_certificates','league_id'),
          ('provider_competition_start_certificates','bootstrap_certificate_id'),
          ('provider_competition_start_certificates','calendar_fingerprint'),
          ('provider_competition_start_certificates','opening_matchday_id'),
          ('provider_competition_start_certificates','competition_started_at'),
          ('provider_competition_start_certificates','start_hash'),
          ('provider_competition_start_heads','league_id'),
          ('provider_competition_start_heads','certificate_id'),
          ('provider_competition_start_heads','start_status'),
          ('provider_competition_start_heads','ever_affected'),
          ('provider_competition_start_heads','first_affected_at'),
          ('provider_competition_start_events','league_id'),
          ('provider_competition_start_events','event_type'),
          ('provider_competition_start_events','start_status'),
          ('provider_competition_start_events','event_payload')
        ) required(table_name, column_name)
        where not exists(
          select 1 from information_schema.columns column_row
          where column_row.table_schema = 'public'
            and column_row.table_name = required.table_name
            and column_row.column_name = required.column_name
        )
      ),
    'constraints_ready',
      exists(select 1 from pg_catalog.pg_constraint c
        where c.conrelid = 'public.provider_competition_start_certificates'::regclass
          and c.conname = 'provider_competition_start_cert_start_hash_check')
      and exists(select 1 from pg_catalog.pg_constraint c
        where c.conrelid = 'public.provider_competition_start_heads'::regclass
          and c.conname = 'provider_competition_start_heads_state_check')
      and exists(select 1 from pg_catalog.pg_constraint c
        where c.conrelid = 'public.provider_competition_start_events'::regclass
          and c.conname = 'provider_competition_start_events_type_check'),
    'indexes_ready',
      to_regclass('public.provider_competition_start_certificates_created_idx') is not null
      and to_regclass('public.provider_competition_start_heads_status_idx') is not null
      and to_regclass('public.provider_competition_start_events_league_idx') is not null,
    'rls_ready',
      coalesce((select relrowsecurity from pg_catalog.pg_class
        where oid = 'public.provider_competition_start_certificates'::regclass), false)
      and coalesce((select relrowsecurity from pg_catalog.pg_class
        where oid = 'public.provider_competition_start_heads'::regclass), false)
      and coalesce((select relrowsecurity from pg_catalog.pg_class
        where oid = 'public.provider_competition_start_events'::regclass), false),
    'direct_write_blocked',
      has_table_privilege('authenticated',
        'public.provider_competition_start_certificates','SELECT')
      and not has_table_privilege('authenticated',
        'public.provider_competition_start_certificates','INSERT')
      and not has_table_privilege('authenticated',
        'public.provider_competition_start_heads','UPDATE')
      and not has_table_privilege('authenticated',
        'public.provider_competition_start_events','DELETE'),
    'immutable_certificate_ready',
      exists(select 1 from pg_catalog.pg_trigger trigger_row
        where trigger_row.tgrelid =
          'public.provider_competition_start_certificates'::regclass
          and trigger_row.tgname =
            'provider_competition_start_certificates_immutable'
          and trigger_row.tgenabled = 'A'),
    'immutable_events_ready',
      exists(select 1 from pg_catalog.pg_trigger trigger_row
        where trigger_row.tgrelid =
          'public.provider_competition_start_events'::regclass
          and trigger_row.tgname = 'provider_competition_start_events_immutable'
          and trigger_row.tgenabled = 'A'),
    'head_guard_ready',
      exists(select 1 from pg_catalog.pg_trigger trigger_row
        where trigger_row.tgrelid =
          'public.provider_competition_start_heads'::regclass
          and trigger_row.tgname = 'provider_competition_start_heads_write_guard'
          and trigger_row.tgenabled = 'A'),
    'assessment_rpc_ready',
      to_regprocedure('public.compute_provider_competition_start_gate_v1(uuid,boolean)')
        is not null
      and to_regprocedure('public.compute_provider_competition_start_hash_v1(uuid,bigint,text,text,text,uuid,smallint,integer,integer,integer,timestamptz)')
        is not null,
    'certify_rpc_ready',
      to_regprocedure('public.certify_provider_competition_start_v1(uuid)') is not null
      and position('provider-competition-start' in v_certify) > 0
      and position('compute_provider_competition_start_hash_v1' in v_certify) > 0,
    'reconcile_rpc_ready',
      to_regprocedure('public.reconcile_provider_competition_start_v1(uuid,boolean)')
        is not null
      and position('provider-competition-start' in v_reconcile) > 0,
    'activation_guard_ready',
      exists(select 1 from pg_catalog.pg_trigger trigger_row
        where trigger_row.tgrelid = 'public.leagues'::regclass
          and trigger_row.tgname = 'provider_competition_start_activation_guard'
          and trigger_row.tgenabled = 'A')
      and position('provider_competition_start_context' in v_activation_guard) > 0,
    'guarded_start_v4_ready',
      to_regprocedure('public.start_league_competition_guarded_v4(uuid)') is not null
      and position('reconcile_provider_season_bootstrap_v1' in v_start) > 0
      and position('certify_provider_competition_start_v1' in v_start) > 0
      and has_function_privilege('authenticated',
        'public.start_league_competition_guarded_v4(uuid)','EXECUTE'),
    'legacy_start_blocked',
      not has_function_privilege('authenticated',
        'public.start_league_competition_guarded_v3(uuid)','EXECUTE')
      and not has_function_privilege('authenticated',
        'public.start_league_competition_guarded_v2(uuid)','EXECUTE')
      and not has_function_privilege('authenticated',
        'public.start_league_competition_guarded(uuid)','EXECUTE')
      and not has_function_privilege('authenticated',
        'public.start_league_competition(uuid)','EXECUTE')
      and not has_function_privilege('service_role',
        'public.start_league_competition_guarded_v3(uuid)','EXECUTE')
      and not has_function_privilege('service_role',
        'public.start_league_competition_guarded_v2(uuid)','EXECUTE')
      and not has_function_privilege('service_role',
        'public.start_league_competition_guarded(uuid)','EXECUTE')
      and not has_function_privilege('service_role',
        'public.start_league_competition(uuid)','EXECUTE'),
    'state_and_health_ready',
      to_regprocedure('public.get_league_provider_competition_start_v1(uuid)')
        is not null
      and to_regprocedure('public.get_league_season_state_v9(uuid)') is not null
      and to_regprocedure('public.get_league_management_state_v19(uuid)') is not null
      and to_regprocedure('public.get_league_provider_sync_health_v30(uuid)')
        is not null,
    'backfill_and_realtime_ready',
      not exists(
        select 1
        from public.leagues league
        join public.provider_season_bootstrap_heads bootstrap
          on bootstrap.league_id = league.id
        left join public.provider_competition_start_heads start_head
          on start_head.league_id = league.id
        where start_head.league_id is null
      )
      and not exists(
        select 1
        from public.provider_competition_start_certificates certificate
        where certificate.start_hash <>
          public.compute_provider_competition_start_hash_v1(
            certificate.league_id,
            certificate.bootstrap_certificate_id,
            certificate.bootstrap_hash,
            certificate.provider_fixture_fingerprint,
            certificate.calendar_fingerprint,
            certificate.opening_matchday_id,
            certificate.opening_matchday_number,
            certificate.fantasy_fixture_count,
            certificate.fantasy_matchday_count,
            certificate.fantasy_team_count,
            certificate.competition_started_at
          )
      )
      and exists(select 1 from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'provider_competition_start_events')
  );
end;
$function$;
revoke all on function public.get_provider_competition_start_integrity_v1()
from public, anon, authenticated;
grant execute on function public.get_provider_competition_start_integrity_v1()
to service_role;

-- Validazione finale: esattamente 20 booleani true.
do $validation$
declare
  v_checks jsonb;
begin
  v_checks := public.get_provider_competition_start_integrity_v1();
  if (select count(*) from jsonb_each(v_checks)) <> 20
    or exists(
      select 1 from jsonb_each(v_checks) check_row
      where jsonb_typeof(check_row.value) is distinct from 'boolean'
         or check_row.value is distinct from 'true'::jsonb
    ) then
    raise exception 'Validazione v0.62.31 non superata: %', v_checks;
  end if;
end;
$validation$;

commit;

select
  (public.get_provider_competition_start_integrity_v1()->>'predecessor_ready')::boolean as predecessor_ready,
  (public.get_provider_competition_start_integrity_v1()->>'certificate_table_ready')::boolean as certificate_table_ready,
  (public.get_provider_competition_start_integrity_v1()->>'head_table_ready')::boolean as head_table_ready,
  (public.get_provider_competition_start_integrity_v1()->>'event_table_ready')::boolean as event_table_ready,
  (public.get_provider_competition_start_integrity_v1()->>'columns_ready')::boolean as columns_ready,
  (public.get_provider_competition_start_integrity_v1()->>'constraints_ready')::boolean as constraints_ready,
  (public.get_provider_competition_start_integrity_v1()->>'indexes_ready')::boolean as indexes_ready,
  (public.get_provider_competition_start_integrity_v1()->>'rls_ready')::boolean as rls_ready,
  (public.get_provider_competition_start_integrity_v1()->>'direct_write_blocked')::boolean as direct_write_blocked,
  (public.get_provider_competition_start_integrity_v1()->>'immutable_certificate_ready')::boolean as immutable_certificate_ready,
  (public.get_provider_competition_start_integrity_v1()->>'immutable_events_ready')::boolean as immutable_events_ready,
  (public.get_provider_competition_start_integrity_v1()->>'head_guard_ready')::boolean as head_guard_ready,
  (public.get_provider_competition_start_integrity_v1()->>'assessment_rpc_ready')::boolean as assessment_rpc_ready,
  (public.get_provider_competition_start_integrity_v1()->>'certify_rpc_ready')::boolean as certify_rpc_ready,
  (public.get_provider_competition_start_integrity_v1()->>'reconcile_rpc_ready')::boolean as reconcile_rpc_ready,
  (public.get_provider_competition_start_integrity_v1()->>'activation_guard_ready')::boolean as activation_guard_ready,
  (public.get_provider_competition_start_integrity_v1()->>'guarded_start_v4_ready')::boolean as guarded_start_v4_ready,
  (public.get_provider_competition_start_integrity_v1()->>'legacy_start_blocked')::boolean as legacy_start_blocked,
  (public.get_provider_competition_start_integrity_v1()->>'state_and_health_ready')::boolean as state_and_health_ready,
  (public.get_provider_competition_start_integrity_v1()->>'backfill_and_realtime_ready')::boolean as backfill_and_realtime_ready;
