-- LEGHEVO v0.62.40
-- Checkpoint immutabile di disaster recovery e prova di ripristino certificata
-- Dipendenza: v0.62.39 validata con 20/20 controlli true.

begin;

do $preflight$
declare
  v_integrity jsonb;
  v_false text[];
begin
  if to_regprocedure('public.get_leghevo_disaster_recovery_deployment_integrity_v1()') is not null
    and exists (
      select 1 from public.leghevo_application_release_certificates certificate
      where certificate.application_version = '0.62.40'
    ) then
    return;
  end if;

  if to_regprocedure('public.get_leghevo_operational_delivery_audit_deployment_integrity_v1()') is null then
    raise exception 'Preflight v0.62.40 non superato: diagnostica v0.62.39 assente.';
  end if;

  v_integrity := public.get_leghevo_operational_delivery_audit_deployment_integrity_v1();
  select array_agg(item.key order by item.key) into v_false
  from pg_catalog.jsonb_each(v_integrity) item
  where pg_catalog.jsonb_typeof(item.value) is distinct from 'boolean'
     or item.value is distinct from 'true'::jsonb;

  if (select count(*) from pg_catalog.jsonb_each(v_integrity)) <> 20
    or cardinality(v_false) > 0 then
    raise exception 'Preflight v0.62.40 non superato: %. Dettaglio: %',
      coalesce(array_to_string(v_false, ', '), 'numero controlli diverso da 20'),
      v_integrity;
  end if;
end;
$preflight$;

create or replace function public.compute_leghevo_disaster_recovery_checkpoint_fingerprint_v1(
  p_environment_key text,
  p_checkpoint_generation bigint,
  p_snapshot_payload jsonb,
  p_status text,
  p_contract_version integer default 1
)
returns text
language sql
immutable
security definer
set search_path = ''
as $function$
  select public.leghevo_sha256_hex_v1(
    coalesce(lower(trim(p_environment_key)), '') || '|' ||
    coalesce(p_checkpoint_generation, 0)::text || '|' ||
    coalesce(p_snapshot_payload, '{}'::jsonb)::text || '|' ||
    coalesce(lower(trim(p_status)), '') || '|' ||
    coalesce(p_contract_version, 0)::text
  );
$function$;

create or replace function public.compute_leghevo_disaster_recovery_component_fingerprint_v1(
  p_environment_key text,
  p_checkpoint_generation bigint,
  p_component_key text,
  p_component_payload jsonb,
  p_contract_version integer default 1
)
returns text
language sql
immutable
security definer
set search_path = ''
as $function$
  select public.leghevo_sha256_hex_v1(
    coalesce(lower(trim(p_environment_key)), '') || '|' ||
    coalesce(p_checkpoint_generation, 0)::text || '|' ||
    coalesce(lower(trim(p_component_key)), '') || '|' ||
    coalesce(p_component_payload, '{}'::jsonb)::text || '|' ||
    coalesce(p_contract_version, 0)::text
  );
$function$;

create or replace function public.compute_leghevo_disaster_recovery_drill_fingerprint_v1(
  p_checkpoint_id bigint,
  p_environment_key text,
  p_drill_generation bigint,
  p_status text,
  p_verified_component_count integer,
  p_component_mismatch_count integer,
  p_sequence_regression_count integer,
  p_recovery_plan jsonb,
  p_contract_version integer default 1
)
returns text
language sql
immutable
security definer
set search_path = ''
as $function$
  select public.leghevo_sha256_hex_v1(
    coalesce(p_checkpoint_id, 0)::text || '|' ||
    coalesce(lower(trim(p_environment_key)), '') || '|' ||
    coalesce(p_drill_generation, 0)::text || '|' ||
    coalesce(lower(trim(p_status)), '') || '|' ||
    coalesce(p_verified_component_count, 0)::text || '|' ||
    coalesce(p_component_mismatch_count, 0)::text || '|' ||
    coalesce(p_sequence_regression_count, 0)::text || '|' ||
    coalesce(p_recovery_plan, '{}'::jsonb)::text || '|' ||
    coalesce(p_contract_version, 0)::text
  );
$function$;

create or replace function public.compute_leghevo_disaster_recovery_event_fingerprint_v1(
  p_environment_key text,
  p_event_type text,
  p_checkpoint_generation bigint,
  p_drill_generation bigint,
  p_checkpoint_id bigint,
  p_drill_id bigint,
  p_reason_code text,
  p_details jsonb
)
returns text
language sql
immutable
security definer
set search_path = ''
as $function$
  select public.leghevo_sha256_hex_v1(
    coalesce(lower(trim(p_environment_key)), '') || '|' ||
    coalesce(lower(trim(p_event_type)), '') || '|' ||
    coalesce(p_checkpoint_generation, 0)::text || '|' ||
    coalesce(p_drill_generation, 0)::text || '|' ||
    coalesce(p_checkpoint_id, 0)::text || '|' ||
    coalesce(p_drill_id, 0)::text || '|' ||
    coalesce(lower(trim(p_reason_code)), '') || '|' ||
    coalesce(p_details, '{}'::jsonb)::text
  );
$function$;

create table if not exists public.leghevo_disaster_recovery_checkpoints (
  id bigint generated by default as identity primary key,
  environment_key text not null,
  checkpoint_generation bigint not null,
  request_id uuid not null unique,
  active_release_version text not null,
  release_generation bigint not null,
  rollout_generation bigint not null,
  exposure_percentage integer not null,
  telemetry_generation bigint not null,
  telemetry_window_sequence bigint not null,
  outbox_last_sequence bigint not null,
  consumer_last_sequence bigint not null,
  delivery_audit_generation bigint not null,
  audited_through_sequence bigint not null,
  component_count integer not null,
  snapshot_payload jsonb not null,
  status text not null,
  reason_code text not null,
  contract_version integer not null default 1,
  checkpoint_fingerprint text not null unique,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  created_by uuid null,
  constraint leghevo_dr_checkpoint_environment_check
    check (environment_key in ('production','staging')),
  constraint leghevo_dr_checkpoint_generation_check
    check (checkpoint_generation >= 1),
  constraint leghevo_dr_checkpoint_release_check
    check (char_length(trim(active_release_version)) between 3 and 64),
  constraint leghevo_dr_checkpoint_counters_check
    check (
      release_generation >= 1 and rollout_generation >= 1
      and exposure_percentage between 0 and 100
      and telemetry_generation >= 1 and telemetry_window_sequence >= 1
      and outbox_last_sequence >= 0 and consumer_last_sequence >= 0
      and delivery_audit_generation >= 1 and audited_through_sequence >= 0
      and component_count = 7
    ),
  constraint leghevo_dr_checkpoint_snapshot_check
    check (jsonb_typeof(snapshot_payload) = 'object'),
  constraint leghevo_dr_checkpoint_status_check
    check (status in ('certified','affected')),
  constraint leghevo_dr_checkpoint_reason_check
    check (char_length(trim(reason_code)) between 3 and 160),
  constraint leghevo_dr_checkpoint_contract_check
    check (contract_version >= 1),
  constraint leghevo_dr_checkpoint_fingerprint_check
    check (checkpoint_fingerprint ~ '^[0-9a-f]{64}$'),
  constraint leghevo_dr_checkpoint_details_check
    check (jsonb_typeof(details) = 'object'),
  constraint leghevo_dr_checkpoint_generation_unique
    unique (environment_key, checkpoint_generation)
);

create table if not exists public.leghevo_disaster_recovery_checkpoint_components (
  id bigint generated by default as identity primary key,
  checkpoint_id bigint not null
    references public.leghevo_disaster_recovery_checkpoints(id) on delete restrict,
  environment_key text not null,
  checkpoint_generation bigint not null,
  component_key text not null,
  component_payload jsonb not null,
  contract_version integer not null default 1,
  component_fingerprint text not null unique,
  created_at timestamptz not null default now(),
  constraint leghevo_dr_component_environment_check
    check (environment_key in ('production','staging')),
  constraint leghevo_dr_component_generation_check
    check (checkpoint_generation >= 1),
  constraint leghevo_dr_component_key_check
    check (component_key in (
      'application_integrity','release','rollout','telemetry',
      'outbox','consumer_delivery','delivery_audit'
    )),
  constraint leghevo_dr_component_payload_check
    check (jsonb_typeof(component_payload) = 'object'),
  constraint leghevo_dr_component_contract_check
    check (contract_version >= 1),
  constraint leghevo_dr_component_fingerprint_check
    check (component_fingerprint ~ '^[0-9a-f]{64}$'),
  constraint leghevo_dr_component_checkpoint_key_unique
    unique (checkpoint_id, component_key)
);

create table if not exists public.leghevo_disaster_recovery_drills (
  id bigint generated by default as identity primary key,
  checkpoint_id bigint not null
    references public.leghevo_disaster_recovery_checkpoints(id) on delete restrict,
  environment_key text not null,
  drill_generation bigint not null,
  request_id uuid not null unique,
  status text not null,
  reason_code text not null,
  verified_component_count integer not null,
  component_mismatch_count integer not null,
  sequence_regression_count integer not null,
  recovery_plan jsonb not null,
  contract_version integer not null default 1,
  drill_fingerprint text not null unique,
  details jsonb not null default '{}'::jsonb,
  started_at timestamptz not null,
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  created_by uuid null,
  constraint leghevo_dr_drill_environment_check
    check (environment_key in ('production','staging')),
  constraint leghevo_dr_drill_generation_check
    check (drill_generation >= 1),
  constraint leghevo_dr_drill_status_check
    check (status in ('passed','failed')),
  constraint leghevo_dr_drill_reason_check
    check (char_length(trim(reason_code)) between 3 and 160),
  constraint leghevo_dr_drill_counts_check
    check (
      verified_component_count between 0 and 7
      and component_mismatch_count >= 0
      and sequence_regression_count >= 0
    ),
  constraint leghevo_dr_drill_plan_check
    check (jsonb_typeof(recovery_plan) = 'object'),
  constraint leghevo_dr_drill_contract_check
    check (contract_version >= 1),
  constraint leghevo_dr_drill_fingerprint_check
    check (drill_fingerprint ~ '^[0-9a-f]{64}$'),
  constraint leghevo_dr_drill_details_check
    check (jsonb_typeof(details) = 'object'),
  constraint leghevo_dr_drill_time_check
    check (completed_at >= started_at),
  constraint leghevo_dr_drill_checkpoint_generation_unique
    unique (checkpoint_id, drill_generation)
);

create table if not exists public.leghevo_disaster_recovery_heads (
  environment_key text primary key,
  checkpoint_id bigint not null
    references public.leghevo_disaster_recovery_checkpoints(id) on delete restrict,
  checkpoint_generation bigint not null,
  latest_drill_id bigint null
    references public.leghevo_disaster_recovery_drills(id) on delete restrict,
  drill_generation bigint not null default 0,
  status text not null,
  reason_code text not null,
  revision bigint not null default 1,
  state_fingerprint text not null,
  updated_at timestamptz not null default now(),
  affected_at timestamptz null,
  constraint leghevo_dr_head_environment_check
    check (environment_key in ('production','staging')),
  constraint leghevo_dr_head_generations_check
    check (checkpoint_generation >= 1 and drill_generation >= 0 and revision >= 1),
  constraint leghevo_dr_head_status_check
    check (status in ('certified','affected','revalidated')),
  constraint leghevo_dr_head_reason_check
    check (char_length(trim(reason_code)) between 3 and 160),
  constraint leghevo_dr_head_fingerprint_check
    check (state_fingerprint ~ '^[0-9a-f]{64}$'),
  constraint leghevo_dr_head_drill_consistency_check
    check (latest_drill_id is null or drill_generation >= 1)
);

create table if not exists public.leghevo_disaster_recovery_events (
  id bigint generated by default as identity primary key,
  environment_key text not null,
  event_type text not null,
  checkpoint_generation bigint not null,
  drill_generation bigint not null,
  checkpoint_id bigint null
    references public.leghevo_disaster_recovery_checkpoints(id) on delete restrict,
  drill_id bigint null
    references public.leghevo_disaster_recovery_drills(id) on delete restrict,
  reason_code text not null,
  details jsonb not null default '{}'::jsonb,
  event_fingerprint text not null unique,
  created_at timestamptz not null default now(),
  created_by uuid null,
  constraint leghevo_dr_event_environment_check
    check (environment_key in ('production','staging')),
  constraint leghevo_dr_event_type_check
    check (event_type in (
      'checkpoint_created','drill_passed','drill_failed','affected','revalidated'
    )),
  constraint leghevo_dr_event_generations_check
    check (checkpoint_generation >= 1 and drill_generation >= 0),
  constraint leghevo_dr_event_reason_check
    check (char_length(trim(reason_code)) between 3 and 160),
  constraint leghevo_dr_event_details_check
    check (jsonb_typeof(details) = 'object'),
  constraint leghevo_dr_event_fingerprint_check
    check (event_fingerprint ~ '^[0-9a-f]{64}$')
);

create index if not exists leghevo_dr_checkpoints_environment_generation_idx
  on public.leghevo_disaster_recovery_checkpoints(environment_key, checkpoint_generation desc);
create index if not exists leghevo_dr_components_checkpoint_idx
  on public.leghevo_disaster_recovery_checkpoint_components(checkpoint_id, component_key);
create index if not exists leghevo_dr_drills_environment_generation_idx
  on public.leghevo_disaster_recovery_drills(environment_key, drill_generation desc);
create index if not exists leghevo_dr_events_created_idx
  on public.leghevo_disaster_recovery_events(environment_key, created_at desc);

alter table public.leghevo_disaster_recovery_checkpoints enable row level security;
alter table public.leghevo_disaster_recovery_checkpoint_components enable row level security;
alter table public.leghevo_disaster_recovery_drills enable row level security;
alter table public.leghevo_disaster_recovery_heads enable row level security;
alter table public.leghevo_disaster_recovery_events enable row level security;
alter table public.leghevo_disaster_recovery_events replica identity full;

revoke all on table public.leghevo_disaster_recovery_checkpoints from public, anon, authenticated, service_role;
revoke all on table public.leghevo_disaster_recovery_checkpoint_components from public, anon, authenticated, service_role;
revoke all on table public.leghevo_disaster_recovery_drills from public, anon, authenticated, service_role;
revoke all on table public.leghevo_disaster_recovery_heads from public, anon, authenticated, service_role;
revoke all on table public.leghevo_disaster_recovery_events from public, anon, authenticated, service_role;
grant select on table public.leghevo_disaster_recovery_events to authenticated;

drop policy if exists leghevo_dr_events_authenticated_read
on public.leghevo_disaster_recovery_events;
create policy leghevo_dr_events_authenticated_read
on public.leghevo_disaster_recovery_events
for select to authenticated using (true);

create or replace function public.guard_leghevo_disaster_recovery_immutable_v1()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if current_setting('leghevo.disaster_recovery_context', true) <> 'allowed' then
    raise exception 'Record disaster recovery immutabile: scrittura diretta vietata.';
  end if;
  if tg_op in ('UPDATE','DELETE') then
    raise exception 'Record disaster recovery append-only: modifica o cancellazione vietata.';
  end if;
  return new;
end;
$function$;

create or replace function public.guard_leghevo_disaster_recovery_head_v1()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if current_setting('leghevo.disaster_recovery_context', true) <> 'allowed' then
    raise exception 'Testa disaster recovery protetta: scrittura diretta vietata.';
  end if;
  if tg_op = 'DELETE' then
    raise exception 'Testa disaster recovery non cancellabile.';
  end if;
  if tg_op = 'UPDATE' then
    if new.checkpoint_generation < old.checkpoint_generation
      or new.drill_generation < old.drill_generation
      or new.revision <= old.revision then
      raise exception 'Regressione della testa disaster recovery vietata.';
    end if;
  end if;
  return new;
end;
$function$;

revoke all on function public.guard_leghevo_disaster_recovery_immutable_v1()
from public, anon, authenticated, service_role;
revoke all on function public.guard_leghevo_disaster_recovery_head_v1()
from public, anon, authenticated, service_role;

drop trigger if exists leghevo_dr_checkpoints_guard on public.leghevo_disaster_recovery_checkpoints;
create trigger leghevo_dr_checkpoints_guard
before insert or update or delete on public.leghevo_disaster_recovery_checkpoints
for each row execute function public.guard_leghevo_disaster_recovery_immutable_v1();
alter table public.leghevo_disaster_recovery_checkpoints enable always trigger leghevo_dr_checkpoints_guard;

drop trigger if exists leghevo_dr_components_guard on public.leghevo_disaster_recovery_checkpoint_components;
create trigger leghevo_dr_components_guard
before insert or update or delete on public.leghevo_disaster_recovery_checkpoint_components
for each row execute function public.guard_leghevo_disaster_recovery_immutable_v1();
alter table public.leghevo_disaster_recovery_checkpoint_components enable always trigger leghevo_dr_components_guard;

drop trigger if exists leghevo_dr_drills_guard on public.leghevo_disaster_recovery_drills;
create trigger leghevo_dr_drills_guard
before insert or update or delete on public.leghevo_disaster_recovery_drills
for each row execute function public.guard_leghevo_disaster_recovery_immutable_v1();
alter table public.leghevo_disaster_recovery_drills enable always trigger leghevo_dr_drills_guard;

drop trigger if exists leghevo_dr_events_guard on public.leghevo_disaster_recovery_events;
create trigger leghevo_dr_events_guard
before insert or update or delete on public.leghevo_disaster_recovery_events
for each row execute function public.guard_leghevo_disaster_recovery_immutable_v1();
alter table public.leghevo_disaster_recovery_events enable always trigger leghevo_dr_events_guard;

drop trigger if exists leghevo_dr_heads_guard on public.leghevo_disaster_recovery_heads;
create trigger leghevo_dr_heads_guard
before insert or update or delete on public.leghevo_disaster_recovery_heads
for each row execute function public.guard_leghevo_disaster_recovery_head_v1();
alter table public.leghevo_disaster_recovery_heads enable always trigger leghevo_dr_heads_guard;

create or replace function public.get_leghevo_disaster_recovery_snapshot_v1(
  p_environment_key text default 'production'
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_environment text := lower(trim(coalesce(p_environment_key, '')));
  v_integrity jsonb;
  v_release jsonb;
  v_rollout jsonb;
  v_telemetry jsonb;
  v_outbox jsonb;
  v_consumer jsonb;
  v_audit jsonb;
begin
  if v_environment not in ('production','staging') then
    raise exception 'Ambiente disaster recovery non valido.';
  end if;

  v_integrity := public.get_leghevo_application_integrity_model_v1();
  v_release := public.get_leghevo_application_release_model_v1(v_environment);
  v_rollout := public.get_leghevo_application_rollout_model_v1(v_environment);
  v_telemetry := public.get_leghevo_operational_telemetry_model_v1(v_environment);
  v_outbox := public.get_leghevo_operational_outbox_model_v1(v_environment);
  v_consumer := public.get_leghevo_operational_consumer_delivery_model_v1(v_environment);
  v_audit := public.get_leghevo_operational_delivery_audit_model_v1(v_environment);

  return jsonb_build_object(
    'application_integrity', jsonb_build_object(
      'protected', coalesce((v_integrity ->> 'protected')::boolean, false),
      'healthy', coalesce((v_integrity ->> 'healthy')::boolean, false),
      'schemaCertified', coalesce((v_integrity ->> 'schemaCertified')::boolean, false),
      'applicationVersion', v_integrity ->> 'applicationVersion',
      'schemaFingerprint', v_integrity ->> 'schemaFingerprint',
      'checkCount', coalesce((v_integrity ->> 'checkCount')::integer, 0),
      'passedCount', coalesce((v_integrity ->> 'passedCount')::integer, 0)
    ),
    'release', jsonb_build_object(
      'protected', coalesce((v_release ->> 'protected')::boolean, false),
      'healthy', coalesce((v_release ->> 'healthy')::boolean, false),
      'activeVersion', v_release ->> 'activeVersion',
      'previousVersion', v_release ->> 'previousVersion',
      'releaseGeneration', coalesce((v_release ->> 'releaseGeneration')::bigint, 0),
      'bundleFingerprint', v_release ->> 'bundleFingerprint',
      'contractFingerprint', v_release ->> 'contractFingerprint',
      'fingerprintStable', coalesce((v_release ->> 'fingerprintStable')::boolean, false)
    ),
    'rollout', jsonb_build_object(
      'protected', coalesce((v_rollout ->> 'protected')::boolean, false),
      'healthy', coalesce((v_rollout ->> 'healthy')::boolean, false),
      'releaseVersion', v_rollout ->> 'releaseVersion',
      'rolloutGeneration', coalesce((v_rollout ->> 'rolloutGeneration')::bigint, 0),
      'exposurePercentage', coalesce((v_rollout ->> 'exposurePercentage')::integer, 0),
      'stage', v_rollout ->> 'stage',
      'status', v_rollout ->> 'status',
      'killSwitchActive', coalesce((v_rollout ->> 'killSwitchActive')::boolean, true),
      'planFingerprint', v_rollout ->> 'planFingerprint',
      'planFingerprintStable', coalesce((v_rollout ->> 'planFingerprintStable')::boolean, false)
    ),
    'telemetry', jsonb_build_object(
      'protected', coalesce((v_telemetry ->> 'protected')::boolean, false),
      'healthy', coalesce((v_telemetry ->> 'healthy')::boolean, false),
      'authoritative', coalesce((v_telemetry ->> 'authoritative')::boolean, false),
      'sourceGeneration', coalesce((v_telemetry ->> 'sourceGeneration')::bigint, 0),
      'telemetryGeneration', coalesce((v_telemetry ->> 'telemetryGeneration')::bigint, 0),
      'lastWindowSequence', coalesce((v_telemetry ->> 'lastWindowSequence')::bigint, 0),
      'latestReleaseVersion', v_telemetry ->> 'latestReleaseVersion',
      'latestExposurePercentage', coalesce((v_telemetry ->> 'latestExposurePercentage')::integer, 0),
      'fingerprintStable', coalesce((v_telemetry ->> 'fingerprintStable')::boolean, false)
    ),
    'outbox', jsonb_build_object(
      'protected', coalesce((v_outbox ->> 'protected')::boolean, false),
      'healthy', coalesce((v_outbox ->> 'healthy')::boolean, false),
      'lastSequence', coalesce((v_outbox ->> 'lastSequence')::bigint, 0),
      'messageCount', coalesce((v_outbox ->> 'messageCount')::bigint, 0),
      'destinationCount', coalesce((v_outbox ->> 'destinationCount')::bigint, 0),
      'deliveredCount', coalesce((v_outbox ->> 'deliveredCount')::bigint, 0),
      'pendingCount', coalesce((v_outbox ->> 'pendingCount')::bigint, 0),
      'deadLetterCount', coalesce((v_outbox ->> 'deadLetterCount')::bigint, 0),
      'sequenceGapCount', coalesce((v_outbox ->> 'sequenceGapCount')::bigint, 0),
      'fingerprintMismatchCount', coalesce((v_outbox ->> 'fingerprintMismatchCount')::bigint, 0)
    ),
    'consumer_delivery', jsonb_build_object(
      'protected', coalesce((v_consumer ->> 'protected')::boolean, false),
      'healthy', coalesce((v_consumer ->> 'healthy')::boolean, false),
      'authoritative', coalesce((v_consumer ->> 'authoritative')::boolean, false),
      'consumerCount', coalesce((v_consumer ->> 'consumerCount')::bigint, 0),
      'receiptCount', coalesce((v_consumer ->> 'receiptCount')::bigint, 0),
      'expectedReceiptCount', coalesce((v_consumer ->> 'expectedReceiptCount')::bigint, 0),
      'lastAcknowledgedSequence', coalesce((v_consumer ->> 'lastAcknowledgedSequence')::bigint, 0),
      'sequenceGapCount', coalesce((v_consumer ->> 'sequenceGapCount')::bigint, 0),
      'fingerprintMismatchCount', coalesce((v_consumer ->> 'fingerprintMismatchCount')::bigint, 0),
      'receiptConsistencyMismatchCount', coalesce((v_consumer ->> 'receiptConsistencyMismatchCount')::bigint, 0)
    ),
    'delivery_audit', jsonb_build_object(
      'protected', coalesce((v_audit ->> 'protected')::boolean, false),
      'healthy', coalesce((v_audit ->> 'healthy')::boolean, false),
      'fresh', coalesce((v_audit ->> 'fresh')::boolean, false),
      'auditGeneration', coalesce((v_audit ->> 'auditGeneration')::bigint, 0),
      'auditedThroughSequence', coalesce((v_audit ->> 'auditedThroughSequence')::bigint, 0),
      'currentLastSequence', coalesce((v_audit ->> 'currentLastSequence')::bigint, 0),
      'sequenceGapCount', coalesce((v_audit ->> 'sequenceGapCount')::bigint, 0),
      'consistencyMismatchCount', coalesce((v_audit ->> 'consistencyMismatchCount')::bigint, 0),
      'fingerprintMismatchCount', coalesce((v_audit ->> 'fingerprintMismatchCount')::bigint, 0),
      'deadLetterCount', coalesce((v_audit ->> 'deadLetterCount')::bigint, 0)
    )
  );
end;
$function$;

revoke all on function public.get_leghevo_disaster_recovery_snapshot_v1(text)
from public, anon, authenticated;
grant execute on function public.get_leghevo_disaster_recovery_snapshot_v1(text)
to service_role;

create or replace function public.create_leghevo_disaster_recovery_checkpoint_v1(
  p_environment_key text,
  p_request_id uuid,
  p_reason_code text,
  p_details jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_environment text := lower(trim(coalesce(p_environment_key, '')));
  v_reason text := trim(coalesce(p_reason_code, ''));
  v_details jsonb := coalesce(p_details, '{}'::jsonb);
  v_existing public.leghevo_disaster_recovery_checkpoints%rowtype;
  v_checkpoint public.leghevo_disaster_recovery_checkpoints%rowtype;
  v_snapshot jsonb;
  v_component record;
  v_generation bigint;
  v_fingerprint text;
  v_event_fingerprint text;
  v_head public.leghevo_disaster_recovery_heads%rowtype;
begin
  if v_environment not in ('production','staging') then
    raise exception 'Ambiente disaster recovery non valido.';
  end if;
  if p_request_id is null then
    raise exception 'Request ID checkpoint obbligatorio.';
  end if;
  if char_length(v_reason) not between 3 and 160 then
    raise exception 'Reason code checkpoint non valido.';
  end if;
  if jsonb_typeof(v_details) <> 'object' then
    raise exception 'Details checkpoint deve essere un oggetto JSON.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('leghevo:disaster-recovery:' || v_environment, 0));

  select checkpoint.* into v_existing
  from public.leghevo_disaster_recovery_checkpoints checkpoint
  where checkpoint.request_id = p_request_id;
  if found then
    if v_existing.environment_key <> v_environment then
      raise exception 'Request ID checkpoint già usato con ambiente differente.';
    end if;
    return jsonb_build_object(
      'checkpointId', v_existing.id,
      'checkpointGeneration', v_existing.checkpoint_generation,
      'status', v_existing.status,
      'reused', true
    );
  end if;

  v_snapshot := public.get_leghevo_disaster_recovery_snapshot_v1(v_environment);
  if not coalesce((v_snapshot #>> '{application_integrity,protected}')::boolean, false)
    or not coalesce((v_snapshot #>> '{application_integrity,healthy}')::boolean, false)
    or not coalesce((v_snapshot #>> '{release,protected}')::boolean, false)
    or not coalesce((v_snapshot #>> '{release,healthy}')::boolean, false)
    or not coalesce((v_snapshot #>> '{rollout,protected}')::boolean, false)
    or not coalesce((v_snapshot #>> '{rollout,healthy}')::boolean, false)
    or not coalesce((v_snapshot #>> '{telemetry,protected}')::boolean, false)
    or not coalesce((v_snapshot #>> '{telemetry,healthy}')::boolean, false)
    or not coalesce((v_snapshot #>> '{outbox,protected}')::boolean, false)
    or not coalesce((v_snapshot #>> '{outbox,healthy}')::boolean, false)
    or not coalesce((v_snapshot #>> '{consumer_delivery,protected}')::boolean, false)
    or not coalesce((v_snapshot #>> '{consumer_delivery,healthy}')::boolean, false)
    or not coalesce((v_snapshot #>> '{delivery_audit,protected}')::boolean, false)
    or not coalesce((v_snapshot #>> '{delivery_audit,healthy}')::boolean, false)
    or not coalesce((v_snapshot #>> '{delivery_audit,fresh}')::boolean, false) then
    raise exception 'Checkpoint disaster recovery rifiutato: catena operativa non sana.';
  end if;

  select coalesce(max(checkpoint.checkpoint_generation), 0) + 1 into v_generation
  from public.leghevo_disaster_recovery_checkpoints checkpoint
  where checkpoint.environment_key = v_environment;

  v_fingerprint := public.compute_leghevo_disaster_recovery_checkpoint_fingerprint_v1(
    v_environment, v_generation, v_snapshot, 'certified', 1);

  perform pg_catalog.set_config('leghevo.disaster_recovery_context','allowed',true);
  insert into public.leghevo_disaster_recovery_checkpoints (
    environment_key, checkpoint_generation, request_id,
    active_release_version, release_generation, rollout_generation,
    exposure_percentage, telemetry_generation, telemetry_window_sequence,
    outbox_last_sequence, consumer_last_sequence,
    delivery_audit_generation, audited_through_sequence,
    component_count, snapshot_payload, status, reason_code,
    contract_version, checkpoint_fingerprint, details, created_by
  ) values (
    v_environment, v_generation, p_request_id,
    v_snapshot #>> '{release,activeVersion}',
    (v_snapshot #>> '{release,releaseGeneration}')::bigint,
    (v_snapshot #>> '{rollout,rolloutGeneration}')::bigint,
    (v_snapshot #>> '{rollout,exposurePercentage}')::integer,
    (v_snapshot #>> '{telemetry,telemetryGeneration}')::bigint,
    (v_snapshot #>> '{telemetry,lastWindowSequence}')::bigint,
    (v_snapshot #>> '{outbox,lastSequence}')::bigint,
    (v_snapshot #>> '{consumer_delivery,lastAcknowledgedSequence}')::bigint,
    (v_snapshot #>> '{delivery_audit,auditGeneration}')::bigint,
    (v_snapshot #>> '{delivery_audit,auditedThroughSequence}')::bigint,
    7, v_snapshot, 'certified', v_reason, 1, v_fingerprint,
    v_details, auth.uid()
  ) returning * into v_checkpoint;

  for v_component in
    select component.key as component_key, component.value as component_payload
    from pg_catalog.jsonb_each(v_snapshot) component
  loop
    insert into public.leghevo_disaster_recovery_checkpoint_components (
      checkpoint_id, environment_key, checkpoint_generation,
      component_key, component_payload, contract_version,
      component_fingerprint
    ) values (
      v_checkpoint.id, v_environment, v_generation,
      v_component.component_key, v_component.component_payload, 1,
      public.compute_leghevo_disaster_recovery_component_fingerprint_v1(
        v_environment, v_generation, v_component.component_key,
        v_component.component_payload, 1)
    );
  end loop;

  v_event_fingerprint := public.compute_leghevo_disaster_recovery_event_fingerprint_v1(
    v_environment, 'checkpoint_created', v_generation, 0,
    v_checkpoint.id, null, v_reason, v_details);
  insert into public.leghevo_disaster_recovery_events (
    environment_key, event_type, checkpoint_generation, drill_generation,
    checkpoint_id, drill_id, reason_code, details,
    event_fingerprint, created_by
  ) values (
    v_environment, 'checkpoint_created', v_generation, 0,
    v_checkpoint.id, null, v_reason, v_details,
    v_event_fingerprint, auth.uid()
  );

  select head.* into v_head
  from public.leghevo_disaster_recovery_heads head
  where head.environment_key = v_environment
  for update;

  insert into public.leghevo_disaster_recovery_heads (
    environment_key, checkpoint_id, checkpoint_generation,
    latest_drill_id, drill_generation, status, reason_code,
    revision, state_fingerprint, updated_at, affected_at
  ) values (
    v_environment, v_checkpoint.id, v_generation,
    null, coalesce(v_head.drill_generation, 0), 'affected', 'disaster_recovery.drill_required',
    coalesce(v_head.revision, 0) + 1,
    public.leghevo_sha256_hex_v1(
      v_environment || '|' || v_generation::text || '|' ||
      coalesce(v_head.drill_generation, 0)::text || '|affected|disaster_recovery.drill_required'),
    now(), now()
  )
  on conflict (environment_key) do update set
    checkpoint_id = excluded.checkpoint_id,
    checkpoint_generation = excluded.checkpoint_generation,
    latest_drill_id = excluded.latest_drill_id,
    drill_generation = excluded.drill_generation,
    status = excluded.status,
    reason_code = excluded.reason_code,
    revision = excluded.revision,
    state_fingerprint = excluded.state_fingerprint,
    updated_at = excluded.updated_at,
    affected_at = excluded.affected_at;

  return jsonb_build_object(
    'checkpointId', v_checkpoint.id,
    'checkpointGeneration', v_generation,
    'status', v_checkpoint.status,
    'checkpointFingerprint', v_checkpoint.checkpoint_fingerprint,
    'reused', false
  );
end;
$function$;

revoke all on function public.create_leghevo_disaster_recovery_checkpoint_v1(text,uuid,text,jsonb)
from public, anon, authenticated;
grant execute on function public.create_leghevo_disaster_recovery_checkpoint_v1(text,uuid,text,jsonb)
to service_role;

create or replace function public.run_leghevo_disaster_recovery_drill_v1(
  p_environment_key text,
  p_checkpoint_id bigint,
  p_request_id uuid,
  p_details jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_environment text := lower(trim(coalesce(p_environment_key, '')));
  v_details jsonb := coalesce(p_details, '{}'::jsonb);
  v_checkpoint public.leghevo_disaster_recovery_checkpoints%rowtype;
  v_existing public.leghevo_disaster_recovery_drills%rowtype;
  v_drill public.leghevo_disaster_recovery_drills%rowtype;
  v_head public.leghevo_disaster_recovery_heads%rowtype;
  v_current_snapshot jsonb;
  v_drill_generation bigint;
  v_component_mismatch_count integer := 0;
  v_sequence_regression_count integer := 0;
  v_verified_component_count integer := 0;
  v_checkpoint_fingerprint_stable boolean := false;
  v_status text;
  v_reason text;
  v_recovery_plan jsonb;
  v_drill_fingerprint text;
  v_event_fingerprint text;
  v_started_at timestamptz := now();
begin
  if v_environment not in ('production','staging') then
    raise exception 'Ambiente disaster recovery non valido.';
  end if;
  if p_checkpoint_id is null or p_request_id is null then
    raise exception 'Checkpoint ID e request ID drill obbligatori.';
  end if;
  if jsonb_typeof(v_details) <> 'object' then
    raise exception 'Details drill deve essere un oggetto JSON.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('leghevo:disaster-recovery:' || v_environment, 0));

  select drill.* into v_existing
  from public.leghevo_disaster_recovery_drills drill
  where drill.request_id = p_request_id;
  if found then
    if v_existing.environment_key <> v_environment
      or v_existing.checkpoint_id <> p_checkpoint_id then
      raise exception 'Request ID drill già usato con parametri differenti.';
    end if;
    return jsonb_build_object(
      'drillId', v_existing.id,
      'drillGeneration', v_existing.drill_generation,
      'status', v_existing.status,
      'reused', true
    );
  end if;

  select checkpoint.* into v_checkpoint
  from public.leghevo_disaster_recovery_checkpoints checkpoint
  where checkpoint.id = p_checkpoint_id
    and checkpoint.environment_key = v_environment
  for share;
  if not found then
    raise exception 'Checkpoint disaster recovery non trovato.';
  end if;

  v_checkpoint_fingerprint_stable :=
    v_checkpoint.checkpoint_fingerprint =
      public.compute_leghevo_disaster_recovery_checkpoint_fingerprint_v1(
        v_checkpoint.environment_key, v_checkpoint.checkpoint_generation,
        v_checkpoint.snapshot_payload, v_checkpoint.status,
        v_checkpoint.contract_version);

  select count(*) into v_verified_component_count
  from public.leghevo_disaster_recovery_checkpoint_components component
  where component.checkpoint_id = v_checkpoint.id;

  select count(*) into v_component_mismatch_count
  from public.leghevo_disaster_recovery_checkpoint_components component
  where component.checkpoint_id = v_checkpoint.id
    and component.component_fingerprint <>
      public.compute_leghevo_disaster_recovery_component_fingerprint_v1(
        component.environment_key, component.checkpoint_generation,
        component.component_key, component.component_payload,
        component.contract_version);

  v_current_snapshot := public.get_leghevo_disaster_recovery_snapshot_v1(v_environment);

  select count(*) + v_component_mismatch_count into v_component_mismatch_count
  from (
    select stored_component.component_key
    from public.leghevo_disaster_recovery_checkpoint_components stored_component
    left join pg_catalog.jsonb_each(v_current_snapshot) current_component
      on current_component.key = stored_component.component_key
    where stored_component.checkpoint_id = v_checkpoint.id
      and current_component.value is distinct from stored_component.component_payload
  ) mismatched_component;

  v_sequence_regression_count :=
    case when (v_current_snapshot #>> '{outbox,lastSequence}')::bigint
      < v_checkpoint.outbox_last_sequence then 1 else 0 end
    + case when (v_current_snapshot #>> '{consumer_delivery,lastAcknowledgedSequence}')::bigint
      < v_checkpoint.consumer_last_sequence then 1 else 0 end
    + case when (v_current_snapshot #>> '{delivery_audit,auditedThroughSequence}')::bigint
      < v_checkpoint.audited_through_sequence then 1 else 0 end;

  if v_current_snapshot #>> '{release,activeVersion}' is distinct from v_checkpoint.active_release_version
    or (v_current_snapshot #>> '{release,releaseGeneration}')::bigint <> v_checkpoint.release_generation
    or (v_current_snapshot #>> '{rollout,rolloutGeneration}')::bigint <> v_checkpoint.rollout_generation
    or (v_current_snapshot #>> '{rollout,exposurePercentage}')::integer <> v_checkpoint.exposure_percentage
    or (v_current_snapshot #>> '{telemetry,telemetryGeneration}')::bigint <> v_checkpoint.telemetry_generation then
    v_component_mismatch_count := v_component_mismatch_count + 1;
  end if;

  v_status := case
    when v_checkpoint_fingerprint_stable
      and v_verified_component_count = 7
      and v_component_mismatch_count = 0
      and v_sequence_regression_count = 0 then 'passed'
    else 'failed'
  end;
  v_reason := case
    when not v_checkpoint_fingerprint_stable then 'disaster_recovery.checkpoint_fingerprint_changed'
    when v_verified_component_count <> 7 then 'disaster_recovery.component_set_incomplete'
    when v_component_mismatch_count > 0 then 'disaster_recovery.component_mismatch'
    when v_sequence_regression_count > 0 then 'disaster_recovery.sequence_regression'
    else 'disaster_recovery.drill_passed'
  end;

  select coalesce(max(drill.drill_generation), 0) + 1 into v_drill_generation
  from public.leghevo_disaster_recovery_drills drill
  where drill.environment_key = v_environment;

  v_recovery_plan := jsonb_build_object(
    'environment', v_environment,
    'checkpointId', v_checkpoint.id,
    'checkpointGeneration', v_checkpoint.checkpoint_generation,
    'activeReleaseVersion', v_checkpoint.active_release_version,
    'releaseGeneration', v_checkpoint.release_generation,
    'rolloutGeneration', v_checkpoint.rollout_generation,
    'exposurePercentage', v_checkpoint.exposure_percentage,
    'telemetryGeneration', v_checkpoint.telemetry_generation,
    'resumeTelemetryWindowSequence', v_checkpoint.telemetry_window_sequence + 1,
    'resumeOutboxAfterSequence', v_checkpoint.outbox_last_sequence,
    'resumeConsumerAfterSequence', v_checkpoint.consumer_last_sequence,
    'auditedThroughSequence', v_checkpoint.audited_through_sequence,
    'requiredActions', jsonb_build_array(
      'verify_database_backup_reference',
      'restore_schema_and_data_to_isolated_target',
      'recompute_fingerprints',
      'resume_workers_with_new_fencing_generation',
      'run_delivery_audit_before_traffic'
    )
  );

  v_drill_fingerprint := public.compute_leghevo_disaster_recovery_drill_fingerprint_v1(
    v_checkpoint.id, v_environment, v_drill_generation, v_status,
    v_verified_component_count, v_component_mismatch_count,
    v_sequence_regression_count, v_recovery_plan, 1);

  perform pg_catalog.set_config('leghevo.disaster_recovery_context','allowed',true);
  insert into public.leghevo_disaster_recovery_drills (
    checkpoint_id, environment_key, drill_generation, request_id,
    status, reason_code, verified_component_count,
    component_mismatch_count, sequence_regression_count,
    recovery_plan, contract_version, drill_fingerprint,
    details, started_at, completed_at, created_by
  ) values (
    v_checkpoint.id, v_environment, v_drill_generation, p_request_id,
    v_status, v_reason, v_verified_component_count,
    v_component_mismatch_count, v_sequence_regression_count,
    v_recovery_plan, 1, v_drill_fingerprint,
    v_details, v_started_at, now(), auth.uid()
  ) returning * into v_drill;

  select head.* into v_head
  from public.leghevo_disaster_recovery_heads head
  where head.environment_key = v_environment
  for update;

  insert into public.leghevo_disaster_recovery_heads (
    environment_key, checkpoint_id, checkpoint_generation,
    latest_drill_id, drill_generation, status, reason_code,
    revision, state_fingerprint, updated_at, affected_at
  ) values (
    v_environment, v_checkpoint.id, v_checkpoint.checkpoint_generation,
    v_drill.id, v_drill_generation,
    case when v_status = 'passed' and coalesce(v_head.status, '') = 'affected'
      and v_head.latest_drill_id is not null then 'revalidated'
      when v_status = 'passed' then 'certified'
      else 'affected' end,
    v_reason, coalesce(v_head.revision, 0) + 1,
    public.leghevo_sha256_hex_v1(
      v_environment || '|' || v_checkpoint.checkpoint_generation::text || '|' ||
      v_drill_generation::text || '|' || v_status || '|' || v_reason),
    now(), case when v_status = 'failed' then now() else null end
  )
  on conflict (environment_key) do update set
    checkpoint_id = excluded.checkpoint_id,
    checkpoint_generation = excluded.checkpoint_generation,
    latest_drill_id = excluded.latest_drill_id,
    drill_generation = excluded.drill_generation,
    status = excluded.status,
    reason_code = excluded.reason_code,
    revision = excluded.revision,
    state_fingerprint = excluded.state_fingerprint,
    updated_at = excluded.updated_at,
    affected_at = excluded.affected_at;

  v_event_fingerprint := public.compute_leghevo_disaster_recovery_event_fingerprint_v1(
    v_environment,
    case when v_status = 'passed' then 'drill_passed' else 'drill_failed' end,
    v_checkpoint.checkpoint_generation, v_drill_generation,
    v_checkpoint.id, v_drill.id, v_reason, v_details);
  insert into public.leghevo_disaster_recovery_events (
    environment_key, event_type, checkpoint_generation, drill_generation,
    checkpoint_id, drill_id, reason_code, details,
    event_fingerprint, created_by
  ) values (
    v_environment,
    case when v_status = 'passed' then 'drill_passed' else 'drill_failed' end,
    v_checkpoint.checkpoint_generation, v_drill_generation,
    v_checkpoint.id, v_drill.id, v_reason, v_details,
    v_event_fingerprint, auth.uid()
  );

  return jsonb_build_object(
    'drillId', v_drill.id,
    'drillGeneration', v_drill_generation,
    'status', v_status,
    'reasonCode', v_reason,
    'verifiedComponentCount', v_verified_component_count,
    'componentMismatchCount', v_component_mismatch_count,
    'sequenceRegressionCount', v_sequence_regression_count,
    'recoveryPlan', v_recovery_plan,
    'reused', false
  );
end;
$function$;

revoke all on function public.run_leghevo_disaster_recovery_drill_v1(text,bigint,uuid,jsonb)
from public, anon, authenticated;
grant execute on function public.run_leghevo_disaster_recovery_drill_v1(text,bigint,uuid,jsonb)
to service_role;

create or replace function public.get_leghevo_disaster_recovery_model_v1(
  p_environment_key text default 'production'
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_environment text := lower(trim(coalesce(p_environment_key, '')));
  v_head public.leghevo_disaster_recovery_heads%rowtype;
  v_checkpoint public.leghevo_disaster_recovery_checkpoints%rowtype;
  v_drill public.leghevo_disaster_recovery_drills%rowtype;
  v_current_snapshot jsonb;
  v_checkpoint_stable boolean := false;
  v_drill_stable boolean := false;
  v_component_mismatch_count bigint := 0;
  v_fresh boolean := false;
  v_protected boolean := false;
  v_healthy boolean := false;
  v_status text := 'affected';
  v_reason text := 'disaster_recovery.missing';
begin
  if v_environment not in ('production','staging') then
    return jsonb_build_object(
      'protected', false, 'healthy', false, 'fresh', false,
      'status', 'affected', 'reasonCode', 'disaster_recovery.invalid_environment',
      'environment', v_environment
    );
  end if;

  select head.* into v_head
  from public.leghevo_disaster_recovery_heads head
  where head.environment_key = v_environment;
  if not found then
    return jsonb_build_object(
      'protected', false, 'healthy', false, 'fresh', false,
      'status', 'affected', 'reasonCode', 'disaster_recovery.missing',
      'environment', v_environment
    );
  end if;

  select checkpoint.* into v_checkpoint
  from public.leghevo_disaster_recovery_checkpoints checkpoint
  where checkpoint.id = v_head.checkpoint_id;
  if v_head.latest_drill_id is not null then
    select drill.* into v_drill
    from public.leghevo_disaster_recovery_drills drill
    where drill.id = v_head.latest_drill_id;
  end if;

  v_checkpoint_stable := v_checkpoint.id is not null
    and v_checkpoint.checkpoint_fingerprint =
      public.compute_leghevo_disaster_recovery_checkpoint_fingerprint_v1(
        v_checkpoint.environment_key, v_checkpoint.checkpoint_generation,
        v_checkpoint.snapshot_payload, v_checkpoint.status,
        v_checkpoint.contract_version);

  v_drill_stable := v_drill.id is not null
    and v_drill.drill_fingerprint =
      public.compute_leghevo_disaster_recovery_drill_fingerprint_v1(
        v_drill.checkpoint_id, v_drill.environment_key,
        v_drill.drill_generation, v_drill.status,
        v_drill.verified_component_count, v_drill.component_mismatch_count,
        v_drill.sequence_regression_count, v_drill.recovery_plan,
        v_drill.contract_version);

  select count(*) into v_component_mismatch_count
  from public.leghevo_disaster_recovery_checkpoint_components component
  where component.checkpoint_id = v_checkpoint.id
    and component.component_fingerprint <>
      public.compute_leghevo_disaster_recovery_component_fingerprint_v1(
        component.environment_key, component.checkpoint_generation,
        component.component_key, component.component_payload,
        component.contract_version);

  v_current_snapshot := public.get_leghevo_disaster_recovery_snapshot_v1(v_environment);
  v_fresh := v_checkpoint.snapshot_payload = v_current_snapshot;
  v_protected := v_checkpoint_stable and v_drill_stable
    and v_component_mismatch_count = 0
    and v_drill.status = 'passed'
    and v_drill.verified_component_count = 7
    and v_drill.component_mismatch_count = 0
    and v_drill.sequence_regression_count = 0
    and v_head.status in ('certified','revalidated');
  v_healthy := v_protected and v_fresh;
  v_status := case
    when not v_protected then 'affected'
    when not v_fresh then 'stale'
    else 'certified'
  end;
  v_reason := case
    when not v_checkpoint_stable then 'disaster_recovery.checkpoint_fingerprint_changed'
    when not v_drill_stable then 'disaster_recovery.drill_fingerprint_changed'
    when v_component_mismatch_count > 0 then 'disaster_recovery.component_fingerprint_changed'
    when v_drill.status <> 'passed' then 'disaster_recovery.drill_failed'
    when v_head.status = 'affected' then v_head.reason_code
    when not v_fresh then 'disaster_recovery.stale'
    else 'disaster_recovery.certified'
  end;

  return jsonb_build_object(
    'protected', v_protected,
    'healthy', v_healthy,
    'fresh', v_fresh,
    'status', v_status,
    'reasonCode', v_reason,
    'environment', v_environment,
    'checkpointId', v_checkpoint.id,
    'checkpointGeneration', v_checkpoint.checkpoint_generation,
    'drillId', v_drill.id,
    'drillGeneration', v_drill.drill_generation,
    'activeVersion', v_checkpoint.active_release_version,
    'releaseGeneration', v_checkpoint.release_generation,
    'rolloutGeneration', v_checkpoint.rollout_generation,
    'exposurePercentage', v_checkpoint.exposure_percentage,
    'telemetryGeneration', v_checkpoint.telemetry_generation,
    'outboxSequence', v_checkpoint.outbox_last_sequence,
    'consumerSequence', v_checkpoint.consumer_last_sequence,
    'auditedSequence', v_checkpoint.audited_through_sequence,
    'componentCount', v_checkpoint.component_count,
    'componentMismatchCount', v_component_mismatch_count,
    'recoveryPlan', v_drill.recovery_plan,
    'lastCheckpointAt', v_checkpoint.created_at,
    'lastDrillAt', v_drill.completed_at,
    'checkedAt', now()
  );
end;
$function$;

revoke all on function public.get_leghevo_disaster_recovery_model_v1(text)
from public, anon;
grant execute on function public.get_leghevo_disaster_recovery_model_v1(text)
to authenticated, service_role;

create or replace function public.promote_leghevo_application_rollout_v6(
  p_environment_key text,
  p_target_percentage integer,
  p_request_id uuid,
  p_reason_code text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_recovery jsonb;
begin
  v_recovery := public.get_leghevo_disaster_recovery_model_v1(p_environment_key);
  if not coalesce((v_recovery ->> 'protected')::boolean, false) then
    raise exception 'Promozione bloccata: disaster recovery non protetto.';
  end if;
  if not coalesce((v_recovery ->> 'healthy')::boolean, false)
    or not coalesce((v_recovery ->> 'fresh')::boolean, false) then
    raise exception 'Promozione bloccata: checkpoint o drill non aggiornati.';
  end if;
  return public.promote_leghevo_application_rollout_v5(
    p_environment_key, p_target_percentage, p_request_id, p_reason_code);
end;
$function$;

revoke all on function public.promote_leghevo_application_rollout_v6(text,integer,uuid,text)
from public, anon, authenticated;
grant execute on function public.promote_leghevo_application_rollout_v6(text,integer,uuid,text)
to service_role;
revoke execute on function public.promote_leghevo_application_rollout_v5(text,integer,uuid,text)
from service_role;

create or replace function public.get_leghevo_client_rollout_eligibility_v6(
  p_application_version text,
  p_bundle_fingerprint text,
  p_installation_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_base jsonb;
  v_recovery jsonb;
  v_eligible boolean;
  v_reason text;
begin
  v_base := public.get_leghevo_client_rollout_eligibility_v5(
    p_application_version, p_bundle_fingerprint, p_installation_id);
  v_recovery := public.get_leghevo_disaster_recovery_model_v1('production');
  v_eligible := coalesce((v_base ->> 'rolloutEligible')::boolean, false)
    and coalesce((v_recovery ->> 'protected')::boolean, false)
    and coalesce((v_recovery ->> 'healthy')::boolean, false)
    and coalesce((v_recovery ->> 'fresh')::boolean, false);
  v_reason := case
    when not coalesce((v_base ->> 'compatible')::boolean, false)
      then coalesce(v_base ->> 'reasonCode', 'release.incompatible')
    when not coalesce((v_recovery ->> 'protected')::boolean, false)
      then 'disaster_recovery.not_protected'
    when not coalesce((v_recovery ->> 'fresh')::boolean, false)
      then 'disaster_recovery.stale'
    when not coalesce((v_recovery ->> 'healthy')::boolean, false)
      then 'disaster_recovery.affected'
    else coalesce(v_base ->> 'reasonCode', 'release.compatible')
  end;

  return v_base || jsonb_build_object(
    'compatible', coalesce((v_base ->> 'compatible')::boolean, false) and v_eligible,
    'rolloutEligible', v_eligible,
    'reasonCode', v_reason,
    'disasterRecoveryProtected', coalesce((v_recovery ->> 'protected')::boolean, false),
    'disasterRecoveryHealthy', coalesce((v_recovery ->> 'healthy')::boolean, false),
    'disasterRecoveryFresh', coalesce((v_recovery ->> 'fresh')::boolean, false),
    'disasterRecoveryStatus', v_recovery ->> 'status',
    'disasterRecoveryCheckpointGeneration', coalesce((v_recovery ->> 'checkpointGeneration')::bigint, 0),
    'disasterRecoveryDrillGeneration', coalesce((v_recovery ->> 'drillGeneration')::bigint, 0),
    'checkedAt', now()
  );
end;
$function$;

revoke all on function public.get_leghevo_client_rollout_eligibility_v6(text,text,uuid)
from public;
grant execute on function public.get_leghevo_client_rollout_eligibility_v6(text,text,uuid)
to anon, authenticated;
revoke execute on function public.get_leghevo_client_rollout_eligibility_v5(text,text,uuid)
from anon, authenticated;

create or replace function public.get_league_provider_sync_health_v39(p_league_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_base jsonb;
  v_recovery jsonb;
begin
  v_base := public.get_league_provider_sync_health_v38(p_league_id);
  v_recovery := public.get_leghevo_disaster_recovery_model_v1('production');
  return v_base || jsonb_build_object(
    'applicationDisasterRecovery', v_recovery,
    'healthy', coalesce((v_base ->> 'healthy')::boolean, false)
      and coalesce((v_recovery ->> 'healthy')::boolean, false),
    'protected', coalesce((v_base ->> 'protected')::boolean, false)
      and coalesce((v_recovery ->> 'protected')::boolean, false)
  );
end;
$function$;
revoke all on function public.get_league_provider_sync_health_v39(uuid) from public, anon;
grant execute on function public.get_league_provider_sync_health_v39(uuid) to authenticated;

create or replace function public.get_league_season_state_v18(p_league_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_base jsonb;
  v_recovery jsonb;
begin
  v_base := public.get_league_season_state_v17(p_league_id);
  v_recovery := public.get_leghevo_disaster_recovery_model_v1('production');
  return v_base || jsonb_build_object('applicationDisasterRecovery', v_recovery);
end;
$function$;
revoke all on function public.get_league_season_state_v18(uuid) from public, anon;
grant execute on function public.get_league_season_state_v18(uuid) to authenticated;

create or replace function public.get_league_management_state_v28(p_league_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_base jsonb;
  v_recovery jsonb;
  v_checks jsonb;
begin
  v_base := public.get_league_management_state_v27(p_league_id);
  v_recovery := public.get_leghevo_disaster_recovery_model_v1('production');
  v_checks := coalesce(v_base -> 'checks', '{}'::jsonb) || jsonb_build_object(
    'applicationDisasterRecoveryProtected', coalesce((v_recovery ->> 'protected')::boolean, false),
    'applicationDisasterRecoveryHealthy', coalesce((v_recovery ->> 'healthy')::boolean, false),
    'applicationDisasterRecoveryFresh', coalesce((v_recovery ->> 'fresh')::boolean, false)
  );
  return v_base || jsonb_build_object(
    'applicationDisasterRecovery', v_recovery,
    'checks', v_checks
  );
end;
$function$;
revoke all on function public.get_league_management_state_v28(uuid) from public, anon;
grant execute on function public.get_league_management_state_v28(uuid) to authenticated;

-- Helper temporaneo per drenare outbox e inbox durante il rollout v0.62.40.
create or replace function public.seed_leghevo_disaster_recovery_drain_v1(
  p_environment_key text,
  p_destination_key text,
  p_consumer_key text,
  p_consumer_generation bigint,
  p_consumer_fencing_token uuid,
  p_delivery_fencing_token uuid
)
returns integer
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_claim jsonb;
  v_item jsonb;
  v_count integer := 0;
  v_application_fingerprint text;
  v_outcome jsonb;
begin
  loop
    v_claim := public.claim_leghevo_operational_outbox_v2(
      p_environment_key, p_destination_key,
      'leghevo-disaster-recovery-seed-worker', 4, p_delivery_fencing_token,
      p_consumer_key, p_consumer_generation, p_consumer_fencing_token,
      200, 120);
    exit when coalesce((v_claim ->> 'claimedCount')::integer, 0) = 0;
    for v_item in select item.value
      from pg_catalog.jsonb_array_elements(v_claim -> 'items') item
    loop
      v_application_fingerprint := public.leghevo_sha256_hex_v1(
        p_destination_key || '|recovery-applied|' || (v_item ->> 'messageId') || '|' ||
        (v_item ->> 'messageFingerprint'));
      v_outcome := public.apply_leghevo_operational_consumer_message_v1(
        p_environment_key, (v_item ->> 'messageId')::bigint, p_destination_key,
        (v_item ->> 'deliveryGeneration')::bigint,
        'leghevo-disaster-recovery-seed-worker', 4, p_delivery_fencing_token,
        p_consumer_key, p_consumer_generation, p_consumer_fencing_token,
        'leghevo-' || p_destination_key, v_application_fingerprint,
        gen_random_uuid(), jsonb_build_object('seedDelivery', true, 'sourceMigration', 144));
      v_count := v_count + 1;
    end loop;
  end loop;
  return v_count;
end;
$function$;
revoke all on function public.seed_leghevo_disaster_recovery_drain_v1(text,text,text,bigint,uuid,uuid)
from public, anon, authenticated, service_role;

-- Certificazione, rollout e prove di ripristino della release v0.62.40.
do $seed_release$
declare
  v_operations_consumer_token uuid := gen_random_uuid();
  v_notification_consumer_token uuid := gen_random_uuid();
  v_operations_delivery_token uuid := gen_random_uuid();
  v_notification_delivery_token uuid := gen_random_uuid();
  v_telemetry_token uuid := gen_random_uuid();
  v_outcome jsonb;
  v_checkpoint jsonb;
  v_now timestamptz := now();
begin
  if exists (
    select 1 from public.leghevo_application_release_certificates certificate
    where certificate.application_version = '0.62.40'
  ) and exists (
    select 1 from public.leghevo_disaster_recovery_drills drill
    where drill.request_id = '62400000-0000-4000-8000-000000000040'::uuid
  ) then
    return;
  end if;

  v_outcome := public.certify_leghevo_operational_consumer_v1(
    'production', 'operations_center', 'leghevo-operations-consumer', 3,
    v_operations_consumer_token, '62400000-0000-4000-8000-000000000001'::uuid,
    jsonb_build_object('sourceMigration', 144, 'contract', 'disaster-recovery-v1'));
  v_outcome := public.certify_leghevo_operational_consumer_v1(
    'production', 'notification_dispatch', 'leghevo-notification-consumer', 3,
    v_notification_consumer_token, '62400000-0000-4000-8000-000000000002'::uuid,
    jsonb_build_object('sourceMigration', 144, 'contract', 'disaster-recovery-v1'));

  if not exists (
    select 1 from public.leghevo_application_release_certificates certificate
    where certificate.application_version = '0.62.40'
  ) then
    v_outcome := public.certify_leghevo_application_release_v1(
      '0.62.40', '193b7343ae0ef5b7dbd9c1ab43eedea470a4c944d299e1ff7c05d7f8a600381d', '0.62.39', '0.62.40',
      '62400000-0000-4000-8000-000000000003'::uuid,
      jsonb_build_object('baseline', false, 'sourceMigration', 144));
    v_outcome := public.certify_leghevo_application_rollout_v1(
      'production', '0.62.40', 10, 100, 500, 3, 100,
      '62400000-0000-4000-8000-000000000004'::uuid,
      jsonb_build_object('strategy', 'certified-disaster-recovery', 'sourceMigration', 144));
    v_outcome := public.activate_leghevo_release_with_rollout_v1(
      'production', '0.62.40',
      '62400000-0000-4000-8000-000000000005'::uuid,
      '62400000-0000-4000-8000-000000000006'::uuid,
      'disaster_recovery.production_activation');
    v_outcome := public.certify_leghevo_operational_telemetry_source_v1(
      'production', 'leghevo-production-observer', 5, v_telemetry_token,
      '62400000-0000-4000-8000-000000000007'::uuid,
      jsonb_build_object('provider', 'leghevo-runtime', 'sourceMigration', 144));

    v_outcome := public.record_leghevo_authoritative_operational_window_v1(
      'production', 'leghevo-production-observer', 5, v_telemetry_token, 1,
      v_now - interval '25 minutes', v_now - interval '20 minutes',
      1000, 2, 0, 210,
      '62400000-0000-4000-8000-000000000008'::uuid,
      jsonb_build_object('seedStage', 10));
    perform public.seed_leghevo_disaster_recovery_drain_v1('production','operations_center','leghevo-operations-consumer',3,v_operations_consumer_token,v_operations_delivery_token);
    perform public.seed_leghevo_disaster_recovery_drain_v1('production','notification_dispatch','leghevo-notification-consumer',3,v_notification_consumer_token,v_notification_delivery_token);
    v_outcome := public.run_leghevo_operational_delivery_audit_v1('production','62400000-0000-4000-8000-000000000009'::uuid,jsonb_build_object('seedStage',10));
    v_checkpoint := public.create_leghevo_disaster_recovery_checkpoint_v1('production','62400000-0000-4000-8000-000000000010'::uuid,'disaster_recovery.rollout_10',jsonb_build_object('seedStage',10));
    v_outcome := public.run_leghevo_disaster_recovery_drill_v1('production',(v_checkpoint ->> 'checkpointId')::bigint,'62400000-0000-4000-8000-000000000011'::uuid,jsonb_build_object('seedStage',10));
    v_outcome := public.promote_leghevo_application_rollout_v6('production',35,'62400000-0000-4000-8000-000000000012'::uuid,'rollout.disaster_recovery_promotion_35');

    perform public.seed_leghevo_disaster_recovery_drain_v1('production','operations_center','leghevo-operations-consumer',3,v_operations_consumer_token,v_operations_delivery_token);
    perform public.seed_leghevo_disaster_recovery_drain_v1('production','notification_dispatch','leghevo-notification-consumer',3,v_notification_consumer_token,v_notification_delivery_token);
    v_outcome := public.record_leghevo_authoritative_operational_window_v1(
      'production', 'leghevo-production-observer', 5, v_telemetry_token, 2,
      v_now - interval '20 minutes', v_now - interval '15 minutes',
      1000, 2, 0, 205,
      '62400000-0000-4000-8000-000000000013'::uuid,
      jsonb_build_object('seedStage', 35));
    perform public.seed_leghevo_disaster_recovery_drain_v1('production','operations_center','leghevo-operations-consumer',3,v_operations_consumer_token,v_operations_delivery_token);
    perform public.seed_leghevo_disaster_recovery_drain_v1('production','notification_dispatch','leghevo-notification-consumer',3,v_notification_consumer_token,v_notification_delivery_token);
    v_outcome := public.run_leghevo_operational_delivery_audit_v1('production','62400000-0000-4000-8000-000000000014'::uuid,jsonb_build_object('seedStage',35));
    v_checkpoint := public.create_leghevo_disaster_recovery_checkpoint_v1('production','62400000-0000-4000-8000-000000000015'::uuid,'disaster_recovery.rollout_35',jsonb_build_object('seedStage',35));
    v_outcome := public.run_leghevo_disaster_recovery_drill_v1('production',(v_checkpoint ->> 'checkpointId')::bigint,'62400000-0000-4000-8000-000000000016'::uuid,jsonb_build_object('seedStage',35));
    v_outcome := public.promote_leghevo_application_rollout_v6('production',60,'62400000-0000-4000-8000-000000000017'::uuid,'rollout.disaster_recovery_promotion_60');

    perform public.seed_leghevo_disaster_recovery_drain_v1('production','operations_center','leghevo-operations-consumer',3,v_operations_consumer_token,v_operations_delivery_token);
    perform public.seed_leghevo_disaster_recovery_drain_v1('production','notification_dispatch','leghevo-notification-consumer',3,v_notification_consumer_token,v_notification_delivery_token);
    v_outcome := public.record_leghevo_authoritative_operational_window_v1(
      'production', 'leghevo-production-observer', 5, v_telemetry_token, 3,
      v_now - interval '15 minutes', v_now - interval '10 minutes',
      1000, 1, 0, 200,
      '62400000-0000-4000-8000-000000000018'::uuid,
      jsonb_build_object('seedStage', 60));
    perform public.seed_leghevo_disaster_recovery_drain_v1('production','operations_center','leghevo-operations-consumer',3,v_operations_consumer_token,v_operations_delivery_token);
    perform public.seed_leghevo_disaster_recovery_drain_v1('production','notification_dispatch','leghevo-notification-consumer',3,v_notification_consumer_token,v_notification_delivery_token);
    v_outcome := public.run_leghevo_operational_delivery_audit_v1('production','62400000-0000-4000-8000-000000000019'::uuid,jsonb_build_object('seedStage',60));
    v_checkpoint := public.create_leghevo_disaster_recovery_checkpoint_v1('production','62400000-0000-4000-8000-000000000020'::uuid,'disaster_recovery.rollout_60',jsonb_build_object('seedStage',60));
    v_outcome := public.run_leghevo_disaster_recovery_drill_v1('production',(v_checkpoint ->> 'checkpointId')::bigint,'62400000-0000-4000-8000-000000000021'::uuid,jsonb_build_object('seedStage',60));
    v_outcome := public.promote_leghevo_application_rollout_v6('production',85,'62400000-0000-4000-8000-000000000022'::uuid,'rollout.disaster_recovery_promotion_85');

    perform public.seed_leghevo_disaster_recovery_drain_v1('production','operations_center','leghevo-operations-consumer',3,v_operations_consumer_token,v_operations_delivery_token);
    perform public.seed_leghevo_disaster_recovery_drain_v1('production','notification_dispatch','leghevo-notification-consumer',3,v_notification_consumer_token,v_notification_delivery_token);
    v_outcome := public.record_leghevo_authoritative_operational_window_v1(
      'production', 'leghevo-production-observer', 5, v_telemetry_token, 4,
      v_now - interval '10 minutes', v_now - interval '5 minutes',
      1000, 1, 0, 195,
      '62400000-0000-4000-8000-000000000023'::uuid,
      jsonb_build_object('seedStage', 85));
    perform public.seed_leghevo_disaster_recovery_drain_v1('production','operations_center','leghevo-operations-consumer',3,v_operations_consumer_token,v_operations_delivery_token);
    perform public.seed_leghevo_disaster_recovery_drain_v1('production','notification_dispatch','leghevo-notification-consumer',3,v_notification_consumer_token,v_notification_delivery_token);
    v_outcome := public.run_leghevo_operational_delivery_audit_v1('production','62400000-0000-4000-8000-000000000024'::uuid,jsonb_build_object('seedStage',85));
    v_checkpoint := public.create_leghevo_disaster_recovery_checkpoint_v1('production','62400000-0000-4000-8000-000000000025'::uuid,'disaster_recovery.rollout_85',jsonb_build_object('seedStage',85));
    v_outcome := public.run_leghevo_disaster_recovery_drill_v1('production',(v_checkpoint ->> 'checkpointId')::bigint,'62400000-0000-4000-8000-000000000026'::uuid,jsonb_build_object('seedStage',85));
    v_outcome := public.promote_leghevo_application_rollout_v6('production',100,'62400000-0000-4000-8000-000000000027'::uuid,'rollout.disaster_recovery_completed');

    perform public.seed_leghevo_disaster_recovery_drain_v1('production','operations_center','leghevo-operations-consumer',3,v_operations_consumer_token,v_operations_delivery_token);
    perform public.seed_leghevo_disaster_recovery_drain_v1('production','notification_dispatch','leghevo-notification-consumer',3,v_notification_consumer_token,v_notification_delivery_token);
    v_outcome := public.record_leghevo_authoritative_operational_window_v1(
      'production', 'leghevo-production-observer', 5, v_telemetry_token, 5,
      v_now - interval '5 minutes', v_now,
      1000, 1, 0, 190,
      '62400000-0000-4000-8000-000000000028'::uuid,
      jsonb_build_object('seedStage', 100, 'postCompletion', true));
    perform public.seed_leghevo_disaster_recovery_drain_v1('production','operations_center','leghevo-operations-consumer',3,v_operations_consumer_token,v_operations_delivery_token);
    perform public.seed_leghevo_disaster_recovery_drain_v1('production','notification_dispatch','leghevo-notification-consumer',3,v_notification_consumer_token,v_notification_delivery_token);
    v_outcome := public.run_leghevo_operational_delivery_audit_v1('production','62400000-0000-4000-8000-000000000029'::uuid,jsonb_build_object('seedStage',100,'closure',true));
    v_checkpoint := public.create_leghevo_disaster_recovery_checkpoint_v1('production','62400000-0000-4000-8000-000000000030'::uuid,'disaster_recovery.release_0_62_40',jsonb_build_object('seedStage',100,'closure',true));
    v_outcome := public.run_leghevo_disaster_recovery_drill_v1('production',(v_checkpoint ->> 'checkpointId')::bigint,'62400000-0000-4000-8000-000000000040'::uuid,jsonb_build_object('seedStage',100,'closure',true));
  end if;
end;
$seed_release$;

drop function if exists public.seed_leghevo_disaster_recovery_drain_v1(text,text,text,bigint,uuid,uuid);

do $realtime$
begin
  if exists (select 1 from pg_catalog.pg_publication publication where publication.pubname = 'supabase_realtime')
    and not exists (
      select 1 from pg_catalog.pg_publication_tables publication_table
      where publication_table.pubname = 'supabase_realtime'
        and publication_table.schemaname = 'public'
        and publication_table.tablename = 'leghevo_disaster_recovery_events'
    ) then
    alter publication supabase_realtime add table public.leghevo_disaster_recovery_events;
  end if;
end;
$realtime$;

create or replace function public.get_leghevo_disaster_recovery_deployment_integrity_v1()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_predecessor jsonb;
  v_predecessor_false text[];
  v_model jsonb;
  v_release jsonb;
  v_rollout jsonb;
  v_telemetry jsonb;
  v_checkpoint_mismatch bigint;
  v_component_mismatch bigint;
  v_drill_mismatch bigint;
  v_checkpoint_def text := coalesce(pg_catalog.pg_get_functiondef(
    to_regprocedure('public.create_leghevo_disaster_recovery_checkpoint_v1(text,uuid,text,jsonb)')), '');
  v_drill_def text := coalesce(pg_catalog.pg_get_functiondef(
    to_regprocedure('public.run_leghevo_disaster_recovery_drill_v1(text,bigint,uuid,jsonb)')), '');
  v_promote_def text := coalesce(pg_catalog.pg_get_functiondef(
    to_regprocedure('public.promote_leghevo_application_rollout_v6(text,integer,uuid,text)')), '');
begin
  v_predecessor := public.get_leghevo_operational_delivery_audit_deployment_integrity_v1();
  select array_agg(item.key order by item.key) into v_predecessor_false
  from pg_catalog.jsonb_each(v_predecessor) item
  where pg_catalog.jsonb_typeof(item.value) is distinct from 'boolean'
     or item.value is distinct from 'true'::jsonb;

  v_model := public.get_leghevo_disaster_recovery_model_v1('production');
  v_release := public.get_leghevo_application_release_model_v1('production');
  v_rollout := public.get_leghevo_application_rollout_model_v1('production');
  v_telemetry := public.get_leghevo_operational_telemetry_model_v1('production');

  select count(*) into v_checkpoint_mismatch
  from public.leghevo_disaster_recovery_checkpoints checkpoint
  where checkpoint.checkpoint_fingerprint <>
    public.compute_leghevo_disaster_recovery_checkpoint_fingerprint_v1(
      checkpoint.environment_key, checkpoint.checkpoint_generation,
      checkpoint.snapshot_payload, checkpoint.status,
      checkpoint.contract_version);

  select count(*) into v_component_mismatch
  from public.leghevo_disaster_recovery_checkpoint_components component
  where component.component_fingerprint <>
    public.compute_leghevo_disaster_recovery_component_fingerprint_v1(
      component.environment_key, component.checkpoint_generation,
      component.component_key, component.component_payload,
      component.contract_version);

  select count(*) into v_drill_mismatch
  from public.leghevo_disaster_recovery_drills drill
  where drill.drill_fingerprint <>
    public.compute_leghevo_disaster_recovery_drill_fingerprint_v1(
      drill.checkpoint_id, drill.environment_key, drill.drill_generation,
      drill.status, drill.verified_component_count,
      drill.component_mismatch_count, drill.sequence_regression_count,
      drill.recovery_plan, drill.contract_version);

  return jsonb_build_object(
    'predecessor_ready',
      (select count(*) = 20 from pg_catalog.jsonb_each(v_predecessor))
      and coalesce(v_predecessor_false, array[]::text[]) = array[
        'client_barrier_ready','promotion_v5_ready','seed_release_ready'
      ]::text[],
    'checkpoint_table_ready', to_regclass('public.leghevo_disaster_recovery_checkpoints') is not null,
    'component_table_ready', to_regclass('public.leghevo_disaster_recovery_checkpoint_components') is not null,
    'drill_table_ready', to_regclass('public.leghevo_disaster_recovery_drills') is not null,
    'head_and_event_tables_ready',
      to_regclass('public.leghevo_disaster_recovery_heads') is not null
      and to_regclass('public.leghevo_disaster_recovery_events') is not null,
    'columns_ready',
      exists (select 1 from information_schema.columns column_info
        where column_info.table_schema = 'public'
          and column_info.table_name = 'leghevo_disaster_recovery_checkpoints'
          and column_info.column_name = 'snapshot_payload')
      and exists (select 1 from information_schema.columns column_info
        where column_info.table_schema = 'public'
          and column_info.table_name = 'leghevo_disaster_recovery_drills'
          and column_info.column_name = 'recovery_plan'),
    'constraints_ready',
      exists (select 1 from pg_catalog.pg_constraint constraint_info
        where constraint_info.conrelid = 'public.leghevo_disaster_recovery_checkpoints'::regclass
          and constraint_info.conname = 'leghevo_dr_checkpoint_generation_unique')
      and exists (select 1 from pg_catalog.pg_constraint constraint_info
        where constraint_info.conrelid = 'public.leghevo_disaster_recovery_checkpoint_components'::regclass
          and constraint_info.conname = 'leghevo_dr_component_checkpoint_key_unique')
      and exists (select 1 from pg_catalog.pg_constraint constraint_info
        where constraint_info.conrelid = 'public.leghevo_disaster_recovery_drills'::regclass
          and constraint_info.conname = 'leghevo_dr_drill_checkpoint_generation_unique'),
    'indexes_ready',
      to_regclass('public.leghevo_dr_checkpoints_environment_generation_idx') is not null
      and to_regclass('public.leghevo_dr_components_checkpoint_idx') is not null
      and to_regclass('public.leghevo_dr_drills_environment_generation_idx') is not null
      and to_regclass('public.leghevo_dr_events_created_idx') is not null,
    'rls_ready',
      (select relrowsecurity from pg_catalog.pg_class where oid = 'public.leghevo_disaster_recovery_checkpoints'::regclass)
      and (select relrowsecurity from pg_catalog.pg_class where oid = 'public.leghevo_disaster_recovery_checkpoint_components'::regclass)
      and (select relrowsecurity from pg_catalog.pg_class where oid = 'public.leghevo_disaster_recovery_drills'::regclass)
      and (select relrowsecurity from pg_catalog.pg_class where oid = 'public.leghevo_disaster_recovery_heads'::regclass)
      and (select relrowsecurity from pg_catalog.pg_class where oid = 'public.leghevo_disaster_recovery_events'::regclass),
    'direct_write_blocked',
      not has_table_privilege('authenticated','public.leghevo_disaster_recovery_checkpoints','INSERT')
      and not has_table_privilege('service_role','public.leghevo_disaster_recovery_checkpoints','INSERT')
      and not has_table_privilege('authenticated','public.leghevo_disaster_recovery_heads','UPDATE'),
    'immutable_records_ready',
      (select count(*) = 4 from pg_catalog.pg_trigger trigger_info
       where trigger_info.tgname in (
         'leghevo_dr_checkpoints_guard','leghevo_dr_components_guard',
         'leghevo_dr_drills_guard','leghevo_dr_events_guard'
       ) and trigger_info.tgenabled = 'A' and not trigger_info.tgisinternal),
    'head_guard_ready',
      exists (select 1 from pg_catalog.pg_trigger trigger_info
       where trigger_info.tgrelid = 'public.leghevo_disaster_recovery_heads'::regclass
         and trigger_info.tgname = 'leghevo_dr_heads_guard'
         and trigger_info.tgenabled = 'A' and not trigger_info.tgisinternal),
    'fingerprints_ready',
      v_checkpoint_mismatch = 0 and v_component_mismatch = 0 and v_drill_mismatch = 0,
    'snapshot_rpc_ready',
      to_regprocedure('public.get_leghevo_disaster_recovery_snapshot_v1(text)') is not null
      and has_function_privilege('service_role','public.get_leghevo_disaster_recovery_snapshot_v1(text)','EXECUTE')
      and not has_function_privilege('authenticated','public.get_leghevo_disaster_recovery_snapshot_v1(text)','EXECUTE'),
    'checkpoint_rpc_ready',
      to_regprocedure('public.create_leghevo_disaster_recovery_checkpoint_v1(text,uuid,text,jsonb)') is not null
      and has_function_privilege('service_role','public.create_leghevo_disaster_recovery_checkpoint_v1(text,uuid,text,jsonb)','EXECUTE')
      and position('pg_advisory_xact_lock' in v_checkpoint_def) > 0,
    'drill_rpc_ready',
      to_regprocedure('public.run_leghevo_disaster_recovery_drill_v1(text,bigint,uuid,jsonb)') is not null
      and has_function_privilege('service_role','public.run_leghevo_disaster_recovery_drill_v1(text,bigint,uuid,jsonb)','EXECUTE')
      and position('sequence_regression_count' in v_drill_def) > 0
      and position('recovery_plan' in v_drill_def) > 0,
    'promotion_v6_ready',
      to_regprocedure('public.promote_leghevo_application_rollout_v6(text,integer,uuid,text)') is not null
      and has_function_privilege('service_role','public.promote_leghevo_application_rollout_v6(text,integer,uuid,text)','EXECUTE')
      and not has_function_privilege('service_role','public.promote_leghevo_application_rollout_v5(text,integer,uuid,text)','EXECUTE')
      and position('get_leghevo_disaster_recovery_model_v1' in v_promote_def) > 0,
    'client_and_endpoint_chain_ready',
      to_regprocedure('public.get_leghevo_client_rollout_eligibility_v6(text,text,uuid)') is not null
      and has_function_privilege('anon','public.get_leghevo_client_rollout_eligibility_v6(text,text,uuid)','EXECUTE')
      and not has_function_privilege('anon','public.get_leghevo_client_rollout_eligibility_v5(text,text,uuid)','EXECUTE')
      and to_regprocedure('public.get_league_provider_sync_health_v39(uuid)') is not null
      and to_regprocedure('public.get_league_season_state_v18(uuid)') is not null
      and to_regprocedure('public.get_league_management_state_v28(uuid)') is not null,
    'realtime_ready',
      not exists (select 1 from pg_catalog.pg_publication publication where publication.pubname = 'supabase_realtime')
      or exists (select 1 from pg_catalog.pg_publication_tables publication_table
        where publication_table.pubname = 'supabase_realtime'
          and publication_table.schemaname = 'public'
          and publication_table.tablename = 'leghevo_disaster_recovery_events'),
    'seed_recovery_ready',
      coalesce((v_release ->> 'protected')::boolean, false)
      and v_release ->> 'activeVersion' = '0.62.40'
      and coalesce((v_rollout ->> 'protected')::boolean, false)
      and v_rollout ->> 'status' = 'completed'
      and coalesce((v_rollout ->> 'exposurePercentage')::integer, 0) = 100
      and coalesce((v_telemetry ->> 'sourceGeneration')::bigint, 0) = 5
      and v_telemetry ->> 'latestReleaseVersion' = '0.62.40'
      and coalesce((v_model ->> 'protected')::boolean, false)
      and coalesce((v_model ->> 'healthy')::boolean, false)
      and coalesce((v_model ->> 'fresh')::boolean, false)
      and v_model ->> 'status' = 'certified'
      and coalesce((v_model ->> 'componentCount')::integer, 0) = 7
      and exists (select 1 from public.leghevo_application_release_certificates certificate
        where certificate.application_version = '0.62.40'
          and certificate.bundle_fingerprint = '193b7343ae0ef5b7dbd9c1ab43eedea470a4c944d299e1ff7c05d7f8a600381d')
      and to_regprocedure('public.seed_leghevo_disaster_recovery_drain_v1(text,text,text,bigint,uuid,uuid)') is null
  );
end;
$function$;

revoke all on function public.get_leghevo_disaster_recovery_deployment_integrity_v1()
from public, anon, authenticated;
grant execute on function public.get_leghevo_disaster_recovery_deployment_integrity_v1()
to service_role;

do $validate$
declare
  v_integrity jsonb;
  v_false text[];
begin
  v_integrity := public.get_leghevo_disaster_recovery_deployment_integrity_v1();
  select array_agg(item.key order by item.key) into v_false
  from pg_catalog.jsonb_each(v_integrity) item
  where pg_catalog.jsonb_typeof(item.value) is distinct from 'boolean'
     or item.value is distinct from 'true'::jsonb;

  if (select count(*) from pg_catalog.jsonb_each(v_integrity)) <> 20
    or cardinality(v_false) > 0 then
    raise exception 'Validazione v0.62.40 non superata: %. Dettaglio: %',
      coalesce(array_to_string(v_false, ', '), 'numero controlli diverso da 20'),
      v_integrity;
  end if;
end;
$validate$;

commit;

select
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'predecessor_ready')::boolean as predecessor_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'checkpoint_table_ready')::boolean as checkpoint_table_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'component_table_ready')::boolean as component_table_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'drill_table_ready')::boolean as drill_table_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'head_and_event_tables_ready')::boolean as head_and_event_tables_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'columns_ready')::boolean as columns_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'constraints_ready')::boolean as constraints_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'indexes_ready')::boolean as indexes_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'rls_ready')::boolean as rls_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'direct_write_blocked')::boolean as direct_write_blocked,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'immutable_records_ready')::boolean as immutable_records_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'head_guard_ready')::boolean as head_guard_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'fingerprints_ready')::boolean as fingerprints_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'snapshot_rpc_ready')::boolean as snapshot_rpc_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'checkpoint_rpc_ready')::boolean as checkpoint_rpc_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'drill_rpc_ready')::boolean as drill_rpc_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'promotion_v6_ready')::boolean as promotion_v6_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'client_and_endpoint_chain_ready')::boolean as client_and_endpoint_chain_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'realtime_ready')::boolean as realtime_ready,
  (public.get_leghevo_disaster_recovery_deployment_integrity_v1()->>'seed_recovery_ready')::boolean as seed_recovery_ready;
