-- LEGHEVO · consegna formazione atomica, revisionata e protetta
-- Versione applicativa: 0.59.1
-- Eseguire dopo 074_competition_model_closure.sql.
-- Script idempotente: può essere eseguito più volte.

begin;

alter table public.lineups
  add column if not exists submission_revision integer not null default 0,
  add column if not exists first_submitted_at timestamptz,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists content_hash text,
  add column if not exists last_submission_request_id uuid;

alter table public.lineups
  drop constraint if exists lineups_submission_revision_check;
alter table public.lineups
  add constraint lineups_submission_revision_check
  check (submission_revision >= 0);

alter table public.lineups
  drop constraint if exists lineups_content_hash_check;
alter table public.lineups
  add constraint lineups_content_hash_check
  check (content_hash is null or length(content_hash) = 32);

comment on column public.lineups.submission_revision is
  'Revisione progressiva della distinta. Impedisce che un dispositivo sovrascriva una versione più recente.';
comment on column public.lineups.content_hash is
  'Impronta deterministica di modulo, titolari e ordine della panchina.';
comment on column public.lineups.last_submission_request_id is
  'Chiave idempotente dell''ultima consegna effettuata dal manager.';

create or replace function public.compute_lineup_content_hash(
  p_lineup_id uuid
)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select md5(
    jsonb_build_object(
      'formation', lineup.formation,
      'starters', coalesce((
        select jsonb_agg(entry.athlete_id order by entry.slot)
        from public.lineup_entries entry
        where entry.lineup_id = lineup.id
          and entry.is_starter
      ), '[]'::jsonb),
      'bench', coalesce((
        select jsonb_agg(entry.athlete_id order by entry.slot)
        from public.lineup_entries entry
        where entry.lineup_id = lineup.id
          and not entry.is_starter
      ), '[]'::jsonb)
    )::text
  )
  from public.lineups lineup
  where lineup.id = p_lineup_id;
$$;

update public.lineups lineup
set
  submission_revision = case
    when lineup.status in ('submitted', 'locked')
      then greatest(lineup.submission_revision, 1)
    else lineup.submission_revision
  end,
  first_submitted_at = coalesce(
    lineup.first_submitted_at,
    lineup.submitted_at
  ),
  updated_at = coalesce(
    lineup.updated_at,
    lineup.submitted_at,
    now()
  ),
  content_hash = coalesce(
    lineup.content_hash,
    public.compute_lineup_content_hash(lineup.id)
  )
where lineup.status in ('submitted', 'locked');

create table if not exists public.lineup_submission_events (
  id bigint generated by default as identity primary key,
  lineup_id uuid not null
    references public.lineups(id) on delete cascade,
  league_id uuid not null
    references public.leagues(id) on delete cascade,
  fantasy_team_id uuid not null
    references public.fantasy_teams(id) on delete cascade,
  matchday_id uuid not null
    references public.matchdays(id) on delete cascade,
  actor_id uuid,
  request_id uuid not null unique,
  event_type text not null,
  revision integer not null,
  formation text not null,
  starter_ids uuid[] not null default array[]::uuid[],
  bench_ids uuid[] not null default array[]::uuid[],
  content_hash text not null,
  submitted_at timestamptz,
  response_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint lineup_submission_events_type_check
    check (event_type in ('baseline', 'submitted', 'updated')),
  constraint lineup_submission_events_revision_check
    check (revision >= 1),
  constraint lineup_submission_events_hash_check
    check (length(content_hash) = 32)
);

create index if not exists lineup_submission_events_team_matchday_idx
  on public.lineup_submission_events (
    fantasy_team_id,
    matchday_id,
    revision desc
  );

alter table public.lineup_submission_events enable row level security;

drop policy if exists lineup_submission_events_read_members
on public.lineup_submission_events;
create policy lineup_submission_events_read_members
on public.lineup_submission_events
for select to authenticated
using (public.is_league_member(league_id));

revoke all on table public.lineup_submission_events
from public, anon, authenticated;
grant select on table public.lineup_submission_events
to authenticated;

insert into public.lineup_submission_events (
  lineup_id,
  league_id,
  fantasy_team_id,
  matchday_id,
  actor_id,
  request_id,
  event_type,
  revision,
  formation,
  starter_ids,
  bench_ids,
  content_hash,
  submitted_at,
  response_payload
)
select
  lineup.id,
  team.league_id,
  lineup.fantasy_team_id,
  lineup.matchday_id,
  team.manager_id,
  gen_random_uuid(),
  'baseline',
  greatest(lineup.submission_revision, 1),
  lineup.formation,
  coalesce((
    select array_agg(entry.athlete_id order by entry.slot)
    from public.lineup_entries entry
    where entry.lineup_id = lineup.id
      and entry.is_starter
  ), array[]::uuid[]),
  coalesce((
    select array_agg(entry.athlete_id order by entry.slot)
    from public.lineup_entries entry
    where entry.lineup_id = lineup.id
      and not entry.is_starter
  ), array[]::uuid[]),
  coalesce(
    lineup.content_hash,
    public.compute_lineup_content_hash(lineup.id)
  ),
  lineup.submitted_at,
  jsonb_build_object(
    'lineupId', lineup.id,
    'revision', greatest(lineup.submission_revision, 1),
    'baseline', true
  )
from public.lineups lineup
join public.fantasy_teams team
  on team.id = lineup.fantasy_team_id
where lineup.status in ('submitted', 'locked')
  and public.compute_lineup_content_hash(lineup.id) is not null
  and not exists (
    select 1
    from public.lineup_submission_events event
    where event.lineup_id = lineup.id
      and event.revision = greatest(lineup.submission_revision, 1)
  );

create or replace function public.save_team_lineup_guarded_v1(
  p_fantasy_team_id uuid,
  p_matchday_id uuid,
  p_formation text,
  p_starter_ids uuid[],
  p_bench_ids uuid[],
  p_expected_revision integer,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_team public.fantasy_teams%rowtype;
  v_matchday public.matchdays%rowtype;
  v_existing public.lineups%rowtype;
  v_saved public.lineups%rowtype;
  v_event public.lineup_submission_events%rowtype;
  v_current_revision integer := 0;
  v_next_revision integer;
  v_hash text;
  v_event_type text;
  v_response jsonb;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if p_request_id is null then
    raise exception 'Identificativo di consegna mancante.';
  end if;

  if coalesce(p_expected_revision, 0) < 0 then
    raise exception 'Revisione formazione non valida.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'lineup:'
        || p_fantasy_team_id::text
        || ':'
        || p_matchday_id::text,
      0
    )
  );

  select event.*
  into v_event
  from public.lineup_submission_events event
  where event.request_id = p_request_id;

  if found then
    if v_event.fantasy_team_id <> p_fantasy_team_id
      or v_event.matchday_id <> p_matchday_id then
      raise exception 'La chiave di consegna è già stata utilizzata.';
    end if;

    return v_event.response_payload
      || jsonb_build_object('idempotentReplay', true);
  end if;

  select team.*
  into v_team
  from public.fantasy_teams team
  where team.id = p_fantasy_team_id
  for update;

  if not found then
    raise exception 'Squadra non trovata.';
  end if;

  if v_team.manager_id <> auth.uid() then
    raise exception 'Puoi consegnare soltanto la tua formazione.';
  end if;

  select matchday.*
  into v_matchday
  from public.matchdays matchday
  where matchday.id = p_matchday_id;

  if not found then
    raise exception 'Giornata non trovata.';
  end if;

  if now() >= v_matchday.locks_at then
    raise exception 'Formazioni bloccate. Fischio già arrivato.';
  end if;

  select lineup.*
  into v_existing
  from public.lineups lineup
  where lineup.fantasy_team_id = p_fantasy_team_id
    and lineup.matchday_id = p_matchday_id
  for update;

  if found then
    v_current_revision := coalesce(v_existing.submission_revision, 0);
  end if;

  if coalesce(p_expected_revision, 0) <> v_current_revision then
    raise exception
      'La formazione è stata aggiornata da un altro dispositivo. Aggiorna la schermata e riprova. [REVISION_CONFLICT]';
  end if;

  v_saved := public.save_team_lineup(
    p_fantasy_team_id,
    p_matchday_id,
    p_formation,
    p_starter_ids,
    p_bench_ids
  );

  v_next_revision := v_current_revision + 1;
  v_hash := public.compute_lineup_content_hash(v_saved.id);
  v_event_type := case
    when v_current_revision = 0 then 'submitted'
    else 'updated'
  end;

  update public.lineups lineup
  set
    submission_revision = v_next_revision,
    first_submitted_at = coalesce(
      lineup.first_submitted_at,
      lineup.submitted_at,
      now()
    ),
    updated_at = now(),
    content_hash = v_hash,
    last_submission_request_id = p_request_id
  where lineup.id = v_saved.id
  returning * into v_saved;

  v_response := jsonb_build_object(
    'lineupId', v_saved.id,
    'teamId', p_fantasy_team_id,
    'matchdayId', p_matchday_id,
    'revision', v_next_revision,
    'contentHash', v_hash,
    'submittedAt', v_saved.submitted_at,
    'firstSubmittedAt', v_saved.first_submitted_at,
    'updatedAt', v_saved.updated_at,
    'status', v_saved.status,
    'eventType', v_event_type,
    'idempotentReplay', false
  );

  insert into public.lineup_submission_events (
    lineup_id,
    league_id,
    fantasy_team_id,
    matchday_id,
    actor_id,
    request_id,
    event_type,
    revision,
    formation,
    starter_ids,
    bench_ids,
    content_hash,
    submitted_at,
    response_payload
  ) values (
    v_saved.id,
    v_team.league_id,
    p_fantasy_team_id,
    p_matchday_id,
    auth.uid(),
    p_request_id,
    v_event_type,
    v_next_revision,
    trim(p_formation),
    coalesce(p_starter_ids, array[]::uuid[]),
    coalesce(p_bench_ids, array[]::uuid[]),
    v_hash,
    v_saved.submitted_at,
    v_response
  );

  return v_response;
end;
$$;

create or replace function public.get_my_lineup_workspace_v2(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_workspace jsonb;
  v_team_id uuid;
  v_matchday_id uuid;
  v_locks_at timestamptz;
  v_lineup public.lineups%rowtype;
  v_starter_count integer := 0;
  v_entry_count integer := 0;
  v_current_hash text;
  v_seconds_until_lock integer := 0;
  v_integrity_ready boolean := true;
  v_can_submit boolean := false;
begin
  v_workspace := public.get_my_lineup_workspace(p_league_id);

  if not coalesce((v_workspace ->> 'available')::boolean, false) then
    return v_workspace || jsonb_build_object(
      'serverNow', now(),
      'submissionPolicy', 'guarded_v1',
      'directWritesBlocked',
        not has_table_privilege('authenticated', 'public.lineups', 'INSERT')
        and not has_table_privilege('authenticated', 'public.lineups', 'UPDATE')
        and not has_table_privilege('authenticated', 'public.lineup_entries', 'INSERT')
        and not has_table_privilege('authenticated', 'public.lineup_entries', 'UPDATE')
    );
  end if;

  v_team_id := (v_workspace ->> 'teamId')::uuid;
  v_matchday_id := (v_workspace -> 'matchday' ->> 'id')::uuid;
  v_locks_at := (v_workspace -> 'matchday' ->> 'locksAt')::timestamptz;
  v_seconds_until_lock := greatest(
    floor(extract(epoch from (v_locks_at - now())))::integer,
    0
  );

  select lineup.*
  into v_lineup
  from public.lineups lineup
  where lineup.fantasy_team_id = v_team_id
    and lineup.matchday_id = v_matchday_id;

  if found then
    select
      count(*) filter (where entry.is_starter)::integer,
      count(*)::integer
    into v_starter_count, v_entry_count
    from public.lineup_entries entry
    where entry.lineup_id = v_lineup.id;

    v_current_hash := public.compute_lineup_content_hash(v_lineup.id);
    v_integrity_ready :=
      v_starter_count = 11
      and v_entry_count >= 11
      and coalesce(v_lineup.submission_revision, 0) >= 1
      and v_lineup.content_hash is not distinct from v_current_hash;
  end if;

  v_can_submit :=
    coalesce((v_workspace ->> 'canSubmit')::boolean, false)
    and now() < v_locks_at
    and coalesce(v_lineup.status::text, 'draft') <> 'locked';

  return v_workspace || jsonb_build_object(
    'serverNow', now(),
    'secondsUntilLock', v_seconds_until_lock,
    'canSubmit', v_can_submit,
    'lockState', case
      when now() >= v_locks_at
        or coalesce(v_lineup.status::text, '') = 'locked'
        then 'locked'
      else 'open'
    end,
    'lineupRevision', coalesce(v_lineup.submission_revision, 0),
    'lineupContentHash', v_lineup.content_hash,
    'firstSubmittedAt', v_lineup.first_submitted_at,
    'updatedAt', v_lineup.updated_at,
    'lockedAt', v_lineup.locked_at,
    'submissionPolicy', 'guarded_v1',
    'integrityReady', v_integrity_ready,
    'starterCount', v_starter_count,
    'entryCount', v_entry_count,
    'directWritesBlocked',
      not has_table_privilege('authenticated', 'public.lineups', 'INSERT')
      and not has_table_privilege('authenticated', 'public.lineups', 'UPDATE')
      and not has_table_privilege('authenticated', 'public.lineup_entries', 'INSERT')
      and not has_table_privilege('authenticated', 'public.lineup_entries', 'UPDATE')
  );
end;
$$;

create or replace function public.get_league_lineup_integrity_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_lineup_count integer := 0;
  v_invalid_starter_count integer := 0;
  v_revision_issue_count integer := 0;
  v_hash_issue_count integer := 0;
  v_audit_issue_count integer := 0;
  v_direct_writes_blocked boolean := false;
  v_healthy boolean := false;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if not public.is_league_member(p_league_id)
    and not exists (
      select 1
      from public.leagues league
      where league.id = p_league_id
        and league.owner_id = auth.uid()
    ) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  select count(*)::integer
  into v_lineup_count
  from public.lineups lineup
  join public.fantasy_teams team
    on team.id = lineup.fantasy_team_id
  where team.league_id = p_league_id;

  select count(*)::integer
  into v_invalid_starter_count
  from public.lineups lineup
  join public.fantasy_teams team
    on team.id = lineup.fantasy_team_id
  where team.league_id = p_league_id
    and lineup.status in ('submitted', 'locked')
    and (
      select count(*)
      from public.lineup_entries entry
      where entry.lineup_id = lineup.id
        and entry.is_starter
    ) <> 11;

  select count(*)::integer
  into v_revision_issue_count
  from public.lineups lineup
  join public.fantasy_teams team
    on team.id = lineup.fantasy_team_id
  where team.league_id = p_league_id
    and lineup.submission_source = 'manager'
    and lineup.status in ('submitted', 'locked')
    and coalesce(lineup.submission_revision, 0) < 1;

  select count(*)::integer
  into v_hash_issue_count
  from public.lineups lineup
  join public.fantasy_teams team
    on team.id = lineup.fantasy_team_id
  where team.league_id = p_league_id
    and lineup.submission_source = 'manager'
    and lineup.status in ('submitted', 'locked')
    and lineup.content_hash is distinct from
      public.compute_lineup_content_hash(lineup.id);

  select count(*)::integer
  into v_audit_issue_count
  from public.lineups lineup
  join public.fantasy_teams team
    on team.id = lineup.fantasy_team_id
  where team.league_id = p_league_id
    and lineup.last_submission_request_id is not null
    and not exists (
      select 1
      from public.lineup_submission_events event
      where event.request_id = lineup.last_submission_request_id
        and event.lineup_id = lineup.id
    );

  v_direct_writes_blocked :=
    not has_table_privilege('authenticated', 'public.lineups', 'INSERT')
    and not has_table_privilege('authenticated', 'public.lineups', 'UPDATE')
    and not has_table_privilege('authenticated', 'public.lineups', 'DELETE')
    and not has_table_privilege('authenticated', 'public.lineup_entries', 'INSERT')
    and not has_table_privilege('authenticated', 'public.lineup_entries', 'UPDATE')
    and not has_table_privilege('authenticated', 'public.lineup_entries', 'DELETE');

  v_healthy :=
    v_invalid_starter_count = 0
    and v_revision_issue_count = 0
    and v_hash_issue_count = 0
    and v_audit_issue_count = 0
    and v_direct_writes_blocked;

  return jsonb_build_object(
    'healthy', v_healthy,
    'lineupCount', v_lineup_count,
    'invalidStarterCount', v_invalid_starter_count,
    'revisionIssueCount', v_revision_issue_count,
    'hashIssueCount', v_hash_issue_count,
    'auditIssueCount', v_audit_issue_count,
    'directWritesBlocked', v_direct_writes_blocked,
    'submissionPolicy', 'guarded_v1'
  );
end;
$$;

-- Il client può leggere le distinte, ma ogni scrittura passa dalla RPC
-- atomica. Le funzioni SECURITY DEFINER interne continuano a gestire lock,
-- recupero automatico e calcolo risultati.
revoke insert, update, delete on table public.lineups
from authenticated;
revoke insert, update, delete on table public.lineup_entries
from authenticated;

revoke all on function public.compute_lineup_content_hash(uuid)
from public, anon, authenticated;
revoke all on function public.save_team_lineup_guarded_v1(
  uuid,
  uuid,
  text,
  uuid[],
  uuid[],
  integer,
  uuid
) from public, anon;
revoke all on function public.get_my_lineup_workspace_v2(uuid)
from public, anon;
revoke all on function public.get_league_lineup_integrity_v1(uuid)
from public, anon;
revoke all on function public.save_team_lineup(
  uuid,
  uuid,
  text,
  uuid[],
  uuid[]
) from public, anon, authenticated;

grant execute on function public.save_team_lineup_guarded_v1(
  uuid,
  uuid,
  text,
  uuid[],
  uuid[],
  integer,
  uuid
) to authenticated;
grant execute on function public.get_my_lineup_workspace_v2(uuid)
to authenticated;
grant execute on function public.get_league_lineup_integrity_v1(uuid)
to authenticated;

commit;

-- Controllo finale: attesi 20 valori true.
select
  (
    select count(*) = 5
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'lineups'
      and column_name in (
        'submission_revision',
        'first_submitted_at',
        'updated_at',
        'content_hash',
        'last_submission_request_id'
      )
  ) as lineup_revision_columns_ready,
  to_regclass('public.lineup_submission_events') is not null
    as lineup_submission_audit_ready,
  to_regprocedure('public.compute_lineup_content_hash(uuid)') is not null
    as lineup_hash_function_ready,
  to_regprocedure(
    'public.save_team_lineup_guarded_v1(uuid,uuid,text,uuid[],uuid[],integer,uuid)'
  ) is not null as guarded_lineup_save_ready,
  to_regprocedure('public.get_my_lineup_workspace_v2(uuid)') is not null
    as lineup_workspace_v2_ready,
  to_regprocedure('public.get_league_lineup_integrity_v1(uuid)') is not null
    as lineup_integrity_diagnostic_ready,
  has_function_privilege(
    'authenticated',
    'public.save_team_lineup_guarded_v1(uuid,uuid,text,uuid[],uuid[],integer,uuid)',
    'EXECUTE'
  ) as authenticated_guarded_save_access_ready,
  has_function_privilege(
    'authenticated',
    'public.get_my_lineup_workspace_v2(uuid)',
    'EXECUTE'
  ) as authenticated_workspace_v2_access_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_lineup_integrity_v1(uuid)',
    'EXECUTE'
  ) as authenticated_lineup_integrity_access_ready,
  not has_function_privilege(
    'authenticated',
    'public.save_team_lineup(uuid,uuid,text,uuid[],uuid[])',
    'EXECUTE'
  ) as legacy_lineup_save_blocked,
  not has_table_privilege('authenticated', 'public.lineups', 'INSERT')
    as direct_lineup_insert_blocked,
  not has_table_privilege('authenticated', 'public.lineups', 'UPDATE')
    as direct_lineup_update_blocked,
  not has_table_privilege('authenticated', 'public.lineups', 'DELETE')
    as direct_lineup_delete_blocked,
  not has_table_privilege('authenticated', 'public.lineup_entries', 'INSERT')
    as direct_lineup_entry_insert_blocked,
  not has_table_privilege('authenticated', 'public.lineup_entries', 'UPDATE')
    as direct_lineup_entry_update_blocked,
  not has_table_privilege('authenticated', 'public.lineup_entries', 'DELETE')
    as direct_lineup_entry_delete_blocked,
  (
    select relrowsecurity
    from pg_catalog.pg_class
    where oid = 'public.lineup_submission_events'::regclass
  ) as lineup_audit_rls_ready,
  exists (
    select 1
    from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'lineup_submission_events'
      and policyname = 'lineup_submission_events_read_members'
  ) as lineup_audit_member_policy_ready,
  coalesce(
    pg_get_functiondef(
      to_regprocedure(
        'public.save_team_lineup_guarded_v1(uuid,uuid,text,uuid[],uuid[],integer,uuid)'
      )
    ) ilike '%pg_advisory_xact_lock%'
      and pg_get_functiondef(
        to_regprocedure(
          'public.save_team_lineup_guarded_v1(uuid,uuid,text,uuid[],uuid[],integer,uuid)'
        )
      ) ilike '%REVISION_CONFLICT%',
    false
  ) as lineup_concurrency_guard_ready,
  coalesce(
    pg_get_functiondef(
      to_regprocedure(
        'public.save_team_lineup_guarded_v1(uuid,uuid,text,uuid[],uuid[],integer,uuid)'
      )
    ) ilike '%idempotentReplay%'
      and pg_get_functiondef(
        to_regprocedure('public.get_my_lineup_workspace_v2(uuid)')
      ) ilike '%directWritesBlocked%',
    false
  ) as lineup_idempotency_and_workspace_guard_ready;
