-- LEGHEVO · blocco scadenza, continuità e certificazione delle distinte
-- Versione applicativa: 0.59.2
-- Eseguire dopo 075_lineup_submission_safety.sql.
-- Script idempotente: può essere eseguito più volte.

begin;

alter table public.lineups
  add column if not exists deadline_lock_revision integer not null default 0,
  add column if not exists deadline_outcome text,
  add column if not exists deadline_request_id uuid;

alter table public.lineups
  drop constraint if exists lineups_deadline_lock_revision_check;
alter table public.lineups
  add constraint lineups_deadline_lock_revision_check
  check (deadline_lock_revision >= 0);

alter table public.lineups
  drop constraint if exists lineups_deadline_outcome_check;
alter table public.lineups
  add constraint lineups_deadline_outcome_check
  check (
    deadline_outcome is null
    or deadline_outcome in ('manager', 'carried')
  );

alter table public.matchdays
  add column if not exists lineups_finalized_at timestamptz,
  add column if not exists lineup_lock_revision integer not null default 0,
  add column if not exists lineup_lock_request_id uuid,
  add column if not exists lineup_lock_hash text,
  add column if not exists lineup_lock_summary jsonb not null default '{}'::jsonb;

alter table public.matchdays
  drop constraint if exists matchdays_lineup_lock_revision_check;
alter table public.matchdays
  add constraint matchdays_lineup_lock_revision_check
  check (lineup_lock_revision >= 0);

alter table public.matchdays
  drop constraint if exists matchdays_lineup_lock_hash_check;
alter table public.matchdays
  add constraint matchdays_lineup_lock_hash_check
  check (lineup_lock_hash is null or length(lineup_lock_hash) = 32);

comment on column public.lineups.deadline_lock_revision is
  'Revisione del congelamento effettuato alla scadenza della giornata.';
comment on column public.lineups.deadline_outcome is
  'manager se consegnata dal Mister, carried se recuperata dalla giornata precedente.';
comment on column public.matchdays.lineups_finalized_at is
  'Istante in cui tutte le distinte della giornata sono state congelate o classificate come mancanti.';
comment on column public.matchdays.lineup_lock_hash is
  'Impronta deterministica degli esiti di blocco di tutte le squadre della giornata.';

create table if not exists public.lineup_deadline_events (
  id bigint generated by default as identity primary key,
  league_id uuid not null
    references public.leagues(id) on delete cascade,
  fantasy_team_id uuid not null
    references public.fantasy_teams(id) on delete cascade,
  matchday_id uuid not null
    references public.matchdays(id) on delete cascade,
  lineup_id uuid
    references public.lineups(id) on delete set null,
  source_lineup_id uuid
    references public.lineups(id) on delete set null,
  request_id uuid not null unique,
  outcome text not null,
  content_hash text,
  locks_at timestamptz not null,
  processed_at timestamptz not null default now(),
  response_payload jsonb not null default '{}'::jsonb,
  constraint lineup_deadline_events_outcome_check
    check (outcome in ('manager', 'carried', 'missing')),
  constraint lineup_deadline_events_hash_check
    check (content_hash is null or length(content_hash) = 32),
  unique (fantasy_team_id, matchday_id)
);

create index if not exists lineup_deadline_events_league_matchday_idx
  on public.lineup_deadline_events (league_id, matchday_id, outcome);

alter table public.lineup_deadline_events enable row level security;

drop policy if exists lineup_deadline_events_read_members
on public.lineup_deadline_events;
create policy lineup_deadline_events_read_members
on public.lineup_deadline_events
for select to authenticated
using (public.is_league_member(league_id));

revoke all on table public.lineup_deadline_events
from public, anon, authenticated;
grant select on table public.lineup_deadline_events
to authenticated;

create or replace function public.leghevo_stable_request_uuid(
  p_value text
)
returns uuid
language sql
immutable
security definer
set search_path = ''
as $$
  select (
    substr(md5(coalesce(p_value, '')), 1, 8)
    || '-'
    || substr(md5(coalesce(p_value, '')), 9, 4)
    || '-4'
    || substr(md5(coalesce(p_value, '')), 14, 3)
    || '-a'
    || substr(md5(coalesce(p_value, '')), 18, 3)
    || '-'
    || substr(md5(coalesce(p_value, '')), 21, 12)
  )::uuid;
$$;

revoke all on function public.leghevo_stable_request_uuid(text)
from public, anon, authenticated;

create or replace function public.prevent_lineup_mutation_after_deadline()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_matchday_id uuid;
  v_locks_at timestamptz;
  v_internal_context text;
begin
  v_internal_context := current_setting(
    'leghevo.lineup_deadline_context',
    true
  );

  if coalesce(v_internal_context, '') = 'on' then
    if tg_op = 'DELETE' then
      return old;
    end if;
    return new;
  end if;

  v_matchday_id := case
    when tg_op = 'DELETE' then old.matchday_id
    else new.matchday_id
  end;

  select matchday.locks_at
  into v_locks_at
  from public.matchdays matchday
  where matchday.id = v_matchday_id;

  if v_locks_at is not null and now() >= v_locks_at then
    raise exception
      'Formazione congelata: la scadenza della giornata è già trascorsa.';
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

create or replace function public.prevent_lineup_entry_mutation_after_deadline()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_lineup_id uuid;
  v_locks_at timestamptz;
  v_internal_context text;
begin
  v_internal_context := current_setting(
    'leghevo.lineup_deadline_context',
    true
  );

  if coalesce(v_internal_context, '') = 'on' then
    if tg_op = 'DELETE' then
      return old;
    end if;
    return new;
  end if;

  v_lineup_id := case
    when tg_op = 'DELETE' then old.lineup_id
    else new.lineup_id
  end;

  select matchday.locks_at
  into v_locks_at
  from public.lineups lineup
  join public.matchdays matchday
    on matchday.id = lineup.matchday_id
  where lineup.id = v_lineup_id;

  if v_locks_at is not null and now() >= v_locks_at then
    raise exception
      'Distinta congelata: titolari e panchina non sono più modificabili.';
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists lineups_prevent_mutation_after_deadline
on public.lineups;
create trigger lineups_prevent_mutation_after_deadline
before update or delete on public.lineups
for each row
execute function public.prevent_lineup_mutation_after_deadline();

drop trigger if exists lineup_entries_prevent_mutation_after_deadline
on public.lineup_entries;
create trigger lineup_entries_prevent_mutation_after_deadline
before insert or update or delete on public.lineup_entries
for each row
execute function public.prevent_lineup_entry_mutation_after_deadline();

create or replace function public.lock_or_carry_team_lineup_guarded_v1(
  p_fantasy_team_id uuid,
  p_matchday_id uuid,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_team public.fantasy_teams%rowtype;
  v_matchday public.matchdays%rowtype;
  v_existing_lineup public.lineups%rowtype;
  v_event public.lineup_deadline_events%rowtype;
  v_preview jsonb;
  v_lineup_id uuid;
  v_source_lineup_id uuid;
  v_outcome text;
  v_hash text;
  v_response jsonb;
begin
  if p_request_id is null then
    raise exception 'Identificativo di blocco mancante.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'lineup-deadline:'
        || p_fantasy_team_id::text
        || ':'
        || p_matchday_id::text,
      0
    )
  );

  select event.*
  into v_event
  from public.lineup_deadline_events event
  where event.request_id = p_request_id;

  if found then
    if v_event.fantasy_team_id <> p_fantasy_team_id
      or v_event.matchday_id <> p_matchday_id then
      raise exception 'La chiave di blocco è già stata utilizzata.';
    end if;

    return v_event.response_payload
      || jsonb_build_object('idempotentReplay', true);
  end if;

  select event.*
  into v_event
  from public.lineup_deadline_events event
  where event.fantasy_team_id = p_fantasy_team_id
    and event.matchday_id = p_matchday_id;

  if found then
    return v_event.response_payload
      || jsonb_build_object('idempotentReplay', true);
  end if;

  select team.*
  into v_team
  from public.fantasy_teams team
  where team.id = p_fantasy_team_id
  for update;

  if not found then
    raise exception 'Squadra non trovata.';
  end if;

  select matchday.*
  into v_matchday
  from public.matchdays matchday
  where matchday.id = p_matchday_id
  for update;

  if not found then
    raise exception 'Giornata non trovata.';
  end if;

  if not public.team_competes_on_matchday(
    p_fantasy_team_id,
    p_matchday_id
  ) then
    raise exception 'La squadra non disputa questa giornata.';
  end if;

  if now() < v_matchday.locks_at then
    return jsonb_build_object(
      'teamId', p_fantasy_team_id,
      'matchdayId', p_matchday_id,
      'outcome', 'pending',
      'locksAt', v_matchday.locks_at,
      'secondsUntilLock', greatest(
        floor(extract(epoch from (v_matchday.locks_at - now())))::integer,
        0
      ),
      'idempotentReplay', false
    );
  end if;

  select lineup.*
  into v_existing_lineup
  from public.lineups lineup
  where lineup.fantasy_team_id = p_fantasy_team_id
    and lineup.matchday_id = p_matchday_id
  for update;

  if found and v_existing_lineup.status in ('submitted', 'locked') then
    perform set_config('leghevo.lineup_deadline_context', 'on', true);

    update public.lineups lineup
    set
      status = 'locked',
      locked_at = coalesce(lineup.locked_at, v_matchday.locks_at),
      deadline_lock_revision = greatest(
        coalesce(lineup.deadline_lock_revision, 0),
        1
      ),
      deadline_outcome = coalesce(
        lineup.deadline_outcome,
        lineup.submission_source
      ),
      deadline_request_id = coalesce(
        lineup.deadline_request_id,
        p_request_id
      ),
      updated_at = greatest(
        coalesce(lineup.updated_at, v_matchday.locks_at),
        v_matchday.locks_at
      )
    where lineup.id = v_existing_lineup.id
    returning * into v_existing_lineup;

    perform set_config('leghevo.lineup_deadline_context', 'off', true);

    v_lineup_id := v_existing_lineup.id;
    v_source_lineup_id := v_existing_lineup.source_lineup_id;
    v_outcome := case
      when v_existing_lineup.submission_source = 'carried' then 'carried'
      else 'manager'
    end;
    v_hash := public.compute_lineup_content_hash(v_lineup_id);

    perform set_config('leghevo.lineup_deadline_context', 'on', true);
    update public.lineups lineup
    set
      content_hash = v_hash,
      deadline_outcome = v_outcome
    where lineup.id = v_lineup_id;
    perform set_config('leghevo.lineup_deadline_context', 'off', true);
  else
    if found then
      perform set_config('leghevo.lineup_deadline_context', 'on', true);
      delete from public.lineups lineup
      where lineup.id = v_existing_lineup.id;
      perform set_config('leghevo.lineup_deadline_context', 'off', true);
    end if;

    v_preview := public.get_reusable_lineup_preview(
      p_fantasy_team_id,
      p_matchday_id
    );

    if v_preview is null then
      v_outcome := 'missing';
      v_lineup_id := null;
      v_source_lineup_id := null;
      v_hash := null;
    else
      v_outcome := 'carried';
      v_source_lineup_id := (v_preview ->> 'sourceLineupId')::uuid;

      perform set_config('leghevo.lineup_deadline_context', 'on', true);

      insert into public.lineups (
        fantasy_team_id,
        matchday_id,
        formation,
        status,
        submitted_at,
        submission_source,
        source_lineup_id,
        locked_at,
        submission_revision,
        first_submitted_at,
        updated_at,
        deadline_lock_revision,
        deadline_outcome,
        deadline_request_id
      ) values (
        p_fantasy_team_id,
        p_matchday_id,
        v_preview ->> 'formation',
        'locked',
        v_matchday.locks_at,
        'carried',
        v_source_lineup_id,
        v_matchday.locks_at,
        1,
        v_matchday.locks_at,
        v_matchday.locks_at,
        1,
        'carried',
        p_request_id
      )
      on conflict (fantasy_team_id, matchday_id) do nothing
      returning id into v_lineup_id;

      if v_lineup_id is null then
        select lineup.id
        into v_lineup_id
        from public.lineups lineup
        where lineup.fantasy_team_id = p_fantasy_team_id
          and lineup.matchday_id = p_matchday_id;
      else
        insert into public.lineup_entries (
          lineup_id,
          athlete_id,
          slot,
          is_starter,
          captain
        )
        select
          v_lineup_id,
          item.value::uuid,
          item.ordinality::smallint,
          true,
          false
        from jsonb_array_elements_text(
          v_preview -> 'starterIds'
        ) with ordinality as item(value, ordinality);

        insert into public.lineup_entries (
          lineup_id,
          athlete_id,
          slot,
          is_starter,
          captain
        )
        select
          v_lineup_id,
          item.value::uuid,
          (11 + item.ordinality)::smallint,
          false,
          false
        from jsonb_array_elements_text(
          v_preview -> 'benchIds'
        ) with ordinality as item(value, ordinality);
      end if;

      v_hash := public.compute_lineup_content_hash(v_lineup_id);

      update public.lineups lineup
      set content_hash = v_hash
      where lineup.id = v_lineup_id;

      perform set_config('leghevo.lineup_deadline_context', 'off', true);
    end if;
  end if;

  v_response := jsonb_build_object(
    'leagueId', v_team.league_id,
    'teamId', p_fantasy_team_id,
    'matchdayId', p_matchday_id,
    'lineupId', v_lineup_id,
    'sourceLineupId', v_source_lineup_id,
    'outcome', v_outcome,
    'contentHash', v_hash,
    'locksAt', v_matchday.locks_at,
    'processedAt', now(),
    'idempotentReplay', false
  );

  insert into public.lineup_deadline_events (
    league_id,
    fantasy_team_id,
    matchday_id,
    lineup_id,
    source_lineup_id,
    request_id,
    outcome,
    content_hash,
    locks_at,
    response_payload
  ) values (
    v_team.league_id,
    p_fantasy_team_id,
    p_matchday_id,
    v_lineup_id,
    v_source_lineup_id,
    p_request_id,
    v_outcome,
    v_hash,
    v_matchday.locks_at,
    v_response
  );

  if v_outcome = 'missing' then
    perform public.create_user_notification(
      v_team.manager_id,
      v_team.league_id,
      'lineup',
      'Formazione non consegnata',
      'Non esisteva una distinta precedente valida: la giornata '
        || v_matchday.number
        || ' sarà calcolata con 0 fantapunti.',
      'lineup',
      jsonb_build_object(
        'event', 'lineup_missing',
        'matchday_id', p_matchday_id,
        'matchday_number', v_matchday.number,
        'fantasy_team_id', p_fantasy_team_id
      ),
      'lineup:missing:'
        || p_fantasy_team_id::text
        || ':'
        || p_matchday_id::text
    );
  elsif v_outcome = 'carried' then
    perform public.create_user_notification(
      v_team.manager_id,
      v_team.league_id,
      'lineup',
      'Formazione recuperata',
      'Per la giornata '
        || v_matchday.number
        || ' è stata confermata automaticamente la distinta precedente.',
      'live',
      jsonb_build_object(
        'event', 'lineup_carried',
        'matchday_id', p_matchday_id,
        'matchday_number', v_matchday.number,
        'source_lineup_id', v_source_lineup_id,
        'fantasy_team_id', p_fantasy_team_id
      ),
      'lineup:carried:'
        || p_fantasy_team_id::text
        || ':'
        || p_matchday_id::text
    );
  end if;

  return v_response;
exception
  when others then
    perform set_config('leghevo.lineup_deadline_context', 'off', true);
    raise;
end;
$$;

revoke all on function public.lock_or_carry_team_lineup_guarded_v1(
  uuid,
  uuid,
  uuid
) from public, anon, authenticated;

create or replace function public.ensure_matchday_lineups_guarded_v1(
  p_matchday_id uuid,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_matchday public.matchdays%rowtype;
  v_team_id uuid;
  v_team_request_id uuid;
  v_result jsonb;
  v_outcome text;
  v_manager_count integer := 0;
  v_carried_count integer := 0;
  v_missing_count integer := 0;
  v_pending_count integer := 0;
  v_team_count integer := 0;
  v_event_count integer := 0;
  v_hash text;
  v_summary jsonb;
begin
  if p_request_id is null then
    raise exception 'Identificativo di chiusura giornata mancante.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'matchday-lineups:' || p_matchday_id::text,
      0
    )
  );

  select matchday.*
  into v_matchday
  from public.matchdays matchday
  where matchday.id = p_matchday_id
  for update;

  if not found then
    raise exception 'Giornata non trovata.';
  end if;

  if v_matchday.lineups_finalized_at is not null then
    return v_matchday.lineup_lock_summary
      || jsonb_build_object(
        'matchdayId', p_matchday_id,
        'lineupsFinalizedAt', v_matchday.lineups_finalized_at,
        'lineupLockRevision', v_matchday.lineup_lock_revision,
        'lineupLockHash', v_matchday.lineup_lock_hash,
        'idempotentReplay', true
      );
  end if;

  if now() < v_matchday.locks_at then
    return jsonb_build_object(
      'matchdayId', p_matchday_id,
      'manager', 0,
      'carried', 0,
      'missing', 0,
      'pending', 1,
      'finalized', false,
      'locksAt', v_matchday.locks_at,
      'secondsUntilLock', greatest(
        floor(extract(epoch from (v_matchday.locks_at - now())))::integer,
        0
      ),
      'idempotentReplay', false
    );
  end if;

  for v_team_id in
    select fixture.home_team_id
    from public.fantasy_fixtures fixture
    where fixture.matchday_id = p_matchday_id

    union

    select fixture.away_team_id
    from public.fantasy_fixtures fixture
    where fixture.matchday_id = p_matchday_id
  loop
    v_team_count := v_team_count + 1;
    v_team_request_id := public.leghevo_stable_request_uuid(
      p_request_id::text || ':' || v_team_id::text
    );

    v_result := public.lock_or_carry_team_lineup_guarded_v1(
      v_team_id,
      p_matchday_id,
      v_team_request_id
    );
    v_outcome := v_result ->> 'outcome';

    if v_outcome = 'manager' then
      v_manager_count := v_manager_count + 1;
    elsif v_outcome = 'carried' then
      v_carried_count := v_carried_count + 1;
    elsif v_outcome = 'missing' then
      v_missing_count := v_missing_count + 1;
    else
      v_pending_count := v_pending_count + 1;
    end if;
  end loop;

  select
    count(*)::integer,
    md5(
      coalesce(
        string_agg(
          event.fantasy_team_id::text
            || ':'
            || event.outcome
            || ':'
            || coalesce(event.content_hash, 'missing'),
          '|'
          order by event.fantasy_team_id
        ),
        ''
      )
    )
  into v_event_count, v_hash
  from public.lineup_deadline_events event
  where event.matchday_id = p_matchday_id;

  if v_team_count = 0 then
    raise exception 'La giornata non contiene partite fantasy.';
  end if;

  if v_pending_count > 0 or v_event_count <> v_team_count then
    raise exception
      'Chiusura distinte incompleta: % squadre attese, % eventi registrati.',
      v_team_count,
      v_event_count;
  end if;

  v_summary := jsonb_build_object(
    'matchdayId', p_matchday_id,
    'manager', v_manager_count,
    'carried', v_carried_count,
    'missing', v_missing_count,
    'pending', 0,
    'teamCount', v_team_count,
    'eventCount', v_event_count,
    'finalized', true,
    'locksAt', v_matchday.locks_at,
    'lineupLockHash', v_hash,
    'idempotentReplay', false
  );

  update public.matchdays matchday
  set
    lineups_finalized_at = now(),
    lineup_lock_revision = matchday.lineup_lock_revision + 1,
    lineup_lock_request_id = p_request_id,
    lineup_lock_hash = v_hash,
    lineup_lock_summary = v_summary
  where matchday.id = p_matchday_id
  returning * into v_matchday;

  return v_summary || jsonb_build_object(
    'lineupsFinalizedAt', v_matchday.lineups_finalized_at,
    'lineupLockRevision', v_matchday.lineup_lock_revision
  );
end;
$$;

revoke all on function public.ensure_matchday_lineups_guarded_v1(
  uuid,
  uuid
) from public, anon, authenticated;

-- Compatibilità: tutte le vecchie chiamate interne passano ora dal modello protetto.
create or replace function public.lock_or_carry_team_lineup(
  p_fantasy_team_id uuid,
  p_matchday_id uuid
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_result jsonb;
begin
  v_result := public.lock_or_carry_team_lineup_guarded_v1(
    p_fantasy_team_id,
    p_matchday_id,
    public.leghevo_stable_request_uuid(
      'lineup-deadline:'
        || p_fantasy_team_id::text
        || ':'
        || p_matchday_id::text
    )
  );

  return coalesce(v_result ->> 'outcome', 'missing');
end;
$$;

revoke all on function public.lock_or_carry_team_lineup(uuid, uuid)
from public, anon, authenticated;

create or replace function public.ensure_matchday_lineups(
  p_matchday_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  return public.ensure_matchday_lineups_guarded_v1(
    p_matchday_id,
    public.leghevo_stable_request_uuid(
      'matchday-lineups:' || p_matchday_id::text
    )
  );
end;
$$;

revoke all on function public.ensure_matchday_lineups(uuid)
from public, anon, authenticated;

create or replace function public.get_my_lineup_workspace_v3(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_workspace jsonb;
  v_team_id uuid;
  v_matchday_id uuid;
  v_event public.lineup_deadline_events%rowtype;
  v_matchday public.matchdays%rowtype;
  v_deadline_outcome text;
  v_deadline_certified boolean := false;
  v_immutable boolean := false;
begin
  v_workspace := public.get_my_lineup_workspace_v2(p_league_id);

  if not coalesce((v_workspace ->> 'available')::boolean, false) then
    return v_workspace || jsonb_build_object(
      'deadlinePolicy', 'guarded_v1',
      'deadlineCertified', false,
      'deadlineEventReady',
        to_regclass('public.lineup_deadline_events') is not null,
      'immutableAfterLock', false
    );
  end if;

  v_team_id := (v_workspace ->> 'teamId')::uuid;
  v_matchday_id := (v_workspace -> 'matchday' ->> 'id')::uuid;

  select matchday.*
  into v_matchday
  from public.matchdays matchday
  where matchday.id = v_matchday_id;

  select event.*
  into v_event
  from public.lineup_deadline_events event
  where event.fantasy_team_id = v_team_id
    and event.matchday_id = v_matchday_id;

  if found then
    v_deadline_outcome := v_event.outcome;
    v_deadline_certified := true;
  elsif now() < v_matchday.locks_at then
    v_deadline_outcome := 'open';
  else
    v_deadline_outcome := 'processing';
  end if;

  v_immutable := now() >= v_matchday.locks_at
    or v_deadline_certified;

  return v_workspace || jsonb_build_object(
    'deadlinePolicy', 'guarded_v1',
    'deadlineOutcome', v_deadline_outcome,
    'deadlineCertified', v_deadline_certified,
    'deadlineProcessedAt', v_event.processed_at,
    'deadlineEventReady', true,
    'immutableAfterLock', v_immutable,
    'matchdayLineupsFinalizedAt', v_matchday.lineups_finalized_at,
    'matchdayLineupLockRevision', v_matchday.lineup_lock_revision,
    'matchdayLineupLockHash', v_matchday.lineup_lock_hash,
    'canSubmit',
      coalesce((v_workspace ->> 'canSubmit')::boolean, false)
      and not v_immutable
  );
end;
$$;

create or replace function public.get_league_lineup_integrity_v2(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_base jsonb;
  v_past_team_slots integer := 0;
  v_deadline_event_count integer := 0;
  v_missing_event_count integer := 0;
  v_locked_without_event_count integer := 0;
  v_event_without_lineup_count integer := 0;
  v_hash_issue_count integer := 0;
  v_finalization_issue_count integer := 0;
  v_triggers_ready boolean := false;
  v_healthy boolean := false;
begin
  v_base := public.get_league_lineup_integrity_v1(p_league_id);

  select count(*)::integer
  into v_past_team_slots
  from (
    select fixture.matchday_id, fixture.home_team_id as fantasy_team_id
    from public.fantasy_fixtures fixture
    join public.matchdays matchday
      on matchday.id = fixture.matchday_id
    where fixture.league_id = p_league_id
      and matchday.locks_at <= now()

    union

    select fixture.matchday_id, fixture.away_team_id as fantasy_team_id
    from public.fantasy_fixtures fixture
    join public.matchdays matchday
      on matchday.id = fixture.matchday_id
    where fixture.league_id = p_league_id
      and matchday.locks_at <= now()
  ) scheduled;

  select count(*)::integer
  into v_deadline_event_count
  from public.lineup_deadline_events event
  where event.league_id = p_league_id;

  v_missing_event_count := greatest(
    v_past_team_slots - v_deadline_event_count,
    0
  );

  select count(*)::integer
  into v_locked_without_event_count
  from public.lineups lineup
  join public.fantasy_teams team
    on team.id = lineup.fantasy_team_id
  where team.league_id = p_league_id
    and lineup.status = 'locked'
    and not exists (
      select 1
      from public.lineup_deadline_events event
      where event.fantasy_team_id = lineup.fantasy_team_id
        and event.matchday_id = lineup.matchday_id
    );

  select count(*)::integer
  into v_event_without_lineup_count
  from public.lineup_deadline_events event
  where event.league_id = p_league_id
    and event.outcome in ('manager', 'carried')
    and event.lineup_id is null;

  select count(*)::integer
  into v_hash_issue_count
  from public.lineup_deadline_events event
  where event.league_id = p_league_id
    and event.outcome in ('manager', 'carried')
    and event.content_hash is distinct from
      public.compute_lineup_content_hash(event.lineup_id);

  select count(*)::integer
  into v_finalization_issue_count
  from public.matchdays matchday
  where matchday.lineups_finalized_at is not null
    and exists (
      select 1
      from public.fantasy_fixtures fixture
      where fixture.matchday_id = matchday.id
        and fixture.league_id = p_league_id
    )
    and (
      matchday.lineup_lock_hash is null
      or matchday.lineup_lock_revision < 1
      or coalesce(
        (matchday.lineup_lock_summary ->> 'finalized')::boolean,
        false
      ) is false
    );

  select count(*) = 2
  into v_triggers_ready
  from pg_catalog.pg_trigger trigger_row
  where not trigger_row.tgisinternal
    and trigger_row.tgname in (
      'lineups_prevent_mutation_after_deadline',
      'lineup_entries_prevent_mutation_after_deadline'
    );

  v_healthy :=
    coalesce((v_base ->> 'healthy')::boolean, true)
    and v_missing_event_count = 0
    and v_locked_without_event_count = 0
    and v_event_without_lineup_count = 0
    and v_hash_issue_count = 0
    and v_finalization_issue_count = 0
    and v_triggers_ready;

  return v_base || jsonb_build_object(
    'version', 2,
    'deadlinePolicy', 'guarded_v1',
    'pastTeamSlots', v_past_team_slots,
    'deadlineEventCount', v_deadline_event_count,
    'missingDeadlineEventCount', v_missing_event_count,
    'lockedWithoutDeadlineEventCount', v_locked_without_event_count,
    'eventWithoutLineupCount', v_event_without_lineup_count,
    'deadlineHashIssueCount', v_hash_issue_count,
    'matchdayFinalizationIssueCount', v_finalization_issue_count,
    'deadlineMutationTriggersReady', v_triggers_ready,
    'healthy', v_healthy
  );
end;
$$;

revoke all on function public.prevent_lineup_mutation_after_deadline()
from public, anon, authenticated;
revoke all on function public.prevent_lineup_entry_mutation_after_deadline()
from public, anon, authenticated;

revoke all on function public.get_my_lineup_workspace_v3(uuid)
from public, anon, authenticated;
revoke all on function public.get_league_lineup_integrity_v2(uuid)
from public, anon, authenticated;

grant execute on function public.get_my_lineup_workspace_v3(uuid)
to authenticated;
grant execute on function public.get_league_lineup_integrity_v2(uuid)
to authenticated;

commit;

-- Controllo finale: attesi 20 valori true.
select
  (
    select count(*) = 3
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'lineups'
      and column_name in (
        'deadline_lock_revision',
        'deadline_outcome',
        'deadline_request_id'
      )
  ) as lineup_deadline_columns_ready,
  (
    select count(*) = 5
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'matchdays'
      and column_name in (
        'lineups_finalized_at',
        'lineup_lock_revision',
        'lineup_lock_request_id',
        'lineup_lock_hash',
        'lineup_lock_summary'
      )
  ) as matchday_lineup_lock_columns_ready,
  to_regclass('public.lineup_deadline_events') is not null
    as lineup_deadline_events_ready,
  to_regprocedure('public.leghevo_stable_request_uuid(text)') is not null
    as stable_request_uuid_ready,
  to_regprocedure(
    'public.lock_or_carry_team_lineup_guarded_v1(uuid,uuid,uuid)'
  ) is not null as guarded_team_lock_ready,
  to_regprocedure(
    'public.ensure_matchday_lineups_guarded_v1(uuid,uuid)'
  ) is not null as guarded_matchday_lock_ready,
  to_regprocedure('public.get_my_lineup_workspace_v3(uuid)') is not null
    as lineup_workspace_v3_ready,
  to_regprocedure('public.get_league_lineup_integrity_v2(uuid)') is not null
    as lineup_integrity_v2_ready,
  to_regprocedure(
    'public.prevent_lineup_mutation_after_deadline()'
  ) is not null as lineup_deadline_trigger_function_ready,
  to_regprocedure(
    'public.prevent_lineup_entry_mutation_after_deadline()'
  ) is not null as lineup_entry_deadline_trigger_function_ready,
  exists (
    select 1
    from pg_catalog.pg_trigger trigger_row
    where not trigger_row.tgisinternal
      and trigger_row.tgname = 'lineups_prevent_mutation_after_deadline'
  ) as lineup_deadline_trigger_ready,
  exists (
    select 1
    from pg_catalog.pg_trigger trigger_row
    where not trigger_row.tgisinternal
      and trigger_row.tgname = 'lineup_entries_prevent_mutation_after_deadline'
  ) as lineup_entry_deadline_trigger_ready,
  (
    select relrowsecurity
    from pg_catalog.pg_class
    where oid = 'public.lineup_deadline_events'::regclass
  ) as lineup_deadline_events_rls_ready,
  exists (
    select 1
    from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'lineup_deadline_events'
      and policyname = 'lineup_deadline_events_read_members'
  ) as lineup_deadline_member_policy_ready,
  has_function_privilege(
    'authenticated',
    'public.get_my_lineup_workspace_v3(uuid)',
    'EXECUTE'
  ) as authenticated_workspace_v3_access_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_lineup_integrity_v2(uuid)',
    'EXECUTE'
  ) as authenticated_lineup_integrity_v2_access_ready,
  not has_function_privilege(
    'authenticated',
    'public.lock_or_carry_team_lineup_guarded_v1(uuid,uuid,uuid)',
    'EXECUTE'
  ) as guarded_team_lock_not_client_callable,
  not has_function_privilege(
    'authenticated',
    'public.ensure_matchday_lineups_guarded_v1(uuid,uuid)',
    'EXECUTE'
  ) as guarded_matchday_lock_not_client_callable,
  coalesce(
    pg_get_functiondef(
      to_regprocedure(
        'public.lock_or_carry_team_lineup_guarded_v1(uuid,uuid,uuid)'
      )
    ) ilike '%pg_advisory_xact_lock%'
      and pg_get_functiondef(
        to_regprocedure(
          'public.lock_or_carry_team_lineup_guarded_v1(uuid,uuid,uuid)'
        )
      ) ilike '%idempotentReplay%',
    false
  ) as deadline_concurrency_and_idempotency_ready,
  coalesce(
    pg_get_functiondef(
      to_regprocedure('public.ensure_matchday_lineups(uuid)')
    ) ilike '%ensure_matchday_lineups_guarded_v1%'
      and pg_get_functiondef(
        to_regprocedure('public.lock_or_carry_team_lineup(uuid,uuid)')
      ) ilike '%lock_or_carry_team_lineup_guarded_v1%',
    false
  ) as legacy_internal_paths_redirected;
