-- LEGHEVO · motore protetto delle sostituzioni e certificazione panchina
-- Versione applicativa: 0.59.3
-- Eseguire dopo 076_lineup_deadline_and_continuity_safety.sql.
-- Script idempotente: può essere eseguito più volte.

begin;

create table if not exists public.lineup_resolution_runs (
  id bigint generated by default as identity primary key,
  league_id uuid not null
    references public.leagues(id) on delete cascade,
  fantasy_team_id uuid not null
    references public.fantasy_teams(id) on delete cascade,
  matchday_id uuid not null
    references public.matchdays(id) on delete cascade,
  lineup_id uuid
    references public.lineups(id) on delete set null,
  request_id uuid not null unique,
  resolution_revision integer not null,
  input_hash text not null,
  result_hash text not null,
  lineup_content_hash text,
  matchday_lineup_lock_hash text,
  max_substitutions integer not null,
  substitutions_used integer not null,
  counted_players integer not null,
  unavailable_starters integer not null,
  total_points numeric(8,2),
  is_ready boolean not null,
  resolution_payload jsonb not null default '{}'::jsonb,
  response_payload jsonb not null default '{}'::jsonb,
  processed_at timestamptz not null default now(),
  superseded_at timestamptz,
  constraint lineup_resolution_runs_revision_check
    check (resolution_revision >= 1),
  constraint lineup_resolution_runs_input_hash_check
    check (length(input_hash) = 32),
  constraint lineup_resolution_runs_result_hash_check
    check (length(result_hash) = 32),
  constraint lineup_resolution_runs_lineup_hash_check
    check (
      lineup_content_hash is null
      or length(lineup_content_hash) = 32
    ),
  constraint lineup_resolution_runs_matchday_hash_check
    check (
      matchday_lineup_lock_hash is null
      or length(matchday_lineup_lock_hash) = 32
    ),
  constraint lineup_resolution_runs_max_substitutions_check
    check (max_substitutions between 0 and 11),
  constraint lineup_resolution_runs_substitutions_used_check
    check (
      substitutions_used between 0 and 11
      and substitutions_used <= max_substitutions
    ),
  constraint lineup_resolution_runs_counted_players_check
    check (counted_players between 0 and 11),
  constraint lineup_resolution_runs_unavailable_starters_check
    check (unavailable_starters between 0 and 11),
  unique (fantasy_team_id, matchday_id, resolution_revision),
  unique (fantasy_team_id, matchday_id, input_hash)
);

create unique index if not exists lineup_resolution_runs_current_idx
  on public.lineup_resolution_runs (fantasy_team_id, matchday_id)
  where superseded_at is null;

create index if not exists lineup_resolution_runs_league_matchday_idx
  on public.lineup_resolution_runs (
    league_id,
    matchday_id,
    superseded_at
  );

create table if not exists public.lineup_substitution_events (
  id bigint generated by default as identity primary key,
  resolution_id bigint not null
    references public.lineup_resolution_runs(id) on delete cascade,
  league_id uuid not null
    references public.leagues(id) on delete cascade,
  fantasy_team_id uuid not null
    references public.fantasy_teams(id) on delete cascade,
  matchday_id uuid not null
    references public.matchdays(id) on delete cascade,
  lineup_id uuid not null
    references public.lineups(id) on delete cascade,
  substitution_sequence smallint not null,
  outgoing_athlete_id uuid not null
    references public.athletes(id),
  incoming_athlete_id uuid not null
    references public.athletes(id),
  starter_slot smallint not null,
  bench_slot smallint not null,
  reason text not null default 'no_vote',
  compatibility_mode public.league_mode not null,
  event_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint lineup_substitution_events_sequence_check
    check (substitution_sequence between 1 and 11),
  constraint lineup_substitution_events_slots_check
    check (starter_slot between 1 and 11 and bench_slot > 11),
  constraint lineup_substitution_events_athletes_check
    check (outgoing_athlete_id <> incoming_athlete_id),
  constraint lineup_substitution_events_reason_check
    check (reason = 'no_vote'),
  unique (resolution_id, substitution_sequence),
  unique (resolution_id, outgoing_athlete_id),
  unique (resolution_id, incoming_athlete_id)
);

create index if not exists lineup_substitution_events_team_matchday_idx
  on public.lineup_substitution_events (
    fantasy_team_id,
    matchday_id,
    substitution_sequence
  );

alter table public.lineup_resolution_runs enable row level security;
alter table public.lineup_substitution_events enable row level security;

drop policy if exists lineup_resolution_runs_read_members
on public.lineup_resolution_runs;
create policy lineup_resolution_runs_read_members
on public.lineup_resolution_runs
for select to authenticated
using (public.is_league_member(league_id));

drop policy if exists lineup_substitution_events_read_members
on public.lineup_substitution_events;
create policy lineup_substitution_events_read_members
on public.lineup_substitution_events
for select to authenticated
using (public.is_league_member(league_id));

revoke all on table public.lineup_resolution_runs
from public, anon, authenticated;
revoke all on table public.lineup_substitution_events
from public, anon, authenticated;
grant select on table public.lineup_resolution_runs
to authenticated;
grant select on table public.lineup_substitution_events
to authenticated;

create or replace function public.prevent_substitution_resolution_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if coalesce(
    current_setting('leghevo.substitution_resolution_context', true),
    ''
  ) = 'on' then
    if tg_op = 'DELETE' then
      return old;
    end if;
    return new;
  end if;

  raise exception
    'Elaborazione sostituzioni certificata: modifica diretta non consentita.';
end;
$$;

drop trigger if exists lineup_resolution_runs_immutable
on public.lineup_resolution_runs;
create trigger lineup_resolution_runs_immutable
before update or delete on public.lineup_resolution_runs
for each row
execute function public.prevent_substitution_resolution_mutation();

drop trigger if exists lineup_substitution_events_immutable
on public.lineup_substitution_events;
create trigger lineup_substitution_events_immutable
before update or delete on public.lineup_substitution_events
for each row
execute function public.prevent_substitution_resolution_mutation();

create or replace function public.frozen_lineup_shape_is_valid_v1(
  p_lineup_id uuid
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_lineup record;
  v_starter_ids uuid[] := array[]::uuid[];
  v_starter_count integer := 0;
  v_min_slot integer;
  v_max_slot integer;
  v_distinct_slots integer := 0;
  v_goalkeepers integer := 0;
  v_defenders integer := 0;
  v_midfielders integer := 0;
  v_attackers integer := 0;
  v_expected_defenders integer;
  v_expected_midfielders integer;
  v_expected_attackers integer;
begin
  select
    lineup.id,
    lineup.formation,
    league.mode
  into v_lineup
  from public.lineups lineup
  join public.fantasy_teams team
    on team.id = lineup.fantasy_team_id
  join public.leagues league
    on league.id = team.league_id
  where lineup.id = p_lineup_id;

  if not found then
    return false;
  end if;

  select
    coalesce(
      array_agg(entry.athlete_id order by entry.slot),
      array[]::uuid[]
    ),
    count(*)::integer,
    min(entry.slot)::integer,
    max(entry.slot)::integer,
    count(distinct entry.slot)::integer
  into
    v_starter_ids,
    v_starter_count,
    v_min_slot,
    v_max_slot,
    v_distinct_slots
  from public.lineup_entries entry
  where entry.lineup_id = p_lineup_id
    and entry.is_starter;

  if v_starter_count <> 11
    or v_min_slot <> 1
    or v_max_slot <> 11
    or v_distinct_slots <> 11 then
    return false;
  end if;

  if v_lineup.mode = 'mantra' then
    return public.mantra_lineup_is_valid(
      v_lineup.formation,
      v_starter_ids
    );
  end if;

  if trim(v_lineup.formation) not in (
    '3-4-3',
    '3-5-2',
    '4-3-3',
    '4-4-2',
    '4-5-1',
    '5-3-2',
    '5-4-1'
  ) then
    return false;
  end if;

  v_expected_defenders :=
    split_part(trim(v_lineup.formation), '-', 1)::integer;
  v_expected_midfielders :=
    split_part(trim(v_lineup.formation), '-', 2)::integer;
  v_expected_attackers :=
    split_part(trim(v_lineup.formation), '-', 3)::integer;

  select
    count(*) filter (where role.role_code = 'P')::integer,
    count(*) filter (where role.role_code = 'D')::integer,
    count(*) filter (where role.role_code = 'C')::integer,
    count(*) filter (where role.role_code = 'A')::integer
  into
    v_goalkeepers,
    v_defenders,
    v_midfielders,
    v_attackers
  from unnest(v_starter_ids) as selected(athlete_id)
  join public.athlete_roles role
    on role.athlete_id = selected.athlete_id
    and role.mode = 'classic';

  return v_goalkeepers = 1
    and v_defenders = v_expected_defenders
    and v_midfielders = v_expected_midfielders
    and v_attackers = v_expected_attackers;
end;
$$;

create or replace function public.lineup_resolution_input_hash_v1(
  p_fantasy_team_id uuid,
  p_matchday_id uuid
)
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_context record;
  v_scores jsonb := '[]'::jsonb;
begin
  select
    team.league_id,
    league.mode,
    coalesce(league.scoring_rules, '{}'::jsonb) as scoring_rules,
    event.id as deadline_event_id,
    event.outcome as deadline_outcome,
    event.lineup_id,
    event.content_hash as deadline_content_hash,
    matchday.lineup_lock_hash,
    matchday.lineup_lock_revision,
    matchday.lineups_finalized_at,
    lineup.formation,
    lineup.status,
    lineup.deadline_lock_revision,
    public.compute_lineup_content_hash(lineup.id) as current_content_hash
  into v_context
  from public.fantasy_teams team
  join public.leagues league
    on league.id = team.league_id
  join public.matchdays matchday
    on matchday.id = p_matchday_id
  left join public.lineup_deadline_events event
    on event.fantasy_team_id = team.id
    and event.matchday_id = matchday.id
  left join public.lineups lineup
    on lineup.id = event.lineup_id
  where team.id = p_fantasy_team_id;

  if not found or v_context.deadline_event_id is null then
    return null;
  end if;

  if v_context.lineup_id is not null then
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'athleteId', entry.athlete_id,
          'slot', entry.slot,
          'isStarter', entry.is_starter,
          'effectiveScore',
            public.get_league_effective_player_score(
              v_context.league_id,
              entry.athlete_id,
              p_matchday_id
            )
        )
        order by entry.is_starter desc, entry.slot
      ),
      '[]'::jsonb
    )
    into v_scores
    from public.lineup_entries entry
    where entry.lineup_id = v_context.lineup_id;
  end if;

  return md5(
    jsonb_build_object(
      'teamId', p_fantasy_team_id,
      'matchdayId', p_matchday_id,
      'leagueId', v_context.league_id,
      'mode', v_context.mode,
      'scoringRules', v_context.scoring_rules,
      'deadlineEventId', v_context.deadline_event_id,
      'deadlineOutcome', v_context.deadline_outcome,
      'lineupId', v_context.lineup_id,
      'deadlineContentHash', v_context.deadline_content_hash,
      'currentContentHash', v_context.current_content_hash,
      'formation', v_context.formation,
      'lineupStatus', v_context.status,
      'deadlineLockRevision', v_context.deadline_lock_revision,
      'matchdayLineupLockHash', v_context.lineup_lock_hash,
      'matchdayLineupLockRevision', v_context.lineup_lock_revision,
      'lineupsFinalizedAt', v_context.lineups_finalized_at,
      'scores', v_scores
    )::text
  );
end;
$$;

create or replace function public.compute_team_matchday_lineup_resolution_v1(
  p_fantasy_team_id uuid,
  p_matchday_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_team public.fantasy_teams%rowtype;
  v_league public.leagues%rowtype;
  v_matchday public.matchdays%rowtype;
  v_deadline_event public.lineup_deadline_events%rowtype;
  v_lineup public.lineups%rowtype;
  v_event_found boolean := false;
  v_lineup_id uuid;
  v_matchday_complete boolean := false;
  v_max_substitutions integer := 5;
  v_substitutions_used integer := 0;
  v_counted_players integer := 0;
  v_unavailable_starters integer := 0;
  v_total_points numeric := 0;
  v_is_ready boolean := false;
  v_starter_count integer := 0;
  v_starter record;
  v_candidate record;
  v_score jsonb;
  v_effective_starter_ids uuid[] := array[]::uuid[];
  v_trial_starter_ids uuid[] := array[]::uuid[];
  v_used_bench_ids uuid[] := array[]::uuid[];
  v_effective_athlete_id uuid;
  v_effective_name text;
  v_effective_role text;
  v_provider_rating numeric;
  v_fantasy_score numeric;
  v_bonuses jsonb;
  v_maluses jsonb;
  v_raw_statistics jsonb;
  v_is_final boolean;
  v_score_origin text;
  v_is_substitute boolean;
  v_replaced_player_name text;
  v_blocked_reason text;
  v_bench_slot integer;
  v_candidate_found boolean;
  v_candidate_valid boolean;
  v_players jsonb := '[]'::jsonb;
  v_substitutions jsonb := '[]'::jsonb;
begin
  select team.*
  into v_team
  from public.fantasy_teams team
  where team.id = p_fantasy_team_id;

  if not found then
    return jsonb_build_object(
      'available', false,
      'matchdayComplete', false,
      'totalPoints', null,
      'isReady', false,
      'countedPlayers', 0,
      'maxSubstitutions', v_max_substitutions,
      'substitutionsUsed', 0,
      'unavailableStarters', 0,
      'players', v_players,
      'substitutions', v_substitutions,
      'integrityError', 'team_not_found'
    );
  end if;

  select league.*
  into v_league
  from public.leagues league
  where league.id = v_team.league_id;

  select matchday.*
  into v_matchday
  from public.matchdays matchday
  where matchday.id = p_matchday_id;

  if not found then
    return jsonb_build_object(
      'available', false,
      'matchdayComplete', false,
      'totalPoints', null,
      'isReady', false,
      'countedPlayers', 0,
      'maxSubstitutions', v_max_substitutions,
      'substitutionsUsed', 0,
      'unavailableStarters', 0,
      'players', v_players,
      'substitutions', v_substitutions,
      'integrityError', 'matchday_not_found'
    );
  end if;

  v_matchday_complete := coalesce(
    public.league_matchday_is_resolved(
      v_team.league_id,
      p_matchday_id
    ),
    false
  );
  v_is_ready := v_matchday_complete;

  if coalesce(v_league.scoring_rules ->> 'max_substitutions', '')
      ~ '^[0-9]+$' then
    v_max_substitutions := least(
      greatest(
        (v_league.scoring_rules ->> 'max_substitutions')::integer,
        0
      ),
      11
    );
  end if;

  select event.*
  into v_deadline_event
  from public.lineup_deadline_events event
  where event.fantasy_team_id = p_fantasy_team_id
    and event.matchday_id = p_matchday_id;

  v_event_found := found;

  if v_event_found then
    v_lineup_id := v_deadline_event.lineup_id;
  else
    select lineup.id
    into v_lineup_id
    from public.lineups lineup
    where lineup.fantasy_team_id = p_fantasy_team_id
      and lineup.matchday_id = p_matchday_id
      and lineup.status in ('submitted', 'locked')
    order by lineup.submitted_at desc nulls last
    limit 1;
  end if;

  if v_lineup_id is null then
    return jsonb_build_object(
      'available', false,
      'matchdayComplete', v_matchday_complete,
      'totalPoints',
        case when v_matchday_complete then 0 else null end,
      'isReady', v_matchday_complete,
      'countedPlayers', 0,
      'maxSubstitutions', v_max_substitutions,
      'substitutionsUsed', 0,
      'unavailableStarters', 0,
      'players', v_players,
      'substitutions', v_substitutions,
      'deadlineOutcome',
        case
          when v_event_found then v_deadline_event.outcome
          else 'open'
        end,
      'lineupContentHash', null
    );
  end if;

  select lineup.*
  into v_lineup
  from public.lineups lineup
  where lineup.id = v_lineup_id;

  if not found then
    return jsonb_build_object(
      'available', false,
      'matchdayComplete', v_matchday_complete,
      'totalPoints', null,
      'isReady', false,
      'countedPlayers', 0,
      'maxSubstitutions', v_max_substitutions,
      'substitutionsUsed', 0,
      'unavailableStarters', 0,
      'players', v_players,
      'substitutions', v_substitutions,
      'integrityError', 'lineup_not_found'
    );
  end if;

  select
    coalesce(
      array_agg(entry.athlete_id order by entry.slot),
      array[]::uuid[]
    ),
    count(*)::integer
  into v_effective_starter_ids, v_starter_count
  from public.lineup_entries entry
  where entry.lineup_id = v_lineup.id
    and entry.is_starter;

  if v_starter_count <> 11
    or not public.frozen_lineup_shape_is_valid_v1(v_lineup.id) then
    return jsonb_build_object(
      'available', false,
      'matchdayComplete', v_matchday_complete,
      'totalPoints', null,
      'isReady', false,
      'countedPlayers', 0,
      'maxSubstitutions', v_max_substitutions,
      'substitutionsUsed', 0,
      'unavailableStarters', 0,
      'players', v_players,
      'substitutions', v_substitutions,
      'integrityError', 'invalid_frozen_lineup',
      'lineupId', v_lineup.id,
      'lineupContentHash',
        public.compute_lineup_content_hash(v_lineup.id)
    );
  end if;

  for v_starter in
    select
      entry.athlete_id,
      entry.slot,
      concat_ws(
        ' ',
        nullif(trim(athlete.first_name), ''),
        athlete.last_name
      ) as player_name,
      coalesce(
        (
          select string_agg(
            role.role_code,
            '/' order by role.role_code
          )
          from public.athlete_roles role
          where role.athlete_id = athlete.id
            and role.mode = v_league.mode
        ),
        '—'
      ) as player_role
    from public.lineup_entries entry
    join public.athletes athlete
      on athlete.id = entry.athlete_id
    where entry.lineup_id = v_lineup.id
      and entry.is_starter
    order by entry.slot
  loop
    v_effective_athlete_id := v_starter.athlete_id;
    v_effective_name := v_starter.player_name;
    v_effective_role := v_starter.player_role;
    v_provider_rating := null;
    v_fantasy_score := null;
    v_bonuses := '{}'::jsonb;
    v_maluses := '{}'::jsonb;
    v_raw_statistics := '{}'::jsonb;
    v_is_final := false;
    v_score_origin := null;
    v_is_substitute := false;
    v_replaced_player_name := null;
    v_blocked_reason := null;
    v_bench_slot := null;
    v_candidate_found := false;

    v_score := public.get_league_effective_player_score(
      v_team.league_id,
      v_starter.athlete_id,
      p_matchday_id
    );

    if v_score is not null
      and nullif(v_score ->> 'providerRating', '') is not null then
      v_provider_rating :=
        nullif(v_score ->> 'providerRating', '')::numeric;
      v_score_origin := coalesce(
        v_score ->> 'scoreOrigin',
        'provider'
      );
      v_fantasy_score := case
        when v_score_origin = 'political' then
          nullif(v_score ->> 'fantasyScore', '')::numeric
        else public.calculate_league_fantasy_score(
          v_provider_rating,
          nullif(v_score ->> 'fantasyScore', '')::numeric,
          coalesce(v_score -> 'rawStatistics', '{}'::jsonb),
          v_league.scoring_rules
        )
      end;
      v_bonuses := coalesce(v_score -> 'bonuses', '{}'::jsonb);
      v_maluses := coalesce(v_score -> 'maluses', '{}'::jsonb);
      v_raw_statistics := coalesce(
        v_score -> 'rawStatistics',
        '{}'::jsonb
      );
      v_is_final := coalesce(
        (v_score ->> 'isFinal')::boolean,
        false
      );
    elsif not v_matchday_complete then
      v_blocked_reason := 'awaiting_score';
    elsif v_substitutions_used >= v_max_substitutions then
      v_blocked_reason := 'limit_reached';
    else
      for v_candidate in
        select
          bench.athlete_id,
          bench.slot as bench_slot,
          concat_ws(
            ' ',
            nullif(trim(athlete.first_name), ''),
            athlete.last_name
          ) as player_name,
          coalesce(
            (
              select string_agg(
                role.role_code,
                '/' order by role.role_code
              )
              from public.athlete_roles role
              where role.athlete_id = athlete.id
                and role.mode = v_league.mode
            ),
            '—'
          ) as player_role,
          nullif(effective.item ->> 'providerRating', '')::numeric
            as provider_rating,
          case
            when effective.item ->> 'scoreOrigin' = 'political' then
              nullif(effective.item ->> 'fantasyScore', '')::numeric
            else public.calculate_league_fantasy_score(
              nullif(
                effective.item ->> 'providerRating',
                ''
              )::numeric,
              nullif(
                effective.item ->> 'fantasyScore',
                ''
              )::numeric,
              coalesce(
                effective.item -> 'rawStatistics',
                '{}'::jsonb
              ),
              v_league.scoring_rules
            )
          end as fantasy_score,
          coalesce(effective.item -> 'bonuses', '{}'::jsonb)
            as bonuses,
          coalesce(effective.item -> 'maluses', '{}'::jsonb)
            as maluses,
          coalesce(
            effective.item -> 'rawStatistics',
            '{}'::jsonb
          ) as raw_statistics,
          coalesce(
            (effective.item ->> 'isFinal')::boolean,
            false
          ) as is_final,
          coalesce(
            effective.item ->> 'scoreOrigin',
            'provider'
          ) as score_origin
        from public.lineup_entries bench
        join public.athletes athlete
          on athlete.id = bench.athlete_id
        cross join lateral (
          select public.get_league_effective_player_score(
            v_team.league_id,
            bench.athlete_id,
            p_matchday_id
          ) as item
        ) effective
        where bench.lineup_id = v_lineup.id
          and not bench.is_starter
          and not (bench.athlete_id = any(v_used_bench_ids))
          and effective.item is not null
          and nullif(
            effective.item ->> 'providerRating',
            ''
          ) is not null
        order by bench.slot
      loop
        if v_league.mode = 'classic' then
          v_candidate_valid :=
            public.lineup_players_are_substitution_compatible(
              v_starter.athlete_id,
              v_candidate.athlete_id,
              v_league.mode
            );
        else
          v_trial_starter_ids := v_effective_starter_ids;
          v_trial_starter_ids[v_starter.slot] :=
            v_candidate.athlete_id;
          v_candidate_valid := public.mantra_lineup_is_valid(
            v_lineup.formation,
            v_trial_starter_ids
          );
        end if;

        if v_candidate_valid then
          v_candidate_found := true;
          exit;
        end if;
      end loop;

      if v_candidate_found then
        v_effective_athlete_id := v_candidate.athlete_id;
        v_effective_name := v_candidate.player_name;
        v_effective_role := v_candidate.player_role;
        v_provider_rating := v_candidate.provider_rating;
        v_fantasy_score := v_candidate.fantasy_score;
        v_bonuses := v_candidate.bonuses;
        v_maluses := v_candidate.maluses;
        v_raw_statistics := v_candidate.raw_statistics;
        v_is_final := v_candidate.is_final;
        v_score_origin := v_candidate.score_origin;
        v_is_substitute := true;
        v_replaced_player_name := v_starter.player_name;
        v_bench_slot := v_candidate.bench_slot;
        v_used_bench_ids := array_append(
          v_used_bench_ids,
          v_candidate.athlete_id
        );
        v_substitutions_used := v_substitutions_used + 1;
        v_effective_starter_ids[v_starter.slot] :=
          v_candidate.athlete_id;

        v_substitutions := v_substitutions || jsonb_build_array(
          jsonb_build_object(
            'sequence', v_substitutions_used,
            'outgoingAthleteId', v_starter.athlete_id,
            'outgoingPlayerName', v_starter.player_name,
            'incomingAthleteId', v_candidate.athlete_id,
            'incomingPlayerName', v_candidate.player_name,
            'starterSlot', v_starter.slot,
            'benchSlot', v_candidate.bench_slot,
            'reason', 'no_vote',
            'mode', v_league.mode,
            'formation', v_lineup.formation,
            'roleValidated', true
          )
        );
      else
        v_blocked_reason := 'no_compatible_bench';
      end if;
    end if;

    if v_provider_rating is not null then
      v_total_points := v_total_points + coalesce(
        v_fantasy_score,
        v_provider_rating,
        0
      );
      v_counted_players := v_counted_players + 1;
      v_is_ready := v_is_ready and coalesce(v_is_final, false);
    elsif v_matchday_complete then
      v_unavailable_starters := v_unavailable_starters + 1;
    end if;

    v_players := v_players || jsonb_build_array(
      jsonb_build_object(
        'athleteId', v_effective_athlete_id,
        'originalAthleteId', v_starter.athlete_id,
        'name', v_effective_name,
        'role', v_effective_role,
        'slot', v_starter.slot,
        'benchSlot', v_bench_slot,
        'providerRating', v_provider_rating,
        'fantasyScore', v_fantasy_score,
        'bonuses', coalesce(v_bonuses, '{}'::jsonb),
        'maluses', coalesce(v_maluses, '{}'::jsonb),
        'rawStatistics',
          coalesce(v_raw_statistics, '{}'::jsonb),
        'isFinal', coalesce(v_is_final, false),
        'scoreOrigin', v_score_origin,
        'isSubstitute', v_is_substitute,
        'replacedPlayerName', v_replaced_player_name,
        'blockedReason', v_blocked_reason
      )
    );
  end loop;

  if v_counted_players = 0 then
    v_total_points := case
      when v_matchday_complete then 0
      else null
    end;
  else
    v_total_points := round(v_total_points, 2);
  end if;

  return jsonb_build_object(
    'available', true,
    'matchdayComplete', v_matchday_complete,
    'totalPoints', v_total_points,
    'isReady', v_is_ready,
    'countedPlayers', v_counted_players,
    'maxSubstitutions', v_max_substitutions,
    'substitutionsUsed', v_substitutions_used,
    'unavailableStarters', v_unavailable_starters,
    'players', v_players,
    'substitutions', v_substitutions,
    'lineupId', v_lineup.id,
    'lineupContentHash',
      public.compute_lineup_content_hash(v_lineup.id),
    'deadlineOutcome',
      case
        when v_event_found then v_deadline_event.outcome
        else v_lineup.submission_source
      end,
    'formation', v_lineup.formation,
    'mode', v_league.mode
  );
end;
$$;

create or replace function public.certify_team_matchday_substitutions_guarded_v1(
  p_fantasy_team_id uuid,
  p_matchday_id uuid,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_team public.fantasy_teams%rowtype;
  v_league public.leagues%rowtype;
  v_matchday public.matchdays%rowtype;
  v_event public.lineup_deadline_events%rowtype;
  v_lineup public.lineups%rowtype;
  v_existing public.lineup_resolution_runs%rowtype;
  v_run public.lineup_resolution_runs%rowtype;
  v_input_hash text;
  v_result_hash text;
  v_resolution jsonb;
  v_response jsonb;
  v_revision integer;
  v_max_substitutions integer;
  v_substitutions_used integer;
  v_counted_players integer;
  v_unavailable_starters integer;
  v_total_points numeric;
  v_is_ready boolean;
begin
  if p_request_id is null then
    raise exception 'Identificativo elaborazione sostituzioni mancante.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'lineup-resolution:'
        || p_fantasy_team_id::text
        || ':'
        || p_matchday_id::text,
      0
    )
  );

  select team.*
  into v_team
  from public.fantasy_teams team
  where team.id = p_fantasy_team_id;

  if not found then
    raise exception 'Squadra non trovata.';
  end if;

  select league.*
  into v_league
  from public.leagues league
  where league.id = v_team.league_id;

  select matchday.*
  into v_matchday
  from public.matchdays matchday
  where matchday.id = p_matchday_id;

  if not found then
    raise exception 'Giornata non trovata.';
  end if;

  if now() < v_matchday.locks_at then
    raise exception
      'Le sostituzioni non possono essere elaborate prima della scadenza.';
  end if;

  perform public.ensure_matchday_lineups(p_matchday_id);

  select matchday.*
  into v_matchday
  from public.matchdays matchday
  where matchday.id = p_matchday_id
  for update;

  if v_matchday.lineups_finalized_at is null
    or v_matchday.lineup_lock_hash is null then
    raise exception
      'Le distinte della giornata non sono state certificate.';
  end if;

  if not coalesce(
    public.league_matchday_is_resolved(
      v_team.league_id,
      p_matchday_id
    ),
    false
  ) then
    raise exception
      'La giornata reale non è ancora completamente risolta.';
  end if;

  select event.*
  into v_event
  from public.lineup_deadline_events event
  where event.fantasy_team_id = p_fantasy_team_id
    and event.matchday_id = p_matchday_id;

  if not found then
    raise exception
      'Esito di scadenza della formazione non trovato.';
  end if;

  if v_event.outcome in ('manager', 'carried') then
    if v_event.lineup_id is null then
      raise exception
        'La distinta certificata non contiene il riferimento formazione.';
    end if;

    select lineup.*
    into v_lineup
    from public.lineups lineup
    where lineup.id = v_event.lineup_id;

    if not found
      or v_lineup.fantasy_team_id <> p_fantasy_team_id
      or v_lineup.matchday_id <> p_matchday_id
      or v_lineup.status <> 'locked'
      or v_lineup.deadline_outcome is distinct from v_event.outcome
      or v_event.content_hash is distinct from
        public.compute_lineup_content_hash(v_event.lineup_id)
      or not public.frozen_lineup_shape_is_valid_v1(
        v_event.lineup_id
      ) then
      raise exception
        'La formazione congelata non supera i controlli di integrità.';
    end if;
  elsif v_event.outcome = 'missing' then
    if v_event.lineup_id is not null then
      raise exception
        'Esito formazione mancante incoerente con una distinta presente.';
    end if;
  else
    raise exception 'Esito di scadenza formazione non valido.';
  end if;

  v_input_hash := public.lineup_resolution_input_hash_v1(
    p_fantasy_team_id,
    p_matchday_id
  );

  if v_input_hash is null then
    raise exception
      'Impossibile calcolare l''impronta dell''elaborazione.';
  end if;

  select run.*
  into v_existing
  from public.lineup_resolution_runs run
  where run.request_id = p_request_id;

  if found then
    if v_existing.fantasy_team_id <> p_fantasy_team_id
      or v_existing.matchday_id <> p_matchday_id
      or v_existing.input_hash <> v_input_hash then
      raise exception
        'La chiave di elaborazione è già stata utilizzata.';
    end if;

    if v_existing.superseded_at is not null then
      perform set_config(
        'leghevo.substitution_resolution_context',
        'on',
        true
      );

      update public.lineup_resolution_runs run
      set superseded_at = now()
      where run.fantasy_team_id = p_fantasy_team_id
        and run.matchday_id = p_matchday_id
        and run.superseded_at is null
        and run.id <> v_existing.id;

      update public.lineup_resolution_runs run
      set superseded_at = null
      where run.id = v_existing.id;
    end if;

    return v_existing.response_payload || jsonb_build_object(
      'idempotentReplay', true,
      'reactivated', v_existing.superseded_at is not null
    );
  end if;

  select run.*
  into v_existing
  from public.lineup_resolution_runs run
  where run.fantasy_team_id = p_fantasy_team_id
    and run.matchday_id = p_matchday_id
    and run.input_hash = v_input_hash;

  if found then
    if v_existing.superseded_at is not null then
      perform set_config(
        'leghevo.substitution_resolution_context',
        'on',
        true
      );

      update public.lineup_resolution_runs run
      set superseded_at = now()
      where run.fantasy_team_id = p_fantasy_team_id
        and run.matchday_id = p_matchday_id
        and run.superseded_at is null
        and run.id <> v_existing.id;

      update public.lineup_resolution_runs run
      set superseded_at = null
      where run.id = v_existing.id;
    end if;

    return v_existing.response_payload || jsonb_build_object(
      'idempotentReplay', true,
      'reactivated', v_existing.superseded_at is not null
    );
  end if;

  v_resolution := public.compute_team_matchday_lineup_resolution_v1(
    p_fantasy_team_id,
    p_matchday_id
  );

  if nullif(v_resolution ->> 'integrityError', '') is not null then
    raise exception
      'Elaborazione sostituzioni bloccata: %.',
      v_resolution ->> 'integrityError';
  end if;

  v_max_substitutions := coalesce(
    (v_resolution ->> 'maxSubstitutions')::integer,
    5
  );
  v_substitutions_used := coalesce(
    (v_resolution ->> 'substitutionsUsed')::integer,
    0
  );
  v_counted_players := coalesce(
    (v_resolution ->> 'countedPlayers')::integer,
    0
  );
  v_unavailable_starters := coalesce(
    (v_resolution ->> 'unavailableStarters')::integer,
    0
  );
  v_total_points := nullif(
    v_resolution ->> 'totalPoints',
    ''
  )::numeric;
  v_is_ready := coalesce(
    (v_resolution ->> 'isReady')::boolean,
    false
  );

  if v_substitutions_used > v_max_substitutions
    or jsonb_array_length(
      coalesce(v_resolution -> 'substitutions', '[]'::jsonb)
    ) <> v_substitutions_used then
    raise exception
      'Il risultato delle sostituzioni non supera i controlli finali.';
  end if;

  v_result_hash := md5(v_resolution::text);

  perform set_config(
    'leghevo.substitution_resolution_context',
    'on',
    true
  );

  update public.lineup_resolution_runs run
  set superseded_at = now()
  where run.fantasy_team_id = p_fantasy_team_id
    and run.matchday_id = p_matchday_id
    and run.superseded_at is null;

  select coalesce(max(run.resolution_revision), 0) + 1
  into v_revision
  from public.lineup_resolution_runs run
  where run.fantasy_team_id = p_fantasy_team_id
    and run.matchday_id = p_matchday_id;

  insert into public.lineup_resolution_runs (
    league_id,
    fantasy_team_id,
    matchday_id,
    lineup_id,
    request_id,
    resolution_revision,
    input_hash,
    result_hash,
    lineup_content_hash,
    matchday_lineup_lock_hash,
    max_substitutions,
    substitutions_used,
    counted_players,
    unavailable_starters,
    total_points,
    is_ready,
    resolution_payload,
    response_payload
  ) values (
    v_team.league_id,
    p_fantasy_team_id,
    p_matchday_id,
    v_event.lineup_id,
    p_request_id,
    v_revision,
    v_input_hash,
    v_result_hash,
    v_event.content_hash,
    v_matchday.lineup_lock_hash,
    v_max_substitutions,
    v_substitutions_used,
    v_counted_players,
    v_unavailable_starters,
    v_total_points,
    v_is_ready,
    v_resolution,
    v_resolution
  )
  returning * into v_run;

  if v_event.lineup_id is not null then
    insert into public.lineup_substitution_events (
      resolution_id,
      league_id,
      fantasy_team_id,
      matchday_id,
      lineup_id,
      substitution_sequence,
      outgoing_athlete_id,
      incoming_athlete_id,
      starter_slot,
      bench_slot,
      reason,
      compatibility_mode,
      event_payload
    )
    select
      v_run.id,
      v_team.league_id,
      p_fantasy_team_id,
      p_matchday_id,
      v_event.lineup_id,
      substitution.ordinality::smallint,
      (substitution.item ->> 'outgoingAthleteId')::uuid,
      (substitution.item ->> 'incomingAthleteId')::uuid,
      (substitution.item ->> 'starterSlot')::smallint,
      (substitution.item ->> 'benchSlot')::smallint,
      'no_vote',
      v_league.mode,
      substitution.item
    from jsonb_array_elements(
      coalesce(v_resolution -> 'substitutions', '[]'::jsonb)
    ) with ordinality as substitution(item, ordinality);
  end if;

  v_response := v_resolution || jsonb_build_object(
    'substitutionPolicy', 'guarded_v1',
    'certified', true,
    'resolutionId', v_run.id,
    'resolutionRevision', v_revision,
    'resolutionInputHash', v_input_hash,
    'resolutionHash', v_result_hash,
    'processedAt', v_run.processed_at,
    'idempotentReplay', false,
    'reactivated', false
  );

  update public.lineup_resolution_runs run
  set response_payload = v_response
  where run.id = v_run.id;

  return v_response;
end;
$$;

-- Compatibilità: risultati, classifica e Live continuano a usare lo stesso nome,
-- ma dopo la chiusura reale passano dal registro certificato e idempotente.
create or replace function public.resolve_team_matchday_lineup(
  p_fantasy_team_id uuid,
  p_matchday_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_team public.fantasy_teams%rowtype;
  v_matchday public.matchdays%rowtype;
  v_preview jsonb;
  v_input_hash text;
  v_complete boolean := false;
begin
  select team.*
  into v_team
  from public.fantasy_teams team
  where team.id = p_fantasy_team_id;

  if not found then
    return public.compute_team_matchday_lineup_resolution_v1(
      p_fantasy_team_id,
      p_matchday_id
    );
  end if;

  select matchday.*
  into v_matchday
  from public.matchdays matchday
  where matchday.id = p_matchday_id;

  if not found then
    return public.compute_team_matchday_lineup_resolution_v1(
      p_fantasy_team_id,
      p_matchday_id
    );
  end if;

  if now() >= v_matchday.locks_at then
    perform public.ensure_matchday_lineups(p_matchday_id);
  end if;

  v_complete := coalesce(
    public.league_matchday_is_resolved(
      v_team.league_id,
      p_matchday_id
    ),
    false
  );

  if not v_complete then
    v_preview := public.compute_team_matchday_lineup_resolution_v1(
      p_fantasy_team_id,
      p_matchday_id
    );

    return v_preview || jsonb_build_object(
      'substitutionPolicy', 'guarded_v1',
      'certified', false,
      'resolutionStatus', 'preview',
      'idempotentReplay', false
    );
  end if;

  v_input_hash := public.lineup_resolution_input_hash_v1(
    p_fantasy_team_id,
    p_matchday_id
  );

  if v_input_hash is null then
    raise exception
      'Distinta non certificata: impossibile elaborare le sostituzioni.';
  end if;

  return public.certify_team_matchday_substitutions_guarded_v1(
    p_fantasy_team_id,
    p_matchday_id,
    public.leghevo_stable_request_uuid(
      'lineup-resolution:'
        || p_fantasy_team_id::text
        || ':'
        || p_matchday_id::text
        || ':'
        || v_input_hash
    )
  );
end;
$$;

create or replace function public.get_league_substitution_integrity_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_resolved_team_slots integer := 0;
  v_current_resolution_count integer := 0;
  v_missing_resolution_count integer := 0;
  v_duplicate_current_count integer := 0;
  v_stale_input_count integer := 0;
  v_result_hash_issue_count integer := 0;
  v_resolution_drift_count integer := 0;
  v_event_count_issue_count integer := 0;
  v_sequence_issue_count integer := 0;
  v_limit_issue_count integer := 0;
  v_lineup_issue_count integer := 0;
  v_deadline_hash_issue_count integer := 0;
  v_triggers_ready boolean := false;
  v_healthy boolean := false;
begin
  if auth.uid() is null
    or not public.is_league_member(p_league_id) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  select count(*)::integer
  into v_resolved_team_slots
  from (
    select fixture.matchday_id, fixture.home_team_id as fantasy_team_id
    from public.fantasy_fixtures fixture
    where fixture.league_id = p_league_id
      and public.league_matchday_is_resolved(
        p_league_id,
        fixture.matchday_id
      )

    union

    select fixture.matchday_id, fixture.away_team_id as fantasy_team_id
    from public.fantasy_fixtures fixture
    where fixture.league_id = p_league_id
      and public.league_matchday_is_resolved(
        p_league_id,
        fixture.matchday_id
      )
  ) resolved_slots;

  select count(*)::integer
  into v_current_resolution_count
  from public.lineup_resolution_runs run
  where run.league_id = p_league_id
    and run.superseded_at is null;

  v_missing_resolution_count := greatest(
    v_resolved_team_slots - v_current_resolution_count,
    0
  );

  select count(*)::integer
  into v_duplicate_current_count
  from (
    select run.fantasy_team_id, run.matchday_id
    from public.lineup_resolution_runs run
    where run.league_id = p_league_id
      and run.superseded_at is null
    group by run.fantasy_team_id, run.matchday_id
    having count(*) > 1
  ) duplicates;

  select count(*)::integer
  into v_stale_input_count
  from public.lineup_resolution_runs run
  where run.league_id = p_league_id
    and run.superseded_at is null
    and run.input_hash is distinct from
      public.lineup_resolution_input_hash_v1(
        run.fantasy_team_id,
        run.matchday_id
      );

  select count(*)::integer
  into v_result_hash_issue_count
  from public.lineup_resolution_runs run
  where run.league_id = p_league_id
    and run.result_hash <> md5(run.resolution_payload::text);

  select count(*)::integer
  into v_resolution_drift_count
  from public.lineup_resolution_runs run
  where run.league_id = p_league_id
    and run.superseded_at is null
    and run.result_hash is distinct from md5(
      public.compute_team_matchday_lineup_resolution_v1(
        run.fantasy_team_id,
        run.matchday_id
      )::text
    );

  select count(*)::integer
  into v_event_count_issue_count
  from public.lineup_resolution_runs run
  where run.league_id = p_league_id
    and (
      select count(*)::integer
      from public.lineup_substitution_events event
      where event.resolution_id = run.id
    ) <> run.substitutions_used;

  select count(*)::integer
  into v_sequence_issue_count
  from (
    select event.resolution_id
    from public.lineup_substitution_events event
    join public.lineup_resolution_runs run
      on run.id = event.resolution_id
    where run.league_id = p_league_id
    group by event.resolution_id
    having min(event.substitution_sequence) <> 1
      or max(event.substitution_sequence) <> count(*)
      or count(distinct event.substitution_sequence) <> count(*)
  ) sequence_issues;

  select count(*)::integer
  into v_limit_issue_count
  from public.lineup_resolution_runs run
  where run.league_id = p_league_id
    and (
      run.substitutions_used > run.max_substitutions
      or run.substitutions_used > 11
      or run.counted_players > 11
      or run.unavailable_starters > 11
    );

  select count(*)::integer
  into v_lineup_issue_count
  from public.lineup_resolution_runs run
  where run.league_id = p_league_id
    and run.lineup_id is not null
    and (
      run.lineup_content_hash is distinct from
        public.compute_lineup_content_hash(run.lineup_id)
      or not public.frozen_lineup_shape_is_valid_v1(run.lineup_id)
    );

  select count(*)::integer
  into v_deadline_hash_issue_count
  from public.lineup_resolution_runs run
  join public.matchdays matchday
    on matchday.id = run.matchday_id
  where run.league_id = p_league_id
    and run.matchday_lineup_lock_hash is distinct from
      matchday.lineup_lock_hash;

  select count(*) = 2
  into v_triggers_ready
  from pg_catalog.pg_trigger trigger_row
  where not trigger_row.tgisinternal
    and trigger_row.tgname in (
      'lineup_resolution_runs_immutable',
      'lineup_substitution_events_immutable'
    );

  v_healthy :=
    v_missing_resolution_count = 0
    and v_duplicate_current_count = 0
    and v_stale_input_count = 0
    and v_result_hash_issue_count = 0
    and v_resolution_drift_count = 0
    and v_event_count_issue_count = 0
    and v_sequence_issue_count = 0
    and v_limit_issue_count = 0
    and v_lineup_issue_count = 0
    and v_deadline_hash_issue_count = 0
    and v_triggers_ready;

  return jsonb_build_object(
    'version', 1,
    'substitutionPolicy', 'guarded_v1',
    'resolvedTeamSlots', v_resolved_team_slots,
    'currentResolutionCount', v_current_resolution_count,
    'missingCurrentResolutionCount', v_missing_resolution_count,
    'duplicateCurrentResolutionCount', v_duplicate_current_count,
    'staleInputCount', v_stale_input_count,
    'resultHashIssueCount', v_result_hash_issue_count,
    'resolutionDriftCount', v_resolution_drift_count,
    'substitutionEventCountIssueCount', v_event_count_issue_count,
    'substitutionSequenceIssueCount', v_sequence_issue_count,
    'substitutionLimitIssueCount', v_limit_issue_count,
    'frozenLineupIssueCount', v_lineup_issue_count,
    'deadlineHashIssueCount', v_deadline_hash_issue_count,
    'immutableTriggersReady', v_triggers_ready,
    'healthy', v_healthy
  );
end;
$$;

revoke all on function public.prevent_substitution_resolution_mutation()
from public, anon, authenticated;
revoke all on function public.frozen_lineup_shape_is_valid_v1(uuid)
from public, anon, authenticated;
revoke all on function public.lineup_resolution_input_hash_v1(uuid, uuid)
from public, anon, authenticated;
revoke all on function public.compute_team_matchday_lineup_resolution_v1(
  uuid,
  uuid
) from public, anon, authenticated;
revoke all on function public.certify_team_matchday_substitutions_guarded_v1(
  uuid,
  uuid,
  uuid
) from public, anon, authenticated;
revoke all on function public.resolve_team_matchday_lineup(uuid, uuid)
from public, anon, authenticated;
revoke all on function public.get_league_substitution_integrity_v1(uuid)
from public, anon, authenticated;

grant execute on function public.get_league_substitution_integrity_v1(uuid)
to authenticated;

commit;

-- Controllo finale: attesi 20 valori true.
select
  to_regclass('public.lineup_resolution_runs') is not null
    as lineup_resolution_runs_ready,
  to_regclass('public.lineup_substitution_events') is not null
    as lineup_substitution_events_ready,
  exists (
    select 1
    from pg_catalog.pg_indexes
    where schemaname = 'public'
      and indexname = 'lineup_resolution_runs_current_idx'
  ) as single_current_resolution_index_ready,
  (
    select relrowsecurity
    from pg_catalog.pg_class
    where oid = 'public.lineup_resolution_runs'::regclass
  ) as lineup_resolution_runs_rls_ready,
  (
    select relrowsecurity
    from pg_catalog.pg_class
    where oid = 'public.lineup_substitution_events'::regclass
  ) as substitution_events_rls_ready,
  exists (
    select 1
    from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'lineup_resolution_runs'
      and policyname = 'lineup_resolution_runs_read_members'
  ) as lineup_resolution_member_policy_ready,
  exists (
    select 1
    from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'lineup_substitution_events'
      and policyname = 'lineup_substitution_events_read_members'
  ) as substitution_events_member_policy_ready,
  to_regprocedure(
    'public.frozen_lineup_shape_is_valid_v1(uuid)'
  ) is not null as frozen_lineup_validator_ready,
  to_regprocedure(
    'public.lineup_resolution_input_hash_v1(uuid,uuid)'
  ) is not null as resolution_input_hash_ready,
  to_regprocedure(
    'public.compute_team_matchday_lineup_resolution_v1(uuid,uuid)'
  ) is not null as deterministic_resolution_engine_ready,
  to_regprocedure(
    'public.certify_team_matchday_substitutions_guarded_v1(uuid,uuid,uuid)'
  ) is not null as guarded_substitution_certification_ready,
  to_regprocedure(
    'public.resolve_team_matchday_lineup(uuid,uuid)'
  ) is not null as legacy_resolution_path_ready,
  to_regprocedure(
    'public.get_league_substitution_integrity_v1(uuid)'
  ) is not null as substitution_diagnostics_ready,
  to_regprocedure(
    'public.prevent_substitution_resolution_mutation()'
  ) is not null as immutable_trigger_function_ready,
  (
    select count(*) = 2
    from pg_catalog.pg_trigger trigger_row
    where not trigger_row.tgisinternal
      and trigger_row.tgname in (
        'lineup_resolution_runs_immutable',
        'lineup_substitution_events_immutable'
      )
  ) as immutable_resolution_triggers_ready,
  not has_function_privilege(
    'authenticated',
    'public.certify_team_matchday_substitutions_guarded_v1(uuid,uuid,uuid)',
    'EXECUTE'
  ) as guarded_certification_not_client_callable,
  has_function_privilege(
    'authenticated',
    'public.get_league_substitution_integrity_v1(uuid)',
    'EXECUTE'
  ) as authenticated_diagnostics_access_ready,
  (
    not has_table_privilege(
      'authenticated',
      'public.lineup_resolution_runs',
      'INSERT'
    )
    and not has_table_privilege(
      'authenticated',
      'public.lineup_resolution_runs',
      'UPDATE'
    )
    and not has_table_privilege(
      'authenticated',
      'public.lineup_resolution_runs',
      'DELETE'
    )
    and not has_table_privilege(
      'authenticated',
      'public.lineup_substitution_events',
      'INSERT'
    )
    and not has_table_privilege(
      'authenticated',
      'public.lineup_substitution_events',
      'UPDATE'
    )
    and not has_table_privilege(
      'authenticated',
      'public.lineup_substitution_events',
      'DELETE'
    )
  ) as certified_tables_write_protected,
  coalesce(
    pg_get_functiondef(
      'public.resolve_team_matchday_lineup(uuid,uuid)'::regprocedure
    ) ilike '%certify_team_matchday_substitutions_guarded_v1%'
      and pg_get_functiondef(
        'public.resolve_team_matchday_lineup(uuid,uuid)'::regprocedure
      ) ilike '%ensure_matchday_lineups%',
    false
  ) as results_and_live_redirected_to_guarded_engine,
  coalesce(
    pg_get_functiondef(
      'public.compute_team_matchday_lineup_resolution_v1(uuid,uuid)'::regprocedure
    ) ilike '%order by bench.slot%'
      and pg_get_functiondef(
        'public.compute_team_matchday_lineup_resolution_v1(uuid,uuid)'::regprocedure
      ) ilike '%max_substitutions%'
      and pg_get_functiondef(
        'public.compute_team_matchday_lineup_resolution_v1(uuid,uuid)'::regprocedure
      ) ilike '%mantra_lineup_is_valid%'
      and pg_get_functiondef(
        'public.certify_team_matchday_substitutions_guarded_v1(uuid,uuid,uuid)'::regprocedure
      ) ilike '%pg_advisory_xact_lock%'
      and pg_get_functiondef(
        'public.certify_team_matchday_substitutions_guarded_v1(uuid,uuid,uuid)'::regprocedure
      ) ilike '%idempotentReplay%',
    false
  ) as bench_limit_roles_concurrency_and_idempotency_ready;
