-- LEGHEVO · proiezione Live giornata protetta e revisionata
-- Versione applicativa: 0.59.4
-- Migrazione prevista: database/078_live_matchday_projection_safety.sql
-- Eseguire dopo LEGHEVO_SUPABASE_GUARDED_SUBSTITUTION_ENGINE_v1.sql
-- / database/077_guarded_substitution_engine.sql.
-- Script idempotente: può essere eseguito più volte.

begin;

create table if not exists public.live_fixture_projection_runs (
  id bigint generated by default as identity primary key,
  league_id uuid not null
    references public.leagues(id) on delete cascade,
  fixture_id uuid not null
    references public.fantasy_fixtures(id) on delete cascade,
  matchday_id uuid not null
    references public.matchdays(id) on delete cascade,
  home_team_id uuid not null
    references public.fantasy_teams(id) on delete cascade,
  away_team_id uuid not null
    references public.fantasy_teams(id) on delete cascade,
  request_id uuid not null unique,
  projection_revision integer not null,
  input_hash text not null,
  result_hash text not null,
  status text not null,
  home_resolution_id bigint
    references public.lineup_resolution_runs(id) on delete set null,
  away_resolution_id bigint
    references public.lineup_resolution_runs(id) on delete set null,
  home_resolution_hash text,
  away_resolution_hash text,
  home_points numeric(8,2),
  away_points numeric(8,2),
  home_goals smallint,
  away_goals smallint,
  home_counted_players smallint not null default 0,
  away_counted_players smallint not null default 0,
  home_ready boolean not null default false,
  away_ready boolean not null default false,
  certified boolean not null default false,
  projection_payload jsonb not null default '{}'::jsonb,
  projected_at timestamptz not null default now(),
  superseded_at timestamptz,
  constraint live_fixture_projection_revision_check
    check (projection_revision >= 1),
  constraint live_fixture_projection_input_hash_check
    check (length(input_hash) = 32),
  constraint live_fixture_projection_result_hash_check
    check (length(result_hash) = 32),
  constraint live_fixture_projection_home_hash_check
    check (
      home_resolution_hash is null
      or length(home_resolution_hash) = 32
    ),
  constraint live_fixture_projection_away_hash_check
    check (
      away_resolution_hash is null
      or length(away_resolution_hash) = 32
    ),
  constraint live_fixture_projection_status_check
    check (status in ('upcoming', 'live', 'pending', 'final')),
  constraint live_fixture_projection_teams_check
    check (home_team_id <> away_team_id),
  constraint live_fixture_projection_home_count_check
    check (home_counted_players between 0 and 11),
  constraint live_fixture_projection_away_count_check
    check (away_counted_players between 0 and 11),
  constraint live_fixture_projection_home_goals_check
    check (home_goals is null or home_goals >= 0),
  constraint live_fixture_projection_away_goals_check
    check (away_goals is null or away_goals >= 0),
  unique (fixture_id, projection_revision),
  unique (fixture_id, input_hash)
);

create unique index if not exists live_fixture_projection_current_idx
  on public.live_fixture_projection_runs (fixture_id)
  where superseded_at is null;

create index if not exists live_fixture_projection_league_matchday_idx
  on public.live_fixture_projection_runs (
    league_id,
    matchday_id,
    superseded_at
  );

alter table public.live_fixture_projection_runs enable row level security;

drop policy if exists live_fixture_projection_read_members
on public.live_fixture_projection_runs;
create policy live_fixture_projection_read_members
on public.live_fixture_projection_runs
for select to authenticated
using (public.is_league_member(league_id));

revoke all on table public.live_fixture_projection_runs
from public, anon, authenticated;
grant select on table public.live_fixture_projection_runs
to authenticated;

create or replace function public.prevent_live_fixture_projection_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if coalesce(
    current_setting('leghevo.live_projection_context', true),
    ''
  ) = 'on' then
    if tg_op = 'DELETE' then
      return old;
    end if;
    return new;
  end if;

  raise exception
    'Proiezione Live certificata: modifica diretta non consentita.';
end;
$$;

drop trigger if exists live_fixture_projection_immutable
on public.live_fixture_projection_runs;
create trigger live_fixture_projection_immutable
before update or delete on public.live_fixture_projection_runs
for each row
execute function public.prevent_live_fixture_projection_mutation();

create or replace function public.live_fixture_projection_input_hash_v1(
  p_fixture_id uuid
)
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_fixture record;
  v_home_input_hash text;
  v_away_input_hash text;
begin
  select
    fixture.id,
    fixture.league_id,
    fixture.matchday_id,
    fixture.home_team_id,
    fixture.away_team_id,
    fixture.finalized_at,
    league.mode,
    coalesce(league.scoring_rules, '{}'::jsonb) as scoring_rules,
    matchday.number,
    matchday.starts_at,
    matchday.locks_at,
    matchday.ends_at,
    matchday.provider_fixture_count,
    matchday.provider_final_fixture_count,
    matchday.lineups_finalized_at,
    matchday.lineup_lock_revision,
    matchday.lineup_lock_hash
  into v_fixture
  from public.fantasy_fixtures fixture
  join public.leagues league
    on league.id = fixture.league_id
  join public.matchdays matchday
    on matchday.id = fixture.matchday_id
  where fixture.id = p_fixture_id;

  if not found then
    return null;
  end if;

  v_home_input_hash := public.lineup_resolution_input_hash_v1(
    v_fixture.home_team_id,
    v_fixture.matchday_id
  );
  v_away_input_hash := public.lineup_resolution_input_hash_v1(
    v_fixture.away_team_id,
    v_fixture.matchday_id
  );

  if v_home_input_hash is null then
    v_home_input_hash := md5(
      public.compute_team_matchday_lineup_resolution_v1(
        v_fixture.home_team_id,
        v_fixture.matchday_id
      )::text
    );
  end if;

  if v_away_input_hash is null then
    v_away_input_hash := md5(
      public.compute_team_matchday_lineup_resolution_v1(
        v_fixture.away_team_id,
        v_fixture.matchday_id
      )::text
    );
  end if;

  return md5(
    jsonb_build_object(
      'fixtureId', v_fixture.id,
      'leagueId', v_fixture.league_id,
      'matchdayId', v_fixture.matchday_id,
      'homeTeamId', v_fixture.home_team_id,
      'awayTeamId', v_fixture.away_team_id,
      'finalizedAt', v_fixture.finalized_at,
      'mode', v_fixture.mode,
      'scoringRules', v_fixture.scoring_rules,
      'matchdayNumber', v_fixture.number,
      'startsAt', v_fixture.starts_at,
      'locksAt', v_fixture.locks_at,
      'endsAt', v_fixture.ends_at,
      'providerFixtureCount', v_fixture.provider_fixture_count,
      'providerFinalFixtureCount',
        v_fixture.provider_final_fixture_count,
      'lineupsFinalizedAt', v_fixture.lineups_finalized_at,
      'lineupLockRevision', v_fixture.lineup_lock_revision,
      'lineupLockHash', v_fixture.lineup_lock_hash,
      'homeResolutionInputHash', v_home_input_hash,
      'awayResolutionInputHash', v_away_input_hash
    )::text
  );
end;
$$;

create or replace function public.compute_live_fixture_projection_v1(
  p_fixture_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_fixture record;
  v_home_resolution jsonb;
  v_away_resolution jsonb;
  v_home_modifier jsonb;
  v_away_modifier jsonb;
  v_goal_resolution jsonb;
  v_home_base_points numeric;
  v_away_base_points numeric;
  v_home_modifier_bonus numeric := 0;
  v_away_modifier_bonus numeric := 0;
  v_home_bonus numeric := 0;
  v_home_points numeric;
  v_away_points numeric;
  v_home_goals smallint;
  v_away_goals smallint;
  v_status text;
  v_home_resolution_hash text;
  v_away_resolution_hash text;
  v_home_certified boolean := false;
  v_away_certified boolean := false;
begin
  select
    fixture.id,
    fixture.league_id,
    fixture.matchday_id,
    fixture.home_team_id,
    fixture.away_team_id,
    fixture.finalized_at,
    league.name as league_name,
    league.mode,
    coalesce(league.scoring_rules, '{}'::jsonb) as scoring_rules,
    matchday.number as matchday_number,
    matchday.starts_at,
    matchday.locks_at,
    matchday.ends_at,
    home_team.name as home_team_name,
    away_team.name as away_team_name
  into v_fixture
  from public.fantasy_fixtures fixture
  join public.leagues league
    on league.id = fixture.league_id
  join public.matchdays matchday
    on matchday.id = fixture.matchday_id
  join public.fantasy_teams home_team
    on home_team.id = fixture.home_team_id
  join public.fantasy_teams away_team
    on away_team.id = fixture.away_team_id
  where fixture.id = p_fixture_id;

  if not found then
    return jsonb_build_object(
      'available', false,
      'integrityError', 'fixture_not_found'
    );
  end if;

  v_home_resolution := public.resolve_team_matchday_lineup(
    v_fixture.home_team_id,
    v_fixture.matchday_id
  );
  v_away_resolution := public.resolve_team_matchday_lineup(
    v_fixture.away_team_id,
    v_fixture.matchday_id
  );

  if nullif(v_home_resolution ->> 'integrityError', '') is not null then
    raise exception
      'Proiezione Live bloccata per la squadra di casa: %.',
      v_home_resolution ->> 'integrityError';
  end if;

  if nullif(v_away_resolution ->> 'integrityError', '') is not null then
    raise exception
      'Proiezione Live bloccata per la squadra ospite: %.',
      v_away_resolution ->> 'integrityError';
  end if;

  v_home_modifier := public.calculate_defense_modifier(
    v_home_resolution,
    v_fixture.mode,
    v_fixture.scoring_rules
  );
  v_away_modifier := public.calculate_defense_modifier(
    v_away_resolution,
    v_fixture.mode,
    v_fixture.scoring_rules
  );

  v_home_base_points := nullif(
    v_home_resolution ->> 'totalPoints',
    ''
  )::numeric;
  v_away_base_points := nullif(
    v_away_resolution ->> 'totalPoints',
    ''
  )::numeric;
  v_home_modifier_bonus := coalesce(
    nullif(v_home_modifier ->> 'bonus', '')::numeric,
    0
  );
  v_away_modifier_bonus := coalesce(
    nullif(v_away_modifier ->> 'bonus', '')::numeric,
    0
  );
  v_home_bonus := coalesce(
    nullif(v_fixture.scoring_rules ->> 'home_bonus', '')::numeric,
    0
  );

  v_home_points := case
    when v_home_base_points is null then null
    else round(
      v_home_base_points + v_home_modifier_bonus + v_home_bonus,
      2
    )
  end;
  v_away_points := case
    when v_away_base_points is null then null
    else round(v_away_base_points + v_away_modifier_bonus, 2)
  end;

  v_goal_resolution := public.resolve_fantasy_fixture_goals(
    v_home_points,
    v_away_points,
    v_fixture.scoring_rules
  );
  v_home_goals := nullif(
    v_goal_resolution ->> 'homeGoals',
    ''
  )::smallint;
  v_away_goals := nullif(
    v_goal_resolution ->> 'awayGoals',
    ''
  )::smallint;

  v_status := case
    when v_fixture.finalized_at is not null then 'final'
    when now() < v_fixture.starts_at then 'upcoming'
    when now() <= coalesce(
      v_fixture.ends_at,
      v_fixture.starts_at + interval '4 days'
    ) then 'live'
    else 'pending'
  end;

  v_home_resolution_hash := coalesce(
    nullif(v_home_resolution ->> 'resolutionHash', ''),
    md5(v_home_resolution::text)
  );
  v_away_resolution_hash := coalesce(
    nullif(v_away_resolution ->> 'resolutionHash', ''),
    md5(v_away_resolution::text)
  );
  v_home_certified := coalesce(
    nullif(v_home_resolution ->> 'certified', '')::boolean,
    false
  );
  v_away_certified := coalesce(
    nullif(v_away_resolution ->> 'certified', '')::boolean,
    false
  );

  return jsonb_build_object(
    'available', true,
    'leagueId', v_fixture.league_id,
    'leagueName', v_fixture.league_name,
    'mode', v_fixture.mode,
    'fixtureId', v_fixture.id,
    'matchdayId', v_fixture.matchday_id,
    'status', v_status,
    'certified', v_home_certified and v_away_certified,
    'matchday', jsonb_build_object(
      'id', v_fixture.matchday_id,
      'number', v_fixture.matchday_number,
      'startsAt', v_fixture.starts_at,
      'locksAt', v_fixture.locks_at,
      'endsAt', v_fixture.ends_at
    ),
    'home', jsonb_build_object(
      'teamId', v_fixture.home_team_id,
      'name', v_fixture.home_team_name,
      'points', v_home_points,
      'basePoints', v_home_base_points,
      'defenseModifier', v_home_modifier,
      'homeBonus',
        case when v_home_points is null then 0 else v_home_bonus end,
      'goals', v_home_goals,
      'countedPlayers', coalesce(
        (v_home_resolution ->> 'countedPlayers')::integer,
        0
      ),
      'ready', coalesce(
        (v_home_resolution ->> 'isReady')::boolean,
        false
      ),
      'lineupOrigin', coalesce(
        nullif(v_home_resolution ->> 'deadlineOutcome', ''),
        'missing'
      ),
      'resolutionId', nullif(
        v_home_resolution ->> 'resolutionId',
        ''
      )::bigint,
      'resolutionRevision', nullif(
        v_home_resolution ->> 'resolutionRevision',
        ''
      )::integer,
      'resolutionHash', v_home_resolution_hash,
      'resolutionStatus', coalesce(
        nullif(v_home_resolution ->> 'resolutionStatus', ''),
        case when v_home_certified then 'certified' else 'preview' end
      ),
      'substitutions', jsonb_build_object(
        'used', coalesce(
          (v_home_resolution ->> 'substitutionsUsed')::integer,
          0
        ),
        'limit', coalesce(
          (v_home_resolution ->> 'maxSubstitutions')::integer,
          5
        ),
        'unavailableStarters', coalesce(
          (v_home_resolution ->> 'unavailableStarters')::integer,
          0
        ),
        'applied', coalesce(
          (v_home_resolution ->> 'matchdayComplete')::boolean,
          false
        )
      )
    ),
    'away', jsonb_build_object(
      'teamId', v_fixture.away_team_id,
      'name', v_fixture.away_team_name,
      'points', v_away_points,
      'basePoints', v_away_base_points,
      'defenseModifier', v_away_modifier,
      'homeBonus', 0,
      'goals', v_away_goals,
      'countedPlayers', coalesce(
        (v_away_resolution ->> 'countedPlayers')::integer,
        0
      ),
      'ready', coalesce(
        (v_away_resolution ->> 'isReady')::boolean,
        false
      ),
      'lineupOrigin', coalesce(
        nullif(v_away_resolution ->> 'deadlineOutcome', ''),
        'missing'
      ),
      'resolutionId', nullif(
        v_away_resolution ->> 'resolutionId',
        ''
      )::bigint,
      'resolutionRevision', nullif(
        v_away_resolution ->> 'resolutionRevision',
        ''
      )::integer,
      'resolutionHash', v_away_resolution_hash,
      'resolutionStatus', coalesce(
        nullif(v_away_resolution ->> 'resolutionStatus', ''),
        case when v_away_certified then 'certified' else 'preview' end
      ),
      'substitutions', jsonb_build_object(
        'used', coalesce(
          (v_away_resolution ->> 'substitutionsUsed')::integer,
          0
        ),
        'limit', coalesce(
          (v_away_resolution ->> 'maxSubstitutions')::integer,
          5
        ),
        'unavailableStarters', coalesce(
          (v_away_resolution ->> 'unavailableStarters')::integer,
          0
        ),
        'applied', coalesce(
          (v_away_resolution ->> 'matchdayComplete')::boolean,
          false
        )
      )
    ),
    'goalMargin', jsonb_build_object(
      'enabled', coalesce(
        (v_goal_resolution ->> 'enabled')::boolean,
        false
      ),
      'minimum', coalesce(
        nullif(v_goal_resolution ->> 'minimum', '')::numeric,
        4
      ),
      'applied', coalesce(
        (v_goal_resolution ->> 'applied')::boolean,
        false
      ),
      'homeBonus', coalesce(
        nullif(v_goal_resolution ->> 'homeBonus', '')::integer,
        0
      ),
      'awayBonus', coalesce(
        nullif(v_goal_resolution ->> 'awayBonus', '')::integer,
        0
      )
    )
  );
end;
$$;

create or replace function public.refresh_live_fixture_projection_guarded_v1(
  p_fixture_id uuid,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_fixture public.fantasy_fixtures%rowtype;
  v_existing public.live_fixture_projection_runs%rowtype;
  v_run public.live_fixture_projection_runs%rowtype;
  v_input_hash text;
  v_result_hash text;
  v_projection jsonb;
  v_revision integer;
  v_home_resolution_id bigint;
  v_away_resolution_id bigint;
  v_home_resolution_hash text;
  v_away_resolution_hash text;
  v_status text;
  v_home_points numeric;
  v_away_points numeric;
  v_home_goals smallint;
  v_away_goals smallint;
  v_home_counted smallint;
  v_away_counted smallint;
  v_home_ready boolean;
  v_away_ready boolean;
  v_certified boolean;
begin
  if p_request_id is null then
    raise exception 'Identificativo proiezione Live mancante.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'live-fixture-projection:' || p_fixture_id::text,
      0
    )
  );

  select fixture.*
  into v_fixture
  from public.fantasy_fixtures fixture
  where fixture.id = p_fixture_id;

  if not found then
    raise exception 'Partita fantasy non trovata.';
  end if;

  if exists (
    select 1
    from public.matchdays matchday
    where matchday.id = v_fixture.matchday_id
      and now() >= matchday.locks_at
  ) then
    perform public.ensure_matchday_lineups(v_fixture.matchday_id);
  end if;

  v_input_hash := public.live_fixture_projection_input_hash_v1(
    p_fixture_id
  );

  if v_input_hash is null then
    raise exception 'Impossibile calcolare l''impronta del Live.';
  end if;

  select run.*
  into v_existing
  from public.live_fixture_projection_runs run
  where run.request_id = p_request_id;

  if found then
    if v_existing.fixture_id <> p_fixture_id
      or v_existing.input_hash <> v_input_hash then
      raise exception
        'La chiave della proiezione Live è già stata utilizzata.';
    end if;

    if v_existing.superseded_at is not null then
      perform set_config(
        'leghevo.live_projection_context',
        'on',
        true
      );

      update public.live_fixture_projection_runs run
      set superseded_at = now()
      where run.fixture_id = p_fixture_id
        and run.superseded_at is null
        and run.id <> v_existing.id;

      update public.live_fixture_projection_runs run
      set superseded_at = null
      where run.id = v_existing.id;
    end if;

    return v_existing.projection_payload || jsonb_build_object(
      'projectionId', v_existing.id,
      'projectionRevision', v_existing.projection_revision,
      'projectionInputHash', v_existing.input_hash,
      'projectionHash', v_existing.result_hash,
      'projectedAt', v_existing.projected_at,
      'idempotentReplay', true,
      'reactivated', v_existing.superseded_at is not null
    );
  end if;

  select run.*
  into v_existing
  from public.live_fixture_projection_runs run
  where run.fixture_id = p_fixture_id
    and run.input_hash = v_input_hash;

  if found then
    if v_existing.superseded_at is not null then
      perform set_config(
        'leghevo.live_projection_context',
        'on',
        true
      );

      update public.live_fixture_projection_runs run
      set superseded_at = now()
      where run.fixture_id = p_fixture_id
        and run.superseded_at is null
        and run.id <> v_existing.id;

      update public.live_fixture_projection_runs run
      set superseded_at = null
      where run.id = v_existing.id;
    end if;

    return v_existing.projection_payload || jsonb_build_object(
      'projectionId', v_existing.id,
      'projectionRevision', v_existing.projection_revision,
      'projectionInputHash', v_existing.input_hash,
      'projectionHash', v_existing.result_hash,
      'projectedAt', v_existing.projected_at,
      'idempotentReplay', true,
      'reactivated', v_existing.superseded_at is not null
    );
  end if;

  v_projection := public.compute_live_fixture_projection_v1(
    p_fixture_id
  );

  if not coalesce(
    (v_projection ->> 'available')::boolean,
    false
  ) then
    raise exception
      'Proiezione Live non disponibile: %.',
      coalesce(v_projection ->> 'integrityError', 'errore sconosciuto');
  end if;

  v_result_hash := md5(v_projection::text);
  v_home_resolution_id := nullif(
    v_projection #>> '{home,resolutionId}',
    ''
  )::bigint;
  v_away_resolution_id := nullif(
    v_projection #>> '{away,resolutionId}',
    ''
  )::bigint;
  v_home_resolution_hash := nullif(
    v_projection #>> '{home,resolutionHash}',
    ''
  );
  v_away_resolution_hash := nullif(
    v_projection #>> '{away,resolutionHash}',
    ''
  );
  v_status := v_projection ->> 'status';
  v_home_points := nullif(
    v_projection #>> '{home,points}',
    ''
  )::numeric;
  v_away_points := nullif(
    v_projection #>> '{away,points}',
    ''
  )::numeric;
  v_home_goals := nullif(
    v_projection #>> '{home,goals}',
    ''
  )::smallint;
  v_away_goals := nullif(
    v_projection #>> '{away,goals}',
    ''
  )::smallint;
  v_home_counted := coalesce(
    (v_projection #>> '{home,countedPlayers}')::smallint,
    0
  );
  v_away_counted := coalesce(
    (v_projection #>> '{away,countedPlayers}')::smallint,
    0
  );
  v_home_ready := coalesce(
    (v_projection #>> '{home,ready}')::boolean,
    false
  );
  v_away_ready := coalesce(
    (v_projection #>> '{away,ready}')::boolean,
    false
  );
  v_certified := coalesce(
    (v_projection ->> 'certified')::boolean,
    false
  );

  if v_status not in ('upcoming', 'live', 'pending', 'final')
    or v_home_counted not between 0 and 11
    or v_away_counted not between 0 and 11 then
    raise exception
      'La proiezione Live non supera i controlli finali.';
  end if;

  perform set_config(
    'leghevo.live_projection_context',
    'on',
    true
  );

  update public.live_fixture_projection_runs run
  set superseded_at = now()
  where run.fixture_id = p_fixture_id
    and run.superseded_at is null;

  select coalesce(max(run.projection_revision), 0) + 1
  into v_revision
  from public.live_fixture_projection_runs run
  where run.fixture_id = p_fixture_id;

  insert into public.live_fixture_projection_runs (
    league_id,
    fixture_id,
    matchday_id,
    home_team_id,
    away_team_id,
    request_id,
    projection_revision,
    input_hash,
    result_hash,
    status,
    home_resolution_id,
    away_resolution_id,
    home_resolution_hash,
    away_resolution_hash,
    home_points,
    away_points,
    home_goals,
    away_goals,
    home_counted_players,
    away_counted_players,
    home_ready,
    away_ready,
    certified,
    projection_payload
  ) values (
    v_fixture.league_id,
    v_fixture.id,
    v_fixture.matchday_id,
    v_fixture.home_team_id,
    v_fixture.away_team_id,
    p_request_id,
    v_revision,
    v_input_hash,
    v_result_hash,
    v_status,
    v_home_resolution_id,
    v_away_resolution_id,
    v_home_resolution_hash,
    v_away_resolution_hash,
    v_home_points,
    v_away_points,
    v_home_goals,
    v_away_goals,
    v_home_counted,
    v_away_counted,
    v_home_ready,
    v_away_ready,
    v_certified,
    v_projection
  )
  returning * into v_run;

  return v_projection || jsonb_build_object(
    'projectionId', v_run.id,
    'projectionRevision', v_run.projection_revision,
    'projectionInputHash', v_run.input_hash,
    'projectionHash', v_run.result_hash,
    'projectedAt', v_run.projected_at,
    'idempotentReplay', false,
    'reactivated', false
  );
end;
$$;

create or replace function public.refresh_live_projection_after_fixture_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_input_hash text;
begin
  if coalesce(
    current_setting('leghevo.live_projection_context', true),
    ''
  ) = 'on' then
    return new;
  end if;

  v_input_hash := public.live_fixture_projection_input_hash_v1(new.id);

  if v_input_hash is not null then
    perform public.refresh_live_fixture_projection_guarded_v1(
      new.id,
      public.leghevo_stable_request_uuid(
        'live-fixture-projection:'
          || new.id::text
          || ':'
          || v_input_hash
      )
    );
  end if;

  return new;
end;
$$;

drop trigger if exists fantasy_fixture_refresh_live_projection
on public.fantasy_fixtures;
create trigger fantasy_fixture_refresh_live_projection
after insert or update of
  home_points,
  away_points,
  home_goals,
  away_goals,
  finalized_at,
  home_base_points,
  away_base_points,
  home_defense_modifier,
  away_defense_modifier,
  home_bonus_applied,
  home_goal_margin_bonus,
  away_goal_margin_bonus,
  home_counted_players,
  away_counted_players,
  home_ready,
  away_ready
on public.fantasy_fixtures
for each row
execute function public.refresh_live_projection_after_fixture_change();

create or replace function public.get_my_live_match_v6(
  p_league_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_match jsonb;
  v_projection jsonb;
  v_fixture_id uuid;
  v_my_team_id uuid;
  v_home_team_id uuid;
  v_input_hash text;
  v_my_substitutions jsonb;
begin
  v_match := public.get_my_live_match_v5(p_league_id);

  if v_match is null then
    return null;
  end if;

  v_fixture_id := (v_match ->> 'fixtureId')::uuid;
  v_my_team_id := (v_match ->> 'myTeamId')::uuid;
  v_home_team_id := (v_match #>> '{home,teamId}')::uuid;
  v_input_hash := public.live_fixture_projection_input_hash_v1(
    v_fixture_id
  );

  if v_input_hash is null then
    raise exception 'Proiezione Live non disponibile.';
  end if;

  v_projection := public.refresh_live_fixture_projection_guarded_v1(
    v_fixture_id,
    public.leghevo_stable_request_uuid(
      'live-fixture-projection:'
        || v_fixture_id::text
        || ':'
        || v_input_hash
    )
  );

  v_my_substitutions := case
    when v_my_team_id = v_home_team_id then
      v_projection #> '{home,substitutions}'
    else v_projection #> '{away,substitutions}'
  end;

  return v_match || jsonb_build_object(
    'status', v_projection -> 'status',
    'home',
      coalesce(v_match -> 'home', '{}'::jsonb)
      || coalesce(v_projection -> 'home', '{}'::jsonb),
    'away',
      coalesce(v_match -> 'away', '{}'::jsonb)
      || coalesce(v_projection -> 'away', '{}'::jsonb),
    'substitutions', coalesce(
      v_my_substitutions,
      jsonb_build_object(
        'used', 0,
        'limit', 5,
        'unavailableStarters', 0,
        'applied', false
      )
    ),
    'goalMargin',
      coalesce(v_match -> 'goalMargin', '{}'::jsonb)
      || coalesce(v_projection -> 'goalMargin', '{}'::jsonb),
    'liveProjection', jsonb_build_object(
      'policy', 'protected_v1',
      'projectionId', v_projection -> 'projectionId',
      'revision', v_projection -> 'projectionRevision',
      'inputHash', v_projection -> 'projectionInputHash',
      'hash', v_projection -> 'projectionHash',
      'projectedAt', v_projection -> 'projectedAt',
      'certified', v_projection -> 'certified',
      'idempotentReplay', v_projection -> 'idempotentReplay'
    )
  );
end;
$$;

create or replace function public.get_league_live_projection_integrity_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_current_count integer := 0;
  v_duplicate_current_count integer := 0;
  v_stale_input_count integer := 0;
  v_result_hash_issue_count integer := 0;
  v_fixture_link_issue_count integer := 0;
  v_payload_issue_count integer := 0;
  v_resolution_link_issue_count integer := 0;
  v_revision_issue_count integer := 0;
  v_triggers_ready boolean := false;
  v_realtime_ready boolean := false;
  v_healthy boolean := false;
begin
  if auth.uid() is not null
    and not public.is_league_member(p_league_id)
    and not public.is_league_admin(p_league_id) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  select count(*)::integer
  into v_current_count
  from public.live_fixture_projection_runs run
  where run.league_id = p_league_id
    and run.superseded_at is null;

  select count(*)::integer
  into v_duplicate_current_count
  from (
    select run.fixture_id
    from public.live_fixture_projection_runs run
    where run.league_id = p_league_id
      and run.superseded_at is null
    group by run.fixture_id
    having count(*) > 1
  ) duplicate_rows;

  select count(*)::integer
  into v_stale_input_count
  from public.live_fixture_projection_runs run
  where run.league_id = p_league_id
    and run.superseded_at is null
    and run.input_hash is distinct from
      public.live_fixture_projection_input_hash_v1(run.fixture_id);

  select count(*)::integer
  into v_result_hash_issue_count
  from public.live_fixture_projection_runs run
  where run.league_id = p_league_id
    and run.result_hash is distinct from md5(run.projection_payload::text);

  select count(*)::integer
  into v_fixture_link_issue_count
  from public.live_fixture_projection_runs run
  join public.fantasy_fixtures fixture
    on fixture.id = run.fixture_id
  where run.league_id = p_league_id
    and (
      run.league_id <> fixture.league_id
      or run.matchday_id <> fixture.matchday_id
      or run.home_team_id <> fixture.home_team_id
      or run.away_team_id <> fixture.away_team_id
    );

  select count(*)::integer
  into v_payload_issue_count
  from public.live_fixture_projection_runs run
  where run.league_id = p_league_id
    and (
      run.status is distinct from run.projection_payload ->> 'status'
      or run.home_points is distinct from nullif(
        run.projection_payload #>> '{home,points}',
        ''
      )::numeric
      or run.away_points is distinct from nullif(
        run.projection_payload #>> '{away,points}',
        ''
      )::numeric
      or run.home_goals is distinct from nullif(
        run.projection_payload #>> '{home,goals}',
        ''
      )::smallint
      or run.away_goals is distinct from nullif(
        run.projection_payload #>> '{away,goals}',
        ''
      )::smallint
      or run.home_counted_players is distinct from coalesce(
        (run.projection_payload #>> '{home,countedPlayers}')::smallint,
        0
      )
      or run.away_counted_players is distinct from coalesce(
        (run.projection_payload #>> '{away,countedPlayers}')::smallint,
        0
      )
      or run.home_ready is distinct from coalesce(
        (run.projection_payload #>> '{home,ready}')::boolean,
        false
      )
      or run.away_ready is distinct from coalesce(
        (run.projection_payload #>> '{away,ready}')::boolean,
        false
      )
      or run.certified is distinct from coalesce(
        (run.projection_payload ->> 'certified')::boolean,
        false
      )
    );

  select count(*)::integer
  into v_resolution_link_issue_count
  from public.live_fixture_projection_runs run
  where run.league_id = p_league_id
    and (
      (
        run.home_resolution_id is not null
        and not exists (
          select 1
          from public.lineup_resolution_runs resolution
          where resolution.id = run.home_resolution_id
            and resolution.fantasy_team_id = run.home_team_id
            and resolution.matchday_id = run.matchday_id
            and resolution.result_hash = run.home_resolution_hash
        )
      )
      or (
        run.away_resolution_id is not null
        and not exists (
          select 1
          from public.lineup_resolution_runs resolution
          where resolution.id = run.away_resolution_id
            and resolution.fantasy_team_id = run.away_team_id
            and resolution.matchday_id = run.matchday_id
            and resolution.result_hash = run.away_resolution_hash
        )
      )
    );

  select count(*)::integer
  into v_revision_issue_count
  from (
    select
      run.fixture_id,
      count(*)::integer as revision_count,
      min(run.projection_revision) as minimum_revision,
      max(run.projection_revision) as maximum_revision,
      count(distinct run.projection_revision)::integer
        as distinct_revision_count
    from public.live_fixture_projection_runs run
    where run.league_id = p_league_id
    group by run.fixture_id
    having min(run.projection_revision) <> 1
      or max(run.projection_revision) <> count(*)
      or count(distinct run.projection_revision) <> count(*)
  ) revision_issues;

  select count(*) = 2
  into v_triggers_ready
  from pg_catalog.pg_trigger trigger_row
  where not trigger_row.tgisinternal
    and trigger_row.tgname in (
      'live_fixture_projection_immutable',
      'fantasy_fixture_refresh_live_projection'
    );

  select exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'live_fixture_projection_runs'
  )
  into v_realtime_ready;

  v_healthy :=
    v_duplicate_current_count = 0
    and v_stale_input_count = 0
    and v_result_hash_issue_count = 0
    and v_fixture_link_issue_count = 0
    and v_payload_issue_count = 0
    and v_resolution_link_issue_count = 0
    and v_revision_issue_count = 0
    and v_triggers_ready
    and v_realtime_ready;

  return jsonb_build_object(
    'version', 1,
    'liveProjectionPolicy', 'protected_v1',
    'currentProjectionCount', v_current_count,
    'duplicateCurrentProjectionCount', v_duplicate_current_count,
    'staleInputCount', v_stale_input_count,
    'resultHashIssueCount', v_result_hash_issue_count,
    'fixtureLinkIssueCount', v_fixture_link_issue_count,
    'payloadIssueCount', v_payload_issue_count,
    'resolutionLinkIssueCount', v_resolution_link_issue_count,
    'revisionIssueCount', v_revision_issue_count,
    'triggersReady', v_triggers_ready,
    'realtimeReady', v_realtime_ready,
    'healthy', v_healthy
  );
end;
$$;

revoke all on function public.prevent_live_fixture_projection_mutation()
from public, anon, authenticated;
revoke all on function public.live_fixture_projection_input_hash_v1(uuid)
from public, anon, authenticated;
revoke all on function public.compute_live_fixture_projection_v1(uuid)
from public, anon, authenticated;
revoke all on function public.refresh_live_fixture_projection_guarded_v1(
  uuid,
  uuid
) from public, anon, authenticated;
revoke all on function public.refresh_live_projection_after_fixture_change()
from public, anon, authenticated;
revoke all on function public.get_my_live_match_v6(uuid)
from public, anon, authenticated;
revoke all on function public.get_league_live_projection_integrity_v1(uuid)
from public, anon, authenticated;

grant execute on function public.get_my_live_match_v6(uuid)
to authenticated;
grant execute on function public.get_league_live_projection_integrity_v1(uuid)
to authenticated;

do $$
begin
  if exists (
    select 1
    from pg_catalog.pg_publication publication
    where publication.pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'live_fixture_projection_runs'
  ) then
    alter publication supabase_realtime
      add table public.live_fixture_projection_runs;
  end if;
end;
$$;

commit;

-- Controllo finale: attesi 20 valori true.
select
  to_regclass('public.live_fixture_projection_runs') is not null
    as live_projection_table_ready,
  exists (
    select 1
    from pg_catalog.pg_indexes
    where schemaname = 'public'
      and indexname = 'live_fixture_projection_current_idx'
  ) as single_current_projection_index_ready,
  exists (
    select 1
    from pg_catalog.pg_indexes
    where schemaname = 'public'
      and indexname = 'live_fixture_projection_league_matchday_idx'
  ) as live_projection_lookup_index_ready,
  (
    select relrowsecurity
    from pg_catalog.pg_class
    where oid = 'public.live_fixture_projection_runs'::regclass
  ) as live_projection_rls_ready,
  exists (
    select 1
    from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'live_fixture_projection_runs'
      and policyname = 'live_fixture_projection_read_members'
  ) as live_projection_member_policy_ready,
  has_table_privilege(
    'authenticated',
    'public.live_fixture_projection_runs',
    'SELECT'
  ) as live_projection_read_access_ready,
  to_regprocedure(
    'public.prevent_live_fixture_projection_mutation()'
  ) is not null as live_projection_mutation_guard_ready,
  exists (
    select 1
    from pg_catalog.pg_trigger trigger_row
    where not trigger_row.tgisinternal
      and trigger_row.tgname = 'live_fixture_projection_immutable'
  ) as live_projection_immutable_trigger_ready,
  to_regprocedure(
    'public.live_fixture_projection_input_hash_v1(uuid)'
  ) is not null as live_projection_input_hash_ready,
  to_regprocedure(
    'public.compute_live_fixture_projection_v1(uuid)'
  ) is not null as deterministic_live_projection_ready,
  to_regprocedure(
    'public.refresh_live_fixture_projection_guarded_v1(uuid,uuid)'
  ) is not null as guarded_live_projection_refresh_ready,
  to_regprocedure(
    'public.refresh_live_projection_after_fixture_change()'
  ) is not null as automatic_live_projection_refresh_ready,
  exists (
    select 1
    from pg_catalog.pg_trigger trigger_row
    where not trigger_row.tgisinternal
      and trigger_row.tgname = 'fantasy_fixture_refresh_live_projection'
  ) as fantasy_fixture_live_trigger_ready,
  to_regprocedure(
    'public.get_my_live_match_v6(uuid)'
  ) is not null as protected_live_match_api_ready,
  to_regprocedure(
    'public.get_league_live_projection_integrity_v1(uuid)'
  ) is not null as live_projection_diagnostics_ready,
  has_function_privilege(
    'authenticated',
    'public.get_my_live_match_v6(uuid)',
    'EXECUTE'
  ) as protected_live_match_access_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_live_projection_integrity_v1(uuid)',
    'EXECUTE'
  ) as live_projection_diagnostics_access_ready,
  (
    not has_function_privilege(
      'authenticated',
      'public.refresh_live_fixture_projection_guarded_v1(uuid,uuid)',
      'EXECUTE'
    )
    and not has_function_privilege(
      'anon',
      'public.refresh_live_fixture_projection_guarded_v1(uuid,uuid)',
      'EXECUTE'
    )
  ) as internal_live_projection_refresh_protected,
  (
    pg_get_functiondef(
      'public.get_my_live_match_v6(uuid)'::regprocedure
    ) ilike '%get_my_live_match_v5%'
    and pg_get_functiondef(
      'public.get_my_live_match_v6(uuid)'::regprocedure
    ) ilike '%refresh_live_fixture_projection_guarded_v1%'
  ) as legacy_live_chain_preserved,
  exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'live_fixture_projection_runs'
  ) as live_projection_realtime_ready;
