-- LEGHEVO · ufficializzazione atomica e revisionata della giornata
-- Versione applicativa: 0.59.5
-- Migrazione prevista: database/079_matchday_officialization_safety.sql
-- Eseguire dopo database/078_live_matchday_projection_safety.sql.
-- Script idempotente: può essere eseguito più volte.

begin;

create table if not exists public.matchday_officialization_runs (
  id bigint generated by default as identity primary key,
  league_id uuid not null
    references public.leagues(id) on delete cascade,
  matchday_id uuid not null
    references public.matchdays(id) on delete cascade,
  request_id uuid not null unique,
  finalization_revision integer not null,
  input_hash text not null,
  result_hash text not null,
  fixture_count integer not null,
  finalized_fixture_count integer not null,
  source_projection_ids jsonb not null default '[]'::jsonb,
  result_payload jsonb not null default '{}'::jsonb,
  finalized_by uuid references public.profiles(id) on delete set null,
  finalized_at timestamptz not null default now(),
  superseded_at timestamptz,
  constraint matchday_officialization_revision_check
    check (finalization_revision >= 1),
  constraint matchday_officialization_input_hash_check
    check (length(input_hash) = 32),
  constraint matchday_officialization_result_hash_check
    check (length(result_hash) = 32),
  constraint matchday_officialization_fixture_count_check
    check (fixture_count >= 1),
  constraint matchday_officialization_finalized_count_check
    check (
      finalized_fixture_count >= 0
      and finalized_fixture_count <= fixture_count
    ),
  unique (matchday_id, finalization_revision)
);

create unique index if not exists matchday_officialization_current_idx
  on public.matchday_officialization_runs (matchday_id)
  where superseded_at is null;

create index if not exists matchday_officialization_league_idx
  on public.matchday_officialization_runs (
    league_id,
    matchday_id,
    finalized_at desc
  );

alter table public.matchday_officialization_runs enable row level security;

drop policy if exists matchday_officialization_read_members
on public.matchday_officialization_runs;
create policy matchday_officialization_read_members
on public.matchday_officialization_runs
for select to authenticated
using (public.is_league_member(league_id));

revoke all on table public.matchday_officialization_runs
from public, anon, authenticated;
grant select on table public.matchday_officialization_runs
to authenticated;

alter table public.fantasy_fixtures
  add column if not exists officialization_run_id bigint
    references public.matchday_officialization_runs(id) on delete set null,
  add column if not exists official_projection_id bigint
    references public.live_fixture_projection_runs(id) on delete set null;

create index if not exists fantasy_fixtures_officialization_run_idx
  on public.fantasy_fixtures (officialization_run_id)
  where officialization_run_id is not null;

create or replace function public.prevent_matchday_officialization_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if coalesce(
    current_setting('leghevo.matchday_officialization_context', true),
    ''
  ) = 'on' then
    if tg_op = 'DELETE' then
      return old;
    end if;
    return new;
  end if;

  raise exception
    'Ufficializzazione certificata: modifica diretta non consentita.';
end;
$$;

drop trigger if exists matchday_officialization_immutable
on public.matchday_officialization_runs;
create trigger matchday_officialization_immutable
before update or delete on public.matchday_officialization_runs
for each row
execute function public.prevent_matchday_officialization_mutation();

create or replace function public.matchday_officialization_input_hash_v1(
  p_league_id uuid,
  p_matchday_id uuid
)
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_hash text;
begin
  select md5(
    jsonb_build_object(
      'leagueId', league.id,
      'matchdayId', matchday.id,
      'leagueMode', league.mode,
      'scoringRules', coalesce(league.scoring_rules, '{}'::jsonb),
      'matchdayNumber', matchday.number,
      'startsAt', matchday.starts_at,
      'locksAt', matchday.locks_at,
      'endsAt', matchday.ends_at,
      'providerFixtureCount', matchday.provider_fixture_count,
      'providerFinalFixtureCount', matchday.provider_final_fixture_count,
      'lineupsFinalizedAt', matchday.lineups_finalized_at,
      'lineupLockRevision', matchday.lineup_lock_revision,
      'lineupLockHash', matchday.lineup_lock_hash,
      'fixtures', coalesce(
        (
          select jsonb_agg(
            jsonb_build_object(
              'fixtureId', fixture.id,
              'homeTeamId', fixture.home_team_id,
              'awayTeamId', fixture.away_team_id,
              'projectionId', projection.id,
              'projectionRevision', projection.projection_revision,
              'projectionInputHash', projection.input_hash,
              'projectionHash', projection.result_hash,
              'projectionStatus', projection.status,
              'certified', projection.certified,
              'homeResolutionHash', projection.home_resolution_hash,
              'awayResolutionHash', projection.away_resolution_hash,
              'homePoints', projection.home_points,
              'awayPoints', projection.away_points,
              'homeGoals', projection.home_goals,
              'awayGoals', projection.away_goals,
              'homeCountedPlayers', projection.home_counted_players,
              'awayCountedPlayers', projection.away_counted_players,
              'homeReady', projection.home_ready,
              'awayReady', projection.away_ready
            )
            order by fixture.id
          )
          from public.fantasy_fixtures fixture
          left join public.live_fixture_projection_runs projection
            on projection.fixture_id = fixture.id
           and projection.superseded_at is null
          where fixture.league_id = p_league_id
            and fixture.matchday_id = p_matchday_id
        ),
        '[]'::jsonb
      )
    )::text
  )
  into v_hash
  from public.leagues league
  join public.matchdays matchday
    on matchday.id = p_matchday_id
  where league.id = p_league_id
    and exists (
      select 1
      from public.fantasy_fixtures fixture
      where fixture.league_id = p_league_id
        and fixture.matchday_id = p_matchday_id
    );

  return v_hash;
end;
$$;

create or replace function public.compute_matchday_officialization_v1(
  p_league_id uuid,
  p_matchday_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_league public.leagues%rowtype;
  v_matchday public.matchdays%rowtype;
  v_fixture_count integer := 0;
  v_ready_count integer := 0;
  v_certified_count integer := 0;
  v_projection_count integer := 0;
  v_fixtures jsonb := '[]'::jsonb;
begin
  select league.*
  into v_league
  from public.leagues league
  where league.id = p_league_id;

  if not found then
    return jsonb_build_object(
      'available', false,
      'integrityError', 'league_not_found'
    );
  end if;

  select matchday.*
  into v_matchday
  from public.matchdays matchday
  where matchday.id = p_matchday_id
    and exists (
      select 1
      from public.fantasy_fixtures fixture
      where fixture.league_id = p_league_id
        and fixture.matchday_id = p_matchday_id
    );

  if not found then
    return jsonb_build_object(
      'available', false,
      'integrityError', 'matchday_not_found'
    );
  end if;

  select
    count(*)::integer,
    count(projection.id)::integer,
    count(*) filter (
      where projection.home_ready
        and projection.away_ready
        and projection.home_points is not null
        and projection.away_points is not null
        and projection.home_goals is not null
        and projection.away_goals is not null
    )::integer,
    count(*) filter (
      where projection.certified
    )::integer,
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'fixtureId', fixture.id,
          'homeTeamId', fixture.home_team_id,
          'awayTeamId', fixture.away_team_id,
          'projectionId', projection.id,
          'projectionRevision', projection.projection_revision,
          'projectionHash', projection.result_hash,
          'status', projection.status,
          'certified', projection.certified,
          'home', coalesce(
            projection.projection_payload -> 'home',
            '{}'::jsonb
          ),
          'away', coalesce(
            projection.projection_payload -> 'away',
            '{}'::jsonb
          ),
          'goalMargin', coalesce(
            projection.projection_payload -> 'goalMargin',
            '{}'::jsonb
          )
        )
        order by fixture.id
      ),
      '[]'::jsonb
    )
  into
    v_fixture_count,
    v_projection_count,
    v_ready_count,
    v_certified_count,
    v_fixtures
  from public.fantasy_fixtures fixture
  left join public.live_fixture_projection_runs projection
    on projection.fixture_id = fixture.id
   and projection.superseded_at is null
  where fixture.league_id = p_league_id
    and fixture.matchday_id = p_matchday_id;

  return jsonb_build_object(
    'available', v_fixture_count > 0,
    'leagueId', p_league_id,
    'matchdayId', p_matchday_id,
    'matchdayNumber', v_matchday.number,
    'fixtureCount', v_fixture_count,
    'projectionCount', v_projection_count,
    'readyCount', v_ready_count,
    'certifiedCount', v_certified_count,
    'allReady',
      v_fixture_count > 0
      and v_projection_count = v_fixture_count
      and v_ready_count = v_fixture_count
      and v_certified_count = v_fixture_count,
    'providerComplete',
      coalesce(v_matchday.provider_fixture_count, 0) = 0
      or coalesce(v_matchday.provider_final_fixture_count, 0)
        >= coalesce(v_matchday.provider_fixture_count, 0),
    'fixtures', v_fixtures
  );
end;
$$;

create or replace function public.finalize_league_matchday_guarded_v1(
  p_league_id uuid,
  p_matchday_id uuid,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_league public.leagues%rowtype;
  v_matchday public.matchdays%rowtype;
  v_existing public.matchday_officialization_runs%rowtype;
  v_run public.matchday_officialization_runs%rowtype;
  v_fixture record;
  v_payload jsonb;
  v_input_hash text;
  v_result_hash text;
  v_source_projection_ids jsonb;
  v_fixture_count integer := 0;
  v_official_count integer := 0;
  v_linked_run_count integer := 0;
  v_revision integer := 1;
  v_updated integer := 0;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if p_request_id is null then
    raise exception 'Identificativo di ufficializzazione mancante.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'matchday-officialization:'
        || p_league_id::text
        || ':'
        || p_matchday_id::text,
      0
    )
  );

  select league.*
  into v_league
  from public.leagues league
  where league.id = p_league_id
  for update;

  if not found then
    raise exception 'Lega non trovata.';
  end if;

  if v_league.owner_id <> auth.uid() then
    raise exception 'Solo il Presidente può ufficializzare la giornata.';
  end if;

  if v_league.competition_started_at is null then
    raise exception 'Avvia la competizione prima di chiudere una giornata.';
  end if;

  if v_league.status in ('completed', 'archived') then
    raise exception 'La stagione è già conclusa e non può essere modificata.';
  end if;

  select matchday.*
  into v_matchday
  from public.matchdays matchday
  where matchday.id = p_matchday_id
    and exists (
      select 1
      from public.fantasy_fixtures fixture
      where fixture.league_id = p_league_id
        and fixture.matchday_id = p_matchday_id
    )
  for update;

  if not found then
    raise exception 'Giornata non trovata nel calendario della lega.';
  end if;

  if now() < coalesce(
    v_matchday.ends_at,
    v_matchday.starts_at + interval '4 days'
  ) then
    raise exception 'La giornata reale non è ancora terminata.';
  end if;

  select
    count(*)::integer,
    count(*) filter (where fixture.finalized_at is not null)::integer,
    count(distinct fixture.officialization_run_id) filter (
      where fixture.officialization_run_id is not null
    )::integer
  into v_fixture_count, v_official_count, v_linked_run_count
  from public.fantasy_fixtures fixture
  where fixture.league_id = p_league_id
    and fixture.matchday_id = p_matchday_id;

  if v_fixture_count = 0 then
    raise exception 'La giornata non contiene partite fantasy.';
  end if;

  if v_official_count = v_fixture_count
    and v_linked_run_count = 1 then
    select run.*
    into v_existing
    from public.matchday_officialization_runs run
    where run.id = (
      select min(fixture.officialization_run_id)
      from public.fantasy_fixtures fixture
      where fixture.league_id = p_league_id
        and fixture.matchday_id = p_matchday_id
    );

    if found then
      return v_existing.result_payload || jsonb_build_object(
        'officializationId', v_existing.id,
        'officializationRevision', v_existing.finalization_revision,
        'officializationInputHash', v_existing.input_hash,
        'officializationHash', v_existing.result_hash,
        'finalizedAt', v_existing.finalized_at,
        'finalizedFixtureCount', v_existing.finalized_fixture_count,
        'idempotentReplay', true
      );
    end if;
  end if;

  if v_official_count > 0 then
    raise exception
      'La giornata presenta un''ufficializzazione parziale. Riapri i risultati già ufficiali prima di riprovare.';
  end if;

  perform public.ensure_matchday_lineups(p_matchday_id);

  for v_fixture in
    select fixture.id
    from public.fantasy_fixtures fixture
    where fixture.league_id = p_league_id
      and fixture.matchday_id = p_matchday_id
    order by fixture.id
    for update
  loop
    perform public.refresh_live_fixture_projection_guarded_v1(
      v_fixture.id,
      public.leghevo_stable_request_uuid(
        'matchday-finalization-source:'
          || p_matchday_id::text
          || ':'
          || v_fixture.id::text
          || ':'
          || coalesce(
            public.live_fixture_projection_input_hash_v1(v_fixture.id),
            'missing'
          )
      )
    );
  end loop;

  v_payload := public.compute_matchday_officialization_v1(
    p_league_id,
    p_matchday_id
  );

  if not coalesce((v_payload ->> 'available')::boolean, false) then
    raise exception 'Ufficializzazione non disponibile per questa giornata.';
  end if;

  if not coalesce((v_payload ->> 'providerComplete')::boolean, false) then
    raise exception 'Il provider non ha ancora chiuso tutte le partite reali della giornata.';
  end if;

  if not coalesce((v_payload ->> 'allReady')::boolean, false) then
    raise exception
      'Mancano voti o sostituzioni certificate: % partite pronte su %.',
      coalesce((v_payload ->> 'readyCount')::integer, 0),
      coalesce((v_payload ->> 'fixtureCount')::integer, 0);
  end if;

  v_input_hash := public.matchday_officialization_input_hash_v1(
    p_league_id,
    p_matchday_id
  );

  if v_input_hash is null then
    raise exception 'Impossibile calcolare l''impronta della giornata.';
  end if;

  select run.*
  into v_existing
  from public.matchday_officialization_runs run
  where run.request_id = p_request_id;

  if found then
    if v_existing.league_id <> p_league_id
      or v_existing.matchday_id <> p_matchday_id
      or v_existing.input_hash <> v_input_hash then
      raise exception
        'La chiave di ufficializzazione è già stata utilizzata.';
    end if;

    return v_existing.result_payload || jsonb_build_object(
      'officializationId', v_existing.id,
      'officializationRevision', v_existing.finalization_revision,
      'officializationInputHash', v_existing.input_hash,
      'officializationHash', v_existing.result_hash,
      'finalizedAt', v_existing.finalized_at,
      'finalizedFixtureCount', v_existing.finalized_fixture_count,
      'idempotentReplay', true
    );
  end if;

  select coalesce(max(run.finalization_revision), 0) + 1
  into v_revision
  from public.matchday_officialization_runs run
  where run.matchday_id = p_matchday_id;

  select coalesce(
    jsonb_agg(
      projection.id
      order by fixture.id
    ),
    '[]'::jsonb
  )
  into v_source_projection_ids
  from public.fantasy_fixtures fixture
  join public.live_fixture_projection_runs projection
    on projection.fixture_id = fixture.id
   and projection.superseded_at is null
  where fixture.league_id = p_league_id
    and fixture.matchday_id = p_matchday_id;

  v_result_hash := md5(v_payload::text);

  perform set_config(
    'leghevo.matchday_officialization_context',
    'on',
    true
  );

  update public.matchday_officialization_runs run
  set superseded_at = now()
  where run.matchday_id = p_matchday_id
    and run.superseded_at is null;

  insert into public.matchday_officialization_runs (
    league_id,
    matchday_id,
    request_id,
    finalization_revision,
    input_hash,
    result_hash,
    fixture_count,
    finalized_fixture_count,
    source_projection_ids,
    result_payload,
    finalized_by
  )
  values (
    p_league_id,
    p_matchday_id,
    p_request_id,
    v_revision,
    v_input_hash,
    v_result_hash,
    v_fixture_count,
    v_fixture_count,
    v_source_projection_ids,
    v_payload,
    auth.uid()
  )
  returning * into v_run;

  update public.fantasy_fixtures fixture
  set
    home_base_points = nullif(
      projection.projection_payload #>> '{home,basePoints}',
      ''
    )::numeric,
    away_base_points = nullif(
      projection.projection_payload #>> '{away,basePoints}',
      ''
    )::numeric,
    home_defense_modifier = coalesce(
      nullif(
        projection.projection_payload #>> '{home,defenseModifier,bonus}',
        ''
      )::numeric,
      0
    ),
    away_defense_modifier = coalesce(
      nullif(
        projection.projection_payload #>> '{away,defenseModifier,bonus}',
        ''
      )::numeric,
      0
    ),
    home_bonus_applied = coalesce(
      nullif(
        projection.projection_payload #>> '{home,homeBonus}',
        ''
      )::numeric,
      0
    ),
    home_goal_margin_bonus = coalesce(
      nullif(
        projection.projection_payload #>> '{goalMargin,homeBonus}',
        ''
      )::smallint,
      0
    ),
    away_goal_margin_bonus = coalesce(
      nullif(
        projection.projection_payload #>> '{goalMargin,awayBonus}',
        ''
      )::smallint,
      0
    ),
    home_points = projection.home_points,
    away_points = projection.away_points,
    home_goals = projection.home_goals,
    away_goals = projection.away_goals,
    home_counted_players = projection.home_counted_players,
    away_counted_players = projection.away_counted_players,
    home_ready = projection.home_ready,
    away_ready = projection.away_ready,
    officialization_run_id = v_run.id,
    official_projection_id = projection.id,
    finalized_at = now(),
    finalized_by = auth.uid()
  from public.live_fixture_projection_runs projection
  where fixture.league_id = p_league_id
    and fixture.matchday_id = p_matchday_id
    and fixture.finalized_at is null
    and projection.fixture_id = fixture.id
    and projection.superseded_at is null;

  get diagnostics v_updated = row_count;

  if v_updated <> v_fixture_count then
    raise exception
      'Ufficializzazione incompleta: % partite aggiornate su %.',
      v_updated,
      v_fixture_count;
  end if;

  return v_payload || jsonb_build_object(
    'officializationId', v_run.id,
    'officializationRevision', v_run.finalization_revision,
    'officializationInputHash', v_run.input_hash,
    'officializationHash', v_run.result_hash,
    'finalizedAt', v_run.finalized_at,
    'finalizedFixtureCount', v_updated,
    'idempotentReplay', false
  );
end;
$$;

create or replace function public.finalize_league_matchday(
  p_league_id uuid,
  p_matchday_id uuid
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_result jsonb;
begin
  v_result := public.finalize_league_matchday_guarded_v1(
    p_league_id,
    p_matchday_id,
    gen_random_uuid()
  );

  return coalesce(
    (v_result ->> 'finalizedFixtureCount')::integer,
    0
  );
end;
$$;

create or replace function public.get_league_matchday_officialization_integrity_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_duplicate_current_count integer := 0;
  v_hash_issue_count integer := 0;
  v_result_hash_issue_count integer := 0;
  v_fixture_link_issue_count integer := 0;
  v_projection_link_issue_count integer := 0;
  v_snapshot_issue_count integer := 0;
  v_partial_matchday_count integer := 0;
  v_revision_issue_count integer := 0;
  v_trigger_ready boolean := false;
  v_realtime_ready boolean := false;
  v_healthy boolean := false;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if not public.is_league_member(p_league_id) then
    raise exception 'Non fai parte della lega selezionata.';
  end if;

  select count(*)::integer
  into v_duplicate_current_count
  from (
    select run.matchday_id
    from public.matchday_officialization_runs run
    where run.league_id = p_league_id
      and run.superseded_at is null
    group by run.matchday_id
    having count(*) > 1
  ) duplicate_current;

  select count(*)::integer
  into v_hash_issue_count
  from public.matchday_officialization_runs run
  where run.league_id = p_league_id
    and (
      length(run.input_hash) <> 32
      or length(run.result_hash) <> 32
    );

  select count(*)::integer
  into v_result_hash_issue_count
  from public.matchday_officialization_runs run
  where run.league_id = p_league_id
    and run.result_hash <> md5(run.result_payload::text);

  select count(*)::integer
  into v_fixture_link_issue_count
  from public.fantasy_fixtures fixture
  left join public.matchday_officialization_runs run
    on run.id = fixture.officialization_run_id
  where fixture.league_id = p_league_id
    and fixture.finalized_at is not null
    and fixture.officialization_run_id is not null
    and (
      run.id is null
      or run.league_id <> fixture.league_id
      or run.matchday_id <> fixture.matchday_id
    );

  select count(*)::integer
  into v_projection_link_issue_count
  from public.fantasy_fixtures fixture
  left join public.live_fixture_projection_runs projection
    on projection.id = fixture.official_projection_id
  where fixture.league_id = p_league_id
    and fixture.official_projection_id is not null
    and (
      projection.id is null
      or projection.fixture_id <> fixture.id
      or projection.league_id <> fixture.league_id
      or projection.matchday_id <> fixture.matchday_id
    );

  select count(*)::integer
  into v_snapshot_issue_count
  from public.fantasy_fixtures fixture
  join public.live_fixture_projection_runs projection
    on projection.id = fixture.official_projection_id
  where fixture.league_id = p_league_id
    and fixture.finalized_at is not null
    and (
      fixture.home_points is distinct from projection.home_points
      or fixture.away_points is distinct from projection.away_points
      or fixture.home_goals is distinct from projection.home_goals
      or fixture.away_goals is distinct from projection.away_goals
      or fixture.home_counted_players
        is distinct from projection.home_counted_players
      or fixture.away_counted_players
        is distinct from projection.away_counted_players
    );

  select count(*)::integer
  into v_partial_matchday_count
  from (
    select
      fixture.matchday_id,
      count(*) filter (where fixture.finalized_at is not null) as official_count,
      count(*) as fixture_count
    from public.fantasy_fixtures fixture
    where fixture.league_id = p_league_id
    group by fixture.matchday_id
    having count(*) filter (where fixture.finalized_at is not null) > 0
      and count(*) filter (where fixture.finalized_at is not null) < count(*)
  ) partial_matchdays;

  select count(*)::integer
  into v_revision_issue_count
  from (
    select
      run.matchday_id,
      min(run.finalization_revision) as minimum_revision,
      max(run.finalization_revision) as maximum_revision,
      count(*)::integer as revision_count,
      count(distinct run.finalization_revision)::integer
        as distinct_revision_count
    from public.matchday_officialization_runs run
    where run.league_id = p_league_id
    group by run.matchday_id
    having min(run.finalization_revision) <> 1
      or max(run.finalization_revision) <> count(*)
      or count(distinct run.finalization_revision) <> count(*)
  ) revision_issues;

  select exists (
    select 1
    from pg_catalog.pg_trigger trigger_row
    where not trigger_row.tgisinternal
      and trigger_row.tgname = 'matchday_officialization_immutable'
  )
  into v_trigger_ready;

  select exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'matchday_officialization_runs'
  )
  into v_realtime_ready;

  v_healthy :=
    v_duplicate_current_count = 0
    and v_hash_issue_count = 0
    and v_result_hash_issue_count = 0
    and v_fixture_link_issue_count = 0
    and v_projection_link_issue_count = 0
    and v_snapshot_issue_count = 0
    and v_partial_matchday_count = 0
    and v_revision_issue_count = 0
    and v_trigger_ready
    and v_realtime_ready;

  return jsonb_build_object(
    'version', 1,
    'officializationPolicy', 'protected_v1',
    'duplicateCurrentCount', v_duplicate_current_count,
    'hashIssueCount', v_hash_issue_count,
    'resultHashIssueCount', v_result_hash_issue_count,
    'fixtureLinkIssueCount', v_fixture_link_issue_count,
    'projectionLinkIssueCount', v_projection_link_issue_count,
    'snapshotIssueCount', v_snapshot_issue_count,
    'partialMatchdayCount', v_partial_matchday_count,
    'revisionIssueCount', v_revision_issue_count,
    'triggerReady', v_trigger_ready,
    'realtimeReady', v_realtime_ready,
    'healthy', v_healthy
  );
end;
$$;

revoke all on function public.prevent_matchday_officialization_mutation()
from public, anon, authenticated;
revoke all on function public.matchday_officialization_input_hash_v1(uuid, uuid)
from public, anon, authenticated;
revoke all on function public.compute_matchday_officialization_v1(uuid, uuid)
from public, anon, authenticated;
revoke all on function public.finalize_league_matchday_guarded_v1(uuid, uuid, uuid)
from public, anon, authenticated;
revoke all on function public.finalize_league_matchday(uuid, uuid)
from public, anon, authenticated;
revoke all on function public.get_league_matchday_officialization_integrity_v1(uuid)
from public, anon, authenticated;

grant execute on function public.finalize_league_matchday_guarded_v1(uuid, uuid, uuid)
to authenticated;
grant execute on function public.finalize_league_matchday(uuid, uuid)
to authenticated;
grant execute on function public.get_league_matchday_officialization_integrity_v1(uuid)
to authenticated;

do $$
begin
  if exists (
    select 1
    from pg_catalog.pg_publication publication
    where publication.pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'matchday_officialization_runs'
  ) then
    alter publication supabase_realtime
      add table public.matchday_officialization_runs;
  end if;
end;
$$;

commit;

-- Controllo finale: attesi 20 valori true.
select
  to_regclass('public.matchday_officialization_runs') is not null
    as officialization_table_ready,
  exists (
    select 1
    from pg_catalog.pg_indexes
    where schemaname = 'public'
      and indexname = 'matchday_officialization_current_idx'
  ) as single_current_officialization_index_ready,
  exists (
    select 1
    from pg_catalog.pg_indexes
    where schemaname = 'public'
      and indexname = 'matchday_officialization_league_idx'
  ) as officialization_lookup_index_ready,
  (
    select relrowsecurity
    from pg_catalog.pg_class
    where oid = 'public.matchday_officialization_runs'::regclass
  ) as officialization_rls_ready,
  exists (
    select 1
    from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'matchday_officialization_runs'
      and policyname = 'matchday_officialization_read_members'
  ) as officialization_member_policy_ready,
  has_table_privilege(
    'authenticated',
    'public.matchday_officialization_runs',
    'SELECT'
  ) as officialization_read_access_ready,
  (
    select count(*) = 2
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'fantasy_fixtures'
      and column_name in (
        'officialization_run_id',
        'official_projection_id'
      )
  ) as fixture_officialization_links_ready,
  to_regprocedure(
    'public.prevent_matchday_officialization_mutation()'
  ) is not null as officialization_mutation_guard_ready,
  exists (
    select 1
    from pg_catalog.pg_trigger trigger_row
    where not trigger_row.tgisinternal
      and trigger_row.tgname = 'matchday_officialization_immutable'
  ) as officialization_immutable_trigger_ready,
  to_regprocedure(
    'public.matchday_officialization_input_hash_v1(uuid,uuid)'
  ) is not null as officialization_input_hash_ready,
  to_regprocedure(
    'public.compute_matchday_officialization_v1(uuid,uuid)'
  ) is not null as deterministic_officialization_ready,
  to_regprocedure(
    'public.finalize_league_matchday_guarded_v1(uuid,uuid,uuid)'
  ) is not null as guarded_officialization_ready,
  to_regprocedure(
    'public.get_league_matchday_officialization_integrity_v1(uuid)'
  ) is not null as officialization_diagnostics_ready,
  has_function_privilege(
    'authenticated',
    'public.finalize_league_matchday_guarded_v1(uuid,uuid,uuid)',
    'EXECUTE'
  ) as guarded_officialization_access_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_matchday_officialization_integrity_v1(uuid)',
    'EXECUTE'
  ) as officialization_diagnostics_access_ready,
  (
    not has_function_privilege(
      'anon',
      'public.finalize_league_matchday_guarded_v1(uuid,uuid,uuid)',
      'EXECUTE'
    )
    and not has_function_privilege(
      'anon',
      'public.get_league_matchday_officialization_integrity_v1(uuid)',
      'EXECUTE'
    )
  ) as anonymous_officialization_blocked,
  (
    not has_function_privilege(
      'authenticated',
      'public.compute_matchday_officialization_v1(uuid,uuid)',
      'EXECUTE'
    )
    and not has_function_privilege(
      'authenticated',
      'public.matchday_officialization_input_hash_v1(uuid,uuid)',
      'EXECUTE'
    )
  ) as internal_officialization_functions_protected,
  (
    pg_get_functiondef(
      'public.finalize_league_matchday(uuid,uuid)'::regprocedure
    ) ilike '%finalize_league_matchday_guarded_v1%'
  ) as legacy_finalize_redirected,
  (
    pg_get_functiondef(
      'public.finalize_league_matchday_guarded_v1(uuid,uuid,uuid)'::regprocedure
    ) ilike '%refresh_live_fixture_projection_guarded_v1%'
    and pg_get_functiondef(
      'public.finalize_league_matchday_guarded_v1(uuid,uuid,uuid)'::regprocedure
    ) ilike '%official_projection_id%'
  ) as live_projection_chain_certified,
  exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'matchday_officialization_runs'
  ) as officialization_realtime_ready;
