-- LEGHEVO · avanzamento protetto della giornata e fotografia classifica
-- Versione applicativa: 0.59.7
-- Migrazione prevista: database/081_matchday_progression_and_standings_snapshot_safety.sql
-- Eseguire dopo database/080_result_correction_continuity_safety.sql.
-- Script idempotente: può essere eseguito più volte.
-- Revisione correttiva: ripristino difensivo della RPC v2 richiesta dalla v3.

begin;

create table if not exists public.matchday_progression_runs (
  id bigint generated by default as identity primary key,
  league_id uuid not null
    references public.leagues(id) on delete cascade,
  matchday_id uuid not null
    references public.matchdays(id) on delete cascade,
  officialization_run_id bigint not null
    references public.matchday_officialization_runs(id) on delete restrict,
  request_id uuid not null unique,
  progression_revision integer not null,
  input_hash text not null,
  standings_hash text not null,
  standings_snapshot jsonb not null default '[]'::jsonb,
  previous_matchday_id uuid
    references public.matchdays(id) on delete set null,
  previous_matchday_number smallint,
  next_matchday_id uuid
    references public.matchdays(id) on delete set null,
  next_matchday_number smallint,
  advanced boolean not null default false,
  season_ready_to_complete boolean not null default false,
  result_payload jsonb not null default '{}'::jsonb,
  progressed_by uuid references public.profiles(id) on delete set null,
  progressed_at timestamptz not null default now(),
  superseded_at timestamptz,
  constraint matchday_progression_revision_check
    check (progression_revision >= 1),
  constraint matchday_progression_input_hash_check
    check (length(input_hash) = 32),
  constraint matchday_progression_standings_hash_check
    check (length(standings_hash) = 32),
  constraint matchday_progression_snapshot_check
    check (jsonb_typeof(standings_snapshot) = 'array'),
  constraint matchday_progression_previous_number_check
    check (
      previous_matchday_number is null
      or previous_matchday_number > 0
    ),
  constraint matchday_progression_next_number_check
    check (
      next_matchday_number is null
      or next_matchday_number > 0
    ),
  constraint matchday_progression_advance_target_check
    check (
      not advanced
      or (
        next_matchday_id is not null
        and next_matchday_number is not null
      )
    ),
  unique (matchday_id, progression_revision)
);

create unique index if not exists matchday_progression_current_idx
  on public.matchday_progression_runs (matchday_id)
  where superseded_at is null;

create index if not exists matchday_progression_league_idx
  on public.matchday_progression_runs (
    league_id,
    matchday_id,
    progressed_at desc
  );

create index if not exists matchday_progression_officialization_idx
  on public.matchday_progression_runs (officialization_run_id);

alter table public.matchday_progression_runs enable row level security;

drop policy if exists matchday_progression_read_members
on public.matchday_progression_runs;
create policy matchday_progression_read_members
on public.matchday_progression_runs
for select to authenticated
using (public.is_league_member(league_id));

revoke all on table public.matchday_progression_runs
from public, anon, authenticated;
grant select on table public.matchday_progression_runs
to authenticated;

create or replace function public.prevent_matchday_progression_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if coalesce(
    current_setting('leghevo.matchday_progression_context', true),
    ''
  ) = 'on' then
    if tg_op = 'DELETE' then
      return old;
    end if;
    return new;
  end if;

  raise exception
    'Progressione certificata: modifica diretta non consentita.';
end;
$$;

drop trigger if exists matchday_progression_immutable
on public.matchday_progression_runs;
create trigger matchday_progression_immutable
before update or delete on public.matchday_progression_runs
for each row
execute function public.prevent_matchday_progression_mutation();

create or replace function public.build_league_standings_snapshot_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_snapshot jsonb;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if not public.is_league_member(p_league_id)
    and not public.is_league_admin(p_league_id) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'position', standing."position",
        'teamId', standing.fantasy_team_id,
        'teamName', standing.team_name,
        'played', standing.played,
        'won', standing.won,
        'drawn', standing.drawn,
        'lost', standing.lost,
        'goalsFor', standing.goals_for,
        'goalsAgainst', standing.goals_against,
        'goalDifference', standing.goal_difference,
        'pointsFor', standing.points_for,
        'leaguePoints', standing.league_points,
        'tiebreaker', standing.standings_tiebreaker,
        'headToHeadPlayed', standing.head_to_head_played,
        'headToHeadPoints', standing.head_to_head_points,
        'headToHeadGoalDifference',
          standing.head_to_head_goal_difference,
        'headToHeadEligible', standing.head_to_head_eligible
      )
      order by standing."position"
    ),
    '[]'::jsonb
  )
  into v_snapshot
  from public.get_league_standings_v2(p_league_id) standing;

  return v_snapshot;
end;
$$;

create or replace function public.settle_matchday_progression_guarded_v1(
  p_league_id uuid,
  p_matchday_id uuid,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_league public.leagues%rowtype;
  v_matchday public.matchdays%rowtype;
  v_next_matchday public.matchdays%rowtype;
  v_officialization public.matchday_officialization_runs%rowtype;
  v_existing public.matchday_progression_runs%rowtype;
  v_run public.matchday_progression_runs%rowtype;
  v_fixture_count integer := 0;
  v_official_count integer := 0;
  v_officialization_count integer := 0;
  v_previous_unofficial_count integer := 0;
  v_revision integer := 0;
  v_standings jsonb := '[]'::jsonb;
  v_standings_hash text;
  v_input_hash text;
  v_advanced boolean := false;
  v_season_ready boolean := false;
  v_payload jsonb;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if p_request_id is null then
    raise exception 'Identificativo di progressione mancante.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'matchday-progression:' || p_league_id::text,
      0
    )
  );

  select league.*
  into v_league
  from public.leagues league
  where league.id = p_league_id
  for update;

  if not found then
    raise exception 'Lega non trovata.';
  end if;

  if v_league.owner_id <> auth.uid() then
    raise exception
      'Solo il Presidente può certificare l''avanzamento della giornata.';
  end if;

  if v_league.competition_started_at is null then
    raise exception 'La competizione non è ancora iniziata.';
  end if;

  if v_league.status in ('completed', 'archived') then
    raise exception 'La stagione è già conclusa.';
  end if;

  select matchday.*
  into v_matchday
  from public.matchdays matchday
  where matchday.id = p_matchday_id
    and exists (
      select 1
      from public.fantasy_fixtures fixture
      where fixture.league_id = p_league_id
        and fixture.matchday_id = matchday.id
    )
  for update;

  if not found then
    raise exception 'Giornata non trovata nel calendario della lega.';
  end if;

  select
    count(*)::integer,
    count(*) filter (
      where fixture.finalized_at is not null
    )::integer,
    count(distinct fixture.officialization_run_id) filter (
      where fixture.officialization_run_id is not null
    )::integer
  into
    v_fixture_count,
    v_official_count,
    v_officialization_count
  from public.fantasy_fixtures fixture
  where fixture.league_id = p_league_id
    and fixture.matchday_id = p_matchday_id;

  if v_fixture_count = 0
    or v_official_count <> v_fixture_count
    or v_officialization_count <> 1 then
    raise exception
      'La giornata deve essere interamente ufficializzata prima dell''avanzamento.';
  end if;

  select officialization.*
  into v_officialization
  from public.matchday_officialization_runs officialization
  where officialization.id = (
    select min(fixture.officialization_run_id)
    from public.fantasy_fixtures fixture
    where fixture.league_id = p_league_id
      and fixture.matchday_id = p_matchday_id
  )
    and officialization.league_id = p_league_id
    and officialization.matchday_id = p_matchday_id
    and officialization.superseded_at is null;

  if not found then
    raise exception
      'La fotografia ufficiale corrente della giornata non è disponibile.';
  end if;

  select run.*
  into v_existing
  from public.matchday_progression_runs run
  where run.request_id = p_request_id;

  if found then
    if v_existing.league_id <> p_league_id
      or v_existing.matchday_id <> p_matchday_id
      or v_existing.officialization_run_id <> v_officialization.id then
      raise exception 'La chiave di progressione è già stata utilizzata.';
    end if;

    return v_existing.result_payload || jsonb_build_object(
      'progressionId', v_existing.id,
      'progressionRevision', v_existing.progression_revision,
      'standingsHash', v_existing.standings_hash,
      'progressedAt', v_existing.progressed_at,
      'idempotentReplay', true
    );
  end if;

  select run.*
  into v_existing
  from public.matchday_progression_runs run
  where run.matchday_id = p_matchday_id
    and run.officialization_run_id = v_officialization.id
    and run.superseded_at is null;

  if found then
    return v_existing.result_payload || jsonb_build_object(
      'progressionId', v_existing.id,
      'progressionRevision', v_existing.progression_revision,
      'standingsHash', v_existing.standings_hash,
      'progressedAt', v_existing.progressed_at,
      'idempotentReplay', true
    );
  end if;

  if v_league.current_matchday_id is null
    or v_league.current_matchday_number is null then
    raise exception
      'La giornata corrente della competizione non è certificata.';
  end if;

  if v_matchday.number > v_league.current_matchday_number then
    raise exception
      'Non puoi saltare la giornata corrente della competizione.';
  end if;

  select count(*)::integer
  into v_previous_unofficial_count
  from public.fantasy_fixtures fixture
  join public.matchdays previous_matchday
    on previous_matchday.id = fixture.matchday_id
  where fixture.league_id = p_league_id
    and previous_matchday.number < v_matchday.number
    and fixture.finalized_at is null;

  if v_previous_unofficial_count > 0 then
    raise exception
      'Esistono giornate precedenti non ancora ufficializzate.';
  end if;

  select next_matchday.*
  into v_next_matchday
  from public.fantasy_fixtures fixture
  join public.matchdays next_matchday
    on next_matchday.id = fixture.matchday_id
  where fixture.league_id = p_league_id
    and next_matchday.number > v_matchday.number
  group by next_matchday.id
  order by next_matchday.number, next_matchday.starts_at, next_matchday.id
  limit 1;

  v_standings := public.build_league_standings_snapshot_v1(p_league_id);
  v_standings_hash := md5(v_standings::text);

  v_input_hash := md5(
    jsonb_build_object(
      'leagueId', p_league_id,
      'matchdayId', p_matchday_id,
      'matchdayNumber', v_matchday.number,
      'officializationId', v_officialization.id,
      'officializationHash', v_officialization.result_hash,
      'standingsHash', v_standings_hash,
      'currentMatchdayId', v_league.current_matchday_id,
      'currentMatchdayNumber', v_league.current_matchday_number,
      'nextMatchdayId', v_next_matchday.id,
      'nextMatchdayNumber', v_next_matchday.number
    )::text
  );

  select coalesce(max(run.progression_revision), 0) + 1
  into v_revision
  from public.matchday_progression_runs run
  where run.matchday_id = p_matchday_id;

  -- La prima ufficializzazione della giornata corrente fa avanzare il
  -- puntatore. Una riufficializzazione di una giornata passata aggiorna
  -- soltanto fotografia e revisione, senza far arretrare il calendario.
  v_advanced :=
    v_matchday.number = v_league.current_matchday_number
    and v_next_matchday.id is not null;
  v_season_ready := v_next_matchday.id is null;

  if v_advanced then
    perform set_config('leghevo.competition_activation', 'allowed', true);

    update public.leagues league
    set
      competition_revision = greatest(league.competition_revision, 0) + 1,
      current_matchday_id = v_next_matchday.id,
      current_matchday_number = v_next_matchday.number,
      updated_at = now()
    where league.id = p_league_id;
  end if;

  v_payload := jsonb_build_object(
    'leagueId', p_league_id,
    'matchdayId', p_matchday_id,
    'matchdayNumber', v_matchday.number,
    'officializationId', v_officialization.id,
    'officializationRevision',
      v_officialization.finalization_revision,
    'standings', v_standings,
    'standingsHash', v_standings_hash,
    'advanced', v_advanced,
    'nextMatchdayId', v_next_matchday.id,
    'nextMatchdayNumber', v_next_matchday.number,
    'seasonReadyToComplete', v_season_ready
  );

  perform set_config(
    'leghevo.matchday_progression_context',
    'on',
    true
  );

  update public.matchday_progression_runs run
  set superseded_at = now()
  where run.matchday_id = p_matchday_id
    and run.superseded_at is null;

  insert into public.matchday_progression_runs (
    league_id,
    matchday_id,
    officialization_run_id,
    request_id,
    progression_revision,
    input_hash,
    standings_hash,
    standings_snapshot,
    previous_matchday_id,
    previous_matchday_number,
    next_matchday_id,
    next_matchday_number,
    advanced,
    season_ready_to_complete,
    result_payload,
    progressed_by
  ) values (
    p_league_id,
    p_matchday_id,
    v_officialization.id,
    p_request_id,
    v_revision,
    v_input_hash,
    v_standings_hash,
    v_standings,
    v_league.current_matchday_id,
    v_league.current_matchday_number,
    v_next_matchday.id,
    v_next_matchday.number,
    v_advanced,
    v_season_ready,
    v_payload,
    auth.uid()
  )
  returning * into v_run;

  return v_payload || jsonb_build_object(
    'progressionId', v_run.id,
    'progressionRevision', v_run.progression_revision,
    'progressionInputHash', v_run.input_hash,
    'progressedAt', v_run.progressed_at,
    'idempotentReplay', false
  );
end;
$$;

-- Compatibilità difensiva v0.59.7:
-- la progressione v3 dipende dall'ufficializzazione correction-aware v2.
-- La funzione viene ricreata con la definizione validata della migrazione 080
-- per rendere questo script autosufficiente anche se la firma v2 non è presente.

create or replace function public.finalize_league_matchday_guarded_v2(
  p_league_id uuid,
  p_matchday_id uuid,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_league public.leagues%rowtype;
  v_matchday public.matchdays%rowtype;
  v_existing public.matchday_officialization_runs%rowtype;
  v_run public.matchday_officialization_runs%rowtype;
  v_fixture record;
  v_payload jsonb;
  v_input_hash text;
  v_result_hash text;
  v_source_projection_ids jsonb;
  v_source_correction_run_ids jsonb;
  v_fixture_count integer := 0;
  v_official_count integer := 0;
  v_pending_count integer := 0;
  v_linked_run_count integer := 0;
  v_revision integer := 1;
  v_updated integer := 0;
  v_active_run_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if p_request_id is null then
    raise exception 'Identificativo di ufficializzazione mancante.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'matchday-officialization:'
        || p_league_id::text
        || ':'
        || p_matchday_id::text,
      0
    )
  );

  select league.*
  into v_league
  from public.leagues league
  where league.id = p_league_id
  for update;

  if not found then
    raise exception 'Lega non trovata.';
  end if;

  if v_league.owner_id <> auth.uid() then
    raise exception 'Solo il Presidente può ufficializzare la giornata.';
  end if;

  if v_league.competition_started_at is null then
    raise exception 'Avvia la competizione prima di chiudere una giornata.';
  end if;

  if v_league.status in ('completed', 'archived') then
    raise exception 'La stagione è già conclusa e non può essere modificata.';
  end if;

  select matchday.*
  into v_matchday
  from public.matchdays matchday
  where matchday.id = p_matchday_id
    and exists (
      select 1
      from public.fantasy_fixtures fixture
      where fixture.league_id = p_league_id
        and fixture.matchday_id = p_matchday_id
    )
  for update;

  if not found then
    raise exception 'Giornata non trovata nel calendario della lega.';
  end if;

  if now() < coalesce(
    v_matchday.ends_at,
    v_matchday.starts_at + interval '4 days'
  ) then
    raise exception 'La giornata reale non è ancora terminata.';
  end if;

  select
    count(*)::integer,
    count(*) filter (where fixture.finalized_at is not null)::integer,
    count(distinct fixture.officialization_run_id) filter (
      where fixture.officialization_run_id is not null
    )::integer
  into v_fixture_count, v_official_count, v_linked_run_count
  from public.fantasy_fixtures fixture
  where fixture.league_id = p_league_id
    and fixture.matchday_id = p_matchday_id;

  if v_fixture_count = 0 then
    raise exception 'La giornata non contiene partite fantasy.';
  end if;

  v_pending_count := v_fixture_count - v_official_count;

  if v_official_count = v_fixture_count
    and v_linked_run_count = 1 then
    select run.*
    into v_existing
    from public.matchday_officialization_runs run
    where run.id = (
      select min(fixture.officialization_run_id)
      from public.fantasy_fixtures fixture
      where fixture.league_id = p_league_id
        and fixture.matchday_id = p_matchday_id
    )
      and run.superseded_at is null;

    if found then
      return v_existing.result_payload || jsonb_build_object(
        'officializationId', v_existing.id,
        'officializationRevision', v_existing.finalization_revision,
        'officializationInputHash', v_existing.input_hash,
        'officializationHash', v_existing.result_hash,
        'finalizedAt', v_existing.finalized_at,
        'finalizedFixtureCount', v_existing.finalized_fixture_count,
        'newlyFinalizedFixtureCount', 0,
        'idempotentReplay', true
      );
    end if;
  end if;

  select run.*
  into v_existing
  from public.matchday_officialization_runs run
  where run.request_id = p_request_id;

  if found then
    if v_existing.league_id <> p_league_id
      or v_existing.matchday_id <> p_matchday_id then
      raise exception
        'La chiave di ufficializzazione è già stata utilizzata.';
    end if;

    return v_existing.result_payload || jsonb_build_object(
      'officializationId', v_existing.id,
      'officializationRevision', v_existing.finalization_revision,
      'officializationInputHash', v_existing.input_hash,
      'officializationHash', v_existing.result_hash,
      'finalizedAt', v_existing.finalized_at,
      'finalizedFixtureCount', v_existing.finalized_fixture_count,
      'newlyFinalizedFixtureCount', 0,
      'idempotentReplay', true
    );
  end if;

  perform public.ensure_matchday_lineups(p_matchday_id);

  for v_fixture in
    select fixture.id
    from public.fantasy_fixtures fixture
    where fixture.league_id = p_league_id
      and fixture.matchday_id = p_matchday_id
      and fixture.finalized_at is null
    order by fixture.id
    for update
  loop
    perform public.refresh_live_fixture_projection_guarded_v1(
      v_fixture.id,
      public.leghevo_stable_request_uuid(
        'matchday-finalization-v2-source:'
          || p_matchday_id::text
          || ':'
          || v_fixture.id::text
          || ':'
          || coalesce(
            public.live_fixture_projection_input_hash_v1(v_fixture.id),
            'missing'
          )
      )
    );
  end loop;

  v_payload := public.compute_matchday_officialization_v2(
    p_league_id,
    p_matchday_id
  );

  if not coalesce((v_payload ->> 'available')::boolean, false) then
    raise exception 'Ufficializzazione non disponibile per questa giornata.';
  end if;

  if not coalesce((v_payload ->> 'providerComplete')::boolean, false) then
    raise exception 'Il provider non ha ancora chiuso tutte le partite reali della giornata.';
  end if;

  if not coalesce((v_payload ->> 'allReady')::boolean, false) then
    raise exception
      'Mancano voti o sostituzioni certificate: % partite pronte su %.',
      coalesce((v_payload ->> 'readyCount')::integer, 0),
      coalesce((v_payload ->> 'fixtureCount')::integer, 0);
  end if;

  v_input_hash := public.matchday_officialization_input_hash_v2(
    p_league_id,
    p_matchday_id
  );

  if v_input_hash is null then
    raise exception 'Impossibile calcolare l''impronta della giornata.';
  end if;

  select coalesce(max(run.finalization_revision), 0) + 1
  into v_revision
  from public.matchday_officialization_runs run
  where run.matchday_id = p_matchday_id;

  select coalesce(
    jsonb_agg(source.projection_id order by source.fixture_id),
    '[]'::jsonb
  )
  into v_source_projection_ids
  from (
    select
      fixture.id as fixture_id,
      coalesce(
        fixture.official_projection_id,
        current_projection.id
      ) as projection_id
    from public.fantasy_fixtures fixture
    left join public.live_fixture_projection_runs current_projection
      on fixture.finalized_at is null
     and current_projection.fixture_id = fixture.id
     and current_projection.superseded_at is null
    where fixture.league_id = p_league_id
      and fixture.matchday_id = p_matchday_id
  ) source;

  select coalesce(
    jsonb_agg(source.correction_run_id order by source.correction_run_id),
    '[]'::jsonb
  )
  into v_source_correction_run_ids
  from (
    select distinct fixture.correction_run_id
    from public.fantasy_fixtures fixture
    where fixture.league_id = p_league_id
      and fixture.matchday_id = p_matchday_id
      and fixture.correction_run_id is not null
  ) source;

  v_result_hash := md5(v_payload::text);

  perform set_config(
    'leghevo.matchday_officialization_context',
    'on',
    true
  );

  update public.matchday_officialization_runs run
  set superseded_at = now()
  where run.matchday_id = p_matchday_id
    and run.superseded_at is null;

  insert into public.matchday_officialization_runs (
    league_id,
    matchday_id,
    request_id,
    finalization_revision,
    input_hash,
    result_hash,
    fixture_count,
    finalized_fixture_count,
    source_projection_ids,
    source_correction_run_ids,
    result_payload,
    finalized_by
  )
  values (
    p_league_id,
    p_matchday_id,
    p_request_id,
    v_revision,
    v_input_hash,
    v_result_hash,
    v_fixture_count,
    v_fixture_count,
    v_source_projection_ids,
    v_source_correction_run_ids,
    v_payload,
    auth.uid()
  )
  returning * into v_run;

  update public.fantasy_fixtures fixture
  set
    home_base_points = nullif(
      projection.projection_payload #>> '{home,basePoints}',
      ''
    )::numeric,
    away_base_points = nullif(
      projection.projection_payload #>> '{away,basePoints}',
      ''
    )::numeric,
    home_defense_modifier = coalesce(
      nullif(
        projection.projection_payload #>> '{home,defenseModifier,bonus}',
        ''
      )::numeric,
      0
    ),
    away_defense_modifier = coalesce(
      nullif(
        projection.projection_payload #>> '{away,defenseModifier,bonus}',
        ''
      )::numeric,
      0
    ),
    home_bonus_applied = coalesce(
      nullif(
        projection.projection_payload #>> '{home,homeBonus}',
        ''
      )::numeric,
      0
    ),
    home_goal_margin_bonus = coalesce(
      nullif(
        projection.projection_payload #>> '{goalMargin,homeBonus}',
        ''
      )::smallint,
      0
    ),
    away_goal_margin_bonus = coalesce(
      nullif(
        projection.projection_payload #>> '{goalMargin,awayBonus}',
        ''
      )::smallint,
      0
    ),
    home_points = projection.home_points,
    away_points = projection.away_points,
    home_goals = projection.home_goals,
    away_goals = projection.away_goals,
    home_counted_players = projection.home_counted_players,
    away_counted_players = projection.away_counted_players,
    home_ready = projection.home_ready,
    away_ready = projection.away_ready,
    official_projection_id = projection.id,
    finalized_at = now(),
    finalized_by = auth.uid()
  from public.live_fixture_projection_runs projection
  where fixture.league_id = p_league_id
    and fixture.matchday_id = p_matchday_id
    and fixture.finalized_at is null
    and projection.fixture_id = fixture.id
    and projection.superseded_at is null;

  get diagnostics v_updated = row_count;

  if v_updated <> v_pending_count then
    raise exception
      'Ufficializzazione incompleta: % partite aggiornate su %.',
      v_updated,
      v_pending_count;
  end if;

  update public.fantasy_fixtures fixture
  set officialization_run_id = v_run.id
  where fixture.league_id = p_league_id
    and fixture.matchday_id = p_matchday_id
    and fixture.finalized_at is not null;

  select run.id
  into v_active_run_id
  from public.matchday_officialization_runs run
  where run.matchday_id = p_matchday_id
    and run.superseded_at is null;

  if v_active_run_id is distinct from v_run.id then
    raise exception 'La revisione ufficiale corrente non è coerente.';
  end if;

  return v_payload || jsonb_build_object(
    'officializationId', v_run.id,
    'officializationRevision', v_run.finalization_revision,
    'officializationInputHash', v_run.input_hash,
    'officializationHash', v_run.result_hash,
    'sourceCorrectionRunIds', v_run.source_correction_run_ids,
    'finalizedAt', v_run.finalized_at,
    'finalizedFixtureCount', v_fixture_count,
    'newlyFinalizedFixtureCount', v_updated,
    'idempotentReplay', false
  );
end;
$$;

-- Compatibilità: tutte le vecchie entrate confluiscono nel percorso v2.

create or replace function public.finalize_league_matchday_guarded_v3(
  p_league_id uuid,
  p_matchday_id uuid,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_officialization jsonb;
  v_progression jsonb;
  v_progression_request_id uuid;
begin
  if p_request_id is null then
    raise exception 'Identificativo di ufficializzazione mancante.';
  end if;

  v_officialization := public.finalize_league_matchday_guarded_v2(
    p_league_id,
    p_matchday_id,
    p_request_id
  );

  v_progression_request_id := public.leghevo_stable_request_uuid(
    'matchday-progression:'
      || p_league_id::text
      || ':'
      || p_matchday_id::text
      || ':'
      || coalesce(v_officialization ->> 'officializationId', 'missing')
  );

  v_progression := public.settle_matchday_progression_guarded_v1(
    p_league_id,
    p_matchday_id,
    v_progression_request_id
  );

  return v_officialization || jsonb_build_object(
    'progression', v_progression,
    'progressionId', v_progression ->> 'progressionId',
    'progressionRevision', v_progression ->> 'progressionRevision',
    'standingsHash', v_progression ->> 'standingsHash',
    'advanced', coalesce((v_progression ->> 'advanced')::boolean, false),
    'nextMatchdayId', v_progression ->> 'nextMatchdayId',
    'nextMatchdayNumber', v_progression ->> 'nextMatchdayNumber',
    'seasonReadyToComplete', coalesce(
      (v_progression ->> 'seasonReadyToComplete')::boolean,
      false
    )
  );
end;
$$;

create or replace function public.finalize_league_matchday(
  p_league_id uuid,
  p_matchday_id uuid
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_result jsonb;
begin
  v_result := public.finalize_league_matchday_guarded_v3(
    p_league_id,
    p_matchday_id,
    gen_random_uuid()
  );

  return coalesce(
    (v_result ->> 'finalizedFixtureCount')::integer,
    0
  );
end;
$$;

create or replace function public.get_league_matchday_progression_integrity_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_league public.leagues%rowtype;
  v_run_count integer := 0;
  v_current_run_count integer := 0;
  v_invalid_link_count integer := 0;
  v_invalid_hash_count integer := 0;
  v_invalid_current_count integer := 0;
  v_revision_gap_count integer := 0;
  v_pointer_valid boolean := false;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if not public.is_league_member(p_league_id)
    and not public.is_league_admin(p_league_id) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  select league.*
  into v_league
  from public.leagues league
  where league.id = p_league_id;

  if not found then
    raise exception 'Lega non trovata.';
  end if;

  select
    count(*)::integer,
    count(*) filter (where run.superseded_at is null)::integer,
    count(*) filter (
      where officialization.id is null
        or officialization.league_id <> run.league_id
        or officialization.matchday_id <> run.matchday_id
    )::integer,
    count(*) filter (
      where run.standings_hash <> md5(run.standings_snapshot::text)
    )::integer,
    count(*) filter (
      where run.superseded_at is null
        and officialization.superseded_at is not null
    )::integer
  into
    v_run_count,
    v_current_run_count,
    v_invalid_link_count,
    v_invalid_hash_count,
    v_invalid_current_count
  from public.matchday_progression_runs run
  left join public.matchday_officialization_runs officialization
    on officialization.id = run.officialization_run_id
  where run.league_id = p_league_id;

  select count(*)::integer
  into v_revision_gap_count
  from (
    select run.matchday_id
    from public.matchday_progression_runs run
    where run.league_id = p_league_id
    group by run.matchday_id
    having min(run.progression_revision) <> 1
      or max(run.progression_revision) <> count(*)
      or count(distinct run.progression_revision) <> count(*)
  ) invalid_revision;

  v_pointer_valid :=
    v_league.current_matchday_id is not null
    and v_league.current_matchday_number is not null
    and exists (
      select 1
      from public.matchdays matchday
      join public.fantasy_fixtures fixture
        on fixture.matchday_id = matchday.id
      where matchday.id = v_league.current_matchday_id
        and matchday.number = v_league.current_matchday_number
        and fixture.league_id = p_league_id
    );

  return jsonb_build_object(
    'healthy',
      v_invalid_link_count = 0
      and v_invalid_hash_count = 0
      and v_invalid_current_count = 0
      and v_revision_gap_count = 0
      and v_pointer_valid,
    'runCount', v_run_count,
    'currentRunCount', v_current_run_count,
    'invalidLinkCount', v_invalid_link_count,
    'invalidHashCount', v_invalid_hash_count,
    'invalidCurrentCount', v_invalid_current_count,
    'revisionGapCount', v_revision_gap_count,
    'currentMatchdayId', v_league.current_matchday_id,
    'currentMatchdayNumber', v_league.current_matchday_number,
    'currentMatchdayPointerValid', v_pointer_valid,
    'progressionPolicy', 'protected_v1'
  );
end;
$$;

revoke all on function public.prevent_matchday_progression_mutation()
from public, anon, authenticated;
revoke all on function public.build_league_standings_snapshot_v1(uuid)
from public, anon;
revoke all on function public.settle_matchday_progression_guarded_v1(uuid, uuid, uuid)
from public, anon, authenticated;
revoke all on function public.finalize_league_matchday_guarded_v3(uuid, uuid, uuid)
from public, anon;
revoke all on function public.get_league_matchday_progression_integrity_v1(uuid)
from public, anon;
revoke all on function public.finalize_league_matchday_guarded_v2(uuid, uuid, uuid)
from public, anon, authenticated;
revoke all on function public.finalize_league_matchday_guarded_v1(uuid, uuid, uuid)
from public, anon, authenticated;
revoke all on function public.finalize_league_matchday(uuid, uuid)
from public, anon;

grant execute on function public.build_league_standings_snapshot_v1(uuid)
to authenticated;
grant execute on function public.finalize_league_matchday_guarded_v3(uuid, uuid, uuid)
to authenticated;
grant execute on function public.get_league_matchday_progression_integrity_v1(uuid)
to authenticated;
grant execute on function public.finalize_league_matchday(uuid, uuid)
to authenticated;

do $$
begin
  if exists (
    select 1
    from pg_catalog.pg_publication publication
    where publication.pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'matchday_progression_runs'
  ) then
    alter publication supabase_realtime
      add table public.matchday_progression_runs;
  end if;
end;
$$;

commit;

-- Controllo finale: attesi 20 valori true.
select
  to_regclass('public.matchday_progression_runs') is not null
    as progression_table_ready,
  (
    select count(*) = 19
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'matchday_progression_runs'
  ) as progression_columns_ready,
  (
    select exists (
      select 1
      from pg_catalog.pg_indexes
      where schemaname = 'public'
        and tablename = 'matchday_progression_runs'
        and indexname = 'matchday_progression_current_idx'
    )
  ) as single_current_progression_index_ready,
  (
    select exists (
      select 1
      from pg_catalog.pg_indexes
      where schemaname = 'public'
        and tablename = 'matchday_progression_runs'
        and indexname = 'matchday_progression_league_idx'
    )
  ) as progression_league_index_ready,
  (
    select relrowsecurity
    from pg_catalog.pg_class
    where oid = 'public.matchday_progression_runs'::regclass
  ) as progression_rls_ready,
  (
    select count(*) = 1
    from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'matchday_progression_runs'
      and policyname = 'matchday_progression_read_members'
  ) as progression_read_policy_ready,
  to_regprocedure(
    'public.prevent_matchday_progression_mutation()'
  ) is not null as progression_guard_function_ready,
  (
    select count(*) = 1
    from pg_catalog.pg_trigger trigger_row
    where not trigger_row.tgisinternal
      and trigger_row.tgname = 'matchday_progression_immutable'
  ) as progression_guard_trigger_ready,
  to_regprocedure(
    'public.build_league_standings_snapshot_v1(uuid)'
  ) is not null as standings_snapshot_function_ready,
  to_regprocedure(
    'public.settle_matchday_progression_guarded_v1(uuid,uuid,uuid)'
  ) is not null as guarded_progression_function_ready,
  to_regprocedure(
    'public.finalize_league_matchday_guarded_v3(uuid,uuid,uuid)'
  ) is not null as guarded_finalization_v3_ready,
  to_regprocedure(
    'public.get_league_matchday_progression_integrity_v1(uuid)'
  ) is not null as progression_integrity_function_ready,
  has_function_privilege(
    'authenticated',
    'public.finalize_league_matchday_guarded_v3(uuid,uuid,uuid)',
    'EXECUTE'
  ) as authenticated_finalization_v3_access_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_matchday_progression_integrity_v1(uuid)',
    'EXECUTE'
  ) as authenticated_progression_diagnostic_access_ready,
  not has_function_privilege(
    'authenticated',
    'public.finalize_league_matchday_guarded_v2(uuid,uuid,uuid)',
    'EXECUTE'
  ) as legacy_finalization_v2_blocked,
  has_table_privilege(
    'authenticated',
    'public.matchday_progression_runs',
    'SELECT'
  ) as authenticated_progression_read_ready,
  not has_table_privilege(
    'authenticated',
    'public.matchday_progression_runs',
    'INSERT'
  ) as authenticated_progression_insert_blocked,
  coalesce(
    pg_get_functiondef(
      to_regprocedure(
        'public.settle_matchday_progression_guarded_v1(uuid,uuid,uuid)'
      )
    ) ilike '%pg_advisory_xact_lock%',
    false
  ) as progression_advisory_lock_ready,
  coalesce(
    pg_get_functiondef(
      to_regprocedure(
        'public.settle_matchday_progression_guarded_v1(uuid,uuid,uuid)'
      )
    ) ilike '%current_matchday_id = v_next_matchday.id%',
    false
  ) as next_matchday_advancement_ready,
  exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'matchday_progression_runs'
  ) as progression_realtime_ready;
