-- LEGHEVO · chiusura protetta e continuità della stagione
-- Versione applicativa: 0.59.8
-- Migrazione prevista: database/082_season_completion_continuity_safety.sql
-- Eseguire dopo database/081_matchday_progression_and_standings_snapshot_safety.sql.
-- Script idempotente: può essere eseguito più volte.

begin;

create table if not exists public.season_completion_runs (
  id bigint generated by default as identity primary key,
  league_id uuid not null unique
    references public.leagues(id) on delete cascade,
  request_id uuid not null unique,
  final_matchday_id uuid not null
    references public.matchdays(id) on delete restrict,
  final_progression_run_id bigint not null
    references public.matchday_progression_runs(id) on delete restrict,
  final_officialization_run_id bigint not null
    references public.matchday_officialization_runs(id) on delete restrict,
  input_hash text not null,
  standings_hash text not null,
  final_standings jsonb not null,
  champion_team_id uuid not null
    references public.fantasy_teams(id) on delete restrict,
  champion_team_name text not null,
  champion_manager_name text not null,
  champion_source text not null,
  season text not null,
  fixture_count integer not null,
  result_payload jsonb not null default '{}'::jsonb,
  adopted_existing boolean not null default false,
  completed_by uuid references public.profiles(id) on delete set null,
  completed_at timestamptz not null default now(),
  constraint season_completion_input_hash_check
    check (length(input_hash) = 32),
  constraint season_completion_standings_hash_check
    check (length(standings_hash) = 32),
  constraint season_completion_standings_check
    check (
      jsonb_typeof(final_standings) = 'array'
      and jsonb_array_length(final_standings) > 0
    ),
  constraint season_completion_champion_source_check
    check (champion_source in ('regular_season', 'playoffs')),
  constraint season_completion_fixture_count_check
    check (fixture_count > 0)
);

create index if not exists season_completion_final_progression_idx
  on public.season_completion_runs (final_progression_run_id);

create index if not exists season_completion_completed_at_idx
  on public.season_completion_runs (league_id, completed_at desc);

alter table public.season_completion_runs enable row level security;

drop policy if exists season_completion_read_members
on public.season_completion_runs;
create policy season_completion_read_members
on public.season_completion_runs
for select to authenticated
using (
  public.is_league_member(league_id)
  or public.is_league_admin(league_id)
);

revoke all on table public.season_completion_runs
from public, anon, authenticated;
grant select on table public.season_completion_runs
to authenticated;

create or replace function public.prevent_season_completion_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if coalesce(
    current_setting('leghevo.season_completion_context', true),
    ''
  ) = 'on' then
    if tg_op = 'DELETE' then
      return old;
    end if;
    return new;
  end if;

  raise exception
    'Chiusura certificata: modifica diretta non consentita.';
end;
$$;

drop trigger if exists season_completion_immutable
on public.season_completion_runs;
create trigger season_completion_immutable
before update or delete on public.season_completion_runs
for each row
execute function public.prevent_season_completion_mutation();

create or replace function public.complete_league_season_core_v2(
  p_league_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_league public.leagues%rowtype;
  v_playoff public.league_playoffs%rowtype;
  v_fixture_count integer := 0;
  v_official_fixture_count integer := 0;
  v_team_count integer := 0;
  v_final_standings jsonb := '[]'::jsonb;
  v_champion_team_id uuid;
  v_champion_team_name text;
  v_champion_manager_name text;
  v_tiebreaker text := 'goal_difference';
  v_champion_source text := 'regular_season';
  v_season text;
  v_completed_at timestamptz := now();
  v_member_user_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  select league.*
  into v_league
  from public.leagues league
  where league.id = p_league_id
  for update;

  if not found then
    raise exception 'Lega non trovata.';
  end if;

  if v_league.owner_id <> auth.uid() then
    raise exception 'Solo il Presidente può chiudere la stagione.';
  end if;

  if v_league.status = 'archived' then
    raise exception 'La lega è già archiviata.';
  end if;

  if v_league.status = 'completed' then
    select summary.champion_team_id
    into v_champion_team_id
    from public.league_season_summaries summary
    where summary.league_id = p_league_id;

    return coalesce(v_champion_team_id, v_league.champion_team_id);
  end if;

  if v_league.status <> 'active'
    or v_league.competition_started_at is null then
    raise exception 'La competizione non è ancora iniziata.';
  end if;

  select
    count(*)::integer,
    count(*) filter (
      where fixture.finalized_at is not null
    )::integer
  into
    v_fixture_count,
    v_official_fixture_count
  from public.fantasy_fixtures fixture
  where fixture.league_id = p_league_id;

  if v_fixture_count = 0 then
    raise exception 'Il calendario non contiene partite.';
  end if;

  if v_official_fixture_count <> v_fixture_count then
    raise exception
      'Tutti i risultati devono essere ufficiali prima della chiusura.';
  end if;

  select playoff.*
  into v_playoff
  from public.league_playoffs playoff
  where playoff.league_id = p_league_id;

  if found and v_playoff.status <> 'completed' then
    raise exception
      'Prima di chiudere la stagione devi completare i Playoff Scudetto.';
  end if;

  select count(*)::integer
  into v_team_count
  from public.fantasy_teams team
  where team.league_id = p_league_id;

  if v_playoff.id is not null then
    v_champion_team_id := v_playoff.champion_team_id;
    v_champion_source := 'playoffs';
  end if;

  with regular_standings as (
    select
      standing.position as regular_position,
      standing.fantasy_team_id,
      standing.team_name,
      profile.display_name as manager_name,
      standing.played,
      standing.won,
      standing.drawn,
      standing.lost,
      standing.goals_for,
      standing.goals_against,
      standing.goal_difference,
      standing.points_for,
      standing.league_points,
      case
        when v_playoff.id is null then standing.position
        when standing.fantasy_team_id = v_playoff.champion_team_id then 0
        when standing.fantasy_team_id = v_playoff.runner_up_team_id then 1
        else standing.position + 2
      end as final_order
    from public.get_league_standings_v2(p_league_id) standing
    join public.fantasy_teams team
      on team.id = standing.fantasy_team_id
    join public.profiles profile
      on profile.id = team.manager_id
  ),
  final_ranked as (
    select
      row_number() over (
        order by regular.final_order, regular.regular_position
      )::integer as final_position,
      regular.*
    from regular_standings regular
  )
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'position', ranked.final_position,
        'regularSeasonPosition', ranked.regular_position,
        'teamId', ranked.fantasy_team_id,
        'teamName', ranked.team_name,
        'managerName', ranked.manager_name,
        'played', ranked.played,
        'won', ranked.won,
        'drawn', ranked.drawn,
        'lost', ranked.lost,
        'goalsFor', ranked.goals_for,
        'goalsAgainst', ranked.goals_against,
        'goalDifference', ranked.goal_difference,
        'pointsFor', ranked.points_for,
        'leaguePoints', ranked.league_points
      )
      order by ranked.final_position
    ),
    '[]'::jsonb
  )
  into v_final_standings
  from final_ranked ranked;

  if jsonb_array_length(v_final_standings) <> v_team_count
    or v_team_count = 0 then
    raise exception
      'La classifica finale non contiene tutte le squadre.';
  end if;

  if v_champion_team_id is null then
    v_champion_team_id :=
      (v_final_standings -> 0 ->> 'teamId')::uuid;
  end if;

  select
    team.name,
    coalesce(profile.display_name, 'Manager')
  into
    v_champion_team_name,
    v_champion_manager_name
  from public.fantasy_teams team
  left join public.profiles profile on profile.id = team.manager_id
  where team.id = v_champion_team_id;

  if v_champion_team_name is null then
    raise exception 'Il campione non appartiene alla lega.';
  end if;

  v_tiebreaker := case
    when lower(
      coalesce(
        v_league.scoring_rules ->> 'standings_tiebreaker',
        'goal_difference'
      )
    ) in (
      'goal_difference',
      'fantasy_points',
      'head_to_head'
    )
      then lower(
        coalesce(
          v_league.scoring_rules ->> 'standings_tiebreaker',
          'goal_difference'
        )
      )
    else 'goal_difference'
  end;

  select coalesce(
    v_league.calendar_season,
    min(matchday.season),
    extract(year from v_completed_at)::integer::text
  )
  into v_season
  from public.matchdays matchday
  join public.fantasy_fixtures fixture
    on fixture.matchday_id = matchday.id
  where fixture.league_id = p_league_id;

  insert into public.league_season_summaries (
    league_id,
    season,
    champion_team_id,
    champion_team_name,
    champion_manager_name,
    champion_source,
    standings_tiebreaker,
    fixture_count,
    final_standings,
    completed_at,
    completed_by
  )
  values (
    p_league_id,
    v_season,
    v_champion_team_id,
    v_champion_team_name,
    v_champion_manager_name,
    v_champion_source,
    v_tiebreaker,
    v_fixture_count,
    v_final_standings,
    v_completed_at,
    auth.uid()
  );

  update public.leagues
  set
    status = 'completed',
    invites_open = false,
    champion_team_id = v_champion_team_id,
    competition_completed_at = v_completed_at,
    scoring_rules = coalesce(scoring_rules, '{}'::jsonb)
      || jsonb_build_object('market_open', false),
    updated_at = v_completed_at
  where id = p_league_id;

  for v_member_user_id in
    select member.user_id
    from public.league_members member
    where member.league_id = p_league_id
  loop
    perform public.create_user_notification(
      v_member_user_id,
      p_league_id,
      'league',
      'Campionato concluso',
      v_champion_team_name
        || ' è Campione di '
        || v_league.name
        || '. La classifica finale è ora nell''albo della lega.',
      'standings',
      jsonb_build_object(
        'event', 'season_completed',
        'champion_team_id', v_champion_team_id,
        'champion_source', v_champion_source,
        'season', v_season
      ),
      'season:completed:'
        || p_league_id::text
        || ':'
        || v_member_user_id::text
    );
  end loop;

  return v_champion_team_id;
end;
$$;


create or replace function public.complete_league_season_guarded_v1(
  p_league_id uuid,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_league public.leagues%rowtype;
  v_existing public.season_completion_runs%rowtype;
  v_final_matchday public.matchdays%rowtype;
  v_final_progression public.matchday_progression_runs%rowtype;
  v_summary public.league_season_summaries%rowtype;
  v_playoff public.league_playoffs%rowtype;
  v_matchday_count integer := 0;
  v_progression_count integer := 0;
  v_fixture_count integer := 0;
  v_champion_team_id uuid;
  v_input_hash text;
  v_standings_hash text;
  v_payload jsonb;
  v_adopted boolean := false;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if p_request_id is null then
    raise exception 'Identificativo di chiusura mancante.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'season-completion:' || p_league_id::text,
      0
    )
  );

  select run.*
  into v_existing
  from public.season_completion_runs run
  where run.request_id = p_request_id;

  if found then
    if v_existing.league_id <> p_league_id then
      raise exception 'Identificativo di chiusura già usato per un''altra lega.';
    end if;
    return v_existing.result_payload;
  end if;

  select run.*
  into v_existing
  from public.season_completion_runs run
  where run.league_id = p_league_id;

  if found then
    return v_existing.result_payload;
  end if;

  select league.*
  into v_league
  from public.leagues league
  where league.id = p_league_id
  for update;

  if not found then
    raise exception 'Lega non trovata.';
  end if;

  if v_league.owner_id <> auth.uid() then
    raise exception 'Solo il Presidente può chiudere la stagione.';
  end if;

  if v_league.status = 'archived' then
    raise exception 'La lega è già archiviata.';
  end if;

  if v_league.competition_started_at is null then
    raise exception 'La competizione non è ancora iniziata.';
  end if;

  select count(distinct fixture.matchday_id)::integer,
         count(*)::integer
  into v_matchday_count, v_fixture_count
  from public.fantasy_fixtures fixture
  where fixture.league_id = p_league_id;

  if v_matchday_count = 0 or v_fixture_count = 0 then
    raise exception 'Il calendario non contiene partite.';
  end if;

  select matchday.*
  into v_final_matchday
  from public.matchdays matchday
  where exists (
    select 1
    from public.fantasy_fixtures fixture
    where fixture.league_id = p_league_id
      and fixture.matchday_id = matchday.id
  )
  order by matchday.number desc, matchday.id
  limit 1;

  select count(distinct progression.matchday_id)::integer
  into v_progression_count
  from public.matchday_progression_runs progression
  join public.matchday_officialization_runs officialization
    on officialization.id = progression.officialization_run_id
  where progression.league_id = p_league_id
    and progression.superseded_at is null
    and officialization.superseded_at is null;

  if v_progression_count <> v_matchday_count then
    raise exception
      'Prima devi certificare la progressione di tutte le giornate ufficiali.';
  end if;

  select progression.*
  into v_final_progression
  from public.matchday_progression_runs progression
  join public.matchday_officialization_runs officialization
    on officialization.id = progression.officialization_run_id
  where progression.league_id = p_league_id
    and progression.matchday_id = v_final_matchday.id
    and progression.superseded_at is null
    and officialization.superseded_at is null
  order by progression.progression_revision desc
  limit 1;

  if not found or not v_final_progression.season_ready_to_complete then
    raise exception
      'L''ultima giornata non è ancora pronta alla chiusura della stagione.';
  end if;

  if v_final_progression.standings_hash
    <> md5(v_final_progression.standings_snapshot::text) then
    raise exception
      'La fotografia finale della classifica non supera il controllo di integrità.';
  end if;

  select playoff.*
  into v_playoff
  from public.league_playoffs playoff
  where playoff.league_id = p_league_id;

  v_input_hash := md5(
    concat_ws(
      '|',
      p_league_id::text,
      v_final_matchday.id::text,
      v_final_progression.id::text,
      v_final_progression.officialization_run_id::text,
      v_final_progression.input_hash,
      v_final_progression.standings_hash,
      coalesce(v_playoff.id::text, ''),
      coalesce(v_playoff.status, ''),
      coalesce(v_playoff.champion_team_id::text, ''),
      v_fixture_count::text
    )
  );

  if v_league.status = 'completed' then
    select summary.*
    into v_summary
    from public.league_season_summaries summary
    where summary.league_id = p_league_id;

    if not found then
      raise exception 'La stagione risulta conclusa ma manca il riepilogo finale.';
    end if;
    v_champion_team_id := v_summary.champion_team_id;
    v_adopted := true;
  else
    v_champion_team_id := public.complete_league_season_core_v2(p_league_id);

    select summary.*
    into v_summary
    from public.league_season_summaries summary
    where summary.league_id = p_league_id;

    if not found then
      raise exception 'La chiusura non ha prodotto il riepilogo finale.';
    end if;
  end if;

  v_standings_hash := md5(v_summary.final_standings::text);
  v_payload := jsonb_build_object(
    'leagueId', p_league_id,
    'completionRunId', null,
    'requestId', p_request_id,
    'finalMatchdayId', v_final_matchday.id,
    'finalMatchdayNumber', v_final_matchday.number,
    'finalProgressionRunId', v_final_progression.id,
    'finalProgressionRevision', v_final_progression.progression_revision,
    'finalOfficializationRunId', v_final_progression.officialization_run_id,
    'championTeamId', v_summary.champion_team_id,
    'championTeamName', v_summary.champion_team_name,
    'championManagerName', v_summary.champion_manager_name,
    'championSource', v_summary.champion_source,
    'season', v_summary.season,
    'fixtureCount', v_summary.fixture_count,
    'standingsHash', v_standings_hash,
    'adoptedExisting', v_adopted,
    'completedAt', v_summary.completed_at
  );

  insert into public.season_completion_runs (
    league_id,
    request_id,
    final_matchday_id,
    final_progression_run_id,
    final_officialization_run_id,
    input_hash,
    standings_hash,
    final_standings,
    champion_team_id,
    champion_team_name,
    champion_manager_name,
    champion_source,
    season,
    fixture_count,
    result_payload,
    adopted_existing,
    completed_by,
    completed_at
  )
  values (
    p_league_id,
    p_request_id,
    v_final_matchday.id,
    v_final_progression.id,
    v_final_progression.officialization_run_id,
    v_input_hash,
    v_standings_hash,
    v_summary.final_standings,
    v_summary.champion_team_id,
    v_summary.champion_team_name,
    v_summary.champion_manager_name,
    v_summary.champion_source,
    v_summary.season,
    v_summary.fixture_count,
    v_payload,
    v_adopted,
    auth.uid(),
    v_summary.completed_at
  )
  returning result_payload || jsonb_build_object('completionRunId', id)
  into v_payload;

  perform set_config('leghevo.season_completion_context', 'on', true);
  update public.season_completion_runs
  set result_payload = v_payload
  where league_id = p_league_id;
  perform set_config('leghevo.season_completion_context', 'off', true);

  return v_payload;
end;
$$;

create or replace function public.complete_league_season(
  p_league_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_result jsonb;
begin
  v_result := public.complete_league_season_guarded_v1(
    p_league_id,
    gen_random_uuid()
  );
  return (v_result ->> 'championTeamId')::uuid;
end;
$$;

create or replace function public.get_league_season_state_v4(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_state jsonb;
  v_run public.season_completion_runs%rowtype;
  v_final_progression public.matchday_progression_runs%rowtype;
  v_matchday_count integer := 0;
  v_progression_count integer := 0;
  v_progression_ready boolean := false;
begin
  v_state := public.get_league_season_state_v3(p_league_id);

  select run.*
  into v_run
  from public.season_completion_runs run
  where run.league_id = p_league_id;

  select count(distinct fixture.matchday_id)::integer
  into v_matchday_count
  from public.fantasy_fixtures fixture
  where fixture.league_id = p_league_id;

  select count(distinct progression.matchday_id)::integer
  into v_progression_count
  from public.matchday_progression_runs progression
  join public.matchday_officialization_runs officialization
    on officialization.id = progression.officialization_run_id
  where progression.league_id = p_league_id
    and progression.superseded_at is null
    and officialization.superseded_at is null;

  select progression.*
  into v_final_progression
  from public.matchday_progression_runs progression
  join public.matchdays matchday
    on matchday.id = progression.matchday_id
  join public.matchday_officialization_runs officialization
    on officialization.id = progression.officialization_run_id
  where progression.league_id = p_league_id
    and progression.superseded_at is null
    and officialization.superseded_at is null
  order by matchday.number desc, progression.progression_revision desc
  limit 1;

  v_progression_ready :=
    v_matchday_count > 0
    and v_progression_count = v_matchday_count
    and v_final_progression.id is not null
    and v_final_progression.season_ready_to_complete
    and v_final_progression.standings_hash
      = md5(v_final_progression.standings_snapshot::text);

  return v_state || jsonb_build_object(
    'canComplete',
      coalesce((v_state ->> 'canComplete')::boolean, false)
      and v_progression_ready,
    'completionCertified', v_run.id is not null,
    'completionRunId', v_run.id,
    'completionStandingsHash', v_run.standings_hash,
    'finalProgressionRunId', v_final_progression.id,
    'finalMatchdayId', v_final_progression.matchday_id,
    'seasonReadyToComplete', v_progression_ready
  );
end;
$$;

create or replace function public.get_league_management_state_v11(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_state jsonb;
  v_season jsonb;
  v_checks jsonb;
begin
  v_state := public.get_league_management_state_v10(p_league_id);
  v_season := public.get_league_season_state_v4(p_league_id);
  v_checks := coalesce(v_state -> 'checks', '{}'::jsonb);

  return v_state || v_season || jsonb_build_object(
    'checks', v_checks || jsonb_build_object(
      'matchdayProgressionReady',
        coalesce((v_season ->> 'seasonReadyToComplete')::boolean, false),
      'seasonCompletionCertified',
        coalesce((v_season ->> 'completionCertified')::boolean, false)
    )
  );
end;
$$;

create or replace function public.get_league_season_completion_integrity_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_league public.leagues%rowtype;
  v_run_count integer := 0;
  v_invalid_link_count integer := 0;
  v_invalid_hash_count integer := 0;
  v_invalid_summary_count integer := 0;
  v_missing_completed_run_count integer := 0;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if not public.is_league_member(p_league_id)
    and not public.is_league_admin(p_league_id) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  select league.*
  into v_league
  from public.leagues league
  where league.id = p_league_id;

  if not found then
    raise exception 'Lega non trovata.';
  end if;

  select
    count(*)::integer,
    count(*) filter (
      where progression.id is null
        or progression.league_id <> run.league_id
        or progression.matchday_id <> run.final_matchday_id
        or progression.officialization_run_id
          <> run.final_officialization_run_id
    )::integer,
    count(*) filter (
      where run.standings_hash <> md5(run.final_standings::text)
        or run.input_hash is null
        or length(run.input_hash) <> 32
    )::integer,
    count(*) filter (
      where summary.league_id is null
        or summary.champion_team_id <> run.champion_team_id
        or md5(summary.final_standings::text) <> run.standings_hash
    )::integer
  into
    v_run_count,
    v_invalid_link_count,
    v_invalid_hash_count,
    v_invalid_summary_count
  from public.season_completion_runs run
  left join public.matchday_progression_runs progression
    on progression.id = run.final_progression_run_id
  left join public.league_season_summaries summary
    on summary.league_id = run.league_id
  where run.league_id = p_league_id;

  v_missing_completed_run_count := case
    when v_league.status in ('completed', 'archived') and v_run_count = 0
      then 1
    else 0
  end;

  return jsonb_build_object(
    'healthy',
      v_invalid_link_count = 0
      and v_invalid_hash_count = 0
      and v_invalid_summary_count = 0
      and v_missing_completed_run_count = 0,
    'runCount', v_run_count,
    'invalidLinkCount', v_invalid_link_count,
    'invalidHashCount', v_invalid_hash_count,
    'invalidSummaryCount', v_invalid_summary_count,
    'missingCompletedRunCount', v_missing_completed_run_count,
    'leagueStatus', v_league.status,
    'completionPolicy', 'protected_v1'
  );
end;
$$;

revoke all on function public.prevent_season_completion_mutation()
from public, anon, authenticated;
revoke all on function public.complete_league_season_core_v2(uuid)
from public, anon, authenticated;
revoke all on function public.complete_league_season_guarded_v1(uuid, uuid)
from public, anon;
revoke all on function public.complete_league_season(uuid)
from public, anon;
revoke all on function public.get_league_season_state_v4(uuid)
from public, anon;
revoke all on function public.get_league_management_state_v11(uuid)
from public, anon;
revoke all on function public.get_league_season_completion_integrity_v1(uuid)
from public, anon;

grant execute on function public.complete_league_season_guarded_v1(uuid, uuid)
to authenticated;
grant execute on function public.complete_league_season(uuid)
to authenticated;
grant execute on function public.get_league_season_state_v4(uuid)
to authenticated;
grant execute on function public.get_league_management_state_v11(uuid)
to authenticated;
grant execute on function public.get_league_season_completion_integrity_v1(uuid)
to authenticated;

do $$
begin
  if exists (
    select 1
    from pg_catalog.pg_publication publication
    where publication.pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'season_completion_runs'
  ) then
    alter publication supabase_realtime
      add table public.season_completion_runs;
  end if;
end;
$$;

commit;

-- Controllo finale: attesi 20 valori true.
select
  to_regclass('public.season_completion_runs') is not null
    as season_completion_table_ready,
  (
    select count(*) = 19
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'season_completion_runs'
  ) as season_completion_columns_ready,
  (
    select count(*) = 1
    from pg_catalog.pg_indexes
    where schemaname = 'public'
      and tablename = 'season_completion_runs'
      and indexname = 'season_completion_runs_league_id_key'
  ) as single_completion_per_league_ready,
  (
    select exists (
      select 1
      from pg_catalog.pg_indexes
      where schemaname = 'public'
        and tablename = 'season_completion_runs'
        and indexname = 'season_completion_final_progression_idx'
    )
  ) as final_progression_index_ready,
  (
    select relrowsecurity
    from pg_catalog.pg_class
    where oid = 'public.season_completion_runs'::regclass
  ) as season_completion_rls_ready,
  (
    select count(*) = 1
    from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'season_completion_runs'
      and policyname = 'season_completion_read_members'
  ) as season_completion_read_policy_ready,
  to_regprocedure('public.prevent_season_completion_mutation()') is not null
    as season_completion_guard_function_ready,
  (
    select count(*) = 1
    from pg_catalog.pg_trigger trigger_row
    where not trigger_row.tgisinternal
      and trigger_row.tgname = 'season_completion_immutable'
  ) as season_completion_guard_trigger_ready,
  to_regprocedure('public.complete_league_season_core_v2(uuid)') is not null
    as season_completion_core_ready,
  to_regprocedure(
    'public.complete_league_season_guarded_v1(uuid,uuid)'
  ) is not null as guarded_season_completion_ready,
  to_regprocedure('public.get_league_season_state_v4(uuid)') is not null
    as season_state_v4_ready,
  to_regprocedure('public.get_league_management_state_v11(uuid)') is not null
    as management_state_v11_ready,
  to_regprocedure(
    'public.get_league_season_completion_integrity_v1(uuid)'
  ) is not null as season_completion_integrity_ready,
  has_function_privilege(
    'authenticated',
    'public.complete_league_season_guarded_v1(uuid,uuid)',
    'EXECUTE'
  ) as authenticated_guarded_completion_access_ready,
  not has_function_privilege(
    'authenticated',
    'public.complete_league_season_core_v2(uuid)',
    'EXECUTE'
  ) as internal_completion_core_blocked,
  has_table_privilege(
    'authenticated',
    'public.season_completion_runs',
    'SELECT'
  ) as authenticated_completion_read_ready,
  not has_table_privilege(
    'authenticated',
    'public.season_completion_runs',
    'INSERT'
  ) as authenticated_completion_insert_blocked,
  coalesce(
    pg_get_functiondef(
      to_regprocedure(
        'public.complete_league_season_guarded_v1(uuid,uuid)'
      )
    ) ilike '%pg_advisory_xact_lock%',
    false
  ) as season_completion_advisory_lock_ready,
  coalesce(
    pg_get_functiondef(
      to_regprocedure(
        'public.complete_league_season_guarded_v1(uuid,uuid)'
      )
    ) ilike '%season_ready_to_complete%',
    false
  ) as final_progression_requirement_ready,
  exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'season_completion_runs'
  ) as season_completion_realtime_ready;
