-- LEGHEVO · coordinatore unico e diagnostica del ciclo giornata
-- Versione applicativa: 0.59.9
-- Migrazione prevista: database/083_matchday_lifecycle_integrity_hub.sql
-- Eseguire dopo database/082_season_completion_continuity_safety.sql.
-- Script idempotente: può essere eseguito più volte.
-- Revisione correttiva: ripristino difensivo di result_correction_runs.

begin;

-- Ripristino difensivo della continuità correzioni.
-- Se la tabella della v0.59.6 è stata rimossa o non è stata materializzata,
-- viene ricreata senza cancellare né modificare i risultati esistenti.
create table if not exists public.result_correction_runs (
  id bigint generated by default as identity primary key,
  league_id uuid not null
    references public.leagues(id) on delete cascade,
  matchday_id uuid not null
    references public.matchdays(id) on delete cascade,
  fixture_id uuid
    references public.fantasy_fixtures(id) on delete cascade,
  request_id uuid not null unique,
  scope text not null,
  correction_revision integer not null,
  input_hash text not null,
  reason text not null,
  previous_officialization_id bigint
    references public.matchday_officialization_runs(id) on delete set null,
  affected_fixture_count integer not null,
  previous_official_fixture_count integer not null,
  result_payload jsonb not null default '{}'::jsonb,
  requested_by uuid references public.profiles(id) on delete set null,
  reopened_at timestamptz not null default now(),
  constraint result_correction_scope_check
    check (scope in ('fixture', 'matchday')),
  constraint result_correction_scope_fixture_check
    check (
      (scope = 'fixture' and fixture_id is not null)
      or (scope = 'matchday' and fixture_id is null)
    ),
  constraint result_correction_revision_check
    check (correction_revision >= 1),
  constraint result_correction_input_hash_check
    check (length(input_hash) = 32),
  constraint result_correction_reason_check
    check (char_length(trim(reason)) between 10 and 240),
  constraint result_correction_affected_check
    check (affected_fixture_count >= 1),
  constraint result_correction_previous_count_check
    check (previous_official_fixture_count >= affected_fixture_count),
  unique (matchday_id, correction_revision)
);

create index if not exists result_correction_league_matchday_idx
  on public.result_correction_runs (
    league_id,
    matchday_id,
    correction_revision desc
  );

create index if not exists result_correction_fixture_idx
  on public.result_correction_runs (fixture_id, reopened_at desc)
  where fixture_id is not null;

alter table public.result_correction_runs enable row level security;

drop policy if exists result_correction_read_members
on public.result_correction_runs;
create policy result_correction_read_members
on public.result_correction_runs
for select to authenticated
using (public.is_league_member(league_id));

revoke all on table public.result_correction_runs
from public, anon, authenticated;
grant select on table public.result_correction_runs
to authenticated;

alter table public.fantasy_fixtures
  add column if not exists correction_run_id bigint;

-- Il DROP CASCADE di una tabella rimuove il vincolo ma può lasciare la colonna:
-- il controllo seguente ricrea il collegamento soltanto quando manca.
do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_constraint constraint_row
    join pg_catalog.pg_attribute attribute_row
      on attribute_row.attrelid = constraint_row.conrelid
     and attribute_row.attnum = any (constraint_row.conkey)
    where constraint_row.contype = 'f'
      and constraint_row.conrelid = 'public.fantasy_fixtures'::regclass
      and constraint_row.confrelid = 'public.result_correction_runs'::regclass
      and attribute_row.attname = 'correction_run_id'
  ) then
    alter table public.fantasy_fixtures
      add constraint fantasy_fixtures_correction_run_id_fkey
      foreign key (correction_run_id)
      references public.result_correction_runs(id)
      on delete set null;
  end if;
end;
$$;

create index if not exists fantasy_fixtures_correction_run_idx
  on public.fantasy_fixtures (correction_run_id)
  where correction_run_id is not null;

alter table public.matchday_officialization_runs
  add column if not exists source_correction_run_ids jsonb
    not null default '[]'::jsonb;

create or replace function public.prevent_result_correction_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if coalesce(
    current_setting('leghevo.result_correction_context', true),
    ''
  ) = 'on' then
    if tg_op = 'DELETE' then
      return old;
    end if;
    return new;
  end if;

  raise exception
    'Registro correzioni certificato: modifica diretta non consentita.';
end;
$$;

drop trigger if exists result_correction_immutable
on public.result_correction_runs;
create trigger result_correction_immutable
before update or delete on public.result_correction_runs
for each row
execute function public.prevent_result_correction_mutation();

do $$
begin
  if exists (
    select 1
    from pg_catalog.pg_publication publication
    where publication.pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'result_correction_runs'
  ) then
    alter publication supabase_realtime
      add table public.result_correction_runs;
  end if;
end;
$$;

-- Il client può leggere i dati necessari tramite RLS, ma ogni mutazione del
-- ciclo giornata deve attraversare esclusivamente le RPC protette già
-- certificate nelle migrazioni 075-082.
revoke insert, update, delete, truncate
on table
  public.matchdays,
  public.fantasy_fixtures,
  public.player_match_scores,
  public.lineups,
  public.lineup_entries,
  public.lineup_submission_events,
  public.lineup_deadline_events,
  public.lineup_resolution_runs,
  public.lineup_substitution_events,
  public.live_fixture_projection_runs,
  public.matchday_officialization_runs,
  public.result_correction_runs,
  public.matchday_progression_runs,
  public.season_completion_runs
from authenticated, anon;

-- Stato operativo compatto della giornata corrente. Non modifica dati e può
-- essere usato dalla Direzione Lega per mostrare una sola catena coerente.
create or replace function public.get_league_matchday_lifecycle_state_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_league public.leagues%rowtype;
  v_matchday public.matchdays%rowtype;
  v_fixture_count integer := 0;
  v_finalized_fixture_count integer := 0;
  v_team_slot_count integer := 0;
  v_resolution_count integer := 0;
  v_projection_count integer := 0;
  v_officialization_count integer := 0;
  v_correction_count integer := 0;
  v_progression_count integer := 0;
  v_completion_count integer := 0;
  v_phase text := 'awaiting_competition';
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if not public.is_league_member(p_league_id)
    and not public.is_league_admin(p_league_id) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  select league.*
  into v_league
  from public.leagues league
  where league.id = p_league_id;

  if not found then
    raise exception 'Lega non trovata.';
  end if;

  if v_league.current_matchday_id is not null then
    select matchday.*
    into v_matchday
    from public.matchdays matchday
    where matchday.id = v_league.current_matchday_id;

    select
      count(*)::integer,
      count(*) filter (where fixture.finalized_at is not null)::integer
    into v_fixture_count, v_finalized_fixture_count
    from public.fantasy_fixtures fixture
    where fixture.league_id = p_league_id
      and fixture.matchday_id = v_league.current_matchday_id;

    v_team_slot_count := v_fixture_count * 2;

    select count(*)::integer
    into v_resolution_count
    from public.lineup_resolution_runs run
    where run.league_id = p_league_id
      and run.matchday_id = v_league.current_matchday_id
      and run.superseded_at is null;

    select count(*)::integer
    into v_projection_count
    from public.live_fixture_projection_runs run
    where run.league_id = p_league_id
      and run.matchday_id = v_league.current_matchday_id
      and run.superseded_at is null;

    select count(*)::integer
    into v_officialization_count
    from public.matchday_officialization_runs run
    where run.league_id = p_league_id
      and run.matchday_id = v_league.current_matchday_id
      and run.superseded_at is null;

    select count(*)::integer
    into v_correction_count
    from public.result_correction_runs run
    where run.league_id = p_league_id
      and run.matchday_id = v_league.current_matchday_id;

    select count(*)::integer
    into v_progression_count
    from public.matchday_progression_runs run
    where run.league_id = p_league_id
      and run.matchday_id = v_league.current_matchday_id
      and run.superseded_at is null;
  end if;

  select count(*)::integer
  into v_completion_count
  from public.season_completion_runs run
  where run.league_id = p_league_id;

  v_phase := case
    when v_league.status in ('completed', 'archived')
      or v_completion_count > 0
      then 'season_completed'
    when v_league.competition_started_at is null
      then 'awaiting_competition'
    when v_league.current_matchday_id is null
      then 'awaiting_matchday'
    when v_matchday.lineups_finalized_at is null
      then 'lineup_open'
    when v_finalized_fixture_count = 0
      then 'live'
    when v_finalized_fixture_count < v_fixture_count
      then 'officializing'
    when v_progression_count = 0
      then 'awaiting_progression'
    else 'progressed'
  end;

  return jsonb_build_object(
    'policy', 'coordinated_v1',
    'phase', v_phase,
    'leagueStatus', v_league.status,
    'competitionStartedAt', v_league.competition_started_at,
    'currentMatchdayId', v_league.current_matchday_id,
    'currentMatchdayNumber', v_league.current_matchday_number,
    'lineupsFinalizedAt', v_matchday.lineups_finalized_at,
    'lineupLockRevision', coalesce(v_matchday.lineup_lock_revision, 0),
    'fixtureCount', v_fixture_count,
    'finalizedFixtureCount', v_finalized_fixture_count,
    'teamSlotCount', v_team_slot_count,
    'currentResolutionCount', v_resolution_count,
    'currentProjectionCount', v_projection_count,
    'currentOfficializationCount', v_officialization_count,
    'correctionCount', v_correction_count,
    'currentProgressionCount', v_progression_count,
    'seasonCompletionCertified', v_completion_count > 0
  );
end;
$$;

-- Diagnostica unificata end-to-end. Ogni sezione conserva il dettaglio della
-- diagnostica specialistica già installata, mentre healthy certifica l'intera
-- catena senza ricostruire o duplicare le regole sportive.
create or replace function public.get_league_matchday_lifecycle_integrity_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_lineup jsonb;
  v_substitution jsonb;
  v_live jsonb;
  v_officialization jsonb;
  v_correction jsonb;
  v_progression jsonb;
  v_completion jsonb;
  v_state jsonb;
  v_direct_writes_blocked boolean := false;
  v_guarded_endpoints_ready boolean := false;
  v_healthy boolean := false;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if not public.is_league_member(p_league_id)
    and not public.is_league_admin(p_league_id) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  v_lineup := public.get_league_lineup_integrity_v2(p_league_id);
  v_substitution := public.get_league_substitution_integrity_v1(p_league_id);
  v_live := public.get_league_live_projection_integrity_v1(p_league_id);
  v_officialization :=
    public.get_league_matchday_officialization_integrity_v1(p_league_id);
  v_correction := public.get_league_result_correction_integrity_v1(p_league_id);
  v_progression :=
    public.get_league_matchday_progression_integrity_v1(p_league_id);
  v_completion :=
    public.get_league_season_completion_integrity_v1(p_league_id);
  v_state := public.get_league_matchday_lifecycle_state_v1(p_league_id);

  v_direct_writes_blocked :=
    not has_table_privilege('authenticated', 'public.matchdays', 'UPDATE')
    and not has_table_privilege(
      'authenticated', 'public.fantasy_fixtures', 'UPDATE'
    )
    and not has_table_privilege(
      'authenticated', 'public.player_match_scores', 'INSERT'
    )
    and not has_table_privilege(
      'authenticated', 'public.lineups', 'UPDATE'
    )
    and not has_table_privilege(
      'authenticated', 'public.lineup_entries', 'INSERT'
    )
    and not has_table_privilege(
      'authenticated', 'public.live_fixture_projection_runs', 'UPDATE'
    )
    and not has_table_privilege(
      'authenticated', 'public.matchday_officialization_runs', 'INSERT'
    )
    and not has_table_privilege(
      'authenticated', 'public.result_correction_runs', 'UPDATE'
    )
    and not has_table_privilege(
      'authenticated', 'public.matchday_progression_runs', 'INSERT'
    )
    and not has_table_privilege(
      'authenticated', 'public.season_completion_runs', 'UPDATE'
    );

  v_guarded_endpoints_ready :=
    has_function_privilege(
      'authenticated',
      'public.save_team_lineup_guarded_v1(uuid,uuid,text,uuid[],uuid[],integer,uuid)',
      'execute'
    )
    and to_regprocedure(
      'public.certify_team_matchday_substitutions_guarded_v1(uuid,uuid,uuid)'
    ) is not null
    and not has_function_privilege(
      'authenticated',
      'public.certify_team_matchday_substitutions_guarded_v1(uuid,uuid,uuid)',
      'execute'
    )
    and has_function_privilege(
      'authenticated',
      'public.get_my_live_match_v6(uuid)',
      'execute'
    )
    and has_function_privilege(
      'authenticated',
      'public.finalize_league_matchday_guarded_v3(uuid,uuid,uuid)',
      'execute'
    )
    and has_function_privilege(
      'authenticated',
      'public.reopen_league_fixture_guarded_v1(uuid,uuid,text,uuid)',
      'execute'
    )
    and has_function_privilege(
      'authenticated',
      'public.complete_league_season_guarded_v1(uuid,uuid)',
      'execute'
    );

  v_healthy :=
    coalesce((v_lineup ->> 'healthy')::boolean, false)
    and coalesce((v_substitution ->> 'healthy')::boolean, false)
    and coalesce((v_live ->> 'healthy')::boolean, false)
    and coalesce((v_officialization ->> 'healthy')::boolean, false)
    and coalesce((v_correction ->> 'healthy')::boolean, false)
    and coalesce((v_progression ->> 'healthy')::boolean, false)
    and coalesce((v_completion ->> 'healthy')::boolean, false)
    and v_direct_writes_blocked
    and v_guarded_endpoints_ready;

  return jsonb_build_object(
    'healthy', v_healthy,
    'policy', 'end_to_end_v1',
    'stageCount', 7,
    'directWritesBlocked', v_direct_writes_blocked,
    'guardedEndpointsReady', v_guarded_endpoints_ready,
    'state', v_state,
    'stages', jsonb_build_object(
      'lineup', v_lineup,
      'substitution', v_substitution,
      'live', v_live,
      'officialization', v_officialization,
      'correction', v_correction,
      'progression', v_progression,
      'completion', v_completion
    )
  );
end;
$$;

create or replace function public.get_league_management_state_v12(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_state jsonb;
  v_lifecycle jsonb;
  v_checks jsonb;
  v_stages jsonb;
begin
  v_state := public.get_league_management_state_v11(p_league_id);
  v_lifecycle :=
    public.get_league_matchday_lifecycle_integrity_v1(p_league_id);
  v_checks := coalesce(v_state -> 'checks', '{}'::jsonb);
  v_stages := coalesce(v_lifecycle -> 'stages', '{}'::jsonb);

  return v_state || jsonb_build_object(
    'matchdayLifecycle', v_lifecycle,
    'checks', v_checks || jsonb_build_object(
      'lineupLifecycleReady',
        coalesce((v_stages #>> '{lineup,healthy}')::boolean, false)
        and coalesce((v_stages #>> '{substitution,healthy}')::boolean, false),
      'liveLifecycleReady',
        coalesce((v_stages #>> '{live,healthy}')::boolean, false)
        and coalesce(
          (v_stages #>> '{officialization,healthy}')::boolean,
          false
        )
        and coalesce((v_stages #>> '{correction,healthy}')::boolean, false),
      'matchdayLifecycleReady',
        coalesce((v_lifecycle ->> 'healthy')::boolean, false)
    )
  );
end;
$$;

revoke all on function public.get_league_matchday_lifecycle_state_v1(uuid)
from public, anon;
revoke all on function public.get_league_matchday_lifecycle_integrity_v1(uuid)
from public, anon;
revoke all on function public.get_league_management_state_v12(uuid)
from public, anon;

grant execute on function public.get_league_matchday_lifecycle_state_v1(uuid)
to authenticated;
grant execute on function public.get_league_matchday_lifecycle_integrity_v1(uuid)
to authenticated;
grant execute on function public.get_league_management_state_v12(uuid)
to authenticated;

commit;

-- Controllo finale: devono risultare esattamente 20 valori true.
select
  to_regprocedure(
    'public.get_league_matchday_lifecycle_state_v1(uuid)'
  ) is not null as lifecycle_state_ready,
  to_regprocedure(
    'public.get_league_matchday_lifecycle_integrity_v1(uuid)'
  ) is not null as lifecycle_integrity_ready,
  (
    to_regprocedure(
      'public.get_league_management_state_v12(uuid)'
    ) is not null
    and to_regclass('public.result_correction_runs') is not null
    and to_regprocedure(
      'public.get_league_result_correction_integrity_v1(uuid)'
    ) is not null
    and exists (
      select 1
      from pg_catalog.pg_trigger trigger_row
      where not trigger_row.tgisinternal
        and trigger_row.tgrelid =
          'public.result_correction_runs'::regclass
        and trigger_row.tgname = 'result_correction_immutable'
    )
  ) as management_and_correction_continuity_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_matchday_lifecycle_state_v1(uuid)',
    'execute'
  ) as authenticated_lifecycle_state_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_matchday_lifecycle_integrity_v1(uuid)',
    'execute'
  ) as authenticated_lifecycle_integrity_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_management_state_v12(uuid)',
    'execute'
  ) as authenticated_management_v12_ready,
  not has_function_privilege(
    'anon',
    'public.get_league_matchday_lifecycle_integrity_v1(uuid)',
    'execute'
  ) as anonymous_lifecycle_blocked,
  not has_table_privilege(
    'authenticated', 'public.matchdays', 'UPDATE'
  ) as matchday_direct_update_blocked,
  not has_table_privilege(
    'authenticated', 'public.fantasy_fixtures', 'UPDATE'
  ) as fixture_direct_update_blocked,
  not has_table_privilege(
    'authenticated', 'public.player_match_scores', 'INSERT'
  ) as score_direct_insert_blocked,
  not has_table_privilege(
    'authenticated', 'public.lineups', 'UPDATE'
  ) as lineup_direct_update_blocked,
  not has_table_privilege(
    'authenticated', 'public.lineup_entries', 'INSERT'
  ) as lineup_entry_direct_insert_blocked,
  not has_table_privilege(
    'authenticated', 'public.lineup_resolution_runs', 'INSERT'
  ) as resolution_direct_insert_blocked,
  not has_table_privilege(
    'authenticated', 'public.live_fixture_projection_runs', 'UPDATE'
  ) as live_projection_direct_update_blocked,
  not has_table_privilege(
    'authenticated', 'public.matchday_officialization_runs', 'INSERT'
  ) as officialization_direct_insert_blocked,
  not has_table_privilege(
    'authenticated', 'public.result_correction_runs', 'UPDATE'
  ) as correction_direct_update_blocked,
  not has_table_privilege(
    'authenticated', 'public.matchday_progression_runs', 'INSERT'
  ) as progression_direct_insert_blocked,
  not has_table_privilege(
    'authenticated', 'public.season_completion_runs', 'UPDATE'
  ) as completion_direct_update_blocked,
  to_regprocedure(
    'public.finalize_league_matchday_guarded_v3(uuid,uuid,uuid)'
  ) is not null as guarded_finalization_ready,
  to_regprocedure(
    'public.complete_league_season_guarded_v1(uuid,uuid)'
  ) is not null as guarded_completion_ready;
