-- LEGHEVO v0.60.3 · Coppa di Lega: certificazione protetta della conclusione
-- Migrazione: database/087_league_cup_completion_certification.sql
-- Eseguire dopo database/086_league_cup_round_finalization_safety.sql.
-- Script idempotente: non crea Coppe, non cambia vincitori e non cancella dati.

begin;

-- Preflight esplicito: la migrazione non presume in silenzio le dipendenze.
do $block$
declare
  v_missing text[] := array[]::text[];
begin
  if to_regclass('public.league_cups') is null then
    v_missing := array_append(v_missing, 'public.league_cups');
  end if;
  if to_regclass('public.league_cup_rounds') is null then
    v_missing := array_append(v_missing, 'public.league_cup_rounds');
  end if;
  if to_regclass('public.league_cup_ties') is null then
    v_missing := array_append(v_missing, 'public.league_cup_ties');
  end if;
  if to_regclass('public.league_cup_entries') is null then
    v_missing := array_append(v_missing, 'public.league_cup_entries');
  end if;
  if to_regclass('public.league_cup_round_finalization_runs') is null then
    v_missing := array_append(v_missing, 'public.league_cup_round_finalization_runs');
  end if;
  if to_regprocedure('public.leghevo_sha256_hex_v1(text)') is null then
    v_missing := array_append(v_missing, 'public.leghevo_sha256_hex_v1(text)');
  end if;
  if to_regprocedure('public.league_cup_round_result_hash_v1(uuid,integer)') is null then
    v_missing := array_append(v_missing, 'public.league_cup_round_result_hash_v1(uuid,integer)');
  end if;
  if to_regprocedure('public.get_league_cup_state_v3(uuid)') is null then
    v_missing := array_append(v_missing, 'public.get_league_cup_state_v3(uuid)');
  end if;

  if coalesce(array_length(v_missing, 1), 0) > 0 then
    raise exception 'Dipendenze v0.60.3 mancanti: %', array_to_string(v_missing, ', ');
  end if;
end;
$block$;

create table if not exists public.league_cup_completion_certificates (
  id bigint generated by default as identity primary key,
  league_id uuid not null
    references public.leagues(id) on delete cascade,
  cup_id uuid not null unique
    references public.league_cups(id) on delete cascade,
  final_round_id uuid not null unique
    references public.league_cup_rounds(id) on delete restrict,
  finalization_run_id bigint not null unique
    references public.league_cup_round_finalization_runs(id) on delete restrict,
  champion_team_id uuid not null
    references public.fantasy_teams(id) on delete restrict,
  runner_up_team_id uuid not null
    references public.fantasy_teams(id) on delete restrict,
  final_round_number smallint not null
    check (final_round_number between 1 and 5),
  source_result_hash text not null
    check (char_length(source_result_hash) = 64),
  completion_fingerprint text not null
    check (char_length(completion_fingerprint) = 64),
  snapshot jsonb not null default '{}'::jsonb,
  certified_by uuid references public.profiles(id) on delete set null,
  certified_at timestamptz not null default now(),
  check (champion_team_id <> runner_up_team_id)
);

create index if not exists league_cup_completion_league_idx
  on public.league_cup_completion_certificates
    (league_id, certified_at desc);
create index if not exists league_cup_completion_champion_idx
  on public.league_cup_completion_certificates
    (champion_team_id, certified_at desc);

alter table public.league_cup_completion_certificates enable row level security;

drop policy if exists league_cup_completion_read_members
on public.league_cup_completion_certificates;
create policy league_cup_completion_read_members
on public.league_cup_completion_certificates
for select to authenticated
using (
  public.is_league_member(league_id)
  or public.is_league_admin(league_id)
);

revoke all on table public.league_cup_completion_certificates
from public, anon, authenticated;
grant select on table public.league_cup_completion_certificates
to authenticated;

create or replace function public.prevent_league_cup_completion_certificate_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  raise exception
    'Certificato conclusione Coppa immutabile: modifica o cancellazione diretta non consentita.';
end;
$$;

revoke all on function public.prevent_league_cup_completion_certificate_mutation()
from public, anon, authenticated;

drop trigger if exists league_cup_completion_certificates_immutable
on public.league_cup_completion_certificates;
create trigger league_cup_completion_certificates_immutable
before update or delete on public.league_cup_completion_certificates
for each row
execute function public.prevent_league_cup_completion_certificate_mutation();

create or replace function public.compute_league_cup_completion_fingerprint_v1(
  p_cup_id uuid
)
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_cup public.league_cups%rowtype;
  v_final_round public.league_cup_rounds%rowtype;
  v_run public.league_cup_round_finalization_runs%rowtype;
  v_ties text := '';
  v_entries text := '';
  v_payload text;
begin
  select cup.*
  into v_cup
  from public.league_cups cup
  where cup.id = p_cup_id;

  if not found or v_cup.status <> 'completed'
    or v_cup.champion_team_id is null
    or v_cup.runner_up_team_id is null then
    return null;
  end if;

  select cup_round.*
  into v_final_round
  from public.league_cup_rounds cup_round
  where cup_round.cup_id = v_cup.id
    and cup_round.round_number = v_cup.round_count;

  if not found or v_final_round.status <> 'official' then
    return null;
  end if;

  select run.*
  into v_run
  from public.league_cup_round_finalization_runs run
  where run.cup_id = v_cup.id
    and run.round_id = v_final_round.id
    and run.cup_completed
  order by run.id desc
  limit 1;

  if not found or v_run.champion_team_id is distinct from v_cup.champion_team_id then
    return null;
  end if;

  select coalesce(
    string_agg(
      tie.bracket_position::text || ':'
      || coalesce(tie.home_team_id::text, '-') || ':'
      || coalesce(tie.away_team_id::text, '-') || ':'
      || coalesce(tie.home_points::text, '-') || ':'
      || coalesce(tie.away_points::text, '-') || ':'
      || coalesce(tie.home_goals::text, '-') || ':'
      || coalesce(tie.away_goals::text, '-') || ':'
      || coalesce(tie.winner_team_id::text, '-') || ':'
      || coalesce(tie.decided_by, '-'),
      '|' order by tie.bracket_position
    ),
    ''
  )
  into v_ties
  from public.league_cup_ties tie
  where tie.round_id = v_final_round.id;

  select coalesce(
    string_agg(
      entry.seed::text || ':'
      || entry.fantasy_team_id::text || ':'
      || coalesce(entry.eliminated_round::text, '-') || ':'
      || coalesce(entry.final_position::text, '-'),
      '|' order by entry.seed
    ),
    ''
  )
  into v_entries
  from public.league_cup_entries entry
  where entry.cup_id = v_cup.id;

  v_payload :=
    v_cup.id::text || '#'
    || v_cup.league_id::text || '#'
    || v_cup.status || '#'
    || v_cup.team_count::text || '#'
    || v_cup.bracket_size::text || '#'
    || v_cup.round_count::text || '#'
    || v_cup.current_round::text || '#'
    || v_cup.champion_team_id::text || '#'
    || v_cup.runner_up_team_id::text || '#'
    || coalesce(v_cup.completed_at::text, '-') || '#'
    || v_final_round.id::text || '#'
    || v_final_round.round_number::text || '#'
    || coalesce(v_final_round.finalized_at::text, '-') || '#'
    || v_run.id::text || '#'
    || v_run.result_hash || '#'
    || v_ties || '#'
    || v_entries;

  return public.leghevo_sha256_hex_v1(v_payload);
end;
$$;

revoke all on function public.compute_league_cup_completion_fingerprint_v1(uuid)
from public, anon, authenticated;

create or replace function public.certify_league_cup_completion_internal_v1(
  p_cup_id uuid,
  p_finalization_run_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_cup public.league_cups%rowtype;
  v_final_round public.league_cup_rounds%rowtype;
  v_run public.league_cup_round_finalization_runs%rowtype;
  v_certificate public.league_cup_completion_certificates%rowtype;
  v_current_result_hash text;
  v_fingerprint text;
begin
  select cup.*
  into v_cup
  from public.league_cups cup
  where cup.id = p_cup_id;

  if not found or v_cup.status <> 'completed' then
    raise exception 'La Coppa non è conclusa: certificazione non disponibile.';
  end if;

  if v_cup.champion_team_id is null or v_cup.runner_up_team_id is null then
    raise exception 'Podio finale della Coppa incompleto.';
  end if;

  select cup_round.*
  into v_final_round
  from public.league_cup_rounds cup_round
  where cup_round.cup_id = v_cup.id
    and cup_round.round_number = v_cup.round_count;

  if not found or v_final_round.status <> 'official' then
    raise exception 'Finale della Coppa non ufficiale.';
  end if;

  select run.*
  into v_run
  from public.league_cup_round_finalization_runs run
  where run.id = p_finalization_run_id
    and run.cup_id = v_cup.id
    and run.round_id = v_final_round.id
    and run.cup_completed;

  if not found then
    raise exception 'Ufficializzazione certificata della finale non trovata.';
  end if;

  if v_run.champion_team_id is distinct from v_cup.champion_team_id then
    raise exception 'Il campione non coincide con l''ufficializzazione della finale.';
  end if;

  v_current_result_hash := public.league_cup_round_result_hash_v1(
    v_cup.id,
    v_final_round.round_number
  );

  if v_current_result_hash is null or v_current_result_hash <> v_run.result_hash then
    raise exception 'L''esito della finale non coincide con la revisione certificata.';
  end if;

  v_fingerprint := public.compute_league_cup_completion_fingerprint_v1(v_cup.id);

  if v_fingerprint is null or char_length(v_fingerprint) <> 64 then
    raise exception 'Impossibile calcolare l''impronta conclusiva della Coppa.';
  end if;

  insert into public.league_cup_completion_certificates (
    league_id,
    cup_id,
    final_round_id,
    finalization_run_id,
    champion_team_id,
    runner_up_team_id,
    final_round_number,
    source_result_hash,
    completion_fingerprint,
    snapshot,
    certified_by,
    certified_at
  ) values (
    v_cup.league_id,
    v_cup.id,
    v_final_round.id,
    v_run.id,
    v_cup.champion_team_id,
    v_cup.runner_up_team_id,
    v_final_round.round_number,
    v_run.result_hash,
    v_fingerprint,
    jsonb_build_object(
      'policy', 'certified_v1',
      'leagueId', v_cup.league_id,
      'cupId', v_cup.id,
      'finalRoundId', v_final_round.id,
      'finalRoundNumber', v_final_round.round_number,
      'finalizationRunId', v_run.id,
      'championTeamId', v_cup.champion_team_id,
      'runnerUpTeamId', v_cup.runner_up_team_id,
      'sourceResultHash', v_run.result_hash,
      'completionFingerprint', v_fingerprint
    ),
    v_run.requested_by,
    coalesce(v_run.finalized_at, v_cup.completed_at, now())
  )
  on conflict (cup_id) do nothing;

  select certificate.*
  into v_certificate
  from public.league_cup_completion_certificates certificate
  where certificate.cup_id = v_cup.id;

  if not found then
    raise exception 'Certificato conclusivo della Coppa non creato.';
  end if;

  if v_certificate.finalization_run_id <> v_run.id
    or v_certificate.completion_fingerprint <> v_fingerprint
    or v_certificate.source_result_hash <> v_run.result_hash then
    raise exception 'Esiste un certificato conclusivo incompatibile.';
  end if;

  return v_certificate.id;
end;
$$;

revoke all on function public.certify_league_cup_completion_internal_v1(uuid, bigint)
from public, anon, authenticated;

create or replace function public.certify_league_cup_completion_on_finalization_v1()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.cup_completed then
    perform public.certify_league_cup_completion_internal_v1(
      new.cup_id,
      new.id
    );
  end if;
  return new;
end;
$$;

revoke all on function public.certify_league_cup_completion_on_finalization_v1()
from public, anon, authenticated;

drop trigger if exists league_cup_completion_after_finalization
on public.league_cup_round_finalization_runs;
create trigger league_cup_completion_after_finalization
after insert on public.league_cup_round_finalization_runs
for each row
when (new.cup_completed)
execute function public.certify_league_cup_completion_on_finalization_v1();

-- Certifica in modo non distruttivo le Coppe già concluse e validate dalla v0.60.2.
do $block$
declare
  v_item record;
begin
  for v_item in
    select cup.id as cup_id, run.id as run_id
    from public.league_cups cup
    join public.league_cup_rounds cup_round
      on cup_round.cup_id = cup.id
      and cup_round.round_number = cup.round_count
      and cup_round.status = 'official'
    join lateral (
      select finalization.id
      from public.league_cup_round_finalization_runs finalization
      where finalization.cup_id = cup.id
        and finalization.round_id = cup_round.id
        and finalization.cup_completed
      order by finalization.id desc
      limit 1
    ) run on true
    where cup.status = 'completed'
      and cup.champion_team_id is not null
      and cup.runner_up_team_id is not null
      and not exists (
        select 1
        from public.league_cup_completion_certificates certificate
        where certificate.cup_id = cup.id
      )
  loop
    perform public.certify_league_cup_completion_internal_v1(
      v_item.cup_id,
      v_item.run_id
    );
  end loop;
end;
$block$;

create or replace function public.get_league_cup_state_v4(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_state jsonb;
  v_cup_id uuid;
  v_certificate public.league_cup_completion_certificates%rowtype;
begin
  v_state := public.get_league_cup_state_v3(p_league_id);
  v_cup_id := nullif(v_state ->> 'cupId', '')::uuid;

  if v_cup_id is not null then
    select certificate.*
    into v_certificate
    from public.league_cup_completion_certificates certificate
    where certificate.cup_id = v_cup_id;
  end if;

  return v_state || jsonb_build_object(
    'completionPolicy', 'certified_v1',
    'completionCertified', v_certificate.id is not null,
    'completionCertificateId', v_certificate.id,
    'completionFingerprint', v_certificate.completion_fingerprint,
    'completionCertifiedAt', v_certificate.certified_at,
    'completionFinalizationRunId', v_certificate.finalization_run_id
  );
end;
$$;

revoke all on function public.get_league_cup_state_v4(uuid)
from public, anon, authenticated;
grant execute on function public.get_league_cup_state_v4(uuid)
to authenticated;

create or replace function public.get_league_cup_completion_integrity_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_completed_count integer := 0;
  v_certificate_count integer := 0;
  v_missing_count integer := 0;
  v_fingerprint_drift_count integer := 0;
  v_source_drift_count integer := 0;
  v_podium_issue_count integer := 0;
  v_link_issue_count integer := 0;
  v_healthy boolean := false;
begin
  if auth.uid() is null
    or (not public.is_league_member(p_league_id)
      and not public.is_league_admin(p_league_id)) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  select count(*)::integer
  into v_completed_count
  from public.league_cups cup
  where cup.league_id = p_league_id
    and cup.status = 'completed';

  select count(*)::integer
  into v_certificate_count
  from public.league_cup_completion_certificates certificate
  where certificate.league_id = p_league_id;

  select count(*)::integer
  into v_missing_count
  from public.league_cups cup
  left join public.league_cup_completion_certificates certificate
    on certificate.cup_id = cup.id
  where cup.league_id = p_league_id
    and cup.status = 'completed'
    and certificate.id is null;

  select count(*)::integer
  into v_fingerprint_drift_count
  from public.league_cup_completion_certificates certificate
  where certificate.league_id = p_league_id
    and certificate.completion_fingerprint is distinct from
      public.compute_league_cup_completion_fingerprint_v1(certificate.cup_id);

  select count(*)::integer
  into v_source_drift_count
  from public.league_cup_completion_certificates certificate
  join public.league_cup_round_finalization_runs run
    on run.id = certificate.finalization_run_id
  where certificate.league_id = p_league_id
    and certificate.source_result_hash is distinct from run.result_hash;

  select count(*)::integer
  into v_podium_issue_count
  from public.league_cup_completion_certificates certificate
  join public.league_cups cup on cup.id = certificate.cup_id
  where certificate.league_id = p_league_id
    and (
      certificate.champion_team_id is distinct from cup.champion_team_id
      or certificate.runner_up_team_id is distinct from cup.runner_up_team_id
      or certificate.champion_team_id = certificate.runner_up_team_id
    );

  select count(*)::integer
  into v_link_issue_count
  from public.league_cup_completion_certificates certificate
  join public.league_cup_rounds cup_round
    on cup_round.id = certificate.final_round_id
  join public.league_cup_round_finalization_runs run
    on run.id = certificate.finalization_run_id
  where certificate.league_id = p_league_id
    and (
      cup_round.cup_id <> certificate.cup_id
      or cup_round.round_number <> certificate.final_round_number
      or cup_round.status <> 'official'
      or run.cup_id <> certificate.cup_id
      or run.round_id <> certificate.final_round_id
      or not run.cup_completed
    );

  v_healthy :=
    v_missing_count = 0
    and v_fingerprint_drift_count = 0
    and v_source_drift_count = 0
    and v_podium_issue_count = 0
    and v_link_issue_count = 0;

  return jsonb_build_object(
    'policy', 'certified_v1',
    'healthy', v_healthy,
    'completedCupCount', v_completed_count,
    'certificateCount', v_certificate_count,
    'missingCertificateCount', v_missing_count,
    'fingerprintDriftCount', v_fingerprint_drift_count,
    'sourceDriftCount', v_source_drift_count,
    'podiumIssueCount', v_podium_issue_count,
    'linkIssueCount', v_link_issue_count
  );
end;
$$;

revoke all on function public.get_league_cup_completion_integrity_v1(uuid)
from public, anon, authenticated;
grant execute on function public.get_league_cup_completion_integrity_v1(uuid)
to authenticated;

do $block$
begin
  if exists (
    select 1 from pg_catalog.pg_publication
    where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'league_cup_completion_certificates'
  ) then
    alter publication supabase_realtime
      add table public.league_cup_completion_certificates;
  end if;
end;
$block$;

commit;

-- Diagnostica finale: devono risultare esattamente 20 valori true.
select
  to_regclass('public.league_cup_completion_certificates') is not null
    as completion_certificate_table_ready,
  exists (
    select 1 from pg_catalog.pg_indexes
    where schemaname = 'public'
      and indexname = 'league_cup_completion_certificates_cup_id_key'
  ) as one_certificate_per_cup_ready,
  exists (
    select 1 from pg_catalog.pg_indexes
    where schemaname = 'public'
      and indexname = 'league_cup_completion_certificates_finalization_run_id_key'
  ) as one_certificate_per_finalization_ready,
  exists (
    select 1 from pg_catalog.pg_indexes
    where schemaname = 'public'
      and indexname = 'league_cup_completion_league_idx'
  ) as certificate_lookup_index_ready,
  coalesce((
    select relation.relrowsecurity
    from pg_catalog.pg_class relation
    where relation.oid = 'public.league_cup_completion_certificates'::regclass
  ), false) as completion_certificate_rls_ready,
  exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'league_cup_completion_certificates'
      and policyname = 'league_cup_completion_read_members'
  ) as completion_certificate_read_policy_ready,
  has_table_privilege(
    'authenticated',
    'public.league_cup_completion_certificates',
    'SELECT'
  ) as authenticated_certificate_read_ready,
  not has_table_privilege(
    'authenticated',
    'public.league_cup_completion_certificates',
    'INSERT'
  ) as direct_certificate_insert_blocked,
  exists (
    select 1
    from pg_catalog.pg_trigger trigger_record
    join pg_catalog.pg_class relation
      on relation.oid = trigger_record.tgrelid
    join pg_catalog.pg_namespace namespace
      on namespace.oid = relation.relnamespace
    where namespace.nspname = 'public'
      and relation.relname = 'league_cup_completion_certificates'
      and trigger_record.tgname = 'league_cup_completion_certificates_immutable'
      and not trigger_record.tgisinternal
  ) as certificate_immutable_trigger_ready,
  to_regprocedure(
    'public.compute_league_cup_completion_fingerprint_v1(uuid)'
  ) is not null as completion_fingerprint_ready,
  to_regprocedure(
    'public.certify_league_cup_completion_internal_v1(uuid,bigint)'
  ) is not null as internal_completion_certifier_ready,
  to_regprocedure(
    'public.certify_league_cup_completion_on_finalization_v1()'
  ) is not null as completion_trigger_function_ready,
  exists (
    select 1
    from pg_catalog.pg_trigger trigger_record
    join pg_catalog.pg_class relation
      on relation.oid = trigger_record.tgrelid
    join pg_catalog.pg_namespace namespace
      on namespace.oid = relation.relnamespace
    where namespace.nspname = 'public'
      and relation.relname = 'league_cup_round_finalization_runs'
      and trigger_record.tgname = 'league_cup_completion_after_finalization'
      and not trigger_record.tgisinternal
  ) as automatic_completion_certification_ready,
  to_regprocedure('public.get_league_cup_state_v4(uuid)') is not null
    as cup_state_v4_ready,
  to_regprocedure(
    'public.get_league_cup_completion_integrity_v1(uuid)'
  ) is not null as completion_integrity_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_cup_state_v4(uuid)',
    'EXECUTE'
  ) as authenticated_state_v4_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_cup_completion_integrity_v1(uuid)',
    'EXECUTE'
  ) as authenticated_completion_diagnostics_ready,
  not has_function_privilege(
    'authenticated',
    'public.certify_league_cup_completion_internal_v1(uuid,bigint)',
    'EXECUTE'
  ) as internal_certifier_private,
  not exists (
    select 1
    from public.league_cups cup
    left join public.league_cup_completion_certificates certificate
      on certificate.cup_id = cup.id
    where cup.status = 'completed'
      and certificate.id is null
  ) as completed_cups_certified,
  exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'league_cup_completion_certificates'
  ) as completion_certificate_realtime_ready;
