-- LEGHEVO v0.60.4 · Supercoppa: programmazione protetta e continuità tra stagioni
-- Migrazione: database/088_league_super_cup_schedule_safety.sql
-- Eseguire dopo database/087_league_cup_completion_certification.sql.
-- Script idempotente: non programma automaticamente Supercoppe e non modifica risultati esistenti.

begin;

-- Preflight esplicito: evita assunzioni silenziose sulle versioni precedenti.
do $block$
declare
  v_missing text[] := array[]::text[];
begin
  if to_regclass('public.leagues') is null then
    v_missing := array_append(v_missing, 'public.leagues');
  end if;
  if to_regclass('public.fantasy_teams') is null then
    v_missing := array_append(v_missing, 'public.fantasy_teams');
  end if;
  if to_regclass('public.matchdays') is null then
    v_missing := array_append(v_missing, 'public.matchdays');
  end if;
  if to_regclass('public.fantasy_fixtures') is null then
    v_missing := array_append(v_missing, 'public.fantasy_fixtures');
  end if;
  if to_regclass('public.league_super_cups') is null then
    v_missing := array_append(v_missing, 'public.league_super_cups');
  end if;
  if to_regclass('public.league_season_summaries') is null then
    v_missing := array_append(v_missing, 'public.league_season_summaries');
  end if;
  if to_regclass('public.league_cups') is null then
    v_missing := array_append(v_missing, 'public.league_cups');
  end if;
  if to_regclass('public.league_cup_completion_certificates') is null then
    v_missing := array_append(v_missing, 'public.league_cup_completion_certificates');
  end if;
  if to_regprocedure('public.resolve_league_super_cup_qualifiers(uuid)') is null then
    v_missing := array_append(v_missing, 'public.resolve_league_super_cup_qualifiers(uuid)');
  end if;
  if to_regprocedure('public.get_league_super_cup_state(uuid)') is null then
    v_missing := array_append(v_missing, 'public.get_league_super_cup_state(uuid)');
  end if;
  if to_regprocedure('public.leghevo_sha256_hex_v1(text)') is null then
    v_missing := array_append(v_missing, 'public.leghevo_sha256_hex_v1(text)');
  end if;
  if to_regprocedure('public.leghevo_stable_request_uuid(text)') is null then
    v_missing := array_append(v_missing, 'public.leghevo_stable_request_uuid(text)');
  end if;

  if coalesce(array_length(v_missing, 1), 0) > 0 then
    raise exception 'Dipendenze v0.60.4 mancanti: %', array_to_string(v_missing, ', ');
  end if;
end;
$block$;

create table if not exists public.league_super_cup_schedule_runs (
  id bigint generated by default as identity primary key,
  league_id uuid not null
    references public.leagues(id) on delete cascade,
  super_cup_id uuid not null unique
    references public.league_super_cups(id) on delete cascade,
  source_league_id uuid not null
    references public.leagues(id) on delete restrict,
  request_id uuid not null,
  requested_by uuid not null
    references public.profiles(id) on delete restrict,
  matchday_id uuid not null
    references public.matchdays(id) on delete restrict,
  matchday_number smallint not null check (matchday_number >= 1),
  league_champion_team_id uuid not null
    references public.fantasy_teams(id) on delete restrict,
  challenger_team_id uuid not null
    references public.fantasy_teams(id) on delete restrict,
  challenger_qualification text not null
    check (challenger_qualification in ('cup_champion', 'cup_runner_up')),
  qualifiers_hash text not null check (char_length(qualifiers_hash) = 64),
  schedule_hash text not null check (char_length(schedule_hash) = 64),
  result_hash text not null check (char_length(result_hash) = 64),
  created_at timestamptz not null default now(),
  check (league_id <> source_league_id),
  check (league_champion_team_id <> challenger_team_id)
);

create unique index if not exists league_super_cup_schedule_request_uidx
  on public.league_super_cup_schedule_runs (league_id, request_id);
create unique index if not exists league_super_cup_schedule_super_cup_uidx
  on public.league_super_cup_schedule_runs (super_cup_id);
create index if not exists league_super_cup_schedule_league_created_idx
  on public.league_super_cup_schedule_runs (league_id, created_at desc, id desc);

alter table public.league_super_cup_schedule_runs enable row level security;

drop policy if exists league_super_cup_schedule_read_members
on public.league_super_cup_schedule_runs;
create policy league_super_cup_schedule_read_members
on public.league_super_cup_schedule_runs
for select to authenticated
using (
  public.is_league_member(league_id)
  or public.is_league_admin(league_id)
);

revoke all on table public.league_super_cup_schedule_runs
from public, anon, authenticated;
grant select on table public.league_super_cup_schedule_runs
to authenticated;

create or replace function public.prevent_league_super_cup_schedule_run_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  raise exception
    'Registro programmazione Supercoppa immutabile: modifica o cancellazione diretta non consentita.';
end;
$$;

revoke all on function public.prevent_league_super_cup_schedule_run_mutation()
from public, anon, authenticated;

drop trigger if exists league_super_cup_schedule_runs_immutable
on public.league_super_cup_schedule_runs;
create trigger league_super_cup_schedule_runs_immutable
before update or delete on public.league_super_cup_schedule_runs
for each row
execute function public.prevent_league_super_cup_schedule_run_mutation();

create or replace function public.compute_league_super_cup_schedule_result_hash_v1(
  p_super_cup_id uuid,
  p_qualifiers_hash text,
  p_schedule_hash text
)
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_super_cup public.league_super_cups%rowtype;
begin
  select super_cup.*
  into v_super_cup
  from public.league_super_cups super_cup
  where super_cup.id = p_super_cup_id;

  if not found then
    return null;
  end if;

  return public.leghevo_sha256_hex_v1(
    v_super_cup.id::text || '#'
    || v_super_cup.league_id::text || '#'
    || v_super_cup.source_league_id::text || '#'
    || v_super_cup.matchday_id::text || '#'
    || v_super_cup.league_champion_team_id::text || '#'
    || v_super_cup.challenger_team_id::text || '#'
    || v_super_cup.challenger_qualification || '#'
    || coalesce(v_super_cup.status, '-') || '#'
    || coalesce(p_qualifiers_hash, '-') || '#'
    || coalesce(p_schedule_hash, '-')
  );
end;
$$;

revoke all on function public.compute_league_super_cup_schedule_result_hash_v1(
  uuid, text, text
) from public, anon, authenticated;

create or replace function public.get_league_super_cup_state_v2(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_state jsonb;
  v_run public.league_super_cup_schedule_runs%rowtype;
begin
  v_state := public.get_league_super_cup_state(p_league_id);

  select run.*
  into v_run
  from public.league_super_cup_schedule_runs run
  where run.league_id = p_league_id
  order by run.created_at desc, run.id desc
  limit 1;

  return coalesce(v_state, '{}'::jsonb) || jsonb_build_object(
    'schedulePolicy', 'guarded_v1',
    'scheduleCertified', v_run.id is not null,
    'scheduleRunId', v_run.id,
    'scheduleRequestId', v_run.request_id,
    'scheduleQualifiersHash', v_run.qualifiers_hash,
    'scheduleHash', v_run.schedule_hash,
    'scheduleResultHash', v_run.result_hash
  );
end;
$$;

revoke all on function public.get_league_super_cup_state_v2(uuid)
from public, anon, authenticated;
grant execute on function public.get_league_super_cup_state_v2(uuid)
to authenticated;

create or replace function public.create_league_super_cup_guarded_v1(
  p_league_id uuid,
  p_matchday_number smallint,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_league public.leagues%rowtype;
  v_existing_run public.league_super_cup_schedule_runs%rowtype;
  v_existing_super_cup_id uuid;
  v_qualifiers jsonb;
  v_source_league_id uuid;
  v_source_season text;
  v_source_summary public.league_season_summaries%rowtype;
  v_source_cup public.league_cups%rowtype;
  v_source_certificate public.league_cup_completion_certificates%rowtype;
  v_source_home_manager_id uuid;
  v_source_challenger_team_id uuid;
  v_source_challenger_manager_id uuid;
  v_home_team public.fantasy_teams%rowtype;
  v_away_team public.fantasy_teams%rowtype;
  v_matchday public.matchdays%rowtype;
  v_super_cup_id uuid;
  v_qualifiers_hash text;
  v_schedule_hash text;
  v_result_hash text;
  v_member_user_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if p_request_id is null then
    raise exception 'Identificativo richiesta mancante.';
  end if;

  if p_matchday_number is null or p_matchday_number < 1 then
    raise exception 'Giornata della Supercoppa non valida.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'leghevo:league-super-cup-schedule:' || p_league_id::text,
      0
    )
  );

  select run.*
  into v_existing_run
  from public.league_super_cup_schedule_runs run
  where run.league_id = p_league_id
    and run.request_id = p_request_id;

  if found then
    return public.get_league_super_cup_state_v2(p_league_id)
      || jsonb_build_object(
        'idempotentReplay', true,
        'scheduleRunId', v_existing_run.id
      );
  end if;

  select league.*
  into v_league
  from public.leagues league
  where league.id = p_league_id
  for update;

  if not found then
    raise exception 'Lega non trovata.';
  end if;

  if v_league.owner_id <> auth.uid() then
    raise exception 'Solo il Presidente può programmare la Supercoppa.';
  end if;

  select super_cup.id
  into v_existing_super_cup_id
  from public.league_super_cups super_cup
  where super_cup.league_id = p_league_id;

  if found then
    return public.get_league_super_cup_state_v2(p_league_id)
      || jsonb_build_object(
        'idempotentReplay', true,
        'alreadyExists', true
      );
  end if;

  if v_league.status <> 'active'
    or v_league.competition_started_at is null then
    raise exception 'La Supercoppa si programma durante una stagione attiva.';
  end if;

  v_qualifiers := public.resolve_league_super_cup_qualifiers(p_league_id);

  if coalesce((v_qualifiers ->> 'eligible')::boolean, false) is false then
    raise exception '%', coalesce(
      v_qualifiers ->> 'reason',
      'La Supercoppa non è disponibile.'
    );
  end if;

  v_source_league_id := nullif(v_qualifiers ->> 'sourceLeagueId', '')::uuid;
  v_source_season := nullif(v_qualifiers ->> 'sourceSeason', '');

  select summary.*
  into v_source_summary
  from public.league_season_summaries summary
  where summary.league_id = v_source_league_id;

  if not found or v_source_summary.champion_team_id is null then
    raise exception 'Campione certificato della stagione precedente non disponibile.';
  end if;

  select cup.*
  into v_source_cup
  from public.league_cups cup
  where cup.league_id = v_source_league_id
    and cup.status = 'completed';

  if not found then
    raise exception 'Coppa precedente conclusa non disponibile.';
  end if;

  select certificate.*
  into v_source_certificate
  from public.league_cup_completion_certificates certificate
  where certificate.cup_id = v_source_cup.id;

  if not found
    or v_source_certificate.champion_team_id is distinct from v_source_cup.champion_team_id
    or v_source_certificate.runner_up_team_id is distinct from v_source_cup.runner_up_team_id then
    raise exception 'La Coppa precedente non possiede una certificazione coerente.';
  end if;

  select team.manager_id
  into v_source_home_manager_id
  from public.fantasy_teams team
  where team.id = v_source_summary.champion_team_id;

  if v_source_home_manager_id is null then
    raise exception 'Manager campione della stagione precedente non identificabile.';
  end if;

  if v_qualifiers ->> 'challengerQualification' = 'cup_runner_up' then
    v_source_challenger_team_id := v_source_cup.runner_up_team_id;
  else
    v_source_challenger_team_id := v_source_cup.champion_team_id;
  end if;

  select team.manager_id
  into v_source_challenger_manager_id
  from public.fantasy_teams team
  where team.id = v_source_challenger_team_id;

  if v_source_challenger_manager_id is null then
    raise exception 'Manager sfidante della stagione precedente non identificabile.';
  end if;

  select team.*
  into v_home_team
  from public.fantasy_teams team
  where team.id = (v_qualifiers -> 'leagueChampion' ->> 'teamId')::uuid
    and team.league_id = p_league_id;

  select team.*
  into v_away_team
  from public.fantasy_teams team
  where team.id = (v_qualifiers -> 'challenger' ->> 'teamId')::uuid
    and team.league_id = p_league_id;

  if v_home_team.id is null or v_away_team.id is null then
    raise exception 'Finalisti della Supercoppa non presenti nella stagione corrente.';
  end if;

  if v_home_team.manager_id is distinct from v_source_home_manager_id
    or v_away_team.manager_id is distinct from v_source_challenger_manager_id then
    raise exception 'Continuità dei manager tra le due stagioni non coerente.';
  end if;

  select matchday.*
  into v_matchday
  from public.matchdays matchday
  where matchday.number = p_matchday_number
    and matchday.locks_at > now()
    and exists (
      select 1
      from public.fantasy_fixtures fixture
      where fixture.league_id = p_league_id
        and fixture.matchday_id = matchday.id
    )
  order by matchday.starts_at
  limit 1;

  if v_matchday.id is null then
    raise exception 'La giornata scelta non è disponibile.';
  end if;

  v_qualifiers_hash := public.leghevo_sha256_hex_v1(
    p_league_id::text || '#'
    || v_source_league_id::text || '#'
    || coalesce(v_source_season, '-') || '#'
    || v_source_summary.champion_team_id::text || '#'
    || v_source_home_manager_id::text || '#'
    || v_source_cup.id::text || '#'
    || v_source_certificate.completion_fingerprint || '#'
    || v_source_challenger_team_id::text || '#'
    || v_source_challenger_manager_id::text || '#'
    || (v_qualifiers ->> 'challengerQualification') || '#'
    || v_home_team.id::text || '#'
    || v_away_team.id::text
  );

  v_schedule_hash := public.leghevo_sha256_hex_v1(
    v_matchday.id::text || '#'
    || v_matchday.number::text || '#'
    || v_matchday.starts_at::text || '#'
    || v_matchday.locks_at::text || '#'
    || coalesce(v_matchday.ends_at::text, '-')
  );

  insert into public.league_super_cups (
    league_id,
    source_league_id,
    matchday_id,
    league_champion_team_id,
    challenger_team_id,
    challenger_qualification,
    created_by
  ) values (
    p_league_id,
    v_source_league_id,
    v_matchday.id,
    v_home_team.id,
    v_away_team.id,
    v_qualifiers ->> 'challengerQualification',
    auth.uid()
  ) returning id into v_super_cup_id;

  v_result_hash := public.compute_league_super_cup_schedule_result_hash_v1(
    v_super_cup_id,
    v_qualifiers_hash,
    v_schedule_hash
  );

  insert into public.league_super_cup_schedule_runs (
    league_id,
    super_cup_id,
    source_league_id,
    request_id,
    requested_by,
    matchday_id,
    matchday_number,
    league_champion_team_id,
    challenger_team_id,
    challenger_qualification,
    qualifiers_hash,
    schedule_hash,
    result_hash
  ) values (
    p_league_id,
    v_super_cup_id,
    v_source_league_id,
    p_request_id,
    auth.uid(),
    v_matchday.id,
    v_matchday.number,
    v_home_team.id,
    v_away_team.id,
    v_qualifiers ->> 'challengerQualification',
    v_qualifiers_hash,
    v_schedule_hash,
    v_result_hash
  );

  if to_regprocedure(
    'public.create_user_notification(uuid,uuid,text,text,text,text,jsonb,text)'
  ) is not null then
    for v_member_user_id in
      select member.user_id
      from public.league_members member
      where member.league_id = p_league_id
    loop
      perform public.create_user_notification(
        v_member_user_id,
        p_league_id,
        'league',
        'Supercoppa programmata',
        pg_catalog.format(
          '%s contro %s alla giornata %s.',
          v_home_team.name,
          v_away_team.name,
          v_matchday.number
        ),
        'leagueSuperCup',
        jsonb_build_object(
          'superCupId', v_super_cup_id,
          'matchdayNumber', v_matchday.number,
          'schedulePolicy', 'guarded_v1'
        ),
        pg_catalog.format('league-super-cup-created:%s', v_super_cup_id)
      );
    end loop;
  end if;

  return public.get_league_super_cup_state_v2(p_league_id)
    || jsonb_build_object(
      'idempotentReplay', false,
      'alreadyExists', false
    );
end;
$$;

revoke all on function public.create_league_super_cup_guarded_v1(
  uuid, smallint, uuid
) from public, anon, authenticated;
grant execute on function public.create_league_super_cup_guarded_v1(
  uuid, smallint, uuid
) to authenticated;

-- Compatibilità: il vecchio endpoint confluisce nel percorso protetto.
create or replace function public.create_league_super_cup(
  p_league_id uuid,
  p_matchday_number smallint
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_state jsonb;
begin
  v_state := public.create_league_super_cup_guarded_v1(
    p_league_id,
    p_matchday_number,
    public.leghevo_stable_request_uuid(
      'legacy-league-super-cup-schedule:'
      || coalesce(auth.uid()::text, 'anonymous')
      || ':' || p_league_id::text
      || ':' || p_matchday_number::text
    )
  );

  return nullif(v_state ->> 'superCupId', '')::uuid;
end;
$$;

revoke all on function public.create_league_super_cup(uuid, smallint)
from public, anon, authenticated;
grant execute on function public.create_league_super_cup(uuid, smallint)
to authenticated;

-- Certifica senza modificarle eventuali Supercoppe già programmate.
with candidates as (
  select
    super_cup.*,
    matchday.number::smallint as matchday_number,
    matchday.starts_at,
    matchday.locks_at,
    matchday.ends_at,
    coalesce(certificate.completion_fingerprint, '-') as source_certificate_hash
  from public.league_super_cups super_cup
  join public.matchdays matchday on matchday.id = super_cup.matchday_id
  left join public.league_cups source_cup
    on source_cup.league_id = super_cup.source_league_id
    and source_cup.status = 'completed'
  left join public.league_cup_completion_certificates certificate
    on certificate.cup_id = source_cup.id
  where not exists (
    select 1
    from public.league_super_cup_schedule_runs run
    where run.super_cup_id = super_cup.id
  )
), hashes as (
  select
    candidate.*,
    public.leghevo_sha256_hex_v1(
      candidate.league_id::text || '#'
      || candidate.source_league_id::text || '#'
      || candidate.source_certificate_hash || '#'
      || candidate.league_champion_team_id::text || '#'
      || candidate.challenger_team_id::text || '#'
      || candidate.challenger_qualification
    ) as qualifiers_hash,
    public.leghevo_sha256_hex_v1(
      candidate.matchday_id::text || '#'
      || candidate.matchday_number::text || '#'
      || candidate.starts_at::text || '#'
      || candidate.locks_at::text || '#'
      || coalesce(candidate.ends_at::text, '-')
    ) as schedule_hash
  from candidates candidate
)
insert into public.league_super_cup_schedule_runs (
  league_id,
  super_cup_id,
  source_league_id,
  request_id,
  requested_by,
  matchday_id,
  matchday_number,
  league_champion_team_id,
  challenger_team_id,
  challenger_qualification,
  qualifiers_hash,
  schedule_hash,
  result_hash,
  created_at
)
select
  hashes.league_id,
  hashes.id,
  hashes.source_league_id,
  public.leghevo_stable_request_uuid(
    'league-super-cup-schedule-backfill:' || hashes.id::text
  ),
  hashes.created_by,
  hashes.matchday_id,
  hashes.matchday_number,
  hashes.league_champion_team_id,
  hashes.challenger_team_id,
  hashes.challenger_qualification,
  hashes.qualifiers_hash,
  hashes.schedule_hash,
  public.compute_league_super_cup_schedule_result_hash_v1(
    hashes.id,
    hashes.qualifiers_hash,
    hashes.schedule_hash
  ),
  hashes.created_at
from hashes
on conflict do nothing;

alter table public.league_super_cup_schedule_runs replica identity full;

do $block$
begin
  if exists (
    select 1
    from pg_catalog.pg_publication publication
    where publication.pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'league_super_cup_schedule_runs'
  ) then
    alter publication supabase_realtime
      add table public.league_super_cup_schedule_runs;
  end if;
end;
$block$;

create or replace function public.get_league_super_cup_schedule_integrity_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_run public.league_super_cup_schedule_runs%rowtype;
  v_hash_matches boolean := false;
  v_source_certified boolean := false;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if not public.is_league_member(p_league_id)
    and not public.is_league_admin(p_league_id) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  select run.*
  into v_run
  from public.league_super_cup_schedule_runs run
  where run.league_id = p_league_id
  order by run.created_at desc, run.id desc
  limit 1;

  if v_run.id is not null then
    v_hash_matches := v_run.result_hash =
      public.compute_league_super_cup_schedule_result_hash_v1(
        v_run.super_cup_id,
        v_run.qualifiers_hash,
        v_run.schedule_hash
      );

    select exists (
      select 1
      from public.league_cups cup
      join public.league_cup_completion_certificates certificate
        on certificate.cup_id = cup.id
      where cup.league_id = v_run.source_league_id
        and cup.status = 'completed'
        and certificate.champion_team_id = cup.champion_team_id
        and certificate.runner_up_team_id = cup.runner_up_team_id
    ) into v_source_certified;
  end if;

  return jsonb_build_object(
    'leagueId', p_league_id,
    'ready', v_run.id is not null and v_hash_matches and v_source_certified,
    'scheduleCertified', v_run.id is not null,
    'scheduleRunId', v_run.id,
    'requestId', v_run.request_id,
    'superCupId', v_run.super_cup_id,
    'sourceLeagueId', v_run.source_league_id,
    'hashMatches', v_hash_matches,
    'sourceCupCertified', v_source_certified,
    'qualifiersHash', v_run.qualifiers_hash,
    'scheduleHash', v_run.schedule_hash,
    'resultHash', v_run.result_hash
  );
end;
$$;

revoke all on function public.get_league_super_cup_schedule_integrity_v1(uuid)
from public, anon, authenticated;
grant execute on function public.get_league_super_cup_schedule_integrity_v1(uuid)
to authenticated;

commit;

-- Diagnostica conclusiva v0.60.4: devono risultare 20 valori true.
select
  to_regclass('public.league_super_cup_schedule_runs') is not null
    as schedule_run_table_ready,
  exists (
    select 1 from pg_catalog.pg_indexes index_record
    where index_record.schemaname = 'public'
      and index_record.indexname = 'league_super_cup_schedule_request_uidx'
  ) as schedule_request_unique_ready,
  exists (
    select 1 from pg_catalog.pg_indexes index_record
    where index_record.schemaname = 'public'
      and index_record.indexname = 'league_super_cup_schedule_super_cup_uidx'
  ) as schedule_super_cup_unique_ready,
  coalesce((
    select class.relrowsecurity
    from pg_catalog.pg_class class
    join pg_catalog.pg_namespace namespace on namespace.oid = class.relnamespace
    where namespace.nspname = 'public'
      and class.relname = 'league_super_cup_schedule_runs'
  ), false) as schedule_run_rls_ready,
  exists (
    select 1 from pg_catalog.pg_policies policy
    where policy.schemaname = 'public'
      and policy.tablename = 'league_super_cup_schedule_runs'
      and policy.policyname = 'league_super_cup_schedule_read_members'
  ) as schedule_read_policy_ready,
  exists (
    select 1
    from pg_catalog.pg_trigger trigger_record
    where trigger_record.tgrelid = 'public.league_super_cup_schedule_runs'::regclass
      and trigger_record.tgname = 'league_super_cup_schedule_runs_immutable'
      and not trigger_record.tgisinternal
  ) as schedule_immutable_trigger_ready,
  not has_table_privilege(
    'authenticated', 'public.league_super_cup_schedule_runs', 'INSERT'
  ) as schedule_direct_insert_blocked,
  not has_table_privilege(
    'authenticated', 'public.league_super_cup_schedule_runs', 'UPDATE'
  ) as schedule_direct_update_blocked,
  not has_table_privilege(
    'authenticated', 'public.league_super_cup_schedule_runs', 'DELETE'
  ) as schedule_direct_delete_blocked,
  to_regprocedure(
    'public.create_league_super_cup_guarded_v1(uuid,smallint,uuid)'
  ) is not null as guarded_schedule_ready,
  has_function_privilege(
    'authenticated',
    'public.create_league_super_cup_guarded_v1(uuid,smallint,uuid)',
    'EXECUTE'
  ) as guarded_schedule_authenticated,
  not has_function_privilege(
    'anon',
    'public.create_league_super_cup_guarded_v1(uuid,smallint,uuid)',
    'EXECUTE'
  ) as guarded_schedule_anon_blocked,
  to_regprocedure('public.get_league_super_cup_state_v2(uuid)') is not null
    as super_cup_state_v2_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_super_cup_state_v2(uuid)',
    'EXECUTE'
  ) as super_cup_state_v2_authenticated,
  coalesce(
    pg_catalog.pg_get_functiondef(
      to_regprocedure('public.create_league_super_cup(uuid,smallint)')
    ) ilike '%create_league_super_cup_guarded_v1%',
    false
  ) as legacy_schedule_routed,
  not exists (
    select 1
    from public.league_super_cups super_cup
    where not exists (
      select 1
      from public.league_super_cup_schedule_runs run
      where run.super_cup_id = super_cup.id
    )
  ) as existing_super_cups_certified,
  not exists (
    select 1
    from public.league_super_cup_schedule_runs run
    where char_length(run.qualifiers_hash) <> 64
      or char_length(run.schedule_hash) <> 64
      or char_length(run.result_hash) <> 64
      or run.result_hash is distinct from
        public.compute_league_super_cup_schedule_result_hash_v1(
          run.super_cup_id,
          run.qualifiers_hash,
          run.schedule_hash
        )
  ) as schedule_hashes_ready,
  not exists (
    select 1
    from public.league_super_cup_schedule_runs run
    where not exists (
      select 1
      from public.league_cups cup
      join public.league_cup_completion_certificates certificate
        on certificate.cup_id = cup.id
      where cup.league_id = run.source_league_id
        and cup.status = 'completed'
        and certificate.champion_team_id = cup.champion_team_id
        and certificate.runner_up_team_id = cup.runner_up_team_id
    )
  ) as source_cup_certification_ready,
  exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'league_super_cup_schedule_runs'
  ) as schedule_realtime_ready,
  to_regprocedure(
    'public.get_league_super_cup_schedule_integrity_v1(uuid)'
  ) is not null as schedule_diagnostics_ready;
