-- LEGHEVO v0.60.5 · Supercoppa: ufficializzazione protetta e verdetto certificato
-- Migrazione: database/089_league_super_cup_finalization_safety.sql
-- Eseguire dopo database/088_league_super_cup_schedule_safety.sql.
-- Script idempotente: non programma Supercoppe, non altera verdetti già certificati
-- e certifica in modo non distruttivo eventuali Supercoppe storiche concluse.

begin;

-- Preflight esplicito: tutte le dipendenze sono verificate prima di ogni scrittura.
do $block$
declare
  v_missing text[] := array[]::text[];
begin
  if to_regclass('public.leagues') is null then
    v_missing := array_append(v_missing, 'public.leagues');
  end if;
  if to_regclass('public.fantasy_teams') is null then
    v_missing := array_append(v_missing, 'public.fantasy_teams');
  end if;
  if to_regclass('public.profiles') is null then
    v_missing := array_append(v_missing, 'public.profiles');
  end if;
  if to_regclass('public.league_members') is null then
    v_missing := array_append(v_missing, 'public.league_members');
  end if;
  if to_regclass('public.matchdays') is null then
    v_missing := array_append(v_missing, 'public.matchdays');
  end if;
  if to_regclass('public.league_super_cups') is null then
    v_missing := array_append(v_missing, 'public.league_super_cups');
  end if;
  if to_regclass('public.league_super_cup_schedule_runs') is null then
    v_missing := array_append(v_missing, 'public.league_super_cup_schedule_runs');
  end if;
  if to_regclass('public.matchday_officialization_runs') is null then
    v_missing := array_append(v_missing, 'public.matchday_officialization_runs');
  end if;
  if to_regclass('public.lineup_resolution_runs') is null then
    v_missing := array_append(v_missing, 'public.lineup_resolution_runs');
  end if;
  if to_regprocedure('public.get_league_super_cup_state_v2(uuid)') is null then
    v_missing := array_append(v_missing, 'public.get_league_super_cup_state_v2(uuid)');
  end if;
  if to_regprocedure('public.is_league_member(uuid)') is null then
    v_missing := array_append(v_missing, 'public.is_league_member(uuid)');
  end if;
  if to_regprocedure('public.is_league_admin(uuid)') is null then
    v_missing := array_append(v_missing, 'public.is_league_admin(uuid)');
  end if;
  if to_regprocedure('public.get_team_matchday_breakdown(uuid,uuid)') is null then
    v_missing := array_append(v_missing, 'public.get_team_matchday_breakdown(uuid,uuid)');
  end if;
  if to_regprocedure('public.resolve_fantasy_fixture_goals(numeric,numeric,jsonb)') is null then
    v_missing := array_append(v_missing, 'public.resolve_fantasy_fixture_goals(numeric,numeric,jsonb)');
  end if;
  if to_regprocedure('public.leghevo_sha256_hex_v1(text)') is null then
    v_missing := array_append(v_missing, 'public.leghevo_sha256_hex_v1(text)');
  end if;
  if to_regprocedure('public.leghevo_stable_request_uuid(text)') is null then
    v_missing := array_append(v_missing, 'public.leghevo_stable_request_uuid(text)');
  end if;

  if coalesce(array_length(v_missing, 1), 0) > 0 then
    raise exception 'Dipendenze v0.60.5 mancanti: %', array_to_string(v_missing, ', ');
  end if;
end;
$block$;

create table if not exists public.league_super_cup_finalization_runs (
  id bigint generated by default as identity primary key,
  league_id uuid not null
    references public.leagues(id) on delete cascade,
  super_cup_id uuid not null unique
    references public.league_super_cups(id) on delete cascade,
  schedule_run_id bigint not null
    references public.league_super_cup_schedule_runs(id) on delete restrict,
  request_id uuid not null,
  requested_by uuid not null
    references public.profiles(id) on delete restrict,
  source_mode text not null
    check (source_mode in ('guarded_v1', 'legacy_backfill')),
  matchday_id uuid not null
    references public.matchdays(id) on delete restrict,
  matchday_officialization_run_id bigint
    references public.matchday_officialization_runs(id) on delete restrict,
  home_resolution_id bigint
    references public.lineup_resolution_runs(id) on delete restrict,
  away_resolution_id bigint
    references public.lineup_resolution_runs(id) on delete restrict,
  schedule_result_hash text not null
    check (char_length(schedule_result_hash) = 64),
  officialization_result_hash text,
  home_resolution_hash text,
  away_resolution_hash text,
  input_hash text not null check (char_length(input_hash) = 64),
  result_hash text not null check (char_length(result_hash) = 64),
  home_points numeric(8,2) not null,
  away_points numeric(8,2) not null,
  home_goals smallint not null check (home_goals >= 0),
  away_goals smallint not null check (away_goals >= 0),
  winner_team_id uuid not null
    references public.fantasy_teams(id) on delete restrict,
  runner_up_team_id uuid not null
    references public.fantasy_teams(id) on delete restrict,
  decided_by text not null
    check (decided_by in ('goals', 'fantasy_points', 'league_champion')),
  finalized_at timestamptz not null default now(),
  check (winner_team_id <> runner_up_team_id),
  check (
    source_mode = 'legacy_backfill'
    or (
      matchday_officialization_run_id is not null
      and home_resolution_id is not null
      and away_resolution_id is not null
      and char_length(officialization_result_hash) = 32
      and char_length(home_resolution_hash) = 32
      and char_length(away_resolution_hash) = 32
    )
  )
);

create unique index if not exists league_super_cup_finalization_request_uidx
  on public.league_super_cup_finalization_runs (league_id, request_id);
create unique index if not exists league_super_cup_finalization_super_cup_uidx
  on public.league_super_cup_finalization_runs (super_cup_id);
create index if not exists league_super_cup_finalization_league_created_idx
  on public.league_super_cup_finalization_runs (
    league_id,
    finalized_at desc,
    id desc
  );

alter table public.league_super_cup_finalization_runs enable row level security;

drop policy if exists league_super_cup_finalization_read_members
on public.league_super_cup_finalization_runs;
create policy league_super_cup_finalization_read_members
on public.league_super_cup_finalization_runs
for select to authenticated
using (
  public.is_league_member(league_id)
  or public.is_league_admin(league_id)
);

revoke all on table public.league_super_cup_finalization_runs
from public, anon, authenticated;
grant select on table public.league_super_cup_finalization_runs
to authenticated;

create or replace function public.prevent_league_super_cup_finalization_run_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  raise exception
    'Registro ufficializzazione Supercoppa immutabile: modifica o cancellazione diretta non consentita.';
end;
$$;

revoke all on function public.prevent_league_super_cup_finalization_run_mutation()
from public, anon, authenticated;

drop trigger if exists league_super_cup_finalization_runs_immutable
on public.league_super_cup_finalization_runs;
create trigger league_super_cup_finalization_runs_immutable
before update or delete on public.league_super_cup_finalization_runs
for each row
execute function public.prevent_league_super_cup_finalization_run_mutation();

create or replace function public.compute_league_super_cup_finalization_input_hash_v1(
  p_super_cup_id uuid,
  p_schedule_result_hash text,
  p_officialization_result_hash text,
  p_home_resolution_hash text,
  p_away_resolution_hash text,
  p_home_points numeric,
  p_away_points numeric,
  p_home_goals smallint,
  p_away_goals smallint,
  p_source_mode text
)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select public.leghevo_sha256_hex_v1(
    coalesce(p_source_mode, '-') || '#'
    || coalesce(p_super_cup_id::text, '-') || '#'
    || coalesce(p_schedule_result_hash, '-') || '#'
    || coalesce(p_officialization_result_hash, '-') || '#'
    || coalesce(p_home_resolution_hash, '-') || '#'
    || coalesce(p_away_resolution_hash, '-') || '#'
    || coalesce(p_home_points::text, '-') || '#'
    || coalesce(p_away_points::text, '-') || '#'
    || coalesce(p_home_goals::text, '-') || '#'
    || coalesce(p_away_goals::text, '-')
  );
$$;

revoke all on function public.compute_league_super_cup_finalization_input_hash_v1(
  uuid, text, text, text, text, numeric, numeric, smallint, smallint, text
) from public, anon, authenticated;

create or replace function public.compute_league_super_cup_finalization_result_hash_v1(
  p_input_hash text,
  p_winner_team_id uuid,
  p_runner_up_team_id uuid,
  p_decided_by text
)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select public.leghevo_sha256_hex_v1(
    coalesce(p_input_hash, '-') || '#'
    || coalesce(p_winner_team_id::text, '-') || '#'
    || coalesce(p_runner_up_team_id::text, '-') || '#'
    || coalesce(p_decided_by, '-')
  );
$$;

revoke all on function public.compute_league_super_cup_finalization_result_hash_v1(
  text, uuid, uuid, text
) from public, anon, authenticated;

create or replace function public.get_league_super_cup_state_v3(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_state jsonb;
  v_run public.league_super_cup_finalization_runs%rowtype;
begin
  v_state := public.get_league_super_cup_state_v2(p_league_id);

  select run.*
  into v_run
  from public.league_super_cup_finalization_runs run
  where run.league_id = p_league_id
  order by run.finalized_at desc, run.id desc
  limit 1;

  return coalesce(v_state, '{}'::jsonb) || jsonb_build_object(
    'finalizationPolicy', 'guarded_v1',
    'finalizationCertified', v_run.id is not null,
    'finalizationRunId', v_run.id,
    'finalizationRequestId', v_run.request_id,
    'finalizationSourceMode', v_run.source_mode,
    'finalizationInputHash', v_run.input_hash,
    'finalizationResultHash', v_run.result_hash,
    'finalizationOfficializationRunId', v_run.matchday_officialization_run_id,
    'finalizationHomeResolutionId', v_run.home_resolution_id,
    'finalizationAwayResolutionId', v_run.away_resolution_id
  );
end;
$$;

revoke all on function public.get_league_super_cup_state_v3(uuid)
from public, anon, authenticated;
grant execute on function public.get_league_super_cup_state_v3(uuid)
to authenticated;

create or replace function public.finalize_league_super_cup_guarded_v1(
  p_league_id uuid,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_league public.leagues%rowtype;
  v_super_cup public.league_super_cups%rowtype;
  v_matchday public.matchdays%rowtype;
  v_schedule_run public.league_super_cup_schedule_runs%rowtype;
  v_existing_run public.league_super_cup_finalization_runs%rowtype;
  v_officialization public.matchday_officialization_runs%rowtype;
  v_home_resolution public.lineup_resolution_runs%rowtype;
  v_away_resolution public.lineup_resolution_runs%rowtype;
  v_scoring_rules jsonb := '{}'::jsonb;
  v_home_breakdown jsonb;
  v_away_breakdown jsonb;
  v_goal_resolution jsonb;
  v_home_points numeric(8,2);
  v_away_points numeric(8,2);
  v_home_goals smallint;
  v_away_goals smallint;
  v_winner_id uuid;
  v_runner_up_id uuid;
  v_decided_by text;
  v_input_hash text;
  v_result_hash text;
  v_finalized_at timestamptz := now();
  v_winner_name text;
  v_member_user_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if p_request_id is null then
    raise exception 'Identificativo richiesta mancante.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'leghevo:league-super-cup-finalization:' || p_league_id::text,
      0
    )
  );

  select run.*
  into v_existing_run
  from public.league_super_cup_finalization_runs run
  where run.league_id = p_league_id
    and run.request_id = p_request_id;

  if found then
    return public.get_league_super_cup_state_v3(p_league_id)
      || jsonb_build_object(
        'idempotentReplay', true,
        'finalizationRunId', v_existing_run.id
      );
  end if;

  select league.*
  into v_league
  from public.leagues league
  where league.id = p_league_id
  for update;

  if not found then
    raise exception 'Lega non trovata.';
  end if;

  if v_league.owner_id <> auth.uid() then
    raise exception 'Solo il Presidente può ufficializzare la Supercoppa.';
  end if;

  select super_cup.*
  into v_super_cup
  from public.league_super_cups super_cup
  where super_cup.league_id = p_league_id
  for update;

  if not found then
    raise exception 'La Supercoppa non è stata programmata.';
  end if;

  select run.*
  into v_schedule_run
  from public.league_super_cup_schedule_runs run
  where run.super_cup_id = v_super_cup.id;

  if not found then
    raise exception 'Programmazione della Supercoppa non certificata.';
  end if;

  select run.*
  into v_existing_run
  from public.league_super_cup_finalization_runs run
  where run.super_cup_id = v_super_cup.id;

  if found then
    return public.get_league_super_cup_state_v3(p_league_id)
      || jsonb_build_object(
        'idempotentReplay', true,
        'alreadyFinalized', true,
        'finalizationRunId', v_existing_run.id
      );
  end if;

  if v_super_cup.status = 'completed' then
    raise exception 'Supercoppa conclusa ma priva di certificato: eseguire nuovamente la migrazione v0.60.5.';
  end if;

  select matchday.*
  into v_matchday
  from public.matchdays matchday
  where matchday.id = v_super_cup.matchday_id;

  if not found then
    raise exception 'Giornata della Supercoppa non trovata.';
  end if;

  if now() < coalesce(
    v_matchday.ends_at,
    v_matchday.starts_at + interval '4 days'
  ) then
    raise exception 'La giornata reale della Supercoppa non è ancora terminata.';
  end if;

  select officialization.*
  into v_officialization
  from public.matchday_officialization_runs officialization
  where officialization.league_id = p_league_id
    and officialization.matchday_id = v_super_cup.matchday_id
    and officialization.superseded_at is null
  order by officialization.finalization_revision desc
  limit 1;

  if not found
    or v_officialization.fixture_count <> v_officialization.finalized_fixture_count then
    raise exception 'La giornata della Supercoppa non è ancora ufficializzata integralmente.';
  end if;

  v_home_breakdown := public.get_team_matchday_breakdown(
    v_super_cup.league_champion_team_id,
    v_super_cup.matchday_id
  );
  v_away_breakdown := public.get_team_matchday_breakdown(
    v_super_cup.challenger_team_id,
    v_super_cup.matchday_id
  );

  if not coalesce((v_home_breakdown ->> 'isReady')::boolean, false)
    or not coalesce((v_away_breakdown ->> 'isReady')::boolean, false)
    or nullif(v_home_breakdown ->> 'totalPoints', '') is null
    or nullif(v_away_breakdown ->> 'totalPoints', '') is null then
    raise exception 'Mancano ancora voti o sostituzioni certificate per la Supercoppa.';
  end if;

  select resolution.*
  into v_home_resolution
  from public.lineup_resolution_runs resolution
  where resolution.fantasy_team_id = v_super_cup.league_champion_team_id
    and resolution.matchday_id = v_super_cup.matchday_id
    and resolution.superseded_at is null
    and resolution.is_ready
  order by resolution.resolution_revision desc
  limit 1;

  select resolution.*
  into v_away_resolution
  from public.lineup_resolution_runs resolution
  where resolution.fantasy_team_id = v_super_cup.challenger_team_id
    and resolution.matchday_id = v_super_cup.matchday_id
    and resolution.superseded_at is null
    and resolution.is_ready
  order by resolution.resolution_revision desc
  limit 1;

  if v_home_resolution.id is null or v_away_resolution.id is null then
    raise exception 'Risoluzioni protette delle due formazioni non disponibili.';
  end if;

  v_home_points := round((v_home_breakdown ->> 'totalPoints')::numeric, 2);
  v_away_points := round((v_away_breakdown ->> 'totalPoints')::numeric, 2);

  select league.scoring_rules
  into v_scoring_rules
  from public.leagues league
  where league.id = p_league_id;

  v_goal_resolution := public.resolve_fantasy_fixture_goals(
    v_home_points,
    v_away_points,
    coalesce(v_scoring_rules, '{}'::jsonb)
  );

  v_home_goals := nullif(v_goal_resolution ->> 'homeGoals', '')::smallint;
  v_away_goals := nullif(v_goal_resolution ->> 'awayGoals', '')::smallint;

  if v_home_goals is null or v_away_goals is null then
    raise exception 'Conversione dei fantapunti in gol non disponibile.';
  end if;

  if v_home_goals > v_away_goals then
    v_winner_id := v_super_cup.league_champion_team_id;
    v_runner_up_id := v_super_cup.challenger_team_id;
    v_decided_by := 'goals';
  elsif v_away_goals > v_home_goals then
    v_winner_id := v_super_cup.challenger_team_id;
    v_runner_up_id := v_super_cup.league_champion_team_id;
    v_decided_by := 'goals';
  elsif v_home_points > v_away_points then
    v_winner_id := v_super_cup.league_champion_team_id;
    v_runner_up_id := v_super_cup.challenger_team_id;
    v_decided_by := 'fantasy_points';
  elsif v_away_points > v_home_points then
    v_winner_id := v_super_cup.challenger_team_id;
    v_runner_up_id := v_super_cup.league_champion_team_id;
    v_decided_by := 'fantasy_points';
  else
    v_winner_id := v_super_cup.league_champion_team_id;
    v_runner_up_id := v_super_cup.challenger_team_id;
    v_decided_by := 'league_champion';
  end if;

  v_input_hash := public.compute_league_super_cup_finalization_input_hash_v1(
    v_super_cup.id,
    v_schedule_run.result_hash,
    v_officialization.result_hash,
    v_home_resolution.result_hash,
    v_away_resolution.result_hash,
    v_home_points,
    v_away_points,
    v_home_goals,
    v_away_goals,
    'guarded_v1'
  );

  v_result_hash := public.compute_league_super_cup_finalization_result_hash_v1(
    v_input_hash,
    v_winner_id,
    v_runner_up_id,
    v_decided_by
  );

  update public.league_super_cups
  set
    status = 'completed',
    home_points = v_home_points,
    away_points = v_away_points,
    home_goals = v_home_goals,
    away_goals = v_away_goals,
    home_ready = true,
    away_ready = true,
    home_counted_players = least(v_home_resolution.counted_players, 11),
    away_counted_players = least(v_away_resolution.counted_players, 11),
    winner_team_id = v_winner_id,
    runner_up_team_id = v_runner_up_id,
    decided_by = v_decided_by,
    finalized_by = auth.uid(),
    completed_at = v_finalized_at
  where id = v_super_cup.id;

  insert into public.league_super_cup_finalization_runs (
    league_id,
    super_cup_id,
    schedule_run_id,
    request_id,
    requested_by,
    source_mode,
    matchday_id,
    matchday_officialization_run_id,
    home_resolution_id,
    away_resolution_id,
    schedule_result_hash,
    officialization_result_hash,
    home_resolution_hash,
    away_resolution_hash,
    input_hash,
    result_hash,
    home_points,
    away_points,
    home_goals,
    away_goals,
    winner_team_id,
    runner_up_team_id,
    decided_by,
    finalized_at
  ) values (
    p_league_id,
    v_super_cup.id,
    v_schedule_run.id,
    p_request_id,
    auth.uid(),
    'guarded_v1',
    v_super_cup.matchday_id,
    v_officialization.id,
    v_home_resolution.id,
    v_away_resolution.id,
    v_schedule_run.result_hash,
    v_officialization.result_hash,
    v_home_resolution.result_hash,
    v_away_resolution.result_hash,
    v_input_hash,
    v_result_hash,
    v_home_points,
    v_away_points,
    v_home_goals,
    v_away_goals,
    v_winner_id,
    v_runner_up_id,
    v_decided_by,
    v_finalized_at
  );

  select team.name
  into v_winner_name
  from public.fantasy_teams team
  where team.id = v_winner_id;

  if to_regprocedure(
    'public.create_user_notification(uuid,uuid,text,text,text,text,jsonb,text)'
  ) is not null then
    for v_member_user_id in
      select member.user_id
      from public.league_members member
      where member.league_id = p_league_id
    loop
      perform public.create_user_notification(
        v_member_user_id,
        p_league_id,
        'result',
        'Supercoppa assegnata',
        coalesce(v_winner_name, 'La squadra vincitrice')
          || ' ha vinto la Supercoppa di '
          || v_league.name
          || '.',
        'leagueSuperCup',
        jsonb_build_object(
          'superCupId', v_super_cup.id,
          'winnerTeamId', v_winner_id,
          'decidedBy', v_decided_by,
          'finalizationPolicy', 'guarded_v1'
        ),
        pg_catalog.format('league-super-cup-completed:%s', v_super_cup.id)
      );
    end loop;
  end if;

  return public.get_league_super_cup_state_v3(p_league_id)
    || jsonb_build_object(
      'idempotentReplay', false,
      'alreadyFinalized', false
    );
end;
$$;

revoke all on function public.finalize_league_super_cup_guarded_v1(uuid, uuid)
from public, anon, authenticated;
grant execute on function public.finalize_league_super_cup_guarded_v1(uuid, uuid)
to authenticated;

-- Compatibilità: il vecchio endpoint confluisce nel percorso protetto.
create or replace function public.finalize_league_super_cup(
  p_league_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  return public.finalize_league_super_cup_guarded_v1(
    p_league_id,
    public.leghevo_stable_request_uuid(
      'legacy-league-super-cup-finalization:' || p_league_id::text
    )
  );
end;
$$;

revoke all on function public.finalize_league_super_cup(uuid)
from public, anon, authenticated;
grant execute on function public.finalize_league_super_cup(uuid)
to authenticated;

-- Backfill non distruttivo delle Supercoppe concluse prima della v0.60.5.
with candidates as (
  select
    super_cup.*,
    schedule_run.id as schedule_run_id,
    schedule_run.result_hash as schedule_result_hash,
    coalesce(super_cup.finalized_by, super_cup.created_by) as requested_by
  from public.league_super_cups super_cup
  join public.league_super_cup_schedule_runs schedule_run
    on schedule_run.super_cup_id = super_cup.id
  where super_cup.status = 'completed'
    and super_cup.winner_team_id is not null
    and super_cup.runner_up_team_id is not null
    and super_cup.home_points is not null
    and super_cup.away_points is not null
    and super_cup.home_goals is not null
    and super_cup.away_goals is not null
    and super_cup.decided_by is not null
    and not exists (
      select 1
      from public.league_super_cup_finalization_runs run
      where run.super_cup_id = super_cup.id
    )
), prepared as (
  select
    candidate.*,
    public.compute_league_super_cup_finalization_input_hash_v1(
      candidate.id,
      candidate.schedule_result_hash,
      null,
      null,
      null,
      candidate.home_points,
      candidate.away_points,
      candidate.home_goals,
      candidate.away_goals,
      'legacy_backfill'
    ) as computed_input_hash
  from candidates candidate
)
insert into public.league_super_cup_finalization_runs (
  league_id,
  super_cup_id,
  schedule_run_id,
  request_id,
  requested_by,
  source_mode,
  matchday_id,
  schedule_result_hash,
  input_hash,
  result_hash,
  home_points,
  away_points,
  home_goals,
  away_goals,
  winner_team_id,
  runner_up_team_id,
  decided_by,
  finalized_at
)
select
  prepared.league_id,
  prepared.id,
  prepared.schedule_run_id,
  public.leghevo_stable_request_uuid(
    'league-super-cup-finalization-backfill:' || prepared.id::text
  ),
  prepared.requested_by,
  'legacy_backfill',
  prepared.matchday_id,
  prepared.schedule_result_hash,
  prepared.computed_input_hash,
  public.compute_league_super_cup_finalization_result_hash_v1(
    prepared.computed_input_hash,
    prepared.winner_team_id,
    prepared.runner_up_team_id,
    prepared.decided_by
  ),
  prepared.home_points,
  prepared.away_points,
  prepared.home_goals,
  prepared.away_goals,
  prepared.winner_team_id,
  prepared.runner_up_team_id,
  prepared.decided_by,
  coalesce(prepared.completed_at, prepared.updated_at, prepared.created_at)
from prepared
on conflict do nothing;

alter table public.league_super_cup_finalization_runs replica identity full;

do $block$
begin
  if exists (
    select 1
    from pg_catalog.pg_publication publication
    where publication.pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'league_super_cup_finalization_runs'
  ) then
    alter publication supabase_realtime
      add table public.league_super_cup_finalization_runs;
  end if;
end;
$block$;

create or replace function public.get_league_super_cup_finalization_integrity_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_run public.league_super_cup_finalization_runs%rowtype;
  v_input_hash_matches boolean := false;
  v_result_hash_matches boolean := false;
  v_verdict_matches boolean := false;
  v_sources_ready boolean := false;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if not public.is_league_member(p_league_id)
    and not public.is_league_admin(p_league_id) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  select run.*
  into v_run
  from public.league_super_cup_finalization_runs run
  where run.league_id = p_league_id
  order by run.finalized_at desc, run.id desc
  limit 1;

  if v_run.id is not null then
    v_input_hash_matches := v_run.input_hash =
      public.compute_league_super_cup_finalization_input_hash_v1(
        v_run.super_cup_id,
        v_run.schedule_result_hash,
        v_run.officialization_result_hash,
        v_run.home_resolution_hash,
        v_run.away_resolution_hash,
        v_run.home_points,
        v_run.away_points,
        v_run.home_goals,
        v_run.away_goals,
        v_run.source_mode
      );

    v_result_hash_matches := v_run.result_hash =
      public.compute_league_super_cup_finalization_result_hash_v1(
        v_run.input_hash,
        v_run.winner_team_id,
        v_run.runner_up_team_id,
        v_run.decided_by
      );

    select exists (
      select 1
      from public.league_super_cups super_cup
      where super_cup.id = v_run.super_cup_id
        and super_cup.status = 'completed'
        and super_cup.home_points = v_run.home_points
        and super_cup.away_points = v_run.away_points
        and super_cup.home_goals = v_run.home_goals
        and super_cup.away_goals = v_run.away_goals
        and super_cup.winner_team_id = v_run.winner_team_id
        and super_cup.runner_up_team_id = v_run.runner_up_team_id
        and super_cup.decided_by = v_run.decided_by
    ) into v_verdict_matches;

    v_sources_ready := case
      when v_run.source_mode = 'legacy_backfill' then true
      else v_run.matchday_officialization_run_id is not null
        and v_run.home_resolution_id is not null
        and v_run.away_resolution_id is not null
        and char_length(v_run.officialization_result_hash) = 32
        and char_length(v_run.home_resolution_hash) = 32
        and char_length(v_run.away_resolution_hash) = 32
    end;
  end if;

  return jsonb_build_object(
    'leagueId', p_league_id,
    'ready', v_run.id is not null
      and v_input_hash_matches
      and v_result_hash_matches
      and v_verdict_matches
      and v_sources_ready,
    'finalizationCertified', v_run.id is not null,
    'finalizationRunId', v_run.id,
    'requestId', v_run.request_id,
    'sourceMode', v_run.source_mode,
    'inputHashMatches', v_input_hash_matches,
    'resultHashMatches', v_result_hash_matches,
    'verdictMatches', v_verdict_matches,
    'sourcesReady', v_sources_ready,
    'inputHash', v_run.input_hash,
    'resultHash', v_run.result_hash
  );
end;
$$;

revoke all on function public.get_league_super_cup_finalization_integrity_v1(uuid)
from public, anon, authenticated;
grant execute on function public.get_league_super_cup_finalization_integrity_v1(uuid)
to authenticated;

commit;

-- Diagnostica conclusiva v0.60.5: devono risultare 20 valori true.
select
  to_regclass('public.league_super_cup_finalization_runs') is not null
    as finalization_run_table_ready,
  exists (
    select 1 from pg_catalog.pg_indexes index_record
    where index_record.schemaname = 'public'
      and index_record.indexname = 'league_super_cup_finalization_request_uidx'
  ) as finalization_request_unique_ready,
  exists (
    select 1 from pg_catalog.pg_indexes index_record
    where index_record.schemaname = 'public'
      and index_record.indexname = 'league_super_cup_finalization_super_cup_uidx'
  ) as finalization_super_cup_unique_ready,
  coalesce((
    select class.relrowsecurity
    from pg_catalog.pg_class class
    join pg_catalog.pg_namespace namespace on namespace.oid = class.relnamespace
    where namespace.nspname = 'public'
      and class.relname = 'league_super_cup_finalization_runs'
  ), false) as finalization_run_rls_ready,
  exists (
    select 1 from pg_catalog.pg_policies policy
    where policy.schemaname = 'public'
      and policy.tablename = 'league_super_cup_finalization_runs'
      and policy.policyname = 'league_super_cup_finalization_read_members'
  ) as finalization_read_policy_ready,
  exists (
    select 1
    from pg_catalog.pg_trigger trigger_record
    where trigger_record.tgrelid = 'public.league_super_cup_finalization_runs'::regclass
      and trigger_record.tgname = 'league_super_cup_finalization_runs_immutable'
      and not trigger_record.tgisinternal
  ) as finalization_immutable_trigger_ready,
  not has_table_privilege(
    'authenticated', 'public.league_super_cup_finalization_runs', 'INSERT'
  ) as finalization_direct_insert_blocked,
  not has_table_privilege(
    'authenticated', 'public.league_super_cup_finalization_runs', 'UPDATE'
  ) as finalization_direct_update_blocked,
  not has_table_privilege(
    'authenticated', 'public.league_super_cup_finalization_runs', 'DELETE'
  ) as finalization_direct_delete_blocked,
  to_regprocedure(
    'public.finalize_league_super_cup_guarded_v1(uuid,uuid)'
  ) is not null as guarded_finalization_ready,
  has_function_privilege(
    'authenticated',
    'public.finalize_league_super_cup_guarded_v1(uuid,uuid)',
    'EXECUTE'
  ) as guarded_finalization_authenticated,
  not has_function_privilege(
    'anon',
    'public.finalize_league_super_cup_guarded_v1(uuid,uuid)',
    'EXECUTE'
  ) as guarded_finalization_anon_blocked,
  to_regprocedure('public.get_league_super_cup_state_v3(uuid)') is not null
    as super_cup_state_v3_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_super_cup_state_v3(uuid)',
    'EXECUTE'
  ) as super_cup_state_v3_authenticated,
  coalesce(
    pg_catalog.pg_get_functiondef(
      to_regprocedure('public.finalize_league_super_cup(uuid)')
    ) ilike '%finalize_league_super_cup_guarded_v1%',
    false
  ) as legacy_finalization_routed,
  not exists (
    select 1
    from public.league_super_cups super_cup
    where super_cup.status = 'completed'
      and not exists (
        select 1
        from public.league_super_cup_finalization_runs run
        where run.super_cup_id = super_cup.id
      )
  ) as completed_super_cups_certified,
  not exists (
    select 1
    from public.league_super_cup_finalization_runs run
    where run.source_mode = 'guarded_v1'
      and (
        run.matchday_officialization_run_id is null
        or run.home_resolution_id is null
        or run.away_resolution_id is null
        or char_length(run.officialization_result_hash) <> 32
        or char_length(run.home_resolution_hash) <> 32
        or char_length(run.away_resolution_hash) <> 32
      )
  ) as guarded_sources_ready,
  not exists (
    select 1
    from public.league_super_cup_finalization_runs run
    where run.input_hash is distinct from
      public.compute_league_super_cup_finalization_input_hash_v1(
        run.super_cup_id,
        run.schedule_result_hash,
        run.officialization_result_hash,
        run.home_resolution_hash,
        run.away_resolution_hash,
        run.home_points,
        run.away_points,
        run.home_goals,
        run.away_goals,
        run.source_mode
      )
      or run.result_hash is distinct from
        public.compute_league_super_cup_finalization_result_hash_v1(
          run.input_hash,
          run.winner_team_id,
          run.runner_up_team_id,
          run.decided_by
        )
  ) as finalization_hashes_ready,
  exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'league_super_cup_finalization_runs'
  ) as finalization_realtime_ready,
  to_regprocedure(
    'public.get_league_super_cup_finalization_integrity_v1(uuid)'
  ) is not null as finalization_diagnostics_ready;
