-- LEGHEVO v0.60.6 · Playoff Scudetto: configurazione atomica e idempotente
-- Migrazione: database/090_league_playoff_configuration_safety.sql
-- Eseguire dopo database/089_league_super_cup_finalization_safety.sql.
-- Non avvia i Playoff, non crea il tabellone e non modifica configurazioni esistenti.

begin;

-- Preflight: verifica soltanto dipendenze già validate nelle versioni precedenti.
do $block$
declare
  v_missing text[] := array[]::text[];
begin
  if to_regclass('public.leagues') is null then
    v_missing := array_append(v_missing, 'public.leagues');
  end if;
  if to_regclass('public.profiles') is null then
    v_missing := array_append(v_missing, 'public.profiles');
  end if;
  if to_regclass('public.league_playoffs') is null then
    v_missing := array_append(v_missing, 'public.league_playoffs');
  end if;
  if to_regprocedure('public.get_league_playoff_state(uuid)') is null then
    v_missing := array_append(v_missing, 'public.get_league_playoff_state(uuid)');
  end if;
  if to_regprocedure('public.is_league_member(uuid)') is null then
    v_missing := array_append(v_missing, 'public.is_league_member(uuid)');
  end if;
  if to_regprocedure('public.is_league_admin(uuid)') is null then
    v_missing := array_append(v_missing, 'public.is_league_admin(uuid)');
  end if;
  if to_regprocedure('public.leghevo_sha256_hex_v1(text)') is null then
    v_missing := array_append(v_missing, 'public.leghevo_sha256_hex_v1(text)');
  end if;
  if to_regprocedure('public.leghevo_stable_request_uuid(text)') is null then
    v_missing := array_append(v_missing, 'public.leghevo_stable_request_uuid(text)');
  end if;

  if coalesce(array_length(v_missing, 1), 0) > 0 then
    raise exception 'Dipendenze v0.60.6 mancanti: %', array_to_string(v_missing, ', ');
  end if;
end;
$block$;

create table if not exists public.league_playoff_configuration_runs (
  id bigint generated by default as identity primary key,
  league_id uuid not null
    references public.leagues(id) on delete cascade,
  playoff_id uuid not null unique
    references public.league_playoffs(id) on delete cascade,
  request_id uuid not null,
  requested_by uuid not null
    references public.profiles(id) on delete restrict,
  source_mode text not null
    check (source_mode in ('guarded_v1', 'legacy_backfill')),
  participant_count smallint not null
    check (participant_count in (4, 8)),
  round_count smallint not null
    check (round_count in (2, 3)),
  league_team_limit integer not null check (league_team_limit >= 2),
  league_status text not null,
  competition_started_at timestamptz,
  configuration_hash text not null
    check (char_length(configuration_hash) = 64),
  result_hash text not null
    check (char_length(result_hash) = 64),
  configured_at timestamptz not null default now(),
  check (
    (participant_count = 4 and round_count = 2)
    or (participant_count = 8 and round_count = 3)
  )
);

create unique index if not exists league_playoff_configuration_request_uidx
  on public.league_playoff_configuration_runs (league_id, request_id);
create unique index if not exists league_playoff_configuration_playoff_uidx
  on public.league_playoff_configuration_runs (playoff_id);
create index if not exists league_playoff_configuration_league_created_idx
  on public.league_playoff_configuration_runs (
    league_id,
    configured_at desc,
    id desc
  );

alter table public.league_playoff_configuration_runs enable row level security;

drop policy if exists league_playoff_configuration_read_members
on public.league_playoff_configuration_runs;
create policy league_playoff_configuration_read_members
on public.league_playoff_configuration_runs
for select to authenticated
using (
  public.is_league_member(league_id)
  or public.is_league_admin(league_id)
);

revoke all on table public.league_playoff_configuration_runs
from public, anon, authenticated;
grant select on table public.league_playoff_configuration_runs
to authenticated;

create or replace function public.prevent_league_playoff_configuration_run_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  raise exception
    'Registro configurazione Playoff immutabile: modifica o cancellazione diretta non consentita.';
end;
$$;

revoke all on function public.prevent_league_playoff_configuration_run_mutation()
from public, anon, authenticated;

drop trigger if exists league_playoff_configuration_runs_immutable
on public.league_playoff_configuration_runs;
create trigger league_playoff_configuration_runs_immutable
before update or delete on public.league_playoff_configuration_runs
for each row
execute function public.prevent_league_playoff_configuration_run_mutation();

create or replace function public.compute_league_playoff_configuration_hash_v1(
  p_league_id uuid,
  p_participant_count smallint,
  p_round_count smallint,
  p_league_team_limit integer,
  p_league_status text,
  p_competition_started_at timestamptz,
  p_source_mode text
)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select public.leghevo_sha256_hex_v1(
    coalesce(p_source_mode, '-') || '#'
    || coalesce(p_league_id::text, '-') || '#'
    || coalesce(p_participant_count::text, '-') || '#'
    || coalesce(p_round_count::text, '-') || '#'
    || coalesce(p_league_team_limit::text, '-') || '#'
    || coalesce(p_league_status, '-') || '#'
    || coalesce(p_competition_started_at::text, '-')
  );
$$;

revoke all on function public.compute_league_playoff_configuration_hash_v1(
  uuid, smallint, smallint, integer, text, timestamptz, text
) from public, anon, authenticated;

create or replace function public.compute_league_playoff_configuration_result_hash_v1(
  p_configuration_hash text,
  p_playoff_id uuid,
  p_requested_by uuid
)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select public.leghevo_sha256_hex_v1(
    coalesce(p_configuration_hash, '-') || '#'
    || coalesce(p_playoff_id::text, '-') || '#'
    || coalesce(p_requested_by::text, '-')
  );
$$;

revoke all on function public.compute_league_playoff_configuration_result_hash_v1(
  text, uuid, uuid
) from public, anon, authenticated;

create or replace function public.configure_league_playoffs_guarded_v1(
  p_league_id uuid,
  p_participant_count smallint,
  p_request_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_league public.leagues%rowtype;
  v_playoff public.league_playoffs%rowtype;
  v_existing_run public.league_playoff_configuration_runs%rowtype;
  v_round_count smallint;
  v_configuration_hash text;
  v_result_hash text;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if p_request_id is null then
    raise exception 'Identificativo richiesta configurazione mancante.';
  end if;

  if p_participant_count not in (4, 8) then
    raise exception 'I playoff possono includere quattro o otto squadre.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'leghevo:playoff-configuration:' || p_league_id::text,
      0
    )
  );

  select run.*
  into v_existing_run
  from public.league_playoff_configuration_runs run
  where run.league_id = p_league_id
    and run.request_id = p_request_id;

  if found then
    if v_existing_run.participant_count <> p_participant_count then
      raise exception
        'La richiesta idempotente è già associata a un formato Playoff differente.';
    end if;
    return v_existing_run.playoff_id;
  end if;

  select league.*
  into v_league
  from public.leagues league
  where league.id = p_league_id
  for update;

  if not found then
    raise exception 'Lega non trovata.';
  end if;

  if v_league.owner_id <> auth.uid() then
    raise exception 'Solo il Presidente può configurare i playoff.';
  end if;

  if v_league.status <> 'draft'
    or v_league.competition_started_at is not null then
    raise exception
      'Il formato playoff si decide prima dell''avvio del campionato.';
  end if;

  if v_league.team_limit < p_participant_count then
    raise exception
      'Il formato scelto supera il numero di squadre della lega.';
  end if;

  v_round_count := case when p_participant_count = 8 then 3 else 2 end;

  select playoff.*
  into v_playoff
  from public.league_playoffs playoff
  where playoff.league_id = p_league_id
  for update;

  if found then
    if v_playoff.participant_count <> p_participant_count
      or v_playoff.round_count <> v_round_count then
      raise exception
        'I Playoff risultano già configurati con un formato differente.';
    end if;

    select run.*
    into v_existing_run
    from public.league_playoff_configuration_runs run
    where run.playoff_id = v_playoff.id;

    if found then
      return v_playoff.id;
    end if;

    v_configuration_hash :=
      public.compute_league_playoff_configuration_hash_v1(
        p_league_id,
        v_playoff.participant_count,
        v_playoff.round_count,
        v_league.team_limit,
        v_league.status::text,
        v_league.competition_started_at,
        'legacy_backfill'
      );
    v_result_hash :=
      public.compute_league_playoff_configuration_result_hash_v1(
        v_configuration_hash,
        v_playoff.id,
        v_playoff.configured_by
      );

    insert into public.league_playoff_configuration_runs (
      league_id,
      playoff_id,
      request_id,
      requested_by,
      source_mode,
      participant_count,
      round_count,
      league_team_limit,
      league_status,
      competition_started_at,
      configuration_hash,
      result_hash,
      configured_at
    )
    values (
      p_league_id,
      v_playoff.id,
      p_request_id,
      v_playoff.configured_by,
      'legacy_backfill',
      v_playoff.participant_count,
      v_playoff.round_count,
      v_league.team_limit,
      v_league.status::text,
      v_league.competition_started_at,
      v_configuration_hash,
      v_result_hash,
      v_playoff.configured_at
    );

    return v_playoff.id;
  end if;

  insert into public.league_playoffs (
    league_id,
    status,
    participant_count,
    round_count,
    current_round,
    configured_by
  )
  values (
    p_league_id,
    'configured',
    p_participant_count,
    v_round_count,
    0,
    auth.uid()
  )
  returning * into v_playoff;

  v_configuration_hash :=
    public.compute_league_playoff_configuration_hash_v1(
      p_league_id,
      p_participant_count,
      v_round_count,
      v_league.team_limit,
      v_league.status::text,
      v_league.competition_started_at,
      'guarded_v1'
    );
  v_result_hash :=
    public.compute_league_playoff_configuration_result_hash_v1(
      v_configuration_hash,
      v_playoff.id,
      auth.uid()
    );

  insert into public.league_playoff_configuration_runs (
    league_id,
    playoff_id,
    request_id,
    requested_by,
    source_mode,
    participant_count,
    round_count,
    league_team_limit,
    league_status,
    competition_started_at,
    configuration_hash,
    result_hash,
    configured_at
  )
  values (
    p_league_id,
    v_playoff.id,
    p_request_id,
    auth.uid(),
    'guarded_v1',
    p_participant_count,
    v_round_count,
    v_league.team_limit,
    v_league.status::text,
    v_league.competition_started_at,
    v_configuration_hash,
    v_result_hash,
    v_playoff.configured_at
  );

  return v_playoff.id;
end;
$$;

revoke all on function public.configure_league_playoffs_guarded_v1(
  uuid, smallint, uuid
) from public, anon, authenticated;
grant execute on function public.configure_league_playoffs_guarded_v1(
  uuid, smallint, uuid
) to authenticated;

-- Certifica senza modificare i Playoff storici già configurati.
insert into public.league_playoff_configuration_runs (
  league_id,
  playoff_id,
  request_id,
  requested_by,
  source_mode,
  participant_count,
  round_count,
  league_team_limit,
  league_status,
  competition_started_at,
  configuration_hash,
  result_hash,
  configured_at
)
select
  playoff.league_id,
  playoff.id,
  public.leghevo_stable_request_uuid(
    'league-playoff-configuration-backfill:' || playoff.id::text
  ),
  playoff.configured_by,
  'legacy_backfill',
  playoff.participant_count,
  playoff.round_count,
  league.team_limit,
  league.status::text,
  league.competition_started_at,
  public.compute_league_playoff_configuration_hash_v1(
    playoff.league_id,
    playoff.participant_count,
    playoff.round_count,
    league.team_limit,
    league.status::text,
    league.competition_started_at,
    'legacy_backfill'
  ),
  public.compute_league_playoff_configuration_result_hash_v1(
    public.compute_league_playoff_configuration_hash_v1(
      playoff.league_id,
      playoff.participant_count,
      playoff.round_count,
      league.team_limit,
      league.status::text,
      league.competition_started_at,
      'legacy_backfill'
    ),
    playoff.id,
    playoff.configured_by
  ),
  playoff.configured_at
from public.league_playoffs playoff
join public.leagues league on league.id = playoff.league_id
where not exists (
  select 1
  from public.league_playoff_configuration_runs run
  where run.playoff_id = playoff.id
)
on conflict do nothing;

-- Mantiene compatibile l'endpoint storico instradandolo sul percorso protetto.
create or replace function public.configure_league_playoffs(
  p_league_id uuid,
  p_participant_count smallint
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
begin
  return public.configure_league_playoffs_guarded_v1(
    p_league_id,
    p_participant_count,
    public.leghevo_stable_request_uuid(
      'league-playoff-configuration-legacy:'
      || p_league_id::text || ':'
      || p_participant_count::text || ':'
      || coalesce(auth.uid()::text, '-')
    )
  );
end;
$$;

revoke all on function public.configure_league_playoffs(uuid, smallint)
from public, anon, authenticated;
grant execute on function public.configure_league_playoffs(uuid, smallint)
to authenticated;

create or replace function public.get_league_playoff_state_v2(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_state jsonb;
  v_run public.league_playoff_configuration_runs%rowtype;
begin
  v_state := public.get_league_playoff_state(p_league_id);

  select run.*
  into v_run
  from public.league_playoff_configuration_runs run
  where run.league_id = p_league_id
  order by run.configured_at desc, run.id desc
  limit 1;

  return coalesce(v_state, '{}'::jsonb) || jsonb_build_object(
    'configurationPolicy',
      case when v_run.id is null then 'legacy' else 'guarded_v1' end,
    'configurationCertified', v_run.id is not null,
    'configurationRunId', v_run.id,
    'configurationRequestId', v_run.request_id,
    'configurationSourceMode', v_run.source_mode,
    'configurationHash', v_run.configuration_hash,
    'configurationResultHash', v_run.result_hash,
    'configurationCertifiedAt', v_run.configured_at
  );
end;
$$;

revoke all on function public.get_league_playoff_state_v2(uuid)
from public, anon, authenticated;
grant execute on function public.get_league_playoff_state_v2(uuid)
to authenticated;

alter table public.league_playoff_configuration_runs replica identity full;

do $block$
begin
  if exists (
    select 1
    from pg_catalog.pg_publication publication
    where publication.pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'league_playoff_configuration_runs'
  ) then
    alter publication supabase_realtime
      add table public.league_playoff_configuration_runs;
  end if;
end;
$block$;

create or replace function public.get_league_playoff_configuration_integrity_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_playoff public.league_playoffs%rowtype;
  v_run public.league_playoff_configuration_runs%rowtype;
  v_hash_matches boolean := false;
  v_result_hash_matches boolean := false;
  v_configuration_matches boolean := false;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if not public.is_league_member(p_league_id)
    and not public.is_league_admin(p_league_id) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  select playoff.*
  into v_playoff
  from public.league_playoffs playoff
  where playoff.league_id = p_league_id;

  select run.*
  into v_run
  from public.league_playoff_configuration_runs run
  where run.league_id = p_league_id
  order by run.configured_at desc, run.id desc
  limit 1;

  if v_run.id is not null then
    v_hash_matches := v_run.configuration_hash =
      public.compute_league_playoff_configuration_hash_v1(
        v_run.league_id,
        v_run.participant_count,
        v_run.round_count,
        v_run.league_team_limit,
        v_run.league_status,
        v_run.competition_started_at,
        v_run.source_mode
      );

    v_result_hash_matches := v_run.result_hash =
      public.compute_league_playoff_configuration_result_hash_v1(
        v_run.configuration_hash,
        v_run.playoff_id,
        v_run.requested_by
      );

    v_configuration_matches := v_playoff.id = v_run.playoff_id
      and v_playoff.participant_count = v_run.participant_count
      and v_playoff.round_count = v_run.round_count;
  end if;

  return jsonb_build_object(
    'leagueId', p_league_id,
    'ready', v_playoff.id is null
      or (
        v_run.id is not null
        and v_hash_matches
        and v_result_hash_matches
        and v_configuration_matches
      ),
    'playoffExists', v_playoff.id is not null,
    'configurationCertified', v_run.id is not null,
    'configurationRunId', v_run.id,
    'sourceMode', v_run.source_mode,
    'hashMatches', v_hash_matches,
    'resultHashMatches', v_result_hash_matches,
    'configurationMatches', v_configuration_matches,
    'configurationHash', v_run.configuration_hash,
    'resultHash', v_run.result_hash
  );
end;
$$;

revoke all on function public.get_league_playoff_configuration_integrity_v1(uuid)
from public, anon, authenticated;
grant execute on function public.get_league_playoff_configuration_integrity_v1(uuid)
to authenticated;

commit;

-- Diagnostica conclusiva v0.60.6: devono risultare 20 valori true.
select
  to_regclass('public.league_playoff_configuration_runs') is not null
    as configuration_run_table_ready,
  exists (
    select 1 from pg_catalog.pg_indexes index_record
    where index_record.schemaname = 'public'
      and index_record.indexname = 'league_playoff_configuration_request_uidx'
  ) as configuration_request_unique_ready,
  exists (
    select 1 from pg_catalog.pg_indexes index_record
    where index_record.schemaname = 'public'
      and index_record.indexname = 'league_playoff_configuration_playoff_uidx'
  ) as configuration_playoff_unique_ready,
  coalesce((
    select class.relrowsecurity
    from pg_catalog.pg_class class
    join pg_catalog.pg_namespace namespace on namespace.oid = class.relnamespace
    where namespace.nspname = 'public'
      and class.relname = 'league_playoff_configuration_runs'
  ), false) as configuration_run_rls_ready,
  exists (
    select 1 from pg_catalog.pg_policies policy
    where policy.schemaname = 'public'
      and policy.tablename = 'league_playoff_configuration_runs'
      and policy.policyname = 'league_playoff_configuration_read_members'
  ) as configuration_read_policy_ready,
  exists (
    select 1
    from pg_catalog.pg_trigger trigger_record
    where trigger_record.tgrelid =
      'public.league_playoff_configuration_runs'::regclass
      and trigger_record.tgname =
        'league_playoff_configuration_runs_immutable'
      and not trigger_record.tgisinternal
  ) as configuration_immutable_trigger_ready,
  not has_table_privilege(
    'authenticated', 'public.league_playoff_configuration_runs', 'INSERT'
  ) as configuration_direct_insert_blocked,
  not has_table_privilege(
    'authenticated', 'public.league_playoff_configuration_runs', 'UPDATE'
  ) as configuration_direct_update_blocked,
  not has_table_privilege(
    'authenticated', 'public.league_playoff_configuration_runs', 'DELETE'
  ) as configuration_direct_delete_blocked,
  to_regprocedure(
    'public.configure_league_playoffs_guarded_v1(uuid,smallint,uuid)'
  ) is not null as guarded_configuration_ready,
  has_function_privilege(
    'authenticated',
    'public.configure_league_playoffs_guarded_v1(uuid,smallint,uuid)',
    'EXECUTE'
  ) as guarded_configuration_authenticated,
  not has_function_privilege(
    'anon',
    'public.configure_league_playoffs_guarded_v1(uuid,smallint,uuid)',
    'EXECUTE'
  ) as guarded_configuration_anon_blocked,
  to_regprocedure('public.get_league_playoff_state_v2(uuid)') is not null
    as playoff_state_v2_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_playoff_state_v2(uuid)',
    'EXECUTE'
  ) as playoff_state_v2_authenticated,
  coalesce(
    pg_catalog.pg_get_functiondef(
      to_regprocedure('public.configure_league_playoffs(uuid,smallint)')
    ) ilike '%configure_league_playoffs_guarded_v1%',
    false
  ) as legacy_configuration_routed,
  not exists (
    select 1
    from public.league_playoffs playoff
    where not exists (
      select 1
      from public.league_playoff_configuration_runs run
      where run.playoff_id = playoff.id
    )
  ) as existing_playoffs_certified,
  not exists (
    select 1
    from public.league_playoff_configuration_runs run
    where run.configuration_hash is distinct from
      public.compute_league_playoff_configuration_hash_v1(
        run.league_id,
        run.participant_count,
        run.round_count,
        run.league_team_limit,
        run.league_status,
        run.competition_started_at,
        run.source_mode
      )
      or run.result_hash is distinct from
      public.compute_league_playoff_configuration_result_hash_v1(
        run.configuration_hash,
        run.playoff_id,
        run.requested_by
      )
  ) as configuration_hashes_ready,
  not exists (
    select 1
    from public.league_playoff_configuration_runs run
    join public.league_playoffs playoff on playoff.id = run.playoff_id
    where playoff.league_id <> run.league_id
      or playoff.participant_count <> run.participant_count
      or playoff.round_count <> run.round_count
  ) as configuration_continuity_ready,
  exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'league_playoff_configuration_runs'
  ) as configuration_realtime_ready,
  to_regprocedure(
    'public.get_league_playoff_configuration_integrity_v1(uuid)'
  ) is not null as configuration_diagnostics_ready;
