-- LEGHEVO v0.60.7 · Playoff Scudetto: avvio protetto e tabellone certificato
-- Migrazione: database/091_league_playoff_start_safety.sql
-- Eseguire dopo database/090_league_playoff_configuration_safety.sql.
-- Non avvia automaticamente alcun Playoff e non modifica risultati già ufficiali.

begin;

-- Preflight esplicito: ogni dipendenza è verificata prima di qualsiasi modifica.
do $block$
declare
  v_missing text[] := array[]::text[];
begin
  if to_regclass('public.leagues') is null then
    v_missing := array_append(v_missing, 'public.leagues');
  end if;
  if to_regclass('public.profiles') is null then
    v_missing := array_append(v_missing, 'public.profiles');
  end if;
  if to_regclass('public.fantasy_teams') is null then
    v_missing := array_append(v_missing, 'public.fantasy_teams');
  end if;
  if to_regclass('public.fantasy_fixtures') is null then
    v_missing := array_append(v_missing, 'public.fantasy_fixtures');
  end if;
  if to_regclass('public.matchdays') is null then
    v_missing := array_append(v_missing, 'public.matchdays');
  end if;
  if to_regclass('public.matchday_progression_runs') is null then
    v_missing := array_append(v_missing, 'public.matchday_progression_runs');
  end if;
  if to_regclass('public.league_playoffs') is null then
    v_missing := array_append(v_missing, 'public.league_playoffs');
  end if;
  if to_regclass('public.league_playoff_entries') is null then
    v_missing := array_append(v_missing, 'public.league_playoff_entries');
  end if;
  if to_regclass('public.league_playoff_rounds') is null then
    v_missing := array_append(v_missing, 'public.league_playoff_rounds');
  end if;
  if to_regclass('public.league_playoff_ties') is null then
    v_missing := array_append(v_missing, 'public.league_playoff_ties');
  end if;
  if to_regclass('public.league_playoff_configuration_runs') is null then
    v_missing := array_append(v_missing, 'public.league_playoff_configuration_runs');
  end if;
  if not exists (
    select 1
    from information_schema.columns column_record
    where column_record.table_schema = 'public'
      and column_record.table_name = 'fantasy_fixtures'
      and column_record.column_name = 'officialization_run_id'
  ) then
    v_missing := array_append(
      v_missing,
      'public.fantasy_fixtures.officialization_run_id'
    );
  end if;
  if to_regprocedure('public.get_league_standings_v2(uuid)') is null then
    v_missing := array_append(v_missing, 'public.get_league_standings_v2(uuid)');
  end if;
  if to_regprocedure('public.get_league_playoff_state_v2(uuid)') is null then
    v_missing := array_append(v_missing, 'public.get_league_playoff_state_v2(uuid)');
  end if;
  if to_regprocedure('public.league_playoff_round_label(integer,integer)') is null then
    v_missing := array_append(
      v_missing,
      'public.league_playoff_round_label(integer,integer)'
    );
  end if;
  if to_regprocedure('public.leghevo_sha256_hex_v1(text)') is null then
    v_missing := array_append(v_missing, 'public.leghevo_sha256_hex_v1(text)');
  end if;
  if to_regprocedure('public.leghevo_stable_request_uuid(text)') is null then
    v_missing := array_append(
      v_missing,
      'public.leghevo_stable_request_uuid(text)'
    );
  end if;
  if to_regprocedure('public.is_league_member(uuid)') is null then
    v_missing := array_append(v_missing, 'public.is_league_member(uuid)');
  end if;
  if to_regprocedure('public.is_league_admin(uuid)') is null then
    v_missing := array_append(v_missing, 'public.is_league_admin(uuid)');
  end if;
  if to_regprocedure('public.start_league_playoffs_legacy_internal_v1(uuid,smallint)') is null
    and to_regprocedure('public.start_league_playoffs(uuid,smallint)') is null then
    v_missing := array_append(
      v_missing,
      'public.start_league_playoffs(uuid,smallint)'
    );
  end if;

  if coalesce(array_length(v_missing, 1), 0) > 0 then
    raise exception
      'Dipendenze v0.60.7 mancanti: %',
      array_to_string(v_missing, ', ');
  end if;
end;
$block$;

-- Conserva una copia interna della funzione storica esattamente come installata.
-- Il rename viene eseguito una sola volta ed evita duplicazioni del motore base.
do $block$
begin
  if to_regprocedure(
    'public.start_league_playoffs_legacy_internal_v1(uuid,smallint)'
  ) is null then
    alter function public.start_league_playoffs(uuid, smallint)
      rename to start_league_playoffs_legacy_internal_v1;
  end if;
end;
$block$;

revoke all on function public.start_league_playoffs_legacy_internal_v1(
  uuid,
  smallint
) from public, anon, authenticated;

create table if not exists public.league_playoff_start_runs (
  id bigint generated by default as identity primary key,
  league_id uuid not null
    references public.leagues(id) on delete cascade,
  playoff_id uuid not null unique
    references public.league_playoffs(id) on delete cascade,
  configuration_run_id bigint not null
    references public.league_playoff_configuration_runs(id) on delete restrict,
  request_id uuid not null,
  requested_by uuid not null
    references public.profiles(id) on delete restrict,
  source_mode text not null
    check (source_mode in ('guarded_v1', 'legacy_backfill')),
  start_matchday_number smallint not null
    check (start_matchday_number >= 1),
  participant_count smallint not null
    check (participant_count in (4, 8)),
  round_count smallint not null
    check (round_count in (2, 3)),
  regular_fixture_count integer not null check (regular_fixture_count >= 0),
  official_fixture_count integer not null check (official_fixture_count >= 0),
  qualified_team_count integer not null check (qualified_team_count >= 0),
  entry_count integer not null check (entry_count >= 0),
  round_record_count integer not null check (round_record_count >= 0),
  tie_count integer not null check (tie_count >= 0),
  qualification_source_hash text not null
    check (char_length(qualification_source_hash) = 64),
  qualification_hash text not null
    check (char_length(qualification_hash) = 64),
  schedule_hash text not null
    check (char_length(schedule_hash) = 64),
  opening_bracket_hash text not null
    check (char_length(opening_bracket_hash) = 64),
  result_hash text not null
    check (char_length(result_hash) = 64),
  started_at timestamptz not null default now(),
  check (official_fixture_count <= regular_fixture_count),
  check (qualified_team_count <= participant_count),
  check (
    (participant_count = 4 and round_count = 2)
    or (participant_count = 8 and round_count = 3)
  )
);

create unique index if not exists league_playoff_start_request_uidx
  on public.league_playoff_start_runs (league_id, request_id);
create unique index if not exists league_playoff_start_playoff_uidx
  on public.league_playoff_start_runs (playoff_id);
create index if not exists league_playoff_start_league_created_idx
  on public.league_playoff_start_runs (league_id, started_at desc, id desc);
create index if not exists league_playoff_start_configuration_idx
  on public.league_playoff_start_runs (configuration_run_id);

alter table public.league_playoff_start_runs enable row level security;

drop policy if exists league_playoff_start_read_members
on public.league_playoff_start_runs;
create policy league_playoff_start_read_members
on public.league_playoff_start_runs
for select to authenticated
using (
  public.is_league_member(league_id)
  or public.is_league_admin(league_id)
);

revoke all on table public.league_playoff_start_runs
from public, anon, authenticated;
grant select on table public.league_playoff_start_runs
to authenticated;

create or replace function public.prevent_league_playoff_start_run_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  raise exception
    'Registro avvio Playoff immutabile: modifica o cancellazione diretta non consentita.';
end;
$$;

revoke all on function public.prevent_league_playoff_start_run_mutation()
from public, anon, authenticated;

drop trigger if exists league_playoff_start_runs_immutable
on public.league_playoff_start_runs;
create trigger league_playoff_start_runs_immutable
before update or delete on public.league_playoff_start_runs
for each row
execute function public.prevent_league_playoff_start_run_mutation();

create or replace function public.compute_league_playoff_qualification_source_hash_v1(
  p_league_id uuid,
  p_participant_count smallint
)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select public.leghevo_sha256_hex_v1(
    coalesce(
      string_agg(
        standing.fantasy_team_id::text || ':'
        || standing.position::text || ':'
        || standing.position::text,
        '|' order by standing.position
      ),
      'empty'
    )
  )
  from public.get_league_standings_v2(p_league_id) standing
  where standing.position <= p_participant_count;
$$;

revoke all on function public.compute_league_playoff_qualification_source_hash_v1(
  uuid,
  smallint
) from public, anon, authenticated;

create or replace function public.compute_league_playoff_qualification_hash_v1(
  p_playoff_id uuid
)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select public.leghevo_sha256_hex_v1(
    coalesce(
      string_agg(
        entry.fantasy_team_id::text || ':'
        || entry.seed::text || ':'
        || entry.regular_season_position::text,
        '|' order by entry.seed
      ),
      'empty'
    )
  )
  from public.league_playoff_entries entry
  where entry.playoff_id = p_playoff_id;
$$;

revoke all on function public.compute_league_playoff_qualification_hash_v1(uuid)
from public, anon, authenticated;

create or replace function public.compute_league_playoff_schedule_hash_v1(
  p_playoff_id uuid
)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select public.leghevo_sha256_hex_v1(
    coalesce(
      string_agg(
        playoff_round.id::text || ':'
        || playoff_round.round_number::text || ':'
        || playoff_round.name || ':'
        || playoff_round.matchday_id::text || ':'
        || matchday.number::text,
        '|' order by playoff_round.round_number
      ),
      'empty'
    )
  )
  from public.league_playoff_rounds playoff_round
  join public.matchdays matchday on matchday.id = playoff_round.matchday_id
  where playoff_round.playoff_id = p_playoff_id;
$$;

revoke all on function public.compute_league_playoff_schedule_hash_v1(uuid)
from public, anon, authenticated;

create or replace function public.compute_league_playoff_opening_bracket_hash_v1(
  p_playoff_id uuid
)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select public.leghevo_sha256_hex_v1(
    coalesce(
      string_agg(
        playoff_round.round_number::text || ':'
        || tie.bracket_position::text || ':'
        || tie.id::text || ':'
        || case
          when playoff_round.round_number = 1
            then coalesce(tie.home_team_id::text, '-')
          else '-'
        end || ':'
        || case
          when playoff_round.round_number = 1
            then coalesce(tie.home_seed::text, '-')
          else '-'
        end || ':'
        || case
          when playoff_round.round_number = 1
            then coalesce(tie.away_team_id::text, '-')
          else '-'
        end || ':'
        || case
          when playoff_round.round_number = 1
            then coalesce(tie.away_seed::text, '-')
          else '-'
        end,
        '|' order by playoff_round.round_number, tie.bracket_position
      ),
      'empty'
    )
  )
  from public.league_playoff_ties tie
  join public.league_playoff_rounds playoff_round
    on playoff_round.id = tie.round_id
  where playoff_round.playoff_id = p_playoff_id;
$$;

revoke all on function public.compute_league_playoff_opening_bracket_hash_v1(uuid)
from public, anon, authenticated;

create or replace function public.compute_league_playoff_start_result_hash_v1(
  p_playoff_id uuid,
  p_configuration_run_id bigint,
  p_start_matchday_number smallint,
  p_participant_count smallint,
  p_round_count smallint,
  p_qualification_source_hash text,
  p_qualification_hash text,
  p_schedule_hash text,
  p_opening_bracket_hash text,
  p_started_at timestamptz
)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select public.leghevo_sha256_hex_v1(
    coalesce(p_playoff_id::text, '-') || '#'
    || coalesce(p_configuration_run_id::text, '-') || '#'
    || coalesce(p_start_matchday_number::text, '-') || '#'
    || coalesce(p_participant_count::text, '-') || '#'
    || coalesce(p_round_count::text, '-') || '#'
    || coalesce(p_qualification_source_hash, '-') || '#'
    || coalesce(p_qualification_hash, '-') || '#'
    || coalesce(p_schedule_hash, '-') || '#'
    || coalesce(p_opening_bracket_hash, '-') || '#'
    || coalesce(extract(epoch from p_started_at)::text, '-')
  );
$$;

revoke all on function public.compute_league_playoff_start_result_hash_v1(
  uuid,
  bigint,
  smallint,
  smallint,
  smallint,
  text,
  text,
  text,
  text,
  timestamptz
) from public, anon, authenticated;

create or replace function public.start_league_playoffs_guarded_v1(
  p_league_id uuid,
  p_start_matchday_number smallint,
  p_request_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_league public.leagues%rowtype;
  v_playoff public.league_playoffs%rowtype;
  v_configuration public.league_playoff_configuration_runs%rowtype;
  v_existing_run public.league_playoff_start_runs%rowtype;
  v_fixture_count integer := 0;
  v_official_fixture_count integer := 0;
  v_fixture_matchday_count integer := 0;
  v_progressed_matchday_count integer := 0;
  v_team_count integer := 0;
  v_available_matchday_count integer := 0;
  v_first_matchday_number smallint;
  v_last_matchday_number smallint;
  v_entry_count integer := 0;
  v_round_record_count integer := 0;
  v_tie_count integer := 0;
  v_qualification_source_hash text;
  v_qualification_hash text;
  v_schedule_hash text;
  v_opening_bracket_hash text;
  v_result_hash text;
  v_playoff_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if p_request_id is null then
    raise exception 'Identificativo richiesta avvio mancante.';
  end if;

  if p_start_matchday_number is null or p_start_matchday_number < 1 then
    raise exception 'Giornata di partenza dei Playoff non valida.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'leghevo:league-playoff-start:' || p_league_id::text,
      0
    )
  );

  select run.*
  into v_existing_run
  from public.league_playoff_start_runs run
  where run.league_id = p_league_id
    and run.request_id = p_request_id;

  if found then
    if v_existing_run.start_matchday_number <> p_start_matchday_number then
      raise exception
        'La richiesta idempotente è già associata a una giornata differente.';
    end if;
    return v_existing_run.playoff_id;
  end if;

  select league.*
  into v_league
  from public.leagues league
  where league.id = p_league_id
  for update;

  if not found then
    raise exception 'Lega non trovata.';
  end if;

  if v_league.owner_id <> auth.uid() then
    raise exception 'Solo il Presidente può avviare i playoff.';
  end if;

  if v_league.status <> 'active'
    or v_league.competition_started_at is null then
    raise exception 'La stagione regolare non è attiva.';
  end if;

  select playoff.*
  into v_playoff
  from public.league_playoffs playoff
  where playoff.league_id = p_league_id
  for update;

  if not found then
    raise exception 'I playoff non sono stati configurati.';
  end if;

  select configuration.*
  into v_configuration
  from public.league_playoff_configuration_runs configuration
  where configuration.playoff_id = v_playoff.id
  order by configuration.configured_at desc, configuration.id desc
  limit 1;

  if not found then
    raise exception 'La configurazione Playoff non è certificata.';
  end if;

  if v_configuration.participant_count <> v_playoff.participant_count
    or v_configuration.round_count <> v_playoff.round_count then
    raise exception
      'La configurazione certificata non coincide con il formato Playoff corrente.';
  end if;

  select run.*
  into v_existing_run
  from public.league_playoff_start_runs run
  where run.playoff_id = v_playoff.id;

  if found then
    if v_existing_run.start_matchday_number <> p_start_matchday_number then
      raise exception
        'I Playoff sono già certificati su una giornata di partenza differente.';
    end if;
    return v_existing_run.playoff_id;
  end if;

  if v_playoff.status in ('active', 'completed') then
    raise exception
      'I Playoff risultano già avviati ma manca il certificato di avvio. Esegui la migrazione di continuità.';
  end if;

  select
    count(*)::integer,
    count(*) filter (
      where fixture.finalized_at is not null
        and fixture.officialization_run_id is not null
    )::integer,
    count(distinct fixture.matchday_id)::integer
  into
    v_fixture_count,
    v_official_fixture_count,
    v_fixture_matchday_count
  from public.fantasy_fixtures fixture
  where fixture.league_id = p_league_id;

  if v_fixture_count = 0
    or v_fixture_count <> v_official_fixture_count then
    raise exception
      'La stagione regolare deve avere tutti i risultati certificati.';
  end if;

  select count(distinct progression.matchday_id)::integer
  into v_progressed_matchday_count
  from public.matchday_progression_runs progression
  where progression.league_id = p_league_id
    and progression.superseded_at is null
    and exists (
      select 1
      from public.fantasy_fixtures fixture
      where fixture.league_id = p_league_id
        and fixture.matchday_id = progression.matchday_id
    );

  if v_progressed_matchday_count <> v_fixture_matchday_count then
    raise exception
      'Manca la progressione certificata di almeno una giornata della stagione regolare.';
  end if;

  select count(*)::integer
  into v_team_count
  from public.fantasy_teams team
  where team.league_id = p_league_id;

  if v_team_count < v_playoff.participant_count then
    raise exception
      'Servono almeno % squadre per avviare i playoff.',
      v_playoff.participant_count;
  end if;

  select
    count(*)::integer,
    min(available.number)::smallint,
    max(available.number)::smallint
  into
    v_available_matchday_count,
    v_first_matchday_number,
    v_last_matchday_number
  from (
    select matchday.number
    from public.matchdays matchday
    where matchday.number >= p_start_matchday_number
      and matchday.locks_at > now()
      and (
        v_league.calendar_season is null
        or matchday.season = v_league.calendar_season
      )
    order by matchday.number
    limit v_playoff.round_count
  ) available;

  if v_available_matchday_count <> v_playoff.round_count
    or v_first_matchday_number <> p_start_matchday_number
    or v_last_matchday_number <>
      p_start_matchday_number + v_playoff.round_count - 1 then
    raise exception
      'Servono % giornate future consecutive a partire dalla giornata %.',
      v_playoff.round_count,
      p_start_matchday_number;
  end if;

  v_qualification_source_hash :=
    public.compute_league_playoff_qualification_source_hash_v1(
      p_league_id,
      v_playoff.participant_count
    );

  v_playoff_id := public.start_league_playoffs_legacy_internal_v1(
    p_league_id,
    p_start_matchday_number
  );

  select playoff.*
  into v_playoff
  from public.league_playoffs playoff
  where playoff.id = v_playoff_id
  for update;

  if not found or v_playoff.status <> 'active' or v_playoff.current_round <> 1 then
    raise exception 'L''avvio dei Playoff non ha prodotto uno stato valido.';
  end if;

  select count(*)::integer
  into v_entry_count
  from public.league_playoff_entries entry
  where entry.playoff_id = v_playoff.id;

  select count(*)::integer
  into v_round_record_count
  from public.league_playoff_rounds playoff_round
  where playoff_round.playoff_id = v_playoff.id;

  select count(*)::integer
  into v_tie_count
  from public.league_playoff_ties tie
  join public.league_playoff_rounds playoff_round
    on playoff_round.id = tie.round_id
  where playoff_round.playoff_id = v_playoff.id;

  if v_entry_count <> v_playoff.participant_count
    or v_round_record_count <> v_playoff.round_count
    or v_tie_count <> v_playoff.participant_count - 1 then
    raise exception
      'Il tabellone Playoff non contiene il numero atteso di qualificate, turni o sfide.';
  end if;

  v_qualification_hash :=
    public.compute_league_playoff_qualification_hash_v1(v_playoff.id);
  v_schedule_hash :=
    public.compute_league_playoff_schedule_hash_v1(v_playoff.id);
  v_opening_bracket_hash :=
    public.compute_league_playoff_opening_bracket_hash_v1(v_playoff.id);

  if v_qualification_source_hash <> v_qualification_hash then
    raise exception
      'Le teste di serie create non coincidono con la classifica certificata.';
  end if;

  v_result_hash := public.compute_league_playoff_start_result_hash_v1(
    v_playoff.id,
    v_configuration.id,
    p_start_matchday_number,
    v_playoff.participant_count,
    v_playoff.round_count,
    v_qualification_source_hash,
    v_qualification_hash,
    v_schedule_hash,
    v_opening_bracket_hash,
    v_playoff.started_at
  );

  insert into public.league_playoff_start_runs (
    league_id,
    playoff_id,
    configuration_run_id,
    request_id,
    requested_by,
    source_mode,
    start_matchday_number,
    participant_count,
    round_count,
    regular_fixture_count,
    official_fixture_count,
    qualified_team_count,
    entry_count,
    round_record_count,
    tie_count,
    qualification_source_hash,
    qualification_hash,
    schedule_hash,
    opening_bracket_hash,
    result_hash,
    started_at
  ) values (
    p_league_id,
    v_playoff.id,
    v_configuration.id,
    p_request_id,
    auth.uid(),
    'guarded_v1',
    p_start_matchday_number,
    v_playoff.participant_count,
    v_playoff.round_count,
    v_fixture_count,
    v_official_fixture_count,
    v_entry_count,
    v_entry_count,
    v_round_record_count,
    v_tie_count,
    v_qualification_source_hash,
    v_qualification_hash,
    v_schedule_hash,
    v_opening_bracket_hash,
    v_result_hash,
    v_playoff.started_at
  );

  return v_playoff.id;
end;
$$;

revoke all on function public.start_league_playoffs_guarded_v1(
  uuid,
  smallint,
  uuid
) from public, anon, authenticated;
grant execute on function public.start_league_playoffs_guarded_v1(
  uuid,
  smallint,
  uuid
) to authenticated;

-- Certifica senza alterazioni i Playoff storici già avviati o completati.
insert into public.league_playoff_start_runs (
  league_id,
  playoff_id,
  configuration_run_id,
  request_id,
  requested_by,
  source_mode,
  start_matchday_number,
  participant_count,
  round_count,
  regular_fixture_count,
  official_fixture_count,
  qualified_team_count,
  entry_count,
  round_record_count,
  tie_count,
  qualification_source_hash,
  qualification_hash,
  schedule_hash,
  opening_bracket_hash,
  result_hash,
  started_at
)
select
  playoff.league_id,
  playoff.id,
  configuration.id,
  public.leghevo_stable_request_uuid(
    'league-playoff-start-backfill:' || playoff.id::text
  ),
  playoff.configured_by,
  'legacy_backfill',
  schedule.start_matchday_number,
  playoff.participant_count,
  playoff.round_count,
  fixture_totals.regular_fixture_count,
  fixture_totals.official_fixture_count,
  entry_totals.entry_count,
  entry_totals.entry_count,
  round_totals.round_record_count,
  tie_totals.tie_count,
  public.compute_league_playoff_qualification_hash_v1(playoff.id),
  public.compute_league_playoff_qualification_hash_v1(playoff.id),
  public.compute_league_playoff_schedule_hash_v1(playoff.id),
  public.compute_league_playoff_opening_bracket_hash_v1(playoff.id),
  public.compute_league_playoff_start_result_hash_v1(
    playoff.id,
    configuration.id,
    schedule.start_matchday_number,
    playoff.participant_count,
    playoff.round_count,
    public.compute_league_playoff_qualification_hash_v1(playoff.id),
    public.compute_league_playoff_qualification_hash_v1(playoff.id),
    public.compute_league_playoff_schedule_hash_v1(playoff.id),
    public.compute_league_playoff_opening_bracket_hash_v1(playoff.id),
    coalesce(playoff.started_at, playoff.configured_at)
  ),
  coalesce(playoff.started_at, playoff.configured_at)
from public.league_playoffs playoff
join public.league_playoff_configuration_runs configuration
  on configuration.playoff_id = playoff.id
cross join lateral (
  select min(matchday.number)::smallint as start_matchday_number
  from public.league_playoff_rounds playoff_round
  join public.matchdays matchday on matchday.id = playoff_round.matchday_id
  where playoff_round.playoff_id = playoff.id
) schedule
cross join lateral (
  select
    count(*)::integer as regular_fixture_count,
    count(*) filter (
      where fixture.finalized_at is not null
        and fixture.officialization_run_id is not null
    )::integer as official_fixture_count
  from public.fantasy_fixtures fixture
  where fixture.league_id = playoff.league_id
) fixture_totals
cross join lateral (
  select count(*)::integer as entry_count
  from public.league_playoff_entries entry
  where entry.playoff_id = playoff.id
) entry_totals
cross join lateral (
  select count(*)::integer as round_record_count
  from public.league_playoff_rounds playoff_round
  where playoff_round.playoff_id = playoff.id
) round_totals
cross join lateral (
  select count(*)::integer as tie_count
  from public.league_playoff_ties tie
  join public.league_playoff_rounds playoff_round
    on playoff_round.id = tie.round_id
  where playoff_round.playoff_id = playoff.id
) tie_totals
where playoff.status in ('active', 'completed')
  and schedule.start_matchday_number is not null
  and not exists (
    select 1
    from public.league_playoff_start_runs run
    where run.playoff_id = playoff.id
  )
on conflict do nothing;

-- Endpoint storico instradato sul percorso protetto.
create or replace function public.start_league_playoffs(
  p_league_id uuid,
  p_start_matchday_number smallint
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
begin
  return public.start_league_playoffs_guarded_v1(
    p_league_id,
    p_start_matchday_number,
    public.leghevo_stable_request_uuid(
      'league-playoff-start-legacy:'
      || p_league_id::text || ':'
      || p_start_matchday_number::text || ':'
      || coalesce(auth.uid()::text, '-')
    )
  );
end;
$$;

revoke all on function public.start_league_playoffs(uuid, smallint)
from public, anon, authenticated;
grant execute on function public.start_league_playoffs(uuid, smallint)
to authenticated;

create or replace function public.get_league_playoff_state_v3(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_state jsonb;
  v_run public.league_playoff_start_runs%rowtype;
begin
  v_state := public.get_league_playoff_state_v2(p_league_id);

  select run.*
  into v_run
  from public.league_playoff_start_runs run
  where run.league_id = p_league_id
  order by run.started_at desc, run.id desc
  limit 1;

  return coalesce(v_state, '{}'::jsonb) || jsonb_build_object(
    'startPolicy',
      case
        when v_run.id is null then 'legacy'
        when v_run.source_mode = 'guarded_v1' then 'guarded_v1'
        else 'legacy'
      end,
    'startCertified', v_run.id is not null,
    'startRunId', v_run.id,
    'startRequestId', v_run.request_id,
    'startSourceMode', v_run.source_mode,
    'startMatchdayNumber', v_run.start_matchday_number,
    'startQualificationSourceHash', v_run.qualification_source_hash,
    'startQualificationHash', v_run.qualification_hash,
    'startScheduleHash', v_run.schedule_hash,
    'startOpeningBracketHash', v_run.opening_bracket_hash,
    'startResultHash', v_run.result_hash,
    'startCertifiedAt', v_run.started_at
  );
end;
$$;

revoke all on function public.get_league_playoff_state_v3(uuid)
from public, anon, authenticated;
grant execute on function public.get_league_playoff_state_v3(uuid)
to authenticated;

create or replace function public.get_league_playoff_start_integrity_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_playoff public.league_playoffs%rowtype;
  v_run public.league_playoff_start_runs%rowtype;
  v_qualification_hash text;
  v_schedule_hash text;
  v_opening_bracket_hash text;
  v_result_hash text;
  v_counts_match boolean := false;
  v_hashes_match boolean := false;
  v_configuration_matches boolean := false;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if not public.is_league_member(p_league_id)
    and not public.is_league_admin(p_league_id) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  select playoff.*
  into v_playoff
  from public.league_playoffs playoff
  where playoff.league_id = p_league_id;

  select run.*
  into v_run
  from public.league_playoff_start_runs run
  where run.league_id = p_league_id
  order by run.started_at desc, run.id desc
  limit 1;

  if v_run.id is not null then
    v_qualification_hash :=
      public.compute_league_playoff_qualification_hash_v1(v_run.playoff_id);
    v_schedule_hash :=
      public.compute_league_playoff_schedule_hash_v1(v_run.playoff_id);
    v_opening_bracket_hash :=
      public.compute_league_playoff_opening_bracket_hash_v1(v_run.playoff_id);
    v_result_hash := public.compute_league_playoff_start_result_hash_v1(
      v_run.playoff_id,
      v_run.configuration_run_id,
      v_run.start_matchday_number,
      v_run.participant_count,
      v_run.round_count,
      v_run.qualification_source_hash,
      v_run.qualification_hash,
      v_run.schedule_hash,
      v_run.opening_bracket_hash,
      v_run.started_at
    );

    v_counts_match :=
      v_run.entry_count = (
        select count(*)::integer
        from public.league_playoff_entries entry
        where entry.playoff_id = v_run.playoff_id
      )
      and v_run.round_record_count = (
        select count(*)::integer
        from public.league_playoff_rounds playoff_round
        where playoff_round.playoff_id = v_run.playoff_id
      )
      and v_run.tie_count = (
        select count(*)::integer
        from public.league_playoff_ties tie
        join public.league_playoff_rounds playoff_round
          on playoff_round.id = tie.round_id
        where playoff_round.playoff_id = v_run.playoff_id
      );

    v_hashes_match :=
      v_run.qualification_hash = v_qualification_hash
      and v_run.schedule_hash = v_schedule_hash
      and v_run.opening_bracket_hash = v_opening_bracket_hash
      and v_run.result_hash = v_result_hash
      and (
        v_run.source_mode = 'legacy_backfill'
        or v_run.qualification_source_hash = v_run.qualification_hash
      );

    v_configuration_matches := exists (
      select 1
      from public.league_playoff_configuration_runs configuration
      where configuration.id = v_run.configuration_run_id
        and configuration.playoff_id = v_run.playoff_id
        and configuration.participant_count = v_run.participant_count
        and configuration.round_count = v_run.round_count
    );
  end if;

  return jsonb_build_object(
    'leagueId', p_league_id,
    'ready',
      v_playoff.id is null
      or v_playoff.status = 'configured'
      or (
        v_run.id is not null
        and v_counts_match
        and v_hashes_match
        and v_configuration_matches
      ),
    'playoffExists', v_playoff.id is not null,
    'playoffStatus', v_playoff.status,
    'startCertified', v_run.id is not null,
    'startRunId', v_run.id,
    'sourceMode', v_run.source_mode,
    'configurationMatches', v_configuration_matches,
    'countsMatch', v_counts_match,
    'hashesMatch', v_hashes_match,
    'qualificationHash', v_run.qualification_hash,
    'scheduleHash', v_run.schedule_hash,
    'openingBracketHash', v_run.opening_bracket_hash,
    'resultHash', v_run.result_hash
  );
end;
$$;

revoke all on function public.get_league_playoff_start_integrity_v1(uuid)
from public, anon, authenticated;
grant execute on function public.get_league_playoff_start_integrity_v1(uuid)
to authenticated;

alter table public.league_playoff_start_runs replica identity full;

do $block$
begin
  if exists (
    select 1
    from pg_catalog.pg_publication publication
    where publication.pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'league_playoff_start_runs'
  ) then
    alter publication supabase_realtime
      add table public.league_playoff_start_runs;
  end if;
end;
$block$;

commit;

-- Diagnostica conclusiva v0.60.7: devono risultare esattamente 20 valori true.
select
  to_regclass('public.league_playoff_start_runs') is not null
    as playoff_start_run_table_ready,
  exists (
    select 1 from pg_catalog.pg_indexes index_record
    where index_record.schemaname = 'public'
      and index_record.indexname = 'league_playoff_start_request_uidx'
  ) as playoff_start_request_unique_ready,
  exists (
    select 1 from pg_catalog.pg_indexes index_record
    where index_record.schemaname = 'public'
      and index_record.indexname = 'league_playoff_start_playoff_uidx'
  ) as playoff_start_playoff_unique_ready,
  coalesce((
    select class.relrowsecurity
    from pg_catalog.pg_class class
    join pg_catalog.pg_namespace namespace on namespace.oid = class.relnamespace
    where namespace.nspname = 'public'
      and class.relname = 'league_playoff_start_runs'
  ), false) as playoff_start_rls_ready,
  exists (
    select 1 from pg_catalog.pg_policies policy
    where policy.schemaname = 'public'
      and policy.tablename = 'league_playoff_start_runs'
      and policy.policyname = 'league_playoff_start_read_members'
  ) as playoff_start_read_policy_ready,
  exists (
    select 1
    from pg_catalog.pg_trigger trigger_record
    where trigger_record.tgrelid = 'public.league_playoff_start_runs'::regclass
      and trigger_record.tgname = 'league_playoff_start_runs_immutable'
      and not trigger_record.tgisinternal
  ) as playoff_start_immutable_trigger_ready,
  not has_table_privilege(
    'authenticated', 'public.league_playoff_start_runs', 'INSERT'
  ) as playoff_start_direct_insert_blocked,
  not has_table_privilege(
    'authenticated', 'public.league_playoff_start_runs', 'UPDATE'
  ) as playoff_start_direct_update_blocked,
  not has_table_privilege(
    'authenticated', 'public.league_playoff_start_runs', 'DELETE'
  ) as playoff_start_direct_delete_blocked,
  to_regprocedure(
    'public.start_league_playoffs_guarded_v1(uuid,smallint,uuid)'
  ) is not null as guarded_playoff_start_ready,
  has_function_privilege(
    'authenticated',
    'public.start_league_playoffs_guarded_v1(uuid,smallint,uuid)',
    'EXECUTE'
  ) as guarded_playoff_start_authenticated,
  not has_function_privilege(
    'anon',
    'public.start_league_playoffs_guarded_v1(uuid,smallint,uuid)',
    'EXECUTE'
  ) as guarded_playoff_start_anon_blocked,
  to_regprocedure(
    'public.start_league_playoffs_legacy_internal_v1(uuid,smallint)'
  ) is not null as playoff_start_legacy_internal_ready,
  coalesce(
    pg_catalog.pg_get_functiondef(
      to_regprocedure('public.start_league_playoffs(uuid,smallint)')
    ) ilike '%start_league_playoffs_guarded_v1%',
    false
  ) as legacy_playoff_start_routed,
  to_regprocedure('public.get_league_playoff_state_v3(uuid)') is not null
    as playoff_state_v3_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_playoff_state_v3(uuid)',
    'EXECUTE'
  ) as playoff_state_v3_authenticated,
  to_regprocedure(
    'public.get_league_playoff_start_integrity_v1(uuid)'
  ) is not null as playoff_start_integrity_ready,
  not exists (
    select 1
    from public.league_playoffs playoff
    where playoff.status in ('active', 'completed')
      and not exists (
        select 1
        from public.league_playoff_start_runs run
        where run.playoff_id = playoff.id
      )
  ) as existing_started_playoffs_certified,
  not exists (
    select 1
    from public.league_playoff_start_runs run
    left join public.league_playoff_configuration_runs configuration
      on configuration.id = run.configuration_run_id
    where configuration.id is null
      or configuration.playoff_id <> run.playoff_id
  ) as playoff_start_configuration_chain_ready,
  exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'league_playoff_start_runs'
  ) as playoff_start_realtime_ready;
