-- LEGHEVO v0.60.8 · Playoff Scudetto: ufficializzazione protetta dei turni
-- Migrazione: database/092_league_playoff_round_finalization_safety.sql
-- Eseguire dopo database/091_league_playoff_start_safety.sql.
-- Non ufficializza automaticamente turni e non cancella risultati esistenti.

begin;

-- Preflight completo prima di qualsiasi modifica.
do $block$
declare
  v_missing text[] := array[]::text[];
begin
  if to_regclass('public.leagues') is null then
    v_missing := array_append(v_missing, 'public.leagues');
  end if;
  if to_regclass('public.profiles') is null then
    v_missing := array_append(v_missing, 'public.profiles');
  end if;
  if to_regclass('public.fantasy_teams') is null then
    v_missing := array_append(v_missing, 'public.fantasy_teams');
  end if;
  if to_regclass('public.matchdays') is null then
    v_missing := array_append(v_missing, 'public.matchdays');
  end if;
  if to_regclass('public.matchday_officialization_runs') is null then
    v_missing := array_append(v_missing, 'public.matchday_officialization_runs');
  end if;
  if to_regclass('public.league_playoffs') is null then
    v_missing := array_append(v_missing, 'public.league_playoffs');
  end if;
  if to_regclass('public.league_playoff_entries') is null then
    v_missing := array_append(v_missing, 'public.league_playoff_entries');
  end if;
  if to_regclass('public.league_playoff_rounds') is null then
    v_missing := array_append(v_missing, 'public.league_playoff_rounds');
  end if;
  if to_regclass('public.league_playoff_ties') is null then
    v_missing := array_append(v_missing, 'public.league_playoff_ties');
  end if;
  if to_regclass('public.league_playoff_start_runs') is null then
    v_missing := array_append(v_missing, 'public.league_playoff_start_runs');
  end if;
  if to_regprocedure('public.get_league_playoff_state_v3(uuid)') is null then
    v_missing := array_append(v_missing, 'public.get_league_playoff_state_v3(uuid)');
  end if;
  if to_regprocedure('public.refresh_league_playoff_round_internal(uuid,integer)') is null then
    v_missing := array_append(
      v_missing,
      'public.refresh_league_playoff_round_internal(uuid,integer)'
    );
  end if;
  if to_regprocedure('public.leghevo_sha256_hex_v1(text)') is null then
    v_missing := array_append(v_missing, 'public.leghevo_sha256_hex_v1(text)');
  end if;
  if to_regprocedure('public.leghevo_stable_request_uuid(text)') is null then
    v_missing := array_append(v_missing, 'public.leghevo_stable_request_uuid(text)');
  end if;
  if to_regprocedure('public.is_league_member(uuid)') is null then
    v_missing := array_append(v_missing, 'public.is_league_member(uuid)');
  end if;
  if to_regprocedure('public.is_league_admin(uuid)') is null then
    v_missing := array_append(v_missing, 'public.is_league_admin(uuid)');
  end if;
  if to_regprocedure(
    'public.finalize_league_playoff_round_legacy_internal_v1(uuid)'
  ) is null
    and to_regprocedure('public.finalize_league_playoff_round(uuid)') is null then
    v_missing := array_append(
      v_missing,
      'public.finalize_league_playoff_round(uuid)'
    );
  end if;

  if coalesce(array_length(v_missing, 1), 0) > 0 then
    raise exception
      'Dipendenze v0.60.8 mancanti: %',
      array_to_string(v_missing, ', ');
  end if;
end;
$block$;

-- Conserva una sola volta il motore storico, che resta invocabile soltanto
-- dal nuovo coordinatore protetto.
do $block$
begin
  if to_regprocedure(
    'public.finalize_league_playoff_round_legacy_internal_v1(uuid)'
  ) is null then
    alter function public.finalize_league_playoff_round(uuid)
      rename to finalize_league_playoff_round_legacy_internal_v1;
  end if;
end;
$block$;

revoke all on function public.finalize_league_playoff_round_legacy_internal_v1(uuid)
from public, anon, authenticated;

create table if not exists public.league_playoff_round_finalization_runs (
  id bigint generated by default as identity primary key,
  league_id uuid not null
    references public.leagues(id) on delete cascade,
  playoff_id uuid not null
    references public.league_playoffs(id) on delete cascade,
  round_id uuid not null unique
    references public.league_playoff_rounds(id) on delete cascade,
  start_run_id bigint not null
    references public.league_playoff_start_runs(id) on delete restrict,
  matchday_officialization_run_id bigint
    references public.matchday_officialization_runs(id) on delete restrict,
  request_id uuid not null,
  requested_by uuid not null
    references public.profiles(id) on delete restrict,
  requested_round_number smallint not null
    check (requested_round_number between 1 and 3),
  source_mode text not null
    check (source_mode in ('guarded_v1', 'legacy_backfill')),
  input_hash text not null check (char_length(input_hash) = 64),
  result_hash text not null check (char_length(result_hash) = 64),
  tie_count integer not null check (tie_count >= 1),
  finalized_tie_count integer not null check (finalized_tie_count >= 1),
  winner_count integer not null check (winner_count >= 1),
  next_round_number smallint check (next_round_number between 1 and 3),
  completed_playoffs boolean not null default false,
  champion_team_id uuid references public.fantasy_teams(id) on delete restrict,
  runner_up_team_id uuid references public.fantasy_teams(id) on delete restrict,
  result_payload jsonb not null default '{}'::jsonb,
  finalized_at timestamptz not null default now(),
  check (finalized_tie_count <= tie_count),
  check (winner_count <= finalized_tie_count),
  check (
    not completed_playoffs
    or (
      champion_team_id is not null
      and runner_up_team_id is not null
      and champion_team_id <> runner_up_team_id
    )
  )
);

create unique index if not exists league_playoff_round_request_uidx
  on public.league_playoff_round_finalization_runs (league_id, request_id);
create unique index if not exists league_playoff_round_round_uidx
  on public.league_playoff_round_finalization_runs (round_id);
create index if not exists league_playoff_round_playoff_idx
  on public.league_playoff_round_finalization_runs (
    playoff_id,
    requested_round_number,
    finalized_at desc
  );
create index if not exists league_playoff_round_officialization_idx
  on public.league_playoff_round_finalization_runs (
    matchday_officialization_run_id
  ) where matchday_officialization_run_id is not null;

alter table public.league_playoff_round_finalization_runs
  enable row level security;

drop policy if exists league_playoff_round_runs_read_members
on public.league_playoff_round_finalization_runs;
create policy league_playoff_round_runs_read_members
on public.league_playoff_round_finalization_runs
for select to authenticated
using (
  public.is_league_member(league_id)
  or public.is_league_admin(league_id)
);

revoke all on table public.league_playoff_round_finalization_runs
from public, anon, authenticated;
grant select on table public.league_playoff_round_finalization_runs
to authenticated;

create or replace function public.prevent_league_playoff_round_run_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  raise exception
    'Registro ufficializzazione Playoff immutabile: modifica o cancellazione diretta non consentita.';
end;
$$;

revoke all on function public.prevent_league_playoff_round_run_mutation()
from public, anon, authenticated;

drop trigger if exists league_playoff_round_runs_immutable
on public.league_playoff_round_finalization_runs;
create trigger league_playoff_round_runs_immutable
before update or delete on public.league_playoff_round_finalization_runs
for each row
execute function public.prevent_league_playoff_round_run_mutation();

create or replace function public.compute_league_playoff_round_input_hash_v1(
  p_playoff_id uuid,
  p_round_number smallint,
  p_matchday_officialization_run_id bigint
)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select public.leghevo_sha256_hex_v1(
    coalesce(
      (
        select string_agg(
          tie.id::text || ':'
          || tie.bracket_position::text || ':'
          || coalesce(tie.home_team_id::text, '-') || ':'
          || coalesce(tie.away_team_id::text, '-') || ':'
          || coalesce(tie.home_seed::text, '-') || ':'
          || coalesce(tie.away_seed::text, '-') || ':'
          || coalesce(tie.home_points::text, '-') || ':'
          || coalesce(tie.away_points::text, '-') || ':'
          || coalesce(tie.home_goals::text, '-') || ':'
          || coalesce(tie.away_goals::text, '-') || ':'
          || tie.home_ready::text || ':'
          || tie.away_ready::text || ':'
          || tie.home_counted_players::text || ':'
          || tie.away_counted_players::text,
          '|' order by tie.bracket_position
        )
        from public.league_playoff_ties tie
        join public.league_playoff_rounds playoff_round
          on playoff_round.id = tie.round_id
        where playoff_round.playoff_id = p_playoff_id
          and playoff_round.round_number = p_round_number
      ),
      'empty'
    ) || '#'
    || coalesce(
      (
        select officialization.id::text || ':'
          || officialization.finalization_revision::text || ':'
          || officialization.input_hash || ':'
          || officialization.result_hash || ':'
          || officialization.fixture_count::text || ':'
          || officialization.finalized_fixture_count::text
        from public.matchday_officialization_runs officialization
        where officialization.id = p_matchday_officialization_run_id
      ),
      'legacy-no-officialization'
    )
  );
$$;

revoke all on function public.compute_league_playoff_round_input_hash_v1(
  uuid,
  smallint,
  bigint
) from public, anon, authenticated;

create or replace function public.compute_league_playoff_round_result_hash_v1(
  p_playoff_id uuid,
  p_round_number smallint
)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select public.leghevo_sha256_hex_v1(
    coalesce(
      (
        select playoff_round.id::text || ':'
          || playoff_round.status || ':'
          || coalesce(
            extract(epoch from playoff_round.finalized_at)::text,
            '-'
          ) || ':'
          || coalesce(playoff_round.finalized_by::text, '-')
        from public.league_playoff_rounds playoff_round
        where playoff_round.playoff_id = p_playoff_id
          and playoff_round.round_number = p_round_number
      ),
      'missing-round'
    ) || '#'
    || coalesce(
      (
        select string_agg(
          tie.id::text || ':'
          || tie.bracket_position::text || ':'
          || coalesce(tie.winner_team_id::text, '-') || ':'
          || coalesce(tie.decided_by, '-') || ':'
          || coalesce(
            extract(epoch from tie.finalized_at)::text,
            '-'
          ),
          '|' order by tie.bracket_position
        )
        from public.league_playoff_ties tie
        join public.league_playoff_rounds playoff_round
          on playoff_round.id = tie.round_id
        where playoff_round.playoff_id = p_playoff_id
          and playoff_round.round_number = p_round_number
      ),
      'empty'
    ) || '#'
    || coalesce(
      (
        select string_agg(
          tie.bracket_position::text || ':'
          || coalesce(tie.home_team_id::text, '-') || ':'
          || coalesce(tie.home_seed::text, '-') || ':'
          || coalesce(tie.away_team_id::text, '-') || ':'
          || coalesce(tie.away_seed::text, '-'),
          '|' order by tie.bracket_position
        )
        from public.league_playoff_ties tie
        join public.league_playoff_rounds playoff_round
          on playoff_round.id = tie.round_id
        where playoff_round.playoff_id = p_playoff_id
          and playoff_round.round_number = p_round_number + 1
      ),
      'no-next-round'
    ) || '#'
    || coalesce(
      (
        select case
          when p_round_number = playoff.round_count then
            playoff.status || ':'
            || coalesce(playoff.champion_team_id::text, '-') || ':'
            || coalesce(playoff.runner_up_team_id::text, '-') || ':'
            || coalesce(
              extract(epoch from playoff.completed_at)::text,
              '-'
            )
          else 'round-advanced'
        end
        from public.league_playoffs playoff
        where playoff.id = p_playoff_id
      ),
      'missing-playoff'
    )
  );
$$;

revoke all on function public.compute_league_playoff_round_result_hash_v1(
  uuid,
  smallint
) from public, anon, authenticated;

create or replace function public.get_league_playoff_state_v4(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_state jsonb;
  v_playoff public.league_playoffs%rowtype;
  v_latest_run public.league_playoff_round_finalization_runs%rowtype;
  v_official_round_count integer := 0;
  v_certified_round_count integer := 0;
  v_current_officialization_ready boolean := false;
  v_rounds_certified boolean := false;
begin
  v_state := public.get_league_playoff_state_v3(p_league_id);

  select playoff.*
  into v_playoff
  from public.league_playoffs playoff
  where playoff.league_id = p_league_id;

  if v_playoff.id is not null then
    select count(*)::integer
    into v_official_round_count
    from public.league_playoff_rounds playoff_round
    where playoff_round.playoff_id = v_playoff.id
      and playoff_round.status = 'official';

    select count(*)::integer
    into v_certified_round_count
    from public.league_playoff_round_finalization_runs run
    where run.playoff_id = v_playoff.id;

    select run.*
    into v_latest_run
    from public.league_playoff_round_finalization_runs run
    where run.playoff_id = v_playoff.id
    order by run.requested_round_number desc, run.id desc
    limit 1;

    v_rounds_certified :=
      v_official_round_count = v_certified_round_count;

    if v_playoff.status = 'active' then
      select exists (
        select 1
        from public.league_playoff_rounds playoff_round
        join public.matchday_officialization_runs officialization
          on officialization.matchday_id = playoff_round.matchday_id
          and officialization.league_id = p_league_id
          and officialization.superseded_at is null
        where playoff_round.playoff_id = v_playoff.id
          and playoff_round.round_number = v_playoff.current_round
      ) into v_current_officialization_ready;
    end if;
  end if;

  return coalesce(v_state, '{}'::jsonb) || jsonb_build_object(
    'roundFinalizationPolicy', 'guarded_v1',
    'officialRoundCount', v_official_round_count,
    'certifiedRoundCount', v_certified_round_count,
    'roundsCertified', v_rounds_certified,
    'currentRoundOfficializationReady', v_current_officialization_ready,
    'canFinalizeCurrent',
      coalesce((v_state ->> 'canFinalizeCurrent')::boolean, false)
      and v_current_officialization_ready,
    'lastRoundRunId', v_latest_run.id,
    'lastCertifiedRound', v_latest_run.requested_round_number,
    'lastRoundFinalizedAt', v_latest_run.finalized_at
  );
end;
$$;

revoke all on function public.get_league_playoff_state_v4(uuid)
from public, anon, authenticated;
grant execute on function public.get_league_playoff_state_v4(uuid)
to authenticated;

create or replace function public.finalize_league_playoff_round_guarded_v1(
  p_league_id uuid,
  p_round_number smallint,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_league public.leagues%rowtype;
  v_playoff public.league_playoffs%rowtype;
  v_round public.league_playoff_rounds%rowtype;
  v_start_run public.league_playoff_start_runs%rowtype;
  v_officialization public.matchday_officialization_runs%rowtype;
  v_existing_run public.league_playoff_round_finalization_runs%rowtype;
  v_tie_count integer := 0;
  v_unready_count integer := 0;
  v_finalized_tie_count integer := 0;
  v_winner_count integer := 0;
  v_next_round_number smallint;
  v_input_hash text;
  v_result_hash text;
  v_state jsonb;
  v_completed boolean := false;
  v_payload jsonb;
  v_run_id bigint;
  v_playoff_id uuid;
  v_round_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if p_request_id is null then
    raise exception 'Identificativo richiesta ufficializzazione mancante.';
  end if;

  if p_round_number is null or p_round_number < 1 then
    raise exception 'Turno Playoff non valido.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'leghevo:league-playoff-round-finalization:' || p_league_id::text,
      0
    )
  );

  select run.*
  into v_existing_run
  from public.league_playoff_round_finalization_runs run
  where run.league_id = p_league_id
    and run.request_id = p_request_id;

  if found then
    if v_existing_run.requested_round_number <> p_round_number then
      raise exception
        'La richiesta idempotente è già associata a un turno differente.';
    end if;

    return public.get_league_playoff_state_v4(p_league_id)
      || jsonb_build_object(
        'idempotentReplay', true,
        'roundFinalizationRunId', v_existing_run.id
      );
  end if;

  select league.*
  into v_league
  from public.leagues league
  where league.id = p_league_id
  for update;

  if not found then
    raise exception 'Lega non trovata.';
  end if;

  if v_league.owner_id <> auth.uid() then
    raise exception 'Solo il Presidente può ufficializzare i playoff.';
  end if;

  select playoff.*
  into v_playoff
  from public.league_playoffs playoff
  where playoff.league_id = p_league_id
  for update;

  if not found or v_playoff.status = 'configured' then
    raise exception 'I playoff non sono ancora iniziati.';
  end if;

  v_playoff_id := v_playoff.id;

  if p_round_number > v_playoff.round_count then
    raise exception 'Il turno richiesto supera il numero di turni configurati.';
  end if;

  select playoff_round.*
  into v_round
  from public.league_playoff_rounds playoff_round
  where playoff_round.playoff_id = v_playoff.id
    and playoff_round.round_number = p_round_number
  for update;

  if not found then
    raise exception 'Turno Playoff non trovato.';
  end if;

  v_round_id := v_round.id;

  select run.*
  into v_existing_run
  from public.league_playoff_round_finalization_runs run
  where run.round_id = v_round.id;

  if found then
    return public.get_league_playoff_state_v4(p_league_id)
      || jsonb_build_object(
        'idempotentReplay', true,
        'roundFinalizationRunId', v_existing_run.id
      );
  end if;

  if v_playoff.status = 'completed' then
    raise exception
      'I Playoff risultano conclusi ma manca il certificato del turno finale.';
  end if;

  if p_round_number <> v_playoff.current_round then
    raise exception 'Il turno richiesto non è quello corrente dei Playoff.';
  end if;

  select run.*
  into v_start_run
  from public.league_playoff_start_runs run
  where run.playoff_id = v_playoff.id;

  if not found then
    raise exception 'L''avvio dei Playoff non è certificato.';
  end if;

  select officialization.*
  into v_officialization
  from public.matchday_officialization_runs officialization
  where officialization.league_id = p_league_id
    and officialization.matchday_id = v_round.matchday_id
    and officialization.superseded_at is null;

  if not found then
    raise exception
      'Prima di ufficializzare i Playoff devi ufficializzare la giornata di campionato.';
  end if;

  perform public.refresh_league_playoff_round_internal(
    v_playoff.id,
    p_round_number
  );

  select
    count(*)::integer,
    count(*) filter (
      where tie.home_team_id is null
        or tie.away_team_id is null
        or not tie.home_ready
        or not tie.away_ready
        or tie.home_points is null
        or tie.away_points is null
        or tie.home_goals is null
        or tie.away_goals is null
    )::integer
  into v_tie_count, v_unready_count
  from public.league_playoff_ties tie
  where tie.round_id = v_round.id;

  if v_tie_count < 1 then
    raise exception 'Il turno Playoff non contiene sfide.';
  end if;

  if v_unready_count > 0 then
    raise exception
      'Mancano ancora voti definitivi per % sfide.',
      v_unready_count;
  end if;

  v_input_hash := public.compute_league_playoff_round_input_hash_v1(
    v_playoff.id,
    p_round_number,
    v_officialization.id
  );

  if v_input_hash is null or char_length(v_input_hash) <> 64 then
    raise exception 'Impossibile certificare la sorgente del turno Playoff.';
  end if;

  perform public.finalize_league_playoff_round_legacy_internal_v1(
    p_league_id
  );

  select playoff.*
  into v_playoff
  from public.league_playoffs playoff
  where playoff.id = v_playoff_id;

  select playoff_round.*
  into v_round
  from public.league_playoff_rounds playoff_round
  where playoff_round.id = v_round_id;

  select
    count(*) filter (where tie.finalized_at is not null)::integer,
    count(*) filter (where tie.winner_team_id is not null)::integer
  into v_finalized_tie_count, v_winner_count
  from public.league_playoff_ties tie
  where tie.round_id = v_round.id;

  if v_round.status <> 'official'
    or v_round.finalized_at is null
    or v_finalized_tie_count <> v_tie_count
    or v_winner_count <> v_tie_count then
    raise exception
      'L''ufficializzazione Playoff non ha prodotto un esito completo.';
  end if;

  if p_round_number = v_playoff.round_count then
    v_completed := true;
    v_next_round_number := null;

    if v_playoff.status <> 'completed'
      or v_playoff.champion_team_id is null
      or v_playoff.runner_up_team_id is null then
      raise exception 'La finale Playoff non ha prodotto un podio valido.';
    end if;
  else
    v_next_round_number := p_round_number + 1;

    if v_playoff.status <> 'active'
      or v_playoff.current_round <> v_next_round_number then
      raise exception 'Il tabellone non è avanzato al turno successivo.';
    end if;

    if exists (
      select 1
      from public.league_playoff_ties tie
      join public.league_playoff_rounds playoff_round
        on playoff_round.id = tie.round_id
      where playoff_round.playoff_id = v_playoff.id
        and playoff_round.round_number = v_next_round_number
        and (tie.home_team_id is null or tie.away_team_id is null)
    ) then
      raise exception 'Il turno successivo non contiene tutti i qualificati.';
    end if;
  end if;

  v_result_hash := public.compute_league_playoff_round_result_hash_v1(
    v_playoff.id,
    p_round_number
  );

  if v_result_hash is null or char_length(v_result_hash) <> 64 then
    raise exception 'Impossibile certificare l''esito del turno Playoff.';
  end if;

  v_payload := jsonb_build_object(
    'playoffId', v_playoff.id,
    'roundId', v_round.id,
    'roundNumber', p_round_number,
    'matchdayId', v_round.matchday_id,
    'matchdayOfficializationRunId', v_officialization.id,
    'tieCount', v_tie_count,
    'winnerCount', v_winner_count,
    'completedPlayoffs', v_completed,
    'nextRoundNumber', v_next_round_number,
    'championTeamId', v_playoff.champion_team_id,
    'runnerUpTeamId', v_playoff.runner_up_team_id
  );

  insert into public.league_playoff_round_finalization_runs (
    league_id,
    playoff_id,
    round_id,
    start_run_id,
    matchday_officialization_run_id,
    request_id,
    requested_by,
    requested_round_number,
    source_mode,
    input_hash,
    result_hash,
    tie_count,
    finalized_tie_count,
    winner_count,
    next_round_number,
    completed_playoffs,
    champion_team_id,
    runner_up_team_id,
    result_payload,
    finalized_at
  ) values (
    p_league_id,
    v_playoff.id,
    v_round.id,
    v_start_run.id,
    v_officialization.id,
    p_request_id,
    auth.uid(),
    p_round_number,
    'guarded_v1',
    v_input_hash,
    v_result_hash,
    v_tie_count,
    v_finalized_tie_count,
    v_winner_count,
    v_next_round_number,
    v_completed,
    v_playoff.champion_team_id,
    v_playoff.runner_up_team_id,
    v_payload,
    coalesce(v_round.finalized_at, now())
  ) returning id into v_run_id;

  v_state := public.get_league_playoff_state_v4(p_league_id);

  return v_state || jsonb_build_object(
    'idempotentReplay', false,
    'roundFinalizationRunId', v_run_id
  );
end;
$$;

revoke all on function public.finalize_league_playoff_round_guarded_v1(
  uuid,
  smallint,
  uuid
) from public, anon, authenticated;
grant execute on function public.finalize_league_playoff_round_guarded_v1(
  uuid,
  smallint,
  uuid
) to authenticated;

-- Compatibilità: il vecchio endpoint usa una richiesta stabile per turno.
create or replace function public.finalize_league_playoff_round(
  p_league_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_playoff public.league_playoffs%rowtype;
  v_request_id uuid;
begin
  select playoff.*
  into v_playoff
  from public.league_playoffs playoff
  where playoff.league_id = p_league_id;

  if not found then
    raise exception 'I playoff non sono stati configurati.';
  end if;

  v_request_id := public.leghevo_stable_request_uuid(
    'league-playoff-round-finalize:'
    || p_league_id::text || ':'
    || v_playoff.id::text || ':'
    || v_playoff.current_round::text
  );

  return public.finalize_league_playoff_round_guarded_v1(
    p_league_id,
    v_playoff.current_round,
    v_request_id
  );
end;
$$;

revoke all on function public.finalize_league_playoff_round(uuid)
from public, anon, authenticated;
grant execute on function public.finalize_league_playoff_round(uuid)
to authenticated;

-- Backfill non distruttivo dei turni già ufficiali.
insert into public.league_playoff_round_finalization_runs (
  league_id,
  playoff_id,
  round_id,
  start_run_id,
  matchday_officialization_run_id,
  request_id,
  requested_by,
  requested_round_number,
  source_mode,
  input_hash,
  result_hash,
  tie_count,
  finalized_tie_count,
  winner_count,
  next_round_number,
  completed_playoffs,
  champion_team_id,
  runner_up_team_id,
  result_payload,
  finalized_at
)
select
  playoff.league_id,
  playoff.id,
  playoff_round.id,
  start_run.id,
  officialization.id,
  public.leghevo_stable_request_uuid(
    'league-playoff-round-legacy:' || playoff_round.id::text
  ),
  coalesce(playoff_round.finalized_by, playoff.configured_by),
  playoff_round.round_number,
  'legacy_backfill',
  public.compute_league_playoff_round_input_hash_v1(
    playoff.id,
    playoff_round.round_number,
    officialization.id
  ),
  public.compute_league_playoff_round_result_hash_v1(
    playoff.id,
    playoff_round.round_number
  ),
  tie_counts.tie_count,
  tie_counts.finalized_tie_count,
  tie_counts.winner_count,
  case
    when playoff_round.round_number < playoff.round_count
      then playoff_round.round_number + 1
    else null
  end,
  playoff_round.round_number = playoff.round_count
    and playoff.status = 'completed',
  case
    when playoff_round.round_number = playoff.round_count
      then playoff.champion_team_id
    else null
  end,
  case
    when playoff_round.round_number = playoff.round_count
      then playoff.runner_up_team_id
    else null
  end,
  jsonb_build_object(
    'playoffId', playoff.id,
    'roundId', playoff_round.id,
    'roundNumber', playoff_round.round_number,
    'legacyBackfill', true,
    'matchdayOfficializationRunId', officialization.id
  ),
  coalesce(playoff_round.finalized_at, playoff.completed_at, now())
from public.league_playoffs playoff
join public.league_playoff_rounds playoff_round
  on playoff_round.playoff_id = playoff.id
join public.league_playoff_start_runs start_run
  on start_run.playoff_id = playoff.id
cross join lateral (
  select
    count(*)::integer as tie_count,
    count(*) filter (where tie.finalized_at is not null)::integer
      as finalized_tie_count,
    count(*) filter (where tie.winner_team_id is not null)::integer
      as winner_count
  from public.league_playoff_ties tie
  where tie.round_id = playoff_round.id
) tie_counts
left join lateral (
  select officialization_run.*
  from public.matchday_officialization_runs officialization_run
  where officialization_run.league_id = playoff.league_id
    and officialization_run.matchday_id = playoff_round.matchday_id
    and officialization_run.superseded_at is null
  order by officialization_run.finalization_revision desc
  limit 1
) officialization on true
where playoff_round.status = 'official'
  and tie_counts.tie_count >= 1
  and tie_counts.finalized_tie_count = tie_counts.tie_count
  and tie_counts.winner_count = tie_counts.tie_count
  and not exists (
    select 1
    from public.league_playoff_round_finalization_runs existing_run
    where existing_run.round_id = playoff_round.id
  );

create or replace function public.get_league_playoff_round_integrity_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_playoff public.league_playoffs%rowtype;
  v_official_round_count integer := 0;
  v_certified_round_count integer := 0;
  v_hash_mismatch_count integer := 0;
  v_source_mismatch_count integer := 0;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;

  if not public.is_league_member(p_league_id)
    and not public.is_league_admin(p_league_id) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  select playoff.*
  into v_playoff
  from public.league_playoffs playoff
  where playoff.league_id = p_league_id;

  if v_playoff.id is not null then
    select count(*)::integer
    into v_official_round_count
    from public.league_playoff_rounds playoff_round
    where playoff_round.playoff_id = v_playoff.id
      and playoff_round.status = 'official';

    select count(*)::integer
    into v_certified_round_count
    from public.league_playoff_round_finalization_runs run
    where run.playoff_id = v_playoff.id;

    select count(*)::integer
    into v_hash_mismatch_count
    from public.league_playoff_round_finalization_runs run
    where run.playoff_id = v_playoff.id
      and (
        run.input_hash <> public.compute_league_playoff_round_input_hash_v1(
          run.playoff_id,
          run.requested_round_number,
          run.matchday_officialization_run_id
        )
        or run.result_hash <> public.compute_league_playoff_round_result_hash_v1(
          run.playoff_id,
          run.requested_round_number
        )
      );

    select count(*)::integer
    into v_source_mismatch_count
    from public.league_playoff_round_finalization_runs run
    join public.league_playoff_rounds playoff_round
      on playoff_round.id = run.round_id
    where run.playoff_id = v_playoff.id
      and (
        playoff_round.playoff_id <> run.playoff_id
        or playoff_round.round_number <> run.requested_round_number
        or not exists (
          select 1
          from public.league_playoff_start_runs start_run
          where start_run.id = run.start_run_id
            and start_run.playoff_id = run.playoff_id
        )
        or (
          run.source_mode = 'guarded_v1'
          and not exists (
            select 1
            from public.matchday_officialization_runs officialization
            where officialization.id = run.matchday_officialization_run_id
              and officialization.league_id = run.league_id
              and officialization.matchday_id = playoff_round.matchday_id
          )
        )
      );
  end if;

  return jsonb_build_object(
    'leagueId', p_league_id,
    'ready',
      v_playoff.id is null
      or v_playoff.status = 'configured'
      or (
        v_official_round_count = v_certified_round_count
        and v_hash_mismatch_count = 0
        and v_source_mismatch_count = 0
      ),
    'playoffExists', v_playoff.id is not null,
    'playoffStatus', v_playoff.status,
    'officialRoundCount', v_official_round_count,
    'certifiedRoundCount', v_certified_round_count,
    'hashMismatchCount', v_hash_mismatch_count,
    'sourceMismatchCount', v_source_mismatch_count
  );
end;
$$;

revoke all on function public.get_league_playoff_round_integrity_v1(uuid)
from public, anon, authenticated;
grant execute on function public.get_league_playoff_round_integrity_v1(uuid)
to authenticated;

alter table public.league_playoff_round_finalization_runs
  replica identity full;

do $block$
begin
  if exists (
    select 1
    from pg_catalog.pg_publication publication
    where publication.pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'league_playoff_round_finalization_runs'
  ) then
    alter publication supabase_realtime
      add table public.league_playoff_round_finalization_runs;
  end if;
end;
$block$;

commit;

-- Diagnostica conclusiva v0.60.8: devono risultare esattamente 20 valori true.
select
  to_regclass('public.league_playoff_round_finalization_runs') is not null
    as playoff_round_run_table_ready,
  exists (
    select 1
    from pg_catalog.pg_indexes index_record
    where index_record.schemaname = 'public'
      and index_record.indexname = 'league_playoff_round_request_uidx'
  ) as playoff_round_request_unique_ready,
  exists (
    select 1
    from pg_catalog.pg_indexes index_record
    where index_record.schemaname = 'public'
      and index_record.indexname = 'league_playoff_round_round_uidx'
  ) as playoff_round_unique_ready,
  coalesce((
    select class.relrowsecurity
    from pg_catalog.pg_class class
    join pg_catalog.pg_namespace namespace
      on namespace.oid = class.relnamespace
    where namespace.nspname = 'public'
      and class.relname = 'league_playoff_round_finalization_runs'
  ), false) as playoff_round_rls_ready,
  exists (
    select 1
    from pg_catalog.pg_policies policy
    where policy.schemaname = 'public'
      and policy.tablename = 'league_playoff_round_finalization_runs'
      and policy.policyname = 'league_playoff_round_runs_read_members'
  ) as playoff_round_read_policy_ready,
  to_regprocedure('public.prevent_league_playoff_round_run_mutation()')
    is not null as playoff_round_immutability_function_ready,
  exists (
    select 1
    from pg_catalog.pg_trigger trigger_record
    where trigger_record.tgrelid =
      'public.league_playoff_round_finalization_runs'::regclass
      and trigger_record.tgname = 'league_playoff_round_runs_immutable'
      and not trigger_record.tgisinternal
  ) as playoff_round_immutability_trigger_ready,
  to_regprocedure(
    'public.compute_league_playoff_round_input_hash_v1(uuid,smallint,bigint)'
  ) is not null as playoff_round_input_hash_ready,
  to_regprocedure(
    'public.compute_league_playoff_round_result_hash_v1(uuid,smallint)'
  ) is not null as playoff_round_result_hash_ready,
  to_regprocedure(
    'public.finalize_league_playoff_round_guarded_v1(uuid,smallint,uuid)'
  ) is not null as playoff_round_guarded_rpc_ready,
  to_regprocedure('public.finalize_league_playoff_round(uuid)') is not null
    as playoff_round_compatibility_rpc_ready,
  to_regprocedure(
    'public.finalize_league_playoff_round_legacy_internal_v1(uuid)'
  ) is not null as playoff_round_legacy_internal_ready,
  to_regprocedure('public.get_league_playoff_state_v4(uuid)') is not null
    as playoff_state_v4_ready,
  to_regprocedure('public.get_league_playoff_round_integrity_v1(uuid)')
    is not null as playoff_round_integrity_rpc_ready,
  has_function_privilege(
    'authenticated',
    'public.finalize_league_playoff_round_guarded_v1(uuid,smallint,uuid)',
    'EXECUTE'
  ) as playoff_round_guarded_authenticated_ready,
  not has_function_privilege(
    'anon',
    'public.finalize_league_playoff_round_guarded_v1(uuid,smallint,uuid)',
    'EXECUTE'
  ) as playoff_round_guarded_anon_blocked,
  not has_table_privilege(
    'authenticated',
    'public.league_playoff_round_finalization_runs',
    'INSERT'
  ) as playoff_round_direct_insert_blocked,
  coalesce((
    select class.relreplident = 'f'
    from pg_catalog.pg_class class
    join pg_catalog.pg_namespace namespace
      on namespace.oid = class.relnamespace
    where namespace.nspname = 'public'
      and class.relname = 'league_playoff_round_finalization_runs'
  ), false) as playoff_round_replica_identity_ready,
  (
    not exists (
      select 1
      from pg_catalog.pg_publication publication
      where publication.pubname = 'supabase_realtime'
    )
    or exists (
      select 1
      from pg_catalog.pg_publication_tables publication_table
      where publication_table.pubname = 'supabase_realtime'
        and publication_table.schemaname = 'public'
        and publication_table.tablename =
          'league_playoff_round_finalization_runs'
    )
  ) as playoff_round_realtime_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_playoff_state_v4(uuid)',
    'EXECUTE'
  ) as playoff_state_v4_authenticated_ready;
