-- LEGHEVO v0.60.9 · Playoff Scudetto: certificazione protetta della conclusione
-- Migrazione: database/093_league_playoff_completion_certification.sql
-- Eseguire dopo database/092_league_playoff_round_finalization_safety.sql.
-- Script idempotente: non crea Playoff, non cambia vincitori e non cancella dati.

begin;

-- Preflight esplicito: la migrazione non presume in silenzio le dipendenze.
do $block$
declare
  v_missing text[] := array[]::text[];
  v_dependency record;
begin
  if to_regclass('public.league_playoffs') is null then
    v_missing := array_append(v_missing, 'public.league_playoffs');
  end if;
  if to_regclass('public.league_playoff_rounds') is null then
    v_missing := array_append(v_missing, 'public.league_playoff_rounds');
  end if;
  if to_regclass('public.league_playoff_ties') is null then
    v_missing := array_append(v_missing, 'public.league_playoff_ties');
  end if;
  if to_regclass('public.league_playoff_entries') is null then
    v_missing := array_append(v_missing, 'public.league_playoff_entries');
  end if;
  if to_regclass('public.league_playoff_round_finalization_runs') is null then
    v_missing := array_append(v_missing, 'public.league_playoff_round_finalization_runs');
  end if;
  if to_regprocedure('public.leghevo_sha256_hex_v1(text)') is null then
    v_missing := array_append(v_missing, 'public.leghevo_sha256_hex_v1(text)');
  end if;
  if to_regprocedure('public.compute_league_playoff_round_result_hash_v1(uuid,smallint)') is null then
    v_missing := array_append(v_missing, 'public.compute_league_playoff_round_result_hash_v1(uuid,smallint)');
  end if;
  if to_regprocedure('public.get_league_playoff_state_v4(uuid)') is null then
    v_missing := array_append(v_missing, 'public.get_league_playoff_state_v4(uuid)');
  end if;

  for v_dependency in
    select *
    from (values
      ('league_playoffs', 'league_id'),
      ('league_playoffs', 'status'),
      ('league_playoffs', 'participant_count'),
      ('league_playoffs', 'round_count'),
      ('league_playoffs', 'current_round'),
      ('league_playoffs', 'champion_team_id'),
      ('league_playoffs', 'runner_up_team_id'),
      ('league_playoffs', 'completed_at'),
      ('league_playoff_rounds', 'playoff_id'),
      ('league_playoff_rounds', 'round_number'),
      ('league_playoff_rounds', 'status'),
      ('league_playoff_rounds', 'finalized_at'),
      ('league_playoff_ties', 'round_id'),
      ('league_playoff_ties', 'bracket_position'),
      ('league_playoff_ties', 'home_team_id'),
      ('league_playoff_ties', 'away_team_id'),
      ('league_playoff_ties', 'home_points'),
      ('league_playoff_ties', 'away_points'),
      ('league_playoff_ties', 'home_goals'),
      ('league_playoff_ties', 'away_goals'),
      ('league_playoff_ties', 'winner_team_id'),
      ('league_playoff_ties', 'decided_by'),
      ('league_playoff_entries', 'playoff_id'),
      ('league_playoff_entries', 'fantasy_team_id'),
      ('league_playoff_entries', 'seed'),
      ('league_playoff_entries', 'regular_season_position'),
      ('league_playoff_entries', 'eliminated_round'),
      ('league_playoff_entries', 'final_position'),
      ('league_playoff_round_finalization_runs', 'id'),
      ('league_playoff_round_finalization_runs', 'league_id'),
      ('league_playoff_round_finalization_runs', 'playoff_id'),
      ('league_playoff_round_finalization_runs', 'round_id'),
      ('league_playoff_round_finalization_runs', 'requested_by'),
      ('league_playoff_round_finalization_runs', 'result_hash'),
      ('league_playoff_round_finalization_runs', 'completed_playoffs'),
      ('league_playoff_round_finalization_runs', 'champion_team_id'),
      ('league_playoff_round_finalization_runs', 'runner_up_team_id'),
      ('league_playoff_round_finalization_runs', 'finalized_at')
    ) as dependency(table_name, column_name)
  loop
    if not exists (
      select 1
      from pg_catalog.pg_attribute attribute
      join pg_catalog.pg_class relation
        on relation.oid = attribute.attrelid
      join pg_catalog.pg_namespace namespace
        on namespace.oid = relation.relnamespace
      where namespace.nspname = 'public'
        and relation.relname = v_dependency.table_name
        and attribute.attname = v_dependency.column_name
        and attribute.attnum > 0
        and not attribute.attisdropped
    ) then
      v_missing := array_append(
        v_missing,
        format('public.%s.%s', v_dependency.table_name, v_dependency.column_name)
      );
    end if;
  end loop;

  if coalesce(array_length(v_missing, 1), 0) > 0 then
    raise exception 'Dipendenze v0.60.9 mancanti: %', array_to_string(v_missing, ', ');
  end if;
end;
$block$;

create table if not exists public.league_playoff_completion_certificates (
  id bigint generated by default as identity primary key,
  league_id uuid not null
    references public.leagues(id) on delete cascade,
  playoff_id uuid not null unique
    references public.league_playoffs(id) on delete cascade,
  final_round_id uuid not null unique
    references public.league_playoff_rounds(id) on delete restrict,
  finalization_run_id bigint not null unique
    references public.league_playoff_round_finalization_runs(id) on delete restrict,
  champion_team_id uuid not null
    references public.fantasy_teams(id) on delete restrict,
  runner_up_team_id uuid not null
    references public.fantasy_teams(id) on delete restrict,
  final_round_number smallint not null
    check (final_round_number between 1 and 3),
  source_result_hash text not null
    check (char_length(source_result_hash) = 64),
  completion_fingerprint text not null
    check (char_length(completion_fingerprint) = 64),
  snapshot jsonb not null default '{}'::jsonb,
  certified_by uuid references public.profiles(id) on delete set null,
  certified_at timestamptz not null default now(),
  check (champion_team_id <> runner_up_team_id)
);

create index if not exists league_playoff_completion_league_idx
  on public.league_playoff_completion_certificates
    (league_id, certified_at desc);
create index if not exists league_playoff_completion_champion_idx
  on public.league_playoff_completion_certificates
    (champion_team_id, certified_at desc);

alter table public.league_playoff_completion_certificates enable row level security;

drop policy if exists league_playoff_completion_read_members
on public.league_playoff_completion_certificates;
create policy league_playoff_completion_read_members
on public.league_playoff_completion_certificates
for select to authenticated
using (
  public.is_league_member(league_id)
  or public.is_league_admin(league_id)
);

revoke all on table public.league_playoff_completion_certificates
from public, anon, authenticated;
grant select on table public.league_playoff_completion_certificates
to authenticated;

create or replace function public.prevent_league_playoff_completion_certificate_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  raise exception
    'Certificato conclusione Playoff immutabile: modifica o cancellazione diretta non consentita.';
end;
$$;

revoke all on function public.prevent_league_playoff_completion_certificate_mutation()
from public, anon, authenticated;

drop trigger if exists league_playoff_completion_certificates_immutable
on public.league_playoff_completion_certificates;
create trigger league_playoff_completion_certificates_immutable
before update or delete on public.league_playoff_completion_certificates
for each row
execute function public.prevent_league_playoff_completion_certificate_mutation();

create or replace function public.compute_league_playoff_completion_fingerprint_v1(
  p_playoff_id uuid
)
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_playoff public.league_playoffs%rowtype;
  v_final_round public.league_playoff_rounds%rowtype;
  v_run public.league_playoff_round_finalization_runs%rowtype;
  v_ties text := '';
  v_entries text := '';
  v_payload text;
begin
  select playoff.*
  into v_playoff
  from public.league_playoffs playoff
  where playoff.id = p_playoff_id;

  if not found or v_playoff.status <> 'completed'
    or v_playoff.champion_team_id is null
    or v_playoff.runner_up_team_id is null then
    return null;
  end if;

  select playoff_round.*
  into v_final_round
  from public.league_playoff_rounds playoff_round
  where playoff_round.playoff_id = v_playoff.id
    and playoff_round.round_number = v_playoff.round_count;

  if not found or v_final_round.status <> 'official' then
    return null;
  end if;

  select run.*
  into v_run
  from public.league_playoff_round_finalization_runs run
  where run.playoff_id = v_playoff.id
    and run.round_id = v_final_round.id
    and run.completed_playoffs
  order by run.id desc
  limit 1;

  if not found
    or v_run.champion_team_id is distinct from v_playoff.champion_team_id
    or v_run.runner_up_team_id is distinct from v_playoff.runner_up_team_id then
    return null;
  end if;

  select coalesce(
    string_agg(
      tie.bracket_position::text || ':'
      || coalesce(tie.home_team_id::text, '-') || ':'
      || coalesce(tie.away_team_id::text, '-') || ':'
      || coalesce(tie.home_points::text, '-') || ':'
      || coalesce(tie.away_points::text, '-') || ':'
      || coalesce(tie.home_goals::text, '-') || ':'
      || coalesce(tie.away_goals::text, '-') || ':'
      || coalesce(tie.winner_team_id::text, '-') || ':'
      || coalesce(tie.decided_by, '-'),
      '|' order by tie.bracket_position
    ),
    ''
  )
  into v_ties
  from public.league_playoff_ties tie
  where tie.round_id = v_final_round.id;

  select coalesce(
    string_agg(
      entry.seed::text || ':'
      || entry.fantasy_team_id::text || ':'
      || entry.regular_season_position::text || ':'
      || coalesce(entry.eliminated_round::text, '-') || ':'
      || coalesce(entry.final_position::text, '-'),
      '|' order by entry.seed
    ),
    ''
  )
  into v_entries
  from public.league_playoff_entries entry
  where entry.playoff_id = v_playoff.id;

  v_payload :=
    v_playoff.id::text || '#'
    || v_playoff.league_id::text || '#'
    || v_playoff.status || '#'
    || v_playoff.participant_count::text || '#'
    || v_playoff.round_count::text || '#'
    || v_playoff.current_round::text || '#'
    || v_playoff.champion_team_id::text || '#'
    || v_playoff.runner_up_team_id::text || '#'
    || coalesce(v_playoff.completed_at::text, '-') || '#'
    || v_final_round.id::text || '#'
    || v_final_round.round_number::text || '#'
    || coalesce(v_final_round.finalized_at::text, '-') || '#'
    || v_run.id::text || '#'
    || v_run.result_hash || '#'
    || v_ties || '#'
    || v_entries;

  return public.leghevo_sha256_hex_v1(v_payload);
end;
$$;

revoke all on function public.compute_league_playoff_completion_fingerprint_v1(uuid)
from public, anon, authenticated;

create or replace function public.certify_league_playoff_completion_internal_v1(
  p_playoff_id uuid,
  p_finalization_run_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_playoff public.league_playoffs%rowtype;
  v_final_round public.league_playoff_rounds%rowtype;
  v_run public.league_playoff_round_finalization_runs%rowtype;
  v_certificate public.league_playoff_completion_certificates%rowtype;
  v_current_result_hash text;
  v_fingerprint text;
begin
  select playoff.*
  into v_playoff
  from public.league_playoffs playoff
  where playoff.id = p_playoff_id;

  if not found or v_playoff.status <> 'completed' then
    raise exception 'I Playoff non sono conclusi: certificazione non disponibile.';
  end if;

  if v_playoff.champion_team_id is null or v_playoff.runner_up_team_id is null then
    raise exception 'Podio finale dei Playoff incompleto.';
  end if;

  select playoff_round.*
  into v_final_round
  from public.league_playoff_rounds playoff_round
  where playoff_round.playoff_id = v_playoff.id
    and playoff_round.round_number = v_playoff.round_count;

  if not found or v_final_round.status <> 'official' then
    raise exception 'Finale dei Playoff non ufficiale.';
  end if;

  select run.*
  into v_run
  from public.league_playoff_round_finalization_runs run
  where run.id = p_finalization_run_id
    and run.playoff_id = v_playoff.id
    and run.round_id = v_final_round.id
    and run.completed_playoffs;

  if not found then
    raise exception 'Ufficializzazione certificata della finale non trovata.';
  end if;

  if v_run.champion_team_id is distinct from v_playoff.champion_team_id
    or v_run.runner_up_team_id is distinct from v_playoff.runner_up_team_id then
    raise exception 'Il podio non coincide con l''ufficializzazione della finale.';
  end if;

  v_current_result_hash := public.compute_league_playoff_round_result_hash_v1(
    v_playoff.id,
    v_final_round.round_number
  );

  if v_current_result_hash is null or v_current_result_hash <> v_run.result_hash then
    raise exception 'L''esito della finale non coincide con la revisione certificata.';
  end if;

  v_fingerprint := public.compute_league_playoff_completion_fingerprint_v1(v_playoff.id);

  if v_fingerprint is null or char_length(v_fingerprint) <> 64 then
    raise exception 'Impossibile calcolare l''impronta conclusiva dei Playoff.';
  end if;

  insert into public.league_playoff_completion_certificates (
    league_id,
    playoff_id,
    final_round_id,
    finalization_run_id,
    champion_team_id,
    runner_up_team_id,
    final_round_number,
    source_result_hash,
    completion_fingerprint,
    snapshot,
    certified_by,
    certified_at
  ) values (
    v_playoff.league_id,
    v_playoff.id,
    v_final_round.id,
    v_run.id,
    v_playoff.champion_team_id,
    v_playoff.runner_up_team_id,
    v_final_round.round_number,
    v_run.result_hash,
    v_fingerprint,
    jsonb_build_object(
      'policy', 'certified_v1',
      'leagueId', v_playoff.league_id,
      'playoffId', v_playoff.id,
      'finalRoundId', v_final_round.id,
      'finalRoundNumber', v_final_round.round_number,
      'finalizationRunId', v_run.id,
      'championTeamId', v_playoff.champion_team_id,
      'runnerUpTeamId', v_playoff.runner_up_team_id,
      'sourceResultHash', v_run.result_hash,
      'completionFingerprint', v_fingerprint
    ),
    v_run.requested_by,
    coalesce(v_run.finalized_at, v_playoff.completed_at, now())
  )
  on conflict (playoff_id) do nothing;

  select certificate.*
  into v_certificate
  from public.league_playoff_completion_certificates certificate
  where certificate.playoff_id = v_playoff.id;

  if not found then
    raise exception 'Certificato conclusivo dei Playoff non creato.';
  end if;

  if v_certificate.finalization_run_id <> v_run.id
    or v_certificate.completion_fingerprint <> v_fingerprint
    or v_certificate.source_result_hash <> v_run.result_hash then
    raise exception 'Esiste un certificato conclusivo incompatibile.';
  end if;

  return v_certificate.id;
end;
$$;

revoke all on function public.certify_league_playoff_completion_internal_v1(uuid, bigint)
from public, anon, authenticated;

create or replace function public.certify_league_playoff_completion_on_finalization_v1()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.completed_playoffs then
    perform public.certify_league_playoff_completion_internal_v1(
      new.playoff_id,
      new.id
    );
  end if;
  return new;
end;
$$;

revoke all on function public.certify_league_playoff_completion_on_finalization_v1()
from public, anon, authenticated;

drop trigger if exists league_playoff_completion_after_finalization
on public.league_playoff_round_finalization_runs;
create trigger league_playoff_completion_after_finalization
after insert on public.league_playoff_round_finalization_runs
for each row
when (new.completed_playoffs)
execute function public.certify_league_playoff_completion_on_finalization_v1();

-- Certifica in modo non distruttivo i Playoff già conclusi e validati dalla v0.60.8.
do $block$
declare
  v_item record;
begin
  for v_item in
    select playoff.id as playoff_id, run.id as run_id
    from public.league_playoffs playoff
    join public.league_playoff_rounds playoff_round
      on playoff_round.playoff_id = playoff.id
      and playoff_round.round_number = playoff.round_count
      and playoff_round.status = 'official'
    join lateral (
      select finalization.id
      from public.league_playoff_round_finalization_runs finalization
      where finalization.playoff_id = playoff.id
        and finalization.round_id = playoff_round.id
        and finalization.completed_playoffs
      order by finalization.id desc
      limit 1
    ) run on true
    where playoff.status = 'completed'
      and playoff.champion_team_id is not null
      and playoff.runner_up_team_id is not null
      and not exists (
        select 1
        from public.league_playoff_completion_certificates certificate
        where certificate.playoff_id = playoff.id
      )
  loop
    perform public.certify_league_playoff_completion_internal_v1(
      v_item.playoff_id,
      v_item.run_id
    );
  end loop;
end;
$block$;

create or replace function public.get_league_playoff_state_v5(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_state jsonb;
  v_playoff_id uuid;
  v_certificate public.league_playoff_completion_certificates%rowtype;
begin
  v_state := public.get_league_playoff_state_v4(p_league_id);
  v_playoff_id := nullif(v_state ->> 'playoffId', '')::uuid;

  if v_playoff_id is not null then
    select certificate.*
    into v_certificate
    from public.league_playoff_completion_certificates certificate
    where certificate.playoff_id = v_playoff_id;
  end if;

  return v_state || jsonb_build_object(
    'completionPolicy', 'certified_v1',
    'completionCertified', v_certificate.id is not null,
    'completionCertificateId', v_certificate.id,
    'completionFingerprint', v_certificate.completion_fingerprint,
    'completionCertifiedAt', v_certificate.certified_at,
    'completionFinalizationRunId', v_certificate.finalization_run_id
  );
end;
$$;

revoke all on function public.get_league_playoff_state_v5(uuid)
from public, anon, authenticated;
grant execute on function public.get_league_playoff_state_v5(uuid)
to authenticated;

create or replace function public.get_league_playoff_completion_integrity_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_completed_count integer := 0;
  v_certificate_count integer := 0;
  v_missing_count integer := 0;
  v_fingerprint_drift_count integer := 0;
  v_source_drift_count integer := 0;
  v_podium_issue_count integer := 0;
  v_link_issue_count integer := 0;
  v_healthy boolean := false;
begin
  if auth.uid() is null
    or (not public.is_league_member(p_league_id)
      and not public.is_league_admin(p_league_id)) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  select count(*)::integer
  into v_completed_count
  from public.league_playoffs playoff
  where playoff.league_id = p_league_id
    and playoff.status = 'completed';

  select count(*)::integer
  into v_certificate_count
  from public.league_playoff_completion_certificates certificate
  where certificate.league_id = p_league_id;

  select count(*)::integer
  into v_missing_count
  from public.league_playoffs playoff
  left join public.league_playoff_completion_certificates certificate
    on certificate.playoff_id = playoff.id
  where playoff.league_id = p_league_id
    and playoff.status = 'completed'
    and certificate.id is null;

  select count(*)::integer
  into v_fingerprint_drift_count
  from public.league_playoff_completion_certificates certificate
  where certificate.league_id = p_league_id
    and certificate.completion_fingerprint is distinct from
      public.compute_league_playoff_completion_fingerprint_v1(certificate.playoff_id);

  select count(*)::integer
  into v_source_drift_count
  from public.league_playoff_completion_certificates certificate
  join public.league_playoff_round_finalization_runs run
    on run.id = certificate.finalization_run_id
  where certificate.league_id = p_league_id
    and certificate.source_result_hash is distinct from run.result_hash;

  select count(*)::integer
  into v_podium_issue_count
  from public.league_playoff_completion_certificates certificate
  join public.league_playoffs playoff on playoff.id = certificate.playoff_id
  where certificate.league_id = p_league_id
    and (
      certificate.champion_team_id is distinct from playoff.champion_team_id
      or certificate.runner_up_team_id is distinct from playoff.runner_up_team_id
      or certificate.champion_team_id = certificate.runner_up_team_id
    );

  select count(*)::integer
  into v_link_issue_count
  from public.league_playoff_completion_certificates certificate
  join public.league_playoff_rounds playoff_round
    on playoff_round.id = certificate.final_round_id
  join public.league_playoff_round_finalization_runs run
    on run.id = certificate.finalization_run_id
  where certificate.league_id = p_league_id
    and (
      playoff_round.playoff_id <> certificate.playoff_id
      or playoff_round.round_number <> certificate.final_round_number
      or playoff_round.status <> 'official'
      or run.playoff_id <> certificate.playoff_id
      or run.round_id <> certificate.final_round_id
      or not run.completed_playoffs
    );

  v_healthy :=
    v_missing_count = 0
    and v_fingerprint_drift_count = 0
    and v_source_drift_count = 0
    and v_podium_issue_count = 0
    and v_link_issue_count = 0;

  return jsonb_build_object(
    'policy', 'certified_v1',
    'healthy', v_healthy,
    'completedPlayoffCount', v_completed_count,
    'certificateCount', v_certificate_count,
    'missingCertificateCount', v_missing_count,
    'fingerprintDriftCount', v_fingerprint_drift_count,
    'sourceDriftCount', v_source_drift_count,
    'podiumIssueCount', v_podium_issue_count,
    'linkIssueCount', v_link_issue_count
  );
end;
$$;

revoke all on function public.get_league_playoff_completion_integrity_v1(uuid)
from public, anon, authenticated;
grant execute on function public.get_league_playoff_completion_integrity_v1(uuid)
to authenticated;

do $block$
begin
  if exists (
    select 1 from pg_catalog.pg_publication
    where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'league_playoff_completion_certificates'
  ) then
    alter publication supabase_realtime
      add table public.league_playoff_completion_certificates;
  end if;
end;
$block$;

commit;

-- Diagnostica finale: devono risultare esattamente 20 valori true.
select
  to_regclass('public.league_playoff_completion_certificates') is not null
    as completion_certificate_table_ready,
  exists (
    select 1 from pg_catalog.pg_indexes
    where schemaname = 'public'
      and indexname = 'league_playoff_completion_certificates_playoff_id_key'
  ) as one_certificate_per_playoff_ready,
  exists (
    select 1 from pg_catalog.pg_indexes
    where schemaname = 'public'
      and indexname = 'league_playoff_completion_certificates_finalization_run_id_key'
  ) as one_certificate_per_finalization_ready,
  exists (
    select 1 from pg_catalog.pg_indexes
    where schemaname = 'public'
      and indexname = 'league_playoff_completion_league_idx'
  ) as certificate_lookup_index_ready,
  coalesce((
    select relation.relrowsecurity
    from pg_catalog.pg_class relation
    where relation.oid = 'public.league_playoff_completion_certificates'::regclass
  ), false) as completion_certificate_rls_ready,
  exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'league_playoff_completion_certificates'
      and policyname = 'league_playoff_completion_read_members'
  ) as completion_certificate_read_policy_ready,
  has_table_privilege(
    'authenticated',
    'public.league_playoff_completion_certificates',
    'SELECT'
  ) as authenticated_certificate_read_ready,
  not has_table_privilege(
    'authenticated',
    'public.league_playoff_completion_certificates',
    'INSERT'
  ) as direct_certificate_insert_blocked,
  exists (
    select 1
    from pg_catalog.pg_trigger trigger_record
    join pg_catalog.pg_class relation
      on relation.oid = trigger_record.tgrelid
    join pg_catalog.pg_namespace namespace
      on namespace.oid = relation.relnamespace
    where namespace.nspname = 'public'
      and relation.relname = 'league_playoff_completion_certificates'
      and trigger_record.tgname = 'league_playoff_completion_certificates_immutable'
      and not trigger_record.tgisinternal
  ) as certificate_immutable_trigger_ready,
  to_regprocedure(
    'public.compute_league_playoff_completion_fingerprint_v1(uuid)'
  ) is not null as completion_fingerprint_ready,
  to_regprocedure(
    'public.certify_league_playoff_completion_internal_v1(uuid,bigint)'
  ) is not null as internal_completion_certifier_ready,
  to_regprocedure(
    'public.certify_league_playoff_completion_on_finalization_v1()'
  ) is not null as completion_trigger_function_ready,
  exists (
    select 1
    from pg_catalog.pg_trigger trigger_record
    join pg_catalog.pg_class relation
      on relation.oid = trigger_record.tgrelid
    join pg_catalog.pg_namespace namespace
      on namespace.oid = relation.relnamespace
    where namespace.nspname = 'public'
      and relation.relname = 'league_playoff_round_finalization_runs'
      and trigger_record.tgname = 'league_playoff_completion_after_finalization'
      and not trigger_record.tgisinternal
  ) as automatic_completion_certification_ready,
  to_regprocedure('public.get_league_playoff_state_v5(uuid)') is not null
    as playoff_state_v5_ready,
  to_regprocedure(
    'public.get_league_playoff_completion_integrity_v1(uuid)'
  ) is not null as completion_integrity_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_playoff_state_v5(uuid)',
    'EXECUTE'
  ) as authenticated_state_v5_ready,
  has_function_privilege(
    'authenticated',
    'public.get_league_playoff_completion_integrity_v1(uuid)',
    'EXECUTE'
  ) as authenticated_completion_diagnostics_ready,
  not has_function_privilege(
    'authenticated',
    'public.certify_league_playoff_completion_internal_v1(uuid,bigint)',
    'EXECUTE'
  ) as internal_certifier_private,
  not exists (
    select 1
    from public.league_playoffs playoff
    left join public.league_playoff_completion_certificates certificate
      on certificate.playoff_id = playoff.id
    where playoff.status = 'completed'
      and certificate.id is null
  ) as completed_playoffs_certified,
  exists (
    select 1
    from pg_catalog.pg_publication_tables publication_table
    where publication_table.pubname = 'supabase_realtime'
      and publication_table.schemaname = 'public'
      and publication_table.tablename = 'league_playoff_completion_certificates'
  ) as completion_certificate_realtime_ready;
