-- LEGHEVO v0.62.29
-- Rinnovo stagione certificato anti-fork.
-- Migrazione interna: database/133_league_season_rollover_lineage_safety.sql
-- Eseguire dopo database/132_league_season_official_snapshot_safety.sql.
-- La stagione successiva nasce soltanto da uno snapshot ufficiale integro.
-- I rinnovi già esistenti non vengono cancellati: vengono adottati e, se la
-- continuità originaria non è più verificabile, marcati affected per la Direzione.

begin;

-- PRE-FLIGHT: lo snapshot ufficiale immutabile della v0.62.28 deve essere integro.
do $preflight$
declare
  v_integrity jsonb;
begin
  if to_regprocedure(
    'public.get_league_season_official_snapshot_integrity_v1()'
  ) is null then
    raise exception
      'Preflight v0.62.29 non superato: manca la diagnostica v0.62.28.';
  end if;

  v_integrity := public.get_league_season_official_snapshot_integrity_v1();
  if (select count(*) from jsonb_each(v_integrity)) <> 20
    or exists (
      select 1
      from jsonb_each(v_integrity) check_row
      where jsonb_typeof(check_row.value) is distinct from 'boolean'
         or check_row.value is distinct from 'true'::jsonb
    ) then
    raise exception
      'Preflight v0.62.29 non superato: la v0.62.28 non è integra.';
  end if;

  if to_regclass('public.league_season_rollovers') is null
    or to_regprocedure('public.renew_league_season(uuid,text)') is null then
    raise exception
      'Preflight v0.62.29 non superato: rinnovo stagione precedente assente.';
  end if;
end;
$preflight$;

create table if not exists public.league_season_rollover_certificates (
  id bigint generated by default as identity primary key,
  source_league_id uuid not null unique
    references public.leagues(id) on delete restrict,
  renewed_league_id uuid not null unique
    references public.leagues(id) on delete restrict,
  request_id uuid not null unique,
  source_snapshot_id bigint not null
    references public.league_season_official_snapshots(id) on delete restrict,
  source_snapshot_hash text not null,
  source_season text not null,
  renewed_season text not null,
  copied_member_count integer not null,
  copied_team_count integer not null,
  source_member_fingerprint text not null,
  renewed_member_fingerprint text not null,
  source_team_fingerprint text not null,
  renewed_team_fingerprint text not null,
  certification_status text not null,
  certification_reason text not null,
  lineage_hash text not null,
  certified_by uuid references public.profiles(id) on delete set null,
  certified_at timestamptz not null default now(),
  result_payload jsonb not null default '{}'::jsonb,
  constraint league_season_rollover_certificate_distinct_check
    check (source_league_id<>renewed_league_id),
  constraint league_season_rollover_certificate_seasons_check
    check (
      source_season~'^[0-9]{4}$'
      and renewed_season~'^[0-9]{4}$'
      and renewed_season::integer>source_season::integer
    ),
  constraint league_season_rollover_certificate_counts_check
    check (copied_member_count>0 and copied_team_count>0),
  constraint league_season_rollover_certificate_snapshot_hash_check
    check (length(source_snapshot_hash)=32),
  constraint league_season_rollover_certificate_member_hashes_check
    check (
      length(source_member_fingerprint)=32
      and length(renewed_member_fingerprint)=32
    ),
  constraint league_season_rollover_certificate_team_hashes_check
    check (
      length(source_team_fingerprint)=32
      and length(renewed_team_fingerprint)=32
    ),
  constraint league_season_rollover_certificate_status_check
    check (certification_status in ('certified','affected')),
  constraint league_season_rollover_certificate_reason_check
    check (char_length(trim(certification_reason)) between 3 and 180),
  constraint league_season_rollover_certificate_lineage_hash_check
    check (length(lineage_hash)=32),
  constraint league_season_rollover_certificate_payload_check
    check (jsonb_typeof(result_payload)='object')
);

create table if not exists public.league_season_rollover_heads (
  source_league_id uuid primary key
    references public.leagues(id) on delete restrict,
  certificate_id bigint not null unique
    references public.league_season_rollover_certificates(id)
    on delete restrict,
  renewed_league_id uuid not null unique
    references public.leagues(id) on delete restrict,
  rollover_status text not null,
  reason_code text not null,
  observed_snapshot_status text not null,
  observed_snapshot_hash text not null,
  affected_at timestamptz,
  last_assessed_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint league_season_rollover_heads_status_check
    check (rollover_status in ('certified','affected')),
  constraint league_season_rollover_heads_reason_check
    check (char_length(trim(reason_code)) between 3 and 180),
  constraint league_season_rollover_heads_snapshot_status_check
    check (observed_snapshot_status in ('official','affected')),
  constraint league_season_rollover_heads_snapshot_hash_check
    check (length(observed_snapshot_hash)=32),
  constraint league_season_rollover_heads_affected_check
    check (
      (rollover_status='certified' and affected_at is null)
      or (rollover_status='affected' and affected_at is not null)
    )
);

create table if not exists public.league_season_rollover_events (
  id bigint generated by default as identity primary key,
  source_league_id uuid not null
    references public.leagues(id) on delete restrict,
  renewed_league_id uuid not null
    references public.leagues(id) on delete restrict,
  certificate_id bigint not null
    references public.league_season_rollover_certificates(id)
    on delete restrict,
  event_type text not null,
  rollover_status text not null,
  reason_code text not null,
  source_snapshot_hash text not null,
  lineage_hash text not null,
  event_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint league_season_rollover_events_type_check
    check (event_type in ('certified','affected','revalidated')),
  constraint league_season_rollover_events_status_check
    check (rollover_status in ('certified','affected')),
  constraint league_season_rollover_events_reason_check
    check (char_length(trim(reason_code)) between 3 and 180),
  constraint league_season_rollover_events_snapshot_hash_check
    check (length(source_snapshot_hash)=32),
  constraint league_season_rollover_events_lineage_hash_check
    check (length(lineage_hash)=32),
  constraint league_season_rollover_events_payload_check
    check (jsonb_typeof(event_payload)='object')
);

create unique index if not exists leagues_previous_league_unique_idx
  on public.leagues(previous_league_id)
  where previous_league_id is not null;

create index if not exists league_season_rollover_certificates_created_idx
  on public.league_season_rollover_certificates(
    source_league_id,certified_at desc
  );
create index if not exists league_season_rollover_heads_status_idx
  on public.league_season_rollover_heads(
    rollover_status,updated_at desc
  );
create index if not exists league_season_rollover_events_source_idx
  on public.league_season_rollover_events(
    source_league_id,created_at desc,id desc
  );
create index if not exists league_season_rollover_events_renewed_idx
  on public.league_season_rollover_events(
    renewed_league_id,created_at desc,id desc
  );

alter table public.league_season_rollover_certificates enable row level security;
alter table public.league_season_rollover_heads enable row level security;
alter table public.league_season_rollover_events enable row level security;
alter table public.league_season_rollover_events replica identity full;

revoke all on public.league_season_rollover_certificates
from public,anon,authenticated,service_role;
revoke all on public.league_season_rollover_heads
from public,anon,authenticated,service_role;
revoke all on public.league_season_rollover_events
from public,anon,authenticated,service_role;
grant select on public.league_season_rollover_certificates to authenticated;
grant select on public.league_season_rollover_heads to authenticated;
grant select on public.league_season_rollover_events to authenticated;

drop policy if exists league_season_rollover_certificates_member_select
on public.league_season_rollover_certificates;
create policy league_season_rollover_certificates_member_select
on public.league_season_rollover_certificates
for select to authenticated
using (
  public.is_league_member(source_league_id)
  or public.is_league_admin(source_league_id)
  or public.is_league_member(renewed_league_id)
  or public.is_league_admin(renewed_league_id)
);

drop policy if exists league_season_rollover_heads_member_select
on public.league_season_rollover_heads;
create policy league_season_rollover_heads_member_select
on public.league_season_rollover_heads
for select to authenticated
using (
  public.is_league_member(source_league_id)
  or public.is_league_admin(source_league_id)
  or public.is_league_member(renewed_league_id)
  or public.is_league_admin(renewed_league_id)
);

drop policy if exists league_season_rollover_events_director_select
on public.league_season_rollover_events;
create policy league_season_rollover_events_director_select
on public.league_season_rollover_events
for select to authenticated
using (
  public.is_league_admin(source_league_id)
  or public.is_league_admin(renewed_league_id)
);

create or replace function public.guard_league_season_rollover_certificate_v1()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
begin
  if tg_op<>'INSERT' then
    raise exception
      'I certificati del rinnovo stagione sono immutabili.';
  end if;

  if current_setting(
    'leghevo.season_rollover_certificate_context',true
  ) is distinct from 'on' then
    raise exception
      'I certificati del rinnovo stagione possono essere creati solo dal database.';
  end if;

  return new;
end;
$function$;

drop trigger if exists league_season_rollover_certificates_immutable
on public.league_season_rollover_certificates;
create trigger league_season_rollover_certificates_immutable
before insert or update or delete
on public.league_season_rollover_certificates
for each row execute function
public.guard_league_season_rollover_certificate_v1();
alter table public.league_season_rollover_certificates
  enable always trigger league_season_rollover_certificates_immutable;

create or replace function public.guard_league_season_rollover_head_v1()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
begin
  if current_setting(
    'leghevo.season_rollover_certificate_context',true
  ) is distinct from 'on' then
    raise exception
      'La testa certificata del rinnovo può essere aggiornata solo dal database.';
  end if;
  if tg_op='DELETE' then
    raise exception 'La testa certificata del rinnovo non può essere eliminata.';
  end if;
  return case when tg_op='INSERT' then new else new end;
end;
$function$;

drop trigger if exists league_season_rollover_heads_guard
on public.league_season_rollover_heads;
create trigger league_season_rollover_heads_guard
before insert or update or delete
on public.league_season_rollover_heads
for each row execute function public.guard_league_season_rollover_head_v1();
alter table public.league_season_rollover_heads
  enable always trigger league_season_rollover_heads_guard;

create or replace function public.guard_league_season_rollover_event_v1()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
begin
  if tg_op<>'INSERT' then
    raise exception 'Lo storico del rinnovo stagione è append-only.';
  end if;
  if current_setting(
    'leghevo.season_rollover_certificate_context',true
  ) is distinct from 'on' then
    raise exception
      'Gli eventi del rinnovo stagione possono essere creati solo dal database.';
  end if;
  return new;
end;
$function$;

drop trigger if exists league_season_rollover_events_immutable
on public.league_season_rollover_events;
create trigger league_season_rollover_events_immutable
before insert or update or delete
on public.league_season_rollover_events
for each row execute function public.guard_league_season_rollover_event_v1();
alter table public.league_season_rollover_events
  enable always trigger league_season_rollover_events_immutable;

-- Blocca inserimenti diretti nella vecchia tabella e protegge il collegamento.
create or replace function public.guard_league_season_rollover_row_v1()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
begin
  if tg_op='INSERT' then
    if current_setting(
      'leghevo.season_rollover_writer_context',true
    ) is distinct from 'on' then
      raise exception
        'Il rinnovo stagione deve passare dalla barriera certificata.';
    end if;
    return new;
  end if;

  raise exception
    'Il collegamento tra stagioni è immutabile dopo il commit.';
end;
$function$;

drop trigger if exists league_season_rollovers_certified_guard
on public.league_season_rollovers;
create trigger league_season_rollovers_certified_guard
before insert or update or delete on public.league_season_rollovers
for each row execute function public.guard_league_season_rollover_row_v1();
alter table public.league_season_rollovers
  enable always trigger league_season_rollovers_certified_guard;

-- Nessuna RPC può creare un ramo alternativo modificando previous_league_id.
create or replace function public.guard_league_season_lineage_link_v1()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
begin
  if tg_op='INSERT' and new.previous_league_id is not null
    and current_setting(
      'leghevo.season_rollover_writer_context',true
    ) is distinct from 'on' then
    raise exception
      'Il collegamento alla stagione precedente deve essere certificato.';
  end if;

  if tg_op='UPDATE'
    and new.previous_league_id is distinct from old.previous_league_id then
    raise exception
      'Il collegamento tra stagioni non può essere riscritto.';
  end if;

  return new;
end;
$function$;

drop trigger if exists leagues_season_lineage_link_guard
on public.leagues;
create trigger leagues_season_lineage_link_guard
before insert or update of previous_league_id on public.leagues
for each row execute function public.guard_league_season_lineage_link_v1();
alter table public.leagues
  enable always trigger leagues_season_lineage_link_guard;

create or replace function public.compute_league_member_identity_fingerprint_v1(
  p_league_id uuid
)
returns text
language sql
stable
security definer
set search_path=''
as $function$
  select pg_catalog.md5(
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'userId',member.user_id,
          'role',member.role
        ) order by member.user_id,member.role
      ),
      '[]'::jsonb
    )::text
  )
  from public.league_members member
  where member.league_id=p_league_id
$function$;

create or replace function public.compute_league_team_identity_fingerprint_v1(
  p_league_id uuid
)
returns text
language sql
stable
security definer
set search_path=''
as $function$
  select pg_catalog.md5(
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'managerId',team.manager_id,
          'teamName',team.name,
          'crestUrl',coalesce(team.crest_url,'')
        ) order by team.manager_id,team.name,coalesce(team.crest_url,'')
      ),
      '[]'::jsonb
    )::text
  )
  from public.fantasy_teams team
  where team.league_id=p_league_id
$function$;

create or replace function public.compute_league_season_rollover_lineage_hash_v1(
  p_source_league_id uuid,
  p_renewed_league_id uuid,
  p_source_snapshot_id bigint,
  p_source_snapshot_hash text,
  p_source_season text,
  p_renewed_season text,
  p_copied_member_count integer,
  p_copied_team_count integer,
  p_source_member_fingerprint text,
  p_renewed_member_fingerprint text,
  p_source_team_fingerprint text,
  p_renewed_team_fingerprint text
)
returns text
language sql
immutable
set search_path=''
as $function$
  select pg_catalog.md5(jsonb_build_object(
    'sourceLeagueId',p_source_league_id,
    'renewedLeagueId',p_renewed_league_id,
    'sourceSnapshotId',p_source_snapshot_id,
    'sourceSnapshotHash',p_source_snapshot_hash,
    'sourceSeason',p_source_season,
    'renewedSeason',p_renewed_season,
    'copiedMemberCount',p_copied_member_count,
    'copiedTeamCount',p_copied_team_count,
    'sourceMemberFingerprint',p_source_member_fingerprint,
    'renewedMemberFingerprint',p_renewed_member_fingerprint,
    'sourceTeamFingerprint',p_source_team_fingerprint,
    'renewedTeamFingerprint',p_renewed_team_fingerprint
  )::text)
$function$;

create or replace function public.is_league_season_official_snapshot_row_valid_v1(
  p_snapshot_id bigint
)
returns boolean
language sql
stable
security definer
set search_path=''
as $function$
  select snapshot_row.snapshot_hash=pg_catalog.md5(jsonb_build_object(
    'leagueId',snapshot_row.league_id,
    'completionRunId',snapshot_row.completion_run_id,
    'completionGateHeadId',snapshot_row.completion_gate_head_id,
    'completionGateGeneration',snapshot_row.completion_gate_generation,
    'completionGateFingerprint',snapshot_row.completion_gate_fingerprint,
    'finalProgressionRunId',snapshot_row.final_progression_run_id,
    'finalOfficializationRunId',snapshot_row.final_officialization_run_id,
    'season',snapshot_row.season,
    'championTeamId',snapshot_row.champion_team_id,
    'championTeamName',snapshot_row.champion_team_name,
    'championManagerName',snapshot_row.champion_manager_name,
    'championSource',snapshot_row.champion_source,
    'standingsTiebreaker',snapshot_row.standings_tiebreaker,
    'fixtureCount',snapshot_row.fixture_count,
    'completionInputHash',snapshot_row.completion_input_hash,
    'standingsHash',snapshot_row.standings_hash,
    'finalStandings',snapshot_row.final_standings,
    'podium',snapshot_row.podium,
    'officializedAt',snapshot_row.officialized_at
  )::text)
  from public.league_season_official_snapshots snapshot_row
  where snapshot_row.id=p_snapshot_id
$function$;

revoke all on function public.compute_league_member_identity_fingerprint_v1(uuid)
from public,anon,authenticated;
revoke all on function public.compute_league_team_identity_fingerprint_v1(uuid)
from public,anon,authenticated;
revoke all on function public.compute_league_season_rollover_lineage_hash_v1(
  uuid,uuid,bigint,text,text,text,integer,integer,text,text,text,text
) from public,anon,authenticated;
revoke all on function public.is_league_season_official_snapshot_row_valid_v1(bigint)
from public,anon,authenticated;
grant execute on function public.compute_league_member_identity_fingerprint_v1(uuid)
to service_role;
grant execute on function public.compute_league_team_identity_fingerprint_v1(uuid)
to service_role;
grant execute on function public.compute_league_season_rollover_lineage_hash_v1(
  uuid,uuid,bigint,text,text,text,integer,integer,text,text,text,text
) to service_role;
grant execute on function public.is_league_season_official_snapshot_row_valid_v1(bigint)
to service_role;

create or replace function public.certify_league_season_rollover_v1(
  p_source_league_id uuid,
  p_request_id uuid,
  p_allow_affected_adoption boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_rollover public.league_season_rollovers%rowtype;
  v_snapshot public.league_season_official_snapshots%rowtype;
  v_snapshot_head public.league_season_official_snapshot_heads%rowtype;
  v_certificate public.league_season_rollover_certificates%rowtype;
  v_head public.league_season_rollover_heads%rowtype;
  v_renewed public.leagues%rowtype;
  v_source_member_count integer;
  v_renewed_member_count integer;
  v_source_team_count integer;
  v_renewed_team_count integer;
  v_source_member_fingerprint text;
  v_renewed_member_fingerprint text;
  v_source_team_fingerprint text;
  v_renewed_team_fingerprint text;
  v_status text;
  v_reason text;
  v_lineage_hash text;
  v_certificate_id bigint;
  v_payload jsonb;
  v_adoption_issue text;
begin
  if p_request_id is null then
    raise exception 'Request ID del rinnovo non valido.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'provider-season-completion-chain:'||p_source_league_id::text,0
    )
  );
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'league-season-official-snapshot:'||p_source_league_id::text,0
    )
  );
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'league-season-rollover-lineage:'||p_source_league_id::text,0
    )
  );

  select certificate.* into v_certificate
  from public.league_season_rollover_certificates certificate
  where certificate.source_league_id=p_source_league_id;

  if found then
    select head.* into v_head
    from public.league_season_rollover_heads head
    where head.certificate_id=v_certificate.id;

    return v_certificate.result_payload || jsonb_build_object(
      'certificateId',v_certificate.id,
      'rolloverStatus',coalesce(v_head.rollover_status,
        v_certificate.certification_status),
      'rolloverReason',coalesce(v_head.reason_code,
        v_certificate.certification_reason),
      'rolloverAffected',coalesce(v_head.rollover_status='affected',
        v_certificate.certification_status='affected')
    );
  end if;

  select rollover.* into v_rollover
  from public.league_season_rollovers rollover
  where rollover.source_league_id=p_source_league_id
  for update;
  if not found then
    raise exception 'Rinnovo stagione da certificare non trovato.';
  end if;

  select snapshot_row.* into v_snapshot
  from public.league_season_official_snapshots snapshot_row
  where snapshot_row.league_id=p_source_league_id
  for share;
  if not found then
    raise exception
      'Rinnovo rifiutato: snapshot ufficiale della stagione assente.';
  end if;

  select snapshot_head.* into v_snapshot_head
  from public.league_season_official_snapshot_heads snapshot_head
  where snapshot_head.snapshot_id=v_snapshot.id
  for share;
  if not found then
    raise exception
      'Rinnovo rifiutato: testa dello snapshot ufficiale assente.';
  end if;

  if not coalesce(
    public.is_league_season_official_snapshot_row_valid_v1(v_snapshot.id),
    false
  ) then
    raise exception
      'Rinnovo rifiutato: hash dello snapshot ufficiale non valido.';
  end if;

  select league.* into v_renewed
  from public.leagues league
  where league.id=v_rollover.renewed_league_id
  for share;
  if not found then
    raise exception
      'Rinnovo rifiutato: stagione rinnovata non trovata.';
  end if;

  if v_renewed.previous_league_id is distinct from p_source_league_id then
    if not p_allow_affected_adoption then
      raise exception
        'Rinnovo rifiutato: collegamento tra le stagioni non coerente.';
    end if;
    v_adoption_issue:='season_rollover.renewed_lineage_mismatch';
  end if;

  if v_rollover.source_season<>v_snapshot.season
    or v_rollover.renewed_season::integer
      <=v_rollover.source_season::integer
    or v_renewed.calendar_season<>v_rollover.renewed_season then
    if not p_allow_affected_adoption then
      raise exception
        'Rinnovo rifiutato: continuità delle stagioni non coerente.';
    end if;
    v_adoption_issue:=coalesce(
      v_adoption_issue,'season_rollover.legacy_season_linkage_mismatch'
    );
  end if;

  select count(*)::integer into v_source_member_count
  from public.league_members member
  where member.league_id=p_source_league_id;
  select count(*)::integer into v_renewed_member_count
  from public.league_members member
  where member.league_id=v_rollover.renewed_league_id;
  select count(*)::integer into v_source_team_count
  from public.fantasy_teams team
  where team.league_id=p_source_league_id;
  select count(*)::integer into v_renewed_team_count
  from public.fantasy_teams team
  where team.league_id=v_rollover.renewed_league_id;

  v_source_member_fingerprint :=
    public.compute_league_member_identity_fingerprint_v1(p_source_league_id);
  v_renewed_member_fingerprint :=
    public.compute_league_member_identity_fingerprint_v1(
      v_rollover.renewed_league_id
    );
  v_source_team_fingerprint :=
    public.compute_league_team_identity_fingerprint_v1(p_source_league_id);
  v_renewed_team_fingerprint :=
    public.compute_league_team_identity_fingerprint_v1(
      v_rollover.renewed_league_id
    );

  v_status := 'certified';
  v_reason := 'season_rollover.lineage_certified';

  if v_adoption_issue is not null then
    v_status := 'affected';
    v_reason := v_adoption_issue;
  elsif v_rollover.renewed_season::integer
      <>v_rollover.source_season::integer+1 then
    v_status := 'affected';
    v_reason := 'season_rollover.legacy_season_gap';
  elsif v_snapshot_head.snapshot_id is null
    or v_snapshot_head.snapshot_status<>'official' then
    v_status := 'affected';
    v_reason := 'season_rollover.source_snapshot_affected';
  elsif v_source_member_count<>v_rollover.copied_member_count
    or v_renewed_member_count<>v_rollover.copied_member_count then
    v_status := 'affected';
    v_reason := 'season_rollover.member_count_drift';
  elsif v_source_team_count<>v_rollover.copied_team_count
    or v_renewed_team_count<>v_rollover.copied_team_count then
    v_status := 'affected';
    v_reason := 'season_rollover.team_count_drift';
  elsif v_source_member_fingerprint<>v_renewed_member_fingerprint then
    v_status := 'affected';
    v_reason := 'season_rollover.member_identity_drift';
  elsif v_source_team_fingerprint<>v_renewed_team_fingerprint then
    v_status := 'affected';
    v_reason := 'season_rollover.team_identity_drift';
  end if;

  if v_status<>'certified' and not p_allow_affected_adoption then
    raise exception 'Rinnovo rifiutato [%]: %',v_reason,v_status;
  end if;

  v_lineage_hash :=
    public.compute_league_season_rollover_lineage_hash_v1(
      p_source_league_id,v_rollover.renewed_league_id,v_snapshot.id,
      v_snapshot.snapshot_hash,v_rollover.source_season,
      v_rollover.renewed_season,v_rollover.copied_member_count,
      v_rollover.copied_team_count,v_source_member_fingerprint,
      v_renewed_member_fingerprint,v_source_team_fingerprint,
      v_renewed_team_fingerprint
    );

  v_certificate_id := pg_catalog.nextval(
    pg_catalog.pg_get_serial_sequence(
      'public.league_season_rollover_certificates','id'
    )::regclass
  );

  v_payload := jsonb_build_object(
    'sourceLeagueId',p_source_league_id,
    'renewedLeagueId',v_rollover.renewed_league_id,
    'sourceSeason',v_rollover.source_season,
    'renewedSeason',v_rollover.renewed_season,
    'certificateId',v_certificate_id,
    'sourceSnapshotId',v_snapshot.id,
    'sourceSnapshotHash',v_snapshot.snapshot_hash,
    'lineageHash',v_lineage_hash,
    'rolloverStatus',v_status,
    'rolloverReason',v_reason,
    'rolloverAffected',v_status='affected',
    'copiedMemberCount',v_rollover.copied_member_count,
    'copiedTeamCount',v_rollover.copied_team_count,
    'certifiedAt',v_rollover.renewed_at
  );

  perform set_config(
    'leghevo.season_rollover_certificate_context','on',true
  );

  insert into public.league_season_rollover_certificates(
    id,source_league_id,renewed_league_id,request_id,
    source_snapshot_id,source_snapshot_hash,source_season,renewed_season,
    copied_member_count,copied_team_count,source_member_fingerprint,
    renewed_member_fingerprint,source_team_fingerprint,
    renewed_team_fingerprint,certification_status,certification_reason,
    lineage_hash,certified_by,certified_at,result_payload
  ) values (
    v_certificate_id,p_source_league_id,v_rollover.renewed_league_id,
    p_request_id,v_snapshot.id,v_snapshot.snapshot_hash,
    v_rollover.source_season,v_rollover.renewed_season,
    v_rollover.copied_member_count,v_rollover.copied_team_count,
    v_source_member_fingerprint,v_renewed_member_fingerprint,
    v_source_team_fingerprint,v_renewed_team_fingerprint,
    v_status,v_reason,v_lineage_hash,v_rollover.renewed_by,
    v_rollover.renewed_at,v_payload
  ) returning * into v_certificate;

  insert into public.league_season_rollover_heads(
    source_league_id,certificate_id,renewed_league_id,rollover_status,
    reason_code,observed_snapshot_status,observed_snapshot_hash,
    affected_at,last_assessed_at,updated_at
  ) values (
    p_source_league_id,v_certificate.id,v_rollover.renewed_league_id,
    v_status,v_reason,v_snapshot_head.snapshot_status,
    v_snapshot.snapshot_hash,
    case when v_status='affected' then now() else null end,
    now(),now()
  );

  insert into public.league_season_rollover_events(
    source_league_id,renewed_league_id,certificate_id,event_type,
    rollover_status,reason_code,source_snapshot_hash,lineage_hash,
    event_payload
  ) values (
    p_source_league_id,v_rollover.renewed_league_id,v_certificate.id,
    case when v_status='certified' then 'certified' else 'affected' end,
    v_status,v_reason,v_snapshot.snapshot_hash,v_lineage_hash,
    jsonb_build_object(
      'adoptedExisting',p_allow_affected_adoption,
      'sourceSnapshotStatus',v_snapshot_head.snapshot_status,
      'requestId',p_request_id
    )
  );

  perform set_config(
    'leghevo.season_rollover_certificate_context','',true
  );

  return v_payload;
end;
$function$;

revoke all on function public.certify_league_season_rollover_v1(
  uuid,uuid,boolean
) from public,anon,authenticated;
grant execute on function public.certify_league_season_rollover_v1(
  uuid,uuid,boolean
) to service_role;

create or replace function public.reconcile_league_season_rollover_v1(
  p_source_league_id uuid,
  p_emit_event boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_certificate public.league_season_rollover_certificates%rowtype;
  v_head public.league_season_rollover_heads%rowtype;
  v_rollover public.league_season_rollovers%rowtype;
  v_snapshot public.league_season_official_snapshots%rowtype;
  v_snapshot_head public.league_season_official_snapshot_heads%rowtype;
  v_renewed public.leagues%rowtype;
  v_expected_hash text;
  v_status text;
  v_reason text;
  v_changed boolean;
  v_previous_status text;
  v_previous_reason text;
begin
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'provider-season-completion-chain:'||p_source_league_id::text,0
    )
  );
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'league-season-official-snapshot:'||p_source_league_id::text,0
    )
  );
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'league-season-rollover-lineage:'||p_source_league_id::text,0
    )
  );

  select certificate.* into v_certificate
  from public.league_season_rollover_certificates certificate
  where certificate.source_league_id=p_source_league_id;
  if not found then
    return jsonb_build_object(
      'protected',true,'certified',false,'healthy',true,
      'status','pending','reasonCode','season_rollover.not_created'
    );
  end if;

  select head.* into v_head
  from public.league_season_rollover_heads head
  where head.certificate_id=v_certificate.id
  for update;
  if not found then
    raise exception 'Testa del rinnovo stagione non trovata.';
  end if;

  select rollover.* into v_rollover
  from public.league_season_rollovers rollover
  where rollover.source_league_id=p_source_league_id;
  select snapshot_row.* into v_snapshot
  from public.league_season_official_snapshots snapshot_row
  where snapshot_row.id=v_certificate.source_snapshot_id;
  select snapshot_head.* into v_snapshot_head
  from public.league_season_official_snapshot_heads snapshot_head
  where snapshot_head.snapshot_id=v_certificate.source_snapshot_id;
  select league.* into v_renewed
  from public.leagues league
  where league.id=v_certificate.renewed_league_id;

  v_expected_hash :=
    public.compute_league_season_rollover_lineage_hash_v1(
      v_certificate.source_league_id,v_certificate.renewed_league_id,
      v_certificate.source_snapshot_id,v_certificate.source_snapshot_hash,
      v_certificate.source_season,v_certificate.renewed_season,
      v_certificate.copied_member_count,v_certificate.copied_team_count,
      v_certificate.source_member_fingerprint,
      v_certificate.renewed_member_fingerprint,
      v_certificate.source_team_fingerprint,
      v_certificate.renewed_team_fingerprint
    );

  v_status := 'certified';
  v_reason := 'season_rollover.lineage_certified';

  if v_certificate.lineage_hash<>v_expected_hash then
    v_status := 'affected';
    v_reason := 'season_rollover.certificate_hash_mismatch';
  elsif v_rollover.source_league_id is null
    or v_rollover.renewed_league_id<>v_certificate.renewed_league_id
    or v_rollover.source_season<>v_certificate.source_season
    or v_rollover.renewed_season<>v_certificate.renewed_season then
    v_status := 'affected';
    v_reason := 'season_rollover.linkage_mismatch';
  elsif v_renewed.id is null
    or v_renewed.previous_league_id is distinct from p_source_league_id then
    v_status := 'affected';
    v_reason := 'season_rollover.renewed_lineage_mismatch';
  elsif v_snapshot.id is null
    or v_snapshot.snapshot_hash<>v_certificate.source_snapshot_hash
    or not coalesce(
      public.is_league_season_official_snapshot_row_valid_v1(v_snapshot.id),
      false
    ) then
    v_status := 'affected';
    v_reason := 'season_rollover.source_snapshot_integrity_failed';
  elsif v_snapshot_head.snapshot_id is null
    or v_snapshot_head.snapshot_status<>'official' then
    v_status := 'affected';
    v_reason := 'season_rollover.source_snapshot_affected';
  elsif v_certificate.certification_status='affected' then
    v_status := 'affected';
    v_reason := v_certificate.certification_reason;
  end if;

  v_previous_status:=v_head.rollover_status;
  v_previous_reason:=v_head.reason_code;
  v_changed := v_previous_status is distinct from v_status
    or v_previous_reason is distinct from v_reason
    or v_head.observed_snapshot_status
      is distinct from coalesce(v_snapshot_head.snapshot_status,'affected')
    or v_head.observed_snapshot_hash
      is distinct from v_certificate.source_snapshot_hash;

  perform set_config(
    'leghevo.season_rollover_certificate_context','on',true
  );

  update public.league_season_rollover_heads
  set rollover_status=v_status,
      reason_code=v_reason,
      observed_snapshot_status=coalesce(
        v_snapshot_head.snapshot_status,'affected'
      ),
      observed_snapshot_hash=v_certificate.source_snapshot_hash,
      affected_at=case
        when v_status='affected' then coalesce(affected_at,now())
        else null
      end,
      last_assessed_at=now(),updated_at=now()
  where source_league_id=p_source_league_id
  returning * into v_head;

  if p_emit_event and v_changed then
    insert into public.league_season_rollover_events(
      source_league_id,renewed_league_id,certificate_id,event_type,
      rollover_status,reason_code,source_snapshot_hash,lineage_hash,
      event_payload
    ) values (
      p_source_league_id,v_certificate.renewed_league_id,v_certificate.id,
      case
        when v_status='affected' then 'affected'
        else 'revalidated'
      end,
      v_status,v_reason,v_certificate.source_snapshot_hash,
      v_certificate.lineage_hash,
      jsonb_build_object(
        'previousStatus',v_previous_status,
        'previousReason',v_previous_reason,
        'sourceSnapshotStatus',coalesce(
          v_snapshot_head.snapshot_status,'affected'
        )
      )
    );
  end if;

  perform set_config(
    'leghevo.season_rollover_certificate_context','',true
  );

  return jsonb_build_object(
    'protected',true,
    'certified',true,
    'healthy',v_status='certified',
    'status',v_status,
    'reasonCode',v_reason,
    'affected',v_status='affected',
    'certificateId',v_certificate.id,
    'sourceLeagueId',v_certificate.source_league_id,
    'renewedLeagueId',v_certificate.renewed_league_id,
    'sourceSeason',v_certificate.source_season,
    'renewedSeason',v_certificate.renewed_season,
    'sourceSnapshotId',v_certificate.source_snapshot_id,
    'sourceSnapshotHash',v_certificate.source_snapshot_hash,
    'lineageHash',v_certificate.lineage_hash,
    'certifiedAt',v_certificate.certified_at,
    'affectedAt',v_head.affected_at
  );
end;
$function$;

revoke all on function public.reconcile_league_season_rollover_v1(uuid,boolean)
from public,anon,authenticated;
grant execute on function public.reconcile_league_season_rollover_v1(uuid,boolean)
to service_role;

create or replace function public.renew_league_season_guarded_v2(
  p_league_id uuid,
  p_next_season text,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_league public.leagues%rowtype;
  v_existing public.league_season_rollovers%rowtype;
  v_existing_certificate public.league_season_rollover_certificates%rowtype;
  v_snapshot public.league_season_official_snapshots%rowtype;
  v_snapshot_head public.league_season_official_snapshot_heads%rowtype;
  v_new_league_id uuid;
  v_invite_code text;
  v_next_season text:=trim(coalesce(p_next_season,''));
  v_member_count integer;
  v_team_count integer;
  v_new_member_count integer;
  v_new_team_count integer;
  v_source_member_fingerprint text;
  v_new_member_fingerprint text;
  v_source_team_fingerprint text;
  v_new_team_fingerprint text;
  v_member_user_id uuid;
  v_result jsonb;
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;
  if p_request_id is null then
    raise exception 'Request ID del rinnovo non valido.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'provider-season-completion-chain:'||p_league_id::text,0
    )
  );
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'league-season-official-snapshot:'||p_league_id::text,0
    )
  );
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'league-season-rollover-lineage:'||p_league_id::text,0
    )
  );

  select league.* into v_league
  from public.leagues league
  where league.id=p_league_id
  for update;
  if not found then
    raise exception 'Lega non trovata.';
  end if;
  if v_league.owner_id<>auth.uid() then
    raise exception 'Solo il Presidente può preparare la nuova stagione.';
  end if;

  select certificate.* into v_existing_certificate
  from public.league_season_rollover_certificates certificate
  where certificate.request_id=p_request_id;
  if found then
    if v_existing_certificate.source_league_id<>p_league_id
      or v_existing_certificate.renewed_season<>v_next_season then
      raise exception
        'Request ID già utilizzato per un rinnovo differente.';
    end if;
    return v_existing_certificate.result_payload
      ||public.reconcile_league_season_rollover_v1(p_league_id,false);
  end if;

  select rollover.* into v_existing
  from public.league_season_rollovers rollover
  where rollover.source_league_id=p_league_id;
  if found then
    if v_existing.renewed_season<>v_next_season then
      raise exception
        'La nuova stagione è già stata preparata per il %.',
        v_existing.renewed_season;
    end if;

    select certificate.* into v_existing_certificate
    from public.league_season_rollover_certificates certificate
    where certificate.source_league_id=p_league_id;

    if not found then
      return public.certify_league_season_rollover_v1(
        p_league_id,p_request_id,true
      );
    end if;

    return v_existing_certificate.result_payload
      ||public.reconcile_league_season_rollover_v1(p_league_id,false);
  end if;

  if v_league.status<>'completed'
    or v_league.competition_completed_at is null then
    raise exception
      'Prima devi chiudere e ufficializzare la stagione corrente.';
  end if;

  perform public.reconcile_league_season_official_snapshot_v1(
    p_league_id,true
  );

  select snapshot_row.* into v_snapshot
  from public.league_season_official_snapshots snapshot_row
  where snapshot_row.league_id=p_league_id
  for share;
  select snapshot_head.* into v_snapshot_head
  from public.league_season_official_snapshot_heads snapshot_head
  where snapshot_head.league_id=p_league_id
  for update;

  if v_snapshot.id is null or v_snapshot_head.snapshot_id is null then
    raise exception
      'Rinnovo bloccato: snapshot ufficiale della stagione assente.';
  end if;
  if v_snapshot_head.snapshot_status<>'official' then
    raise exception
      'Rinnovo bloccato [season_rollover.source_snapshot_affected]: %',
      v_snapshot_head.reason_code;
  end if;
  if not coalesce(
    public.is_league_season_official_snapshot_row_valid_v1(v_snapshot.id),
    false
  ) then
    raise exception
      'Rinnovo bloccato: integrità dello snapshot ufficiale non valida.';
  end if;

  if v_next_season!~'^[0-9]{4}$'
    or v_next_season::integer<2000
    or v_next_season::integer>2100 then
    raise exception
      'La nuova stagione deve avere quattro cifre tra 2000 e 2100.';
  end if;
  if v_snapshot.season!~'^[0-9]{4}$'
    or v_next_season::integer<>v_snapshot.season::integer+1 then
    raise exception
      'La nuova stagione deve essere esattamente successiva al %.',
      v_snapshot.season;
  end if;

  select count(*)::integer into v_member_count
  from public.league_members member
  where member.league_id=p_league_id;
  select count(*)::integer into v_team_count
  from public.fantasy_teams team
  where team.league_id=p_league_id;

  if v_member_count=0 or v_team_count<>v_member_count then
    raise exception
      'Partecipanti e squadre della stagione conclusa non sono allineati.';
  end if;

  v_source_member_fingerprint :=
    public.compute_league_member_identity_fingerprint_v1(p_league_id);
  v_source_team_fingerprint :=
    public.compute_league_team_identity_fingerprint_v1(p_league_id);

  loop
    v_invite_code:=upper(substr(
      replace(gen_random_uuid()::text,'-',''),1,10
    ));
    exit when not exists (
      select 1 from public.leagues league
      where league.invite_code=v_invite_code
    );
  end loop;

  perform set_config('leghevo.season_rollover_writer_context','on',true);

  insert into public.leagues(
    owner_id,name,invite_code,mode,status,team_limit,starting_credits,
    roster_size,scoring_rules,invites_open,calendar_season,
    previous_league_id
  ) values (
    v_league.owner_id,v_league.name,v_invite_code,v_league.mode,'draft',
    v_league.team_limit,v_league.starting_credits,v_league.roster_size,
    (coalesce(v_league.scoring_rules,'{}'::jsonb)-'market_open')
      ||jsonb_build_object('market_open',false),
    false,v_next_season,p_league_id
  ) returning id into v_new_league_id;

  insert into public.league_members(league_id,user_id,role,joined_at)
  select v_new_league_id,member.user_id,member.role,now()
  from public.league_members member
  where member.league_id=p_league_id;

  insert into public.fantasy_teams(
    league_id,manager_id,name,crest_url,credits_remaining
  )
  select v_new_league_id,team.manager_id,team.name,team.crest_url,
    v_league.starting_credits
  from public.fantasy_teams team
  where team.league_id=p_league_id;

  select count(*)::integer into v_new_member_count
  from public.league_members member
  where member.league_id=v_new_league_id;
  select count(*)::integer into v_new_team_count
  from public.fantasy_teams team
  where team.league_id=v_new_league_id;

  v_new_member_fingerprint :=
    public.compute_league_member_identity_fingerprint_v1(v_new_league_id);
  v_new_team_fingerprint :=
    public.compute_league_team_identity_fingerprint_v1(v_new_league_id);

  if v_new_member_count<>v_member_count
    or v_new_team_count<>v_team_count
    or v_new_member_fingerprint<>v_source_member_fingerprint
    or v_new_team_fingerprint<>v_source_team_fingerprint then
    raise exception
      'Rinnovo annullato: copia atomica di partecipanti e squadre non coerente.';
  end if;

  insert into public.league_season_rollovers(
    source_league_id,renewed_league_id,source_season,renewed_season,
    copied_member_count,copied_team_count,renewed_at,renewed_by
  ) values (
    p_league_id,v_new_league_id,v_snapshot.season,v_next_season,
    v_member_count,v_team_count,now(),auth.uid()
  );

  perform set_config('leghevo.season_rollover_writer_context','',true);

  v_result := public.certify_league_season_rollover_v1(
    p_league_id,p_request_id,false
  );

  update public.leagues
  set status='archived',updated_at=now()
  where id=p_league_id;

  for v_member_user_id in
    select member.user_id
    from public.league_members member
    where member.league_id=v_new_league_id
  loop
    perform public.create_user_notification(
      v_member_user_id,v_new_league_id,'league',
      'Nuova stagione certificata',
      v_league.name||' riparte nel '||v_next_season
        ||'. La continuità con lo snapshot ufficiale è certificata.',
      'league',
      jsonb_build_object(
        'event','season_renewed_certified',
        'source_league_id',p_league_id,
        'renewed_league_id',v_new_league_id,
        'source_season',v_snapshot.season,
        'renewed_season',v_next_season,
        'lineage_hash',v_result->>'lineageHash'
      ),
      'season:renewed-certified:'||p_league_id::text||':'
        ||v_member_user_id::text
    );
  end loop;

  return v_result;
end;
$function$;

revoke all on function public.renew_league_season_guarded_v2(
  uuid,text,uuid
) from public,anon,service_role;
grant execute on function public.renew_league_season_guarded_v2(
  uuid,text,uuid
) to authenticated;

-- Anche la RPC storica passa dalla nuova barriera, senza vie di aggiramento.
create or replace function public.renew_league_season(
  p_league_id uuid,
  p_next_season text
)
returns uuid
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_result jsonb;
begin
  v_result:=public.renew_league_season_guarded_v2(
    p_league_id,p_next_season,gen_random_uuid()
  );
  return nullif(v_result->>'renewedLeagueId','')::uuid;
end;
$function$;
revoke all on function public.renew_league_season(uuid,text)
from public,anon,service_role;
grant execute on function public.renew_league_season(uuid,text)
to authenticated;

create or replace function public.reconcile_league_season_rollover_from_snapshot_v1()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
begin
  if exists (
    select 1 from public.league_season_rollover_certificates certificate
    where certificate.source_league_id=new.league_id
  ) then
    perform public.reconcile_league_season_rollover_v1(new.league_id,true);
  end if;
  return new;
end;
$function$;

drop trigger if exists league_season_rollover_snapshot_reconcile
on public.league_season_official_snapshot_heads;
create trigger league_season_rollover_snapshot_reconcile
after update of snapshot_status,reason_code,observed_completion_gate_generation,
  observed_completion_gate_fingerprint
on public.league_season_official_snapshot_heads
for each row
when (
  old.snapshot_status is distinct from new.snapshot_status
  or old.reason_code is distinct from new.reason_code
  or old.observed_completion_gate_generation
    is distinct from new.observed_completion_gate_generation
  or old.observed_completion_gate_fingerprint
    is distinct from new.observed_completion_gate_fingerprint
)
execute function public.reconcile_league_season_rollover_from_snapshot_v1();
alter table public.league_season_official_snapshot_heads
  enable always trigger league_season_rollover_snapshot_reconcile;

-- Adozione non distruttiva dei rinnovi già creati dalle versioni precedenti.
do $backfill$
declare
  v_row record;
begin
  for v_row in
    select rollover.source_league_id
    from public.league_season_rollovers rollover
    left join public.league_season_rollover_certificates certificate
      on certificate.source_league_id=rollover.source_league_id
    where certificate.id is null
    order by rollover.renewed_at,rollover.source_league_id
  loop
    perform public.certify_league_season_rollover_v1(
      v_row.source_league_id,
      pg_catalog.md5(
        'legacy-season-rollover:'||v_row.source_league_id::text
      )::uuid,
      true
    );
  end loop;
end;
$backfill$;

create or replace function public.get_league_season_rollover_gate_v1(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $function$
declare
  v_out_certificate public.league_season_rollover_certificates%rowtype;
  v_in_certificate public.league_season_rollover_certificates%rowtype;
  v_out_head public.league_season_rollover_heads%rowtype;
  v_in_head public.league_season_rollover_heads%rowtype;
  v_out_latest jsonb;
  v_in_latest jsonb;
  v_outgoing jsonb;
  v_incoming jsonb;
  v_primary jsonb;
  v_has_outgoing boolean:=false;
  v_has_incoming boolean:=false;
  v_healthy boolean:=true;
  v_status text:='pending';
  v_reason text:='season_rollover.not_created';
begin
  if auth.uid() is null then
    raise exception 'Devi effettuare l''accesso.';
  end if;
  if not public.is_league_member(p_league_id)
    and not public.is_league_admin(p_league_id) then
    raise exception 'Non fai parte di questa lega.';
  end if;

  select certificate.* into v_out_certificate
  from public.league_season_rollover_certificates certificate
  where certificate.source_league_id=p_league_id;
  v_has_outgoing:=found;

  if v_has_outgoing then
    select head.* into v_out_head
    from public.league_season_rollover_heads head
    where head.certificate_id=v_out_certificate.id;
    if not found then
      raise exception 'Testa del rinnovo uscente certificato non trovata.';
    end if;

    select jsonb_build_object(
      'id',event_row.id,
      'eventType',event_row.event_type,
      'status',event_row.rollover_status,
      'reasonCode',event_row.reason_code,
      'createdAt',event_row.created_at
    ) into v_out_latest
    from public.league_season_rollover_events event_row
    where event_row.certificate_id=v_out_certificate.id
    order by event_row.created_at desc,event_row.id desc
    limit 1;

    v_outgoing:=jsonb_build_object(
      'relation','outgoing',
      'healthy',v_out_head.rollover_status='certified',
      'status',v_out_head.rollover_status,
      'reasonCode',v_out_head.reason_code,
      'affected',v_out_head.rollover_status='affected',
      'certificateId',v_out_certificate.id,
      'sourceLeagueId',v_out_certificate.source_league_id,
      'renewedLeagueId',v_out_certificate.renewed_league_id,
      'sourceSeason',v_out_certificate.source_season,
      'renewedSeason',v_out_certificate.renewed_season,
      'sourceSnapshotId',v_out_certificate.source_snapshot_id,
      'sourceSnapshotHash',v_out_certificate.source_snapshot_hash,
      'lineageHash',v_out_certificate.lineage_hash,
      'copiedMemberCount',v_out_certificate.copied_member_count,
      'copiedTeamCount',v_out_certificate.copied_team_count,
      'certifiedAt',v_out_certificate.certified_at,
      'affectedAt',v_out_head.affected_at,
      'latestEvent',v_out_latest
    );
  end if;

  select certificate.* into v_in_certificate
  from public.league_season_rollover_certificates certificate
  where certificate.renewed_league_id=p_league_id;
  v_has_incoming:=found;

  if v_has_incoming then
    select head.* into v_in_head
    from public.league_season_rollover_heads head
    where head.certificate_id=v_in_certificate.id;
    if not found then
      raise exception 'Testa del rinnovo entrante certificato non trovata.';
    end if;

    select jsonb_build_object(
      'id',event_row.id,
      'eventType',event_row.event_type,
      'status',event_row.rollover_status,
      'reasonCode',event_row.reason_code,
      'createdAt',event_row.created_at
    ) into v_in_latest
    from public.league_season_rollover_events event_row
    where event_row.certificate_id=v_in_certificate.id
    order by event_row.created_at desc,event_row.id desc
    limit 1;

    v_incoming:=jsonb_build_object(
      'relation','incoming',
      'healthy',v_in_head.rollover_status='certified',
      'status',v_in_head.rollover_status,
      'reasonCode',v_in_head.reason_code,
      'affected',v_in_head.rollover_status='affected',
      'certificateId',v_in_certificate.id,
      'sourceLeagueId',v_in_certificate.source_league_id,
      'renewedLeagueId',v_in_certificate.renewed_league_id,
      'sourceSeason',v_in_certificate.source_season,
      'renewedSeason',v_in_certificate.renewed_season,
      'sourceSnapshotId',v_in_certificate.source_snapshot_id,
      'sourceSnapshotHash',v_in_certificate.source_snapshot_hash,
      'lineageHash',v_in_certificate.lineage_hash,
      'copiedMemberCount',v_in_certificate.copied_member_count,
      'copiedTeamCount',v_in_certificate.copied_team_count,
      'certifiedAt',v_in_certificate.certified_at,
      'affectedAt',v_in_head.affected_at,
      'latestEvent',v_in_latest
    );
  end if;

  if not v_has_outgoing and not v_has_incoming then
    return jsonb_build_object(
      'protected',true,'certified',false,'healthy',true,
      'status','pending','reasonCode','season_rollover.not_created',
      'affected',false,'isSource',false,
      'incoming',null,'outgoing',null
    );
  end if;

  v_primary:=coalesce(v_outgoing,v_incoming);
  v_healthy:=(not v_has_outgoing or v_out_head.rollover_status='certified')
    and (not v_has_incoming or v_in_head.rollover_status='certified');
  v_status:=case when v_healthy then 'certified' else 'affected' end;
  v_reason:=case
    when v_has_outgoing and v_out_head.rollover_status='affected'
      then v_out_head.reason_code
    when v_has_incoming and v_in_head.rollover_status='affected'
      then v_in_head.reason_code
    else coalesce(v_primary->>'reasonCode','season_rollover.lineage_certified')
  end;

  return v_primary||jsonb_build_object(
    'protected',true,
    'certified',true,
    'relation',case
      when v_has_outgoing and v_has_incoming then 'bidirectional'
      when v_has_outgoing then 'outgoing'
      else 'incoming'
    end,
    'isSource',v_has_outgoing,
    'healthy',v_healthy,
    'status',v_status,
    'reasonCode',v_reason,
    'affected',not v_healthy,
    'incoming',v_incoming,
    'outgoing',v_outgoing
  );
end;
$function$;
revoke all on function public.get_league_season_rollover_gate_v1(uuid)
from public,anon,service_role;
grant execute on function public.get_league_season_rollover_gate_v1(uuid)
to authenticated;

create or replace function public.get_league_season_state_v7(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $function$
declare
  v_state jsonb;
  v_rollover jsonb;
  v_snapshot_ready boolean;
begin
  v_state:=public.get_league_season_state_v6(p_league_id);
  v_rollover:=public.get_league_season_rollover_gate_v1(p_league_id);
  v_snapshot_ready:=coalesce(
      (v_state->>'officialSnapshotPublished')::boolean,false
    ) and coalesce(
      v_state->>'officialSnapshotStatus','pending'
    )='official';

  return v_state||jsonb_build_object(
    'seasonRolloverProtected',true,
    'seasonRolloverCertified',
      coalesce((v_rollover->>'certified')::boolean,false),
    'seasonRolloverHealthy',
      coalesce((v_rollover->>'healthy')::boolean,true),
    'seasonRolloverStatus',coalesce(v_rollover->>'status','pending'),
    'seasonRolloverReason',v_rollover->>'reasonCode',
    'seasonRolloverAffected',
      coalesce((v_rollover->>'affected')::boolean,false),
    'seasonRolloverCertificateId',
      nullif(v_rollover->>'certificateId','')::bigint,
    'seasonRolloverLineageHash',v_rollover->>'lineageHash',
    'seasonRolloverSourceSnapshotHash',
      v_rollover->>'sourceSnapshotHash',
    'canRenew',coalesce((v_state->>'canRenew')::boolean,false)
      and v_snapshot_ready
      and not (
        coalesce((v_rollover->>'certified')::boolean,false)
        and coalesce((v_rollover->>'isSource')::boolean,false)
      ),
    'seasonRollover',v_rollover
  );
end;
$function$;
revoke all on function public.get_league_season_state_v7(uuid)
from public,anon,service_role;
grant execute on function public.get_league_season_state_v7(uuid)
to authenticated;

create or replace function public.get_league_management_state_v17(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $function$
declare
  v_state jsonb;
  v_season jsonb;
  v_checks jsonb;
begin
  v_state:=public.get_league_management_state_v16(p_league_id);
  v_season:=public.get_league_season_state_v7(p_league_id);
  v_checks:=coalesce(v_state->'checks','{}'::jsonb);

  return v_state||v_season||jsonb_build_object(
    'checks',v_checks||jsonb_build_object(
      'seasonRolloverProtected',true,
      'seasonRolloverCertified',
        coalesce((v_season->>'seasonRolloverCertified')::boolean,false),
      'seasonRolloverHealthy',
        coalesce((v_season->>'seasonRolloverHealthy')::boolean,true)
    )
  );
end;
$function$;
revoke all on function public.get_league_management_state_v17(uuid)
from public,anon,service_role;
grant execute on function public.get_league_management_state_v17(uuid)
to authenticated;

create or replace function public.get_league_provider_sync_health_v28(
  p_league_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $function$
declare
  v_base jsonb;
  v_rollover jsonb;
  v_healthy boolean;
begin
  v_base:=public.get_league_provider_sync_health_v27(p_league_id);
  v_rollover:=public.get_league_season_rollover_gate_v1(p_league_id);
  v_healthy:=coalesce((v_base->>'healthy')::boolean,false)
    and coalesce((v_rollover->>'healthy')::boolean,true);

  return v_base||jsonb_build_object(
    'protected',coalesce((v_base->>'protected')::boolean,false)
      and coalesce((v_rollover->>'protected')::boolean,false),
    'healthy',v_healthy,
    'status',case when v_healthy then coalesce(v_base->>'status','idle')
      else 'attention' end,
    'seasonRolloverLineage',v_rollover
  );
end;
$function$;
revoke all on function public.get_league_provider_sync_health_v28(uuid)
from public,anon,service_role;
grant execute on function public.get_league_provider_sync_health_v28(uuid)
to authenticated;

-- Solo lo storico append-only viene pubblicato in Realtime.
do $realtime$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='league_season_rollover_events'
  ) then
    alter publication supabase_realtime
      add table public.league_season_rollover_events;
  end if;
end;
$realtime$;

create or replace function public.get_league_season_rollover_integrity_v1()
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $function$
declare
  v_guarded text:='';
  v_legacy text:='';
  v_certify text:='';
  v_reconcile text:='';
  v_state text:='';
  v_management text:='';
begin
  select lower(pg_catalog.pg_get_functiondef(
    'public.renew_league_season_guarded_v2(uuid,text,uuid)'::regprocedure
  )) into v_guarded;
  select lower(pg_catalog.pg_get_functiondef(
    'public.renew_league_season(uuid,text)'::regprocedure
  )) into v_legacy;
  select lower(pg_catalog.pg_get_functiondef(
    'public.certify_league_season_rollover_v1(uuid,uuid,boolean)'::regprocedure
  )) into v_certify;
  select lower(pg_catalog.pg_get_functiondef(
    'public.reconcile_league_season_rollover_v1(uuid,boolean)'::regprocedure
  )) into v_reconcile;
  select lower(pg_catalog.pg_get_functiondef(
    'public.get_league_season_state_v7(uuid)'::regprocedure
  )) into v_state;
  select lower(pg_catalog.pg_get_functiondef(
    'public.get_league_management_state_v17(uuid)'::regprocedure
  )) into v_management;

  return jsonb_build_object(
    'predecessor_ready',
      to_regprocedure(
        'public.get_league_season_official_snapshot_integrity_v1()'
      ) is not null
      and (select count(*) from jsonb_each(
        public.get_league_season_official_snapshot_integrity_v1()
      ))=20
      and not exists (
        select 1 from jsonb_each(
          public.get_league_season_official_snapshot_integrity_v1()
        ) check_row
        where jsonb_typeof(check_row.value) is distinct from 'boolean'
           or check_row.value is distinct from 'true'::jsonb
      ),
    'certificate_table_ready',
      to_regclass('public.league_season_rollover_certificates') is not null,
    'head_table_ready',
      to_regclass('public.league_season_rollover_heads') is not null,
    'event_table_ready',
      to_regclass('public.league_season_rollover_events') is not null,
    'columns_ready',not exists (
      select 1 from (values
        ('league_season_rollover_certificates','source_snapshot_hash'),
        ('league_season_rollover_certificates','lineage_hash'),
        ('league_season_rollover_certificates','request_id'),
        ('league_season_rollover_heads','rollover_status'),
        ('league_season_rollover_heads','affected_at'),
        ('league_season_rollover_events','event_type'),
        ('league_season_rollover_events','event_payload')
      ) required(table_name,column_name)
      where not exists (
        select 1 from information_schema.columns column_row
        where column_row.table_schema='public'
          and column_row.table_name=required.table_name
          and column_row.column_name=required.column_name
      )
    ),
    'constraints_ready',
      (select count(*) from pg_catalog.pg_constraint constraint_row
       where constraint_row.conrelid=
         'public.league_season_rollover_certificates'::regclass
         and constraint_row.contype in ('p','u','f','c'))>=17
      and (select count(*) from pg_catalog.pg_constraint constraint_row
       where constraint_row.conrelid=
         'public.league_season_rollover_heads'::regclass
         and constraint_row.contype in ('p','u','f','c'))>=9
      and (select count(*) from pg_catalog.pg_constraint constraint_row
       where constraint_row.conrelid=
         'public.league_season_rollover_events'::regclass
         and constraint_row.contype in ('p','f','c'))>=10,
    'indexes_ready',
      to_regclass(
        'public.league_season_rollover_certificates_created_idx'
      ) is not null
      and to_regclass(
        'public.league_season_rollover_heads_status_idx'
      ) is not null
      and to_regclass(
        'public.league_season_rollover_events_source_idx'
      ) is not null
      and to_regclass(
        'public.league_season_rollover_events_renewed_idx'
      ) is not null,
    'rls_ready',
      (select relrowsecurity from pg_catalog.pg_class
       where oid='public.league_season_rollover_certificates'::regclass)
      and (select relrowsecurity from pg_catalog.pg_class
       where oid='public.league_season_rollover_heads'::regclass)
      and (select relrowsecurity from pg_catalog.pg_class
       where oid='public.league_season_rollover_events'::regclass)
      and exists (
        select 1 from pg_catalog.pg_policy policy_row
        where policy_row.polrelid=
          'public.league_season_rollover_certificates'::regclass
          and policy_row.polname=
            'league_season_rollover_certificates_member_select'
      )
      and exists (
        select 1 from pg_catalog.pg_policy policy_row
        where policy_row.polrelid=
          'public.league_season_rollover_heads'::regclass
          and policy_row.polname='league_season_rollover_heads_member_select'
      )
      and exists (
        select 1 from pg_catalog.pg_policy policy_row
        where policy_row.polrelid=
          'public.league_season_rollover_events'::regclass
          and policy_row.polname=
            'league_season_rollover_events_director_select'
      ),
    'direct_write_blocked',
      not has_table_privilege('authenticated',
        'public.league_season_rollover_certificates','INSERT')
      and not has_table_privilege('authenticated',
        'public.league_season_rollover_heads','UPDATE')
      and not has_table_privilege('authenticated',
        'public.league_season_rollover_events','INSERT')
      and not has_table_privilege('service_role',
        'public.league_season_rollover_certificates','INSERT')
      and not has_table_privilege('service_role',
        'public.league_season_rollover_heads','UPDATE')
      and not has_table_privilege('service_role',
        'public.league_season_rollover_events','INSERT'),
    'immutable_certificate_ready',exists (
      select 1 from pg_catalog.pg_trigger trigger_row
      where trigger_row.tgrelid=
        'public.league_season_rollover_certificates'::regclass
        and trigger_row.tgname=
          'league_season_rollover_certificates_immutable'
        and trigger_row.tgenabled='A' and not trigger_row.tgisinternal
    )
    and exists (
      select 1 from pg_catalog.pg_trigger trigger_row
      where trigger_row.tgrelid=
        'public.league_season_rollover_heads'::regclass
        and trigger_row.tgname='league_season_rollover_heads_guard'
        and trigger_row.tgenabled='A' and not trigger_row.tgisinternal
    ),
    'rollover_and_lineage_guards_ready',
      exists (
        select 1 from pg_catalog.pg_trigger trigger_row
        where trigger_row.tgrelid='public.league_season_rollovers'::regclass
          and trigger_row.tgname='league_season_rollovers_certified_guard'
          and trigger_row.tgenabled='A' and not trigger_row.tgisinternal
      )
      and exists (
        select 1 from pg_catalog.pg_trigger trigger_row
        where trigger_row.tgrelid='public.leagues'::regclass
          and trigger_row.tgname='leagues_season_lineage_link_guard'
          and trigger_row.tgenabled='A' and not trigger_row.tgisinternal
      )
      and to_regclass(
        'public.leagues_previous_league_unique_idx'
      ) is not null,
    'immutable_events_ready',exists (
      select 1 from pg_catalog.pg_trigger trigger_row
      where trigger_row.tgrelid=
        'public.league_season_rollover_events'::regclass
        and trigger_row.tgname='league_season_rollover_events_immutable'
        and trigger_row.tgenabled='A' and not trigger_row.tgisinternal
    ),
    'fingerprint_helpers_ready',
      to_regprocedure(
        'public.compute_league_member_identity_fingerprint_v1(uuid)'
      ) is not null
      and to_regprocedure(
        'public.compute_league_team_identity_fingerprint_v1(uuid)'
      ) is not null
      and to_regprocedure(
        'public.compute_league_season_rollover_lineage_hash_v1(uuid,uuid,bigint,text,text,text,integer,integer,text,text,text,text)'
      ) is not null
      and to_regprocedure(
        'public.is_league_season_official_snapshot_row_valid_v1(bigint)'
      ) is not null,
    'certify_rpc_ready',
      to_regprocedure(
        'public.certify_league_season_rollover_v1(uuid,uuid,boolean)'
      ) is not null
      and position('provider-season-completion-chain' in v_certify)>0
      and position('league-season-official-snapshot' in v_certify)>0
      and position('league-season-rollover-lineage' in v_certify)>0
      and position('source_snapshot_hash' in v_certify)>0,
    'reconcile_rpc_ready',
      to_regprocedure(
        'public.reconcile_league_season_rollover_v1(uuid,boolean)'
      ) is not null
      and position('provider-season-completion-chain' in v_reconcile)>0
      and position('league-season-official-snapshot' in v_reconcile)>0
      and position('league-season-rollover-lineage' in v_reconcile)>0
      and position('certificate_hash_mismatch' in v_reconcile)>0
      and position('source_snapshot_affected' in v_reconcile)>0,
    'guarded_renewal_ready',
      to_regprocedure(
        'public.renew_league_season_guarded_v2(uuid,text,uuid)'
      ) is not null
      and has_function_privilege('authenticated',
        'public.renew_league_season_guarded_v2(uuid,text,uuid)','EXECUTE')
      and not has_function_privilege('anon',
        'public.renew_league_season_guarded_v2(uuid,text,uuid)','EXECUTE')
      and position('provider-season-completion-chain' in v_guarded)>0
      and position('league-season-official-snapshot' in v_guarded)>0
      and position('league-season-rollover-lineage' in v_guarded)>0
      and position('source_snapshot_affected' in v_guarded)>0
      and position('certify_league_season_rollover_v1' in v_guarded)>0,
    'legacy_rpc_protected',
      to_regprocedure('public.renew_league_season(uuid,text)') is not null
      and position('renew_league_season_guarded_v2' in v_legacy)>0
      and has_function_privilege('authenticated',
        'public.renew_league_season(uuid,text)','EXECUTE')
      and not has_function_privilege('anon',
        'public.renew_league_season(uuid,text)','EXECUTE'),
    'snapshot_reconcile_trigger_ready',exists (
      select 1 from pg_catalog.pg_trigger trigger_row
      where trigger_row.tgrelid=
        'public.league_season_official_snapshot_heads'::regclass
        and trigger_row.tgname='league_season_rollover_snapshot_reconcile'
        and trigger_row.tgenabled='A' and not trigger_row.tgisinternal
    ),
    'state_and_management_ready',
      to_regprocedure('public.get_league_season_state_v7(uuid)') is not null
      and to_regprocedure(
        'public.get_league_management_state_v17(uuid)'
      ) is not null
      and has_function_privilege('authenticated',
        'public.get_league_season_state_v7(uuid)','EXECUTE')
      and has_function_privilege('authenticated',
        'public.get_league_management_state_v17(uuid)','EXECUTE')
      and position('seasonrolloverprotected' in replace(v_state,'_',''))>0
      and position('seasonrolloverprotected' in replace(v_management,'_',''))>0,
    'backfill_and_health_ready',
      not exists (
        select 1
        from public.league_season_rollovers rollover
        left join public.league_season_official_snapshots snapshot_row
          on snapshot_row.league_id=rollover.source_league_id
        left join public.league_season_rollover_certificates certificate
          on certificate.source_league_id=rollover.source_league_id
        left join public.league_season_rollover_heads head
          on head.certificate_id=certificate.id
        where snapshot_row.id is null
           or certificate.id is null
           or head.certificate_id is null
           or certificate.renewed_league_id<>rollover.renewed_league_id
           or certificate.source_snapshot_id<>snapshot_row.id
           or certificate.lineage_hash<>
             public.compute_league_season_rollover_lineage_hash_v1(
               certificate.source_league_id,certificate.renewed_league_id,
               certificate.source_snapshot_id,certificate.source_snapshot_hash,
               certificate.source_season,certificate.renewed_season,
               certificate.copied_member_count,certificate.copied_team_count,
               certificate.source_member_fingerprint,
               certificate.renewed_member_fingerprint,
               certificate.source_team_fingerprint,
               certificate.renewed_team_fingerprint
             )
      )
      and to_regprocedure(
        'public.get_league_provider_sync_health_v28(uuid)'
      ) is not null
      and has_function_privilege('authenticated',
        'public.get_league_provider_sync_health_v28(uuid)','EXECUTE')
      and exists (
        select 1 from pg_publication_tables
        where pubname='supabase_realtime' and schemaname='public'
          and tablename='league_season_rollover_events'
      )
  );
end;
$function$;

revoke all on function public.get_league_season_rollover_integrity_v1()
from public,anon,authenticated;
grant execute on function public.get_league_season_rollover_integrity_v1()
to service_role;

-- Validazione transazionale: esattamente 20 controlli booleani true.
do $validation$
declare
  v_checks jsonb;
begin
  v_checks:=public.get_league_season_rollover_integrity_v1();
  if (select count(*) from jsonb_each(v_checks))<>20
    or exists (
      select 1 from jsonb_each(v_checks) check_row
      where jsonb_typeof(check_row.value) is distinct from 'boolean'
         or check_row.value is distinct from 'true'::jsonb
    ) then
    raise exception
      'Validazione v0.62.29 non superata: %',v_checks;
  end if;
end;
$validation$;

commit;

-- Diagnostica finale: devono comparire esattamente 20 valori true.
select
  (public.get_league_season_rollover_integrity_v1()
    ->>'predecessor_ready')::boolean as predecessor_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'certificate_table_ready')::boolean as certificate_table_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'head_table_ready')::boolean as head_table_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'event_table_ready')::boolean as event_table_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'columns_ready')::boolean as columns_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'constraints_ready')::boolean as constraints_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'indexes_ready')::boolean as indexes_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'rls_ready')::boolean as rls_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'direct_write_blocked')::boolean as direct_write_blocked,
  (public.get_league_season_rollover_integrity_v1()
    ->>'immutable_certificate_ready')::boolean
      as immutable_certificate_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'rollover_and_lineage_guards_ready')::boolean
      as rollover_and_lineage_guards_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'immutable_events_ready')::boolean as immutable_events_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'fingerprint_helpers_ready')::boolean as fingerprint_helpers_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'certify_rpc_ready')::boolean as certify_rpc_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'reconcile_rpc_ready')::boolean as reconcile_rpc_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'guarded_renewal_ready')::boolean as guarded_renewal_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'legacy_rpc_protected')::boolean as legacy_rpc_protected,
  (public.get_league_season_rollover_integrity_v1()
    ->>'snapshot_reconcile_trigger_ready')::boolean
      as snapshot_reconcile_trigger_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'state_and_management_ready')::boolean
      as state_and_management_ready,
  (public.get_league_season_rollover_integrity_v1()
    ->>'backfill_and_health_ready')::boolean
      as backfill_and_health_ready;
