-- LEGHEVO v0.62.30
-- Bootstrap provider certificato della nuova stagione.
-- Migrazione interna: database/134_provider_new_season_bootstrap_barrier_safety.sql
-- Eseguire dopo database/133_league_season_rollover_lineage_safety.sql.
--
-- La nuova stagione non può consumare il catalogo calciatori della stagione
-- precedente e non può generare il calendario su partite provider non coerenti.
-- Le leghe non provenienti da un rinnovo certificato restano compatibili.
-- Una regressione successiva non cancella dati sportivi: marca il bootstrap
-- affected e rende necessaria la verifica della Direzione.

begin;

-- PRE-FLIGHT: la continuità anti-fork della v0.62.29 deve essere integra.
do $preflight$
declare
  v_integrity jsonb;
  v_missing text[]:=array[]::text[];
  v_required text;
begin
  if to_regprocedure('public.get_league_season_rollover_integrity_v1()') is null then
    raise exception
      'Preflight v0.62.30 non superato: manca la diagnostica v0.62.29.';
  end if;

  v_integrity:=public.get_league_season_rollover_integrity_v1();
  if (select count(*) from jsonb_each(v_integrity))<>20
    or exists(
      select 1 from jsonb_each(v_integrity) c
      where jsonb_typeof(c.value) is distinct from 'boolean'
         or c.value is distinct from 'true'::jsonb
    ) then
    raise exception
      'Preflight v0.62.30 non superato: la v0.62.29 non è integra.';
  end if;

  foreach v_required in array array[
    'public.leagues','public.league_season_rollover_certificates',
    'public.league_season_rollover_heads','public.provider_player_catalog_heads',
    'public.provider_player_catalog_reconciliations',
    'public.provider_sync_publications','public.provider_sync_runs',
    'public.provider_sync_scope_certificates','public.provider_fixtures',
    'public.matchdays','public.fantasy_fixtures','public.auctions',
    'public.auction_items','public.roster_entries'
  ] loop
    if to_regclass(v_required) is null then
      v_missing:=array_append(v_missing,'table '||v_required);
    end if;
  end loop;

  foreach v_required in array array[
    'public.renew_league_season_guarded_v2(uuid,text,uuid)',
    'public.get_league_season_state_v7(uuid)',
    'public.get_league_management_state_v17(uuid)',
    'public.get_league_provider_sync_health_v28(uuid)',
    'public.is_league_admin(uuid)',
    'public.is_league_member(uuid)'
  ] loop
    if to_regprocedure(v_required) is null then
      v_missing:=array_append(v_missing,'function '||v_required);
    end if;
  end loop;

  if coalesce(array_length(v_missing,1),0)>0 then
    raise exception 'Preflight v0.62.30 non superato. Dipendenze mancanti: %',
      array_to_string(v_missing,'; ');
  end if;
end;
$preflight$;

create table if not exists public.provider_season_bootstrap_certificates(
  id bigint generated by default as identity primary key,
  league_id uuid not null unique references public.leagues(id) on delete restrict,
  rollover_certificate_id bigint not null unique
    references public.league_season_rollover_certificates(id) on delete restrict,
  provider text not null,
  competition_code text not null,
  season integer not null,
  catalog_head_id uuid not null
    references public.provider_player_catalog_heads(id) on delete restrict,
  catalog_publication_id uuid not null
    references public.provider_sync_publications(id) on delete restrict,
  catalog_run_id uuid not null
    references public.provider_sync_runs(id) on delete restrict,
  catalog_generation bigint not null,
  catalog_player_count integer not null,
  fixture_scope_certificate_id uuid not null
    references public.provider_sync_scope_certificates(id) on delete restrict,
  fixture_publication_id uuid not null
    references public.provider_sync_publications(id) on delete restrict,
  fixture_run_id uuid not null
    references public.provider_sync_runs(id) on delete restrict,
  fixture_count integer not null,
  matchday_count integer not null,
  fixture_team_count integer not null,
  first_kickoff_at timestamptz not null,
  last_kickoff_at timestamptz not null,
  fixture_fingerprint text not null,
  bootstrap_hash text not null,
  certified_by uuid references public.profiles(id) on delete set null,
  certified_at timestamptz not null default now(),
  result_payload jsonb not null default '{}'::jsonb,
  constraint provider_season_bootstrap_cert_provider_check
    check(char_length(trim(provider)) between 1 and 100 and provider!~E'[\r\n]'),
  constraint provider_season_bootstrap_cert_competition_check
    check(competition_code='IT-SA'),
  constraint provider_season_bootstrap_cert_season_check
    check(season between 2000 and 2200),
  constraint provider_season_bootstrap_cert_generation_check
    check(catalog_generation>0),
  constraint provider_season_bootstrap_cert_counts_check
    check(catalog_player_count>=300 and fixture_count>=380
      and matchday_count>=38 and fixture_team_count>=20),
  constraint provider_season_bootstrap_cert_dates_check
    check(first_kickoff_at<=last_kickoff_at),
  constraint provider_season_bootstrap_cert_fixture_hash_check
    check(fixture_fingerprint~'^[0-9a-f]{32}$'),
  constraint provider_season_bootstrap_cert_hash_check
    check(bootstrap_hash~'^[0-9a-f]{32}$'),
  constraint provider_season_bootstrap_cert_payload_check
    check(jsonb_typeof(result_payload)='object')
);

create table if not exists public.provider_season_bootstrap_heads(
  league_id uuid primary key references public.leagues(id) on delete restrict,
  certificate_id bigint unique
    references public.provider_season_bootstrap_certificates(id) on delete restrict,
  bootstrap_status text not null,
  reason_code text not null,
  observed_season integer not null,
  catalog_ready boolean not null default false,
  fixtures_ready boolean not null default false,
  observed_provider text,
  observed_catalog_season integer,
  observed_catalog_generation bigint,
  observed_catalog_player_count integer not null default 0,
  observed_fixture_count integer not null default 0,
  observed_matchday_count integer not null default 0,
  observed_fixture_team_count integer not null default 0,
  observed_fixture_fingerprint text,
  affected_at timestamptz,
  last_assessed_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint provider_season_bootstrap_heads_status_check
    check(bootstrap_status in ('waiting','catalog_ready','ready','affected')),
  constraint provider_season_bootstrap_heads_reason_check
    check(char_length(trim(reason_code)) between 3 and 180),
  constraint provider_season_bootstrap_heads_season_check
    check(observed_season between 2000 and 2200),
  constraint provider_season_bootstrap_heads_provider_check
    check(observed_provider is null or (
      char_length(trim(observed_provider)) between 1 and 100
      and observed_provider!~E'[\r\n]'
    )),
  constraint provider_season_bootstrap_heads_catalog_check
    check(
      observed_catalog_season is null
      or observed_catalog_season between 2000 and 2200
    ),
  constraint provider_season_bootstrap_heads_generation_check
    check(observed_catalog_generation is null or observed_catalog_generation>0),
  constraint provider_season_bootstrap_heads_counts_check
    check(
      observed_catalog_player_count>=0
      and observed_fixture_count>=0
      and observed_matchday_count>=0
      and observed_fixture_team_count>=0
    ),
  constraint provider_season_bootstrap_heads_fixture_hash_check
    check(
      observed_fixture_fingerprint is null
      or observed_fixture_fingerprint~'^[0-9a-f]{32}$'
    ),
  constraint provider_season_bootstrap_heads_state_check
    check(
      (bootstrap_status='waiting' and not catalog_ready and not fixtures_ready
        and certificate_id is null and affected_at is null)
      or (bootstrap_status='catalog_ready' and catalog_ready and not fixtures_ready
        and certificate_id is null and affected_at is null)
      or (bootstrap_status='ready' and catalog_ready and fixtures_ready
        and certificate_id is not null and affected_at is null)
      or (bootstrap_status='affected' and affected_at is not null)
    )
);

create table if not exists public.provider_season_bootstrap_events(
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete restrict,
  certificate_id bigint
    references public.provider_season_bootstrap_certificates(id) on delete restrict,
  event_type text not null,
  bootstrap_status text not null,
  reason_code text not null,
  observed_season integer not null,
  catalog_ready boolean not null,
  fixtures_ready boolean not null,
  observed_catalog_generation bigint,
  observed_catalog_player_count integer not null,
  observed_fixture_count integer not null,
  observed_matchday_count integer not null,
  observed_fixture_team_count integer not null,
  observed_fixture_fingerprint text,
  event_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint provider_season_bootstrap_events_type_check
    check(event_type in ('waiting','catalog_ready','certified','affected','revalidated')),
  constraint provider_season_bootstrap_events_status_check
    check(bootstrap_status in ('waiting','catalog_ready','ready','affected')),
  constraint provider_season_bootstrap_events_reason_check
    check(char_length(trim(reason_code)) between 3 and 180),
  constraint provider_season_bootstrap_events_season_check
    check(observed_season between 2000 and 2200),
  constraint provider_season_bootstrap_events_generation_check
    check(observed_catalog_generation is null or observed_catalog_generation>0),
  constraint provider_season_bootstrap_events_counts_check
    check(
      observed_catalog_player_count>=0 and observed_fixture_count>=0
      and observed_matchday_count>=0 and observed_fixture_team_count>=0
    ),
  constraint provider_season_bootstrap_events_fixture_hash_check
    check(
      observed_fixture_fingerprint is null
      or observed_fixture_fingerprint~'^[0-9a-f]{32}$'
    ),
  constraint provider_season_bootstrap_events_payload_check
    check(jsonb_typeof(event_payload)='object')
);

create index if not exists provider_season_bootstrap_certificates_created_idx
  on public.provider_season_bootstrap_certificates(league_id,certified_at desc);
create index if not exists provider_season_bootstrap_heads_status_idx
  on public.provider_season_bootstrap_heads(bootstrap_status,updated_at desc);
create index if not exists provider_season_bootstrap_events_league_idx
  on public.provider_season_bootstrap_events(league_id,created_at desc,id desc);

alter table public.provider_season_bootstrap_certificates enable row level security;
alter table public.provider_season_bootstrap_heads enable row level security;
alter table public.provider_season_bootstrap_events enable row level security;
alter table public.provider_season_bootstrap_events replica identity full;

revoke all on public.provider_season_bootstrap_certificates
from public,anon,authenticated,service_role;
revoke all on public.provider_season_bootstrap_heads
from public,anon,authenticated,service_role;
revoke all on public.provider_season_bootstrap_events
from public,anon,authenticated,service_role;
grant select on public.provider_season_bootstrap_certificates to authenticated;
grant select on public.provider_season_bootstrap_heads to authenticated;
grant select on public.provider_season_bootstrap_events to authenticated;

drop policy if exists provider_season_bootstrap_certificates_member_select
on public.provider_season_bootstrap_certificates;
create policy provider_season_bootstrap_certificates_member_select
on public.provider_season_bootstrap_certificates
for select to authenticated using(
  public.is_league_member(league_id) or public.is_league_admin(league_id)
);

drop policy if exists provider_season_bootstrap_heads_member_select
on public.provider_season_bootstrap_heads;
create policy provider_season_bootstrap_heads_member_select
on public.provider_season_bootstrap_heads
for select to authenticated using(
  public.is_league_member(league_id) or public.is_league_admin(league_id)
);

drop policy if exists provider_season_bootstrap_events_member_select
on public.provider_season_bootstrap_events;
create policy provider_season_bootstrap_events_member_select
on public.provider_season_bootstrap_events
for select to authenticated using(
  public.is_league_member(league_id) or public.is_league_admin(league_id)
);

create or replace function public.prevent_provider_season_bootstrap_immutable_v1()
returns trigger language plpgsql security definer set search_path='' as $function$
begin
  raise exception 'Registro bootstrap provider immutabile.';
end;
$function$;
revoke all on function public.prevent_provider_season_bootstrap_immutable_v1()
from public,anon,authenticated,service_role;

drop trigger if exists provider_season_bootstrap_certificates_immutable
on public.provider_season_bootstrap_certificates;
create trigger provider_season_bootstrap_certificates_immutable
before update or delete on public.provider_season_bootstrap_certificates
for each row execute function public.prevent_provider_season_bootstrap_immutable_v1();
alter table public.provider_season_bootstrap_certificates
  enable always trigger provider_season_bootstrap_certificates_immutable;

drop trigger if exists provider_season_bootstrap_events_immutable
on public.provider_season_bootstrap_events;
create trigger provider_season_bootstrap_events_immutable
before update or delete on public.provider_season_bootstrap_events
for each row execute function public.prevent_provider_season_bootstrap_immutable_v1();
alter table public.provider_season_bootstrap_events
  enable always trigger provider_season_bootstrap_events_immutable;

create or replace function public.guard_provider_season_bootstrap_writes_v1()
returns trigger language plpgsql security definer set search_path='' as $function$
begin
  if coalesce(current_setting('leghevo.provider_season_bootstrap_context',true),'')<>'on' then
    raise exception 'Scrittura bootstrap provider consentita solo alle RPC certificate.';
  end if;
  if tg_op='DELETE' then return old; end if;
  return new;
end;
$function$;
revoke all on function public.guard_provider_season_bootstrap_writes_v1()
from public,anon,authenticated,service_role;

drop trigger if exists provider_season_bootstrap_certificates_insert_guard
on public.provider_season_bootstrap_certificates;
create trigger provider_season_bootstrap_certificates_insert_guard
before insert on public.provider_season_bootstrap_certificates
for each row execute function public.guard_provider_season_bootstrap_writes_v1();
alter table public.provider_season_bootstrap_certificates
  enable always trigger provider_season_bootstrap_certificates_insert_guard;

drop trigger if exists provider_season_bootstrap_events_insert_guard
on public.provider_season_bootstrap_events;
create trigger provider_season_bootstrap_events_insert_guard
before insert on public.provider_season_bootstrap_events
for each row execute function public.guard_provider_season_bootstrap_writes_v1();
alter table public.provider_season_bootstrap_events
  enable always trigger provider_season_bootstrap_events_insert_guard;

drop trigger if exists provider_season_bootstrap_heads_write_guard
on public.provider_season_bootstrap_heads;
create trigger provider_season_bootstrap_heads_write_guard
before insert or update or delete on public.provider_season_bootstrap_heads
for each row execute function public.guard_provider_season_bootstrap_writes_v1();
alter table public.provider_season_bootstrap_heads
  enable always trigger provider_season_bootstrap_heads_write_guard;

create or replace function public.compute_provider_season_fixture_fingerprint_v1(
  p_provider text,p_season integer
)
returns text language sql stable security definer set search_path='' as $function$
  select pg_catalog.md5(coalesce(pg_catalog.string_agg(
    fixture.provider_fixture_id||'|'||fixture.season||'|'||
    coalesce(fixture.matchday_id::text,'')||'|'||
    fixture.home_team_provider_id||'|'||fixture.away_team_provider_id,
    E'\n' order by fixture.provider_fixture_id
  ),''))
  from public.provider_fixtures fixture
  where fixture.provider=p_provider
    and fixture.competition_code='IT-SA'
    and fixture.season=p_season::text;
$function$;
revoke all on function public.compute_provider_season_fixture_fingerprint_v1(text,integer)
from public,anon,authenticated;
grant execute on function public.compute_provider_season_fixture_fingerprint_v1(text,integer)
to service_role;

create or replace function public.compute_provider_season_bootstrap_hash_v1(
  p_league_id uuid,p_rollover_certificate_id bigint,p_provider text,
  p_season integer,p_catalog_head_id uuid,p_catalog_generation bigint,
  p_catalog_player_count integer,p_fixture_scope_certificate_id uuid,
  p_fixture_count integer,p_matchday_count integer,p_fixture_team_count integer,
  p_fixture_fingerprint text
)
returns text language sql immutable security definer set search_path='' as $function$
  select pg_catalog.md5(jsonb_build_object(
    'leagueId',p_league_id,'rolloverCertificateId',p_rollover_certificate_id,
    'provider',p_provider,'competitionCode','IT-SA','season',p_season,
    'catalogHeadId',p_catalog_head_id,'catalogGeneration',p_catalog_generation,
    'catalogPlayerCount',p_catalog_player_count,
    'fixtureScopeCertificateId',p_fixture_scope_certificate_id,
    'fixtureCount',p_fixture_count,'matchdayCount',p_matchday_count,
    'fixtureTeamCount',p_fixture_team_count,'fixtureFingerprint',p_fixture_fingerprint
  )::text);
$function$;
revoke all on function public.compute_provider_season_bootstrap_hash_v1(
  uuid,bigint,text,integer,uuid,bigint,integer,uuid,integer,integer,integer,text
) from public,anon,authenticated;
grant execute on function public.compute_provider_season_bootstrap_hash_v1(
  uuid,bigint,text,integer,uuid,bigint,integer,uuid,integer,integer,integer,text
) to service_role;

create or replace function public.compute_provider_season_bootstrap_gate_v1(
  p_league_id uuid
)
returns jsonb language plpgsql stable security definer set search_path='' as $function$
declare
  v_league public.leagues%rowtype;
  v_rollover public.league_season_rollover_certificates%rowtype;
  v_rollover_head public.league_season_rollover_heads%rowtype;
  v_catalog public.provider_player_catalog_heads%rowtype;
  v_catalog_publication public.provider_sync_publications%rowtype;
  v_catalog_run public.provider_sync_runs%rowtype;
  v_fixture_scope public.provider_sync_scope_certificates%rowtype;
  v_fixture_publication public.provider_sync_publications%rowtype;
  v_fixture_run public.provider_sync_runs%rowtype;
  v_existing public.provider_season_bootstrap_certificates%rowtype;
  v_season integer;
  v_fixture_count integer:=0;
  v_matchday_count integer:=0;
  v_fixture_team_count integer:=0;
  v_unlinked_count integer:=0;
  v_unknown_count integer:=0;
  v_first_kickoff timestamptz;
  v_last_kickoff timestamptz;
  v_fixture_fingerprint text;
  v_catalog_ready boolean:=false;
  v_fixtures_ready boolean:=false;
  v_status text:='waiting';
  v_reason text:='provider_bootstrap.waiting';
  v_affected boolean:=false;
  v_market_activity_exists boolean:=false;
  v_calendar_activity_exists boolean:=false;
begin
  select league.* into v_league from public.leagues league
  where league.id=p_league_id;
  if not found then raise exception 'Lega non trovata.'; end if;

  if v_league.previous_league_id is null then
    return jsonb_build_object(
      'protected',true,'applicable',false,'healthy',true,'affected',false,
      'status','ready','reasonCode','provider_bootstrap.not_required',
      'season',case when coalesce(v_league.calendar_season,'')~'^[0-9]{4}$'
        then v_league.calendar_season::integer else null end,
      'catalogReady',true,'fixturesReady',true,'certified',false
    );
  end if;

  if coalesce(v_league.calendar_season,'')!~'^[0-9]{4}$' then
    return jsonb_build_object(
      'protected',true,'applicable',true,'healthy',false,'affected',true,
      'status','affected','reasonCode','provider_bootstrap.invalid_league_season',
      'season',null,'catalogReady',false,'fixturesReady',false,'certified',false
    );
  end if;
  v_season:=v_league.calendar_season::integer;

  select certificate.* into v_rollover
  from public.league_season_rollover_certificates certificate
  where certificate.renewed_league_id=p_league_id;
  select head.* into v_rollover_head
  from public.league_season_rollover_heads head
  where head.renewed_league_id=p_league_id;

  if v_rollover.id is null or v_rollover_head.certificate_id is null then
    v_status:='affected';v_reason:='provider_bootstrap.rollover_certificate_missing';
    v_affected:=true;
  elsif v_rollover.renewed_season::integer<>v_season then
    v_status:='affected';v_reason:='provider_bootstrap.rollover_season_mismatch';
    v_affected:=true;
  elsif v_rollover_head.rollover_status<>'certified' then
    v_status:='affected';v_reason:='provider_bootstrap.rollover_affected';
    v_affected:=true;
  end if;

  select head.* into v_catalog
  from public.provider_player_catalog_heads head
  where head.competition_code='IT-SA'
  order by case when head.latest_season=v_season then 0 else 1 end,
    head.latest_season desc,head.updated_at desc
  limit 1;

  if not v_affected then
    if v_catalog.id is null then
      v_reason:='provider_bootstrap.catalog_missing';
    elsif v_catalog.latest_season<v_season then
      v_reason:='provider_bootstrap.catalog_previous_season';
    elsif v_catalog.latest_season>v_season then
      v_status:='affected';v_reason:='provider_bootstrap.catalog_season_advanced';
      v_affected:=true;
    elsif v_catalog.active_player_count<300 then
      v_reason:='provider_bootstrap.catalog_incomplete';
    else
      select publication.* into v_catalog_publication
      from public.provider_sync_publications publication
      where publication.id=v_catalog.latest_publication_id;
      select run.* into v_catalog_run from public.provider_sync_runs run
      where run.id=v_catalog.latest_run_id;
      if v_catalog_publication.status<>'published'
        or v_catalog_run.status<>'completed' then
        v_reason:='provider_bootstrap.catalog_not_published';
      elsif not exists(
        select 1 from public.provider_player_catalog_reconciliations reconciliation
        where reconciliation.head_id=v_catalog.id
          and reconciliation.run_id=v_catalog.latest_run_id
          and reconciliation.publication_id=v_catalog.latest_publication_id
          and reconciliation.status='applied'
          and reconciliation.season=v_season
          and reconciliation.generation=v_catalog.generation
      ) then
        v_reason:='provider_bootstrap.catalog_reconciliation_missing';
      else
        v_catalog_ready:=true;
        v_status:='catalog_ready';
        v_reason:='provider_bootstrap.catalog_ready';
      end if;
    end if;
  end if;

  if v_catalog_ready and not v_affected then
    select scope.* into v_fixture_scope
    from public.provider_sync_scope_certificates scope
    join public.provider_sync_publications publication
      on publication.id=scope.publication_id
    join public.provider_sync_runs run on run.id=scope.run_id
    where scope.provider=v_catalog.provider
      and scope.sync_type='sync-fixtures'
      and scope.scope_kind='date'
      and scope.requested_season=v_season
      and scope.status='certified'
      and publication.status='published'
      and run.status='completed'
    order by scope.certified_at desc nulls last,scope.updated_at desc
    limit 1;

    select count(*)::integer,count(distinct fixture.matchday_id)::integer,
      count(*) filter(where fixture.matchday_id is null)::integer,
      count(*) filter(where fixture.provider_lifecycle_state='unknown')::integer,
      min(fixture.kickoff_at),max(fixture.kickoff_at)
    into v_fixture_count,v_matchday_count,v_unlinked_count,v_unknown_count,
      v_first_kickoff,v_last_kickoff
    from public.provider_fixtures fixture
    where fixture.provider=v_catalog.provider
      and fixture.competition_code='IT-SA'
      and fixture.season=v_season::text;

    select count(distinct team_id)::integer into v_fixture_team_count
    from (
      select fixture.home_team_provider_id as team_id
      from public.provider_fixtures fixture
      where fixture.provider=v_catalog.provider
        and fixture.competition_code='IT-SA'
        and fixture.season=v_season::text
      union
      select fixture.away_team_provider_id as team_id
      from public.provider_fixtures fixture
      where fixture.provider=v_catalog.provider
        and fixture.competition_code='IT-SA'
        and fixture.season=v_season::text
    ) provider_teams;

    v_fixture_fingerprint:=public.compute_provider_season_fixture_fingerprint_v1(
      v_catalog.provider,v_season
    );

    if v_fixture_scope.id is null then
      v_reason:='provider_bootstrap.fixture_scope_missing';
    elsif v_fixture_count<380 or v_matchday_count<38
      or v_fixture_team_count<20 then
      v_reason:='provider_bootstrap.fixture_coverage_incomplete';
    elsif v_unlinked_count>0 then
      v_reason:='provider_bootstrap.fixtures_unlinked';
    elsif v_unknown_count>0 then
      v_reason:='provider_bootstrap.fixture_lifecycle_unknown';
    elsif exists(
      select 1 from public.provider_fixtures fixture
      join public.matchdays matchday on matchday.id=fixture.matchday_id
      where fixture.provider=v_catalog.provider
        and fixture.competition_code='IT-SA'
        and fixture.season=v_season::text
        and (matchday.competition_code<>'IT-SA' or matchday.season<>v_season::text)
    ) then
      v_status:='affected';v_reason:='provider_bootstrap.fixture_scope_mismatch';
      v_affected:=true;
    else
      select publication.* into v_fixture_publication
      from public.provider_sync_publications publication
      where publication.id=v_fixture_scope.publication_id;
      select run.* into v_fixture_run from public.provider_sync_runs run
      where run.id=v_fixture_scope.run_id;
      v_fixtures_ready:=true;
      v_status:='ready';
      v_reason:='provider_bootstrap.ready';
    end if;
  end if;

  select certificate.* into v_existing
  from public.provider_season_bootstrap_certificates certificate
  where certificate.league_id=p_league_id;

  if v_existing.id is not null then
    if v_existing.bootstrap_hash<>public.compute_provider_season_bootstrap_hash_v1(
      v_existing.league_id,v_existing.rollover_certificate_id,
      v_existing.provider,v_existing.season,v_existing.catalog_head_id,
      v_existing.catalog_generation,v_existing.catalog_player_count,
      v_existing.fixture_scope_certificate_id,v_existing.fixture_count,
      v_existing.matchday_count,v_existing.fixture_team_count,
      v_existing.fixture_fingerprint
    ) then
      v_status:='affected';v_reason:='provider_bootstrap.certificate_hash_mismatch';
      v_affected:=true;
    elsif not v_catalog_ready or not v_fixtures_ready then
      v_status:='affected';v_reason:='provider_bootstrap.certified_scope_regressed';
      v_affected:=true;
    elsif v_existing.season<>v_season
      or v_existing.provider<>v_catalog.provider
      or v_existing.catalog_head_id<>v_catalog.id
      or v_existing.catalog_generation<>v_catalog.generation
      or v_existing.catalog_player_count<>v_catalog.active_player_count
      or v_existing.fixture_fingerprint<>v_fixture_fingerprint then
      v_status:='affected';v_reason:='provider_bootstrap.generation_or_scope_changed';
      v_affected:=true;
    end if;
  else
    select
      exists(select 1 from public.roster_entries roster
        where roster.league_id=p_league_id)
      or exists(select 1 from public.auction_items item
        join public.auctions auction on auction.id=item.auction_id
        where auction.league_id=p_league_id),
      exists(select 1 from public.fantasy_fixtures fixture
        where fixture.league_id=p_league_id)
    into v_market_activity_exists,v_calendar_activity_exists;

    if v_market_activity_exists and not v_catalog_ready then
      v_status:='affected';
      v_reason:='provider_bootstrap.market_before_catalog_ready';
      v_affected:=true;
    elsif v_calendar_activity_exists
      and (not v_catalog_ready or not v_fixtures_ready) then
      v_status:='affected';
      v_reason:='provider_bootstrap.calendar_before_certification';
      v_affected:=true;
    end if;
  end if;

  return jsonb_build_object(
    'protected',true,'applicable',true,
    'healthy',not v_affected and v_catalog_ready,
    'affected',v_affected,'status',v_status,'reasonCode',v_reason,
    'leagueId',p_league_id,'season',v_season,
    'rolloverCertificateId',v_rollover.id,
    'catalogReady',v_catalog_ready,'fixturesReady',v_fixtures_ready,
    'provider',v_catalog.provider,'catalogHeadId',v_catalog.id,
    'catalogPublicationId',v_catalog.latest_publication_id,
    'catalogRunId',v_catalog.latest_run_id,
    'catalogSeason',v_catalog.latest_season,
    'catalogGeneration',v_catalog.generation,
    'catalogPlayerCount',coalesce(v_catalog.active_player_count,0),
    'fixtureScopeCertificateId',v_fixture_scope.id,
    'fixturePublicationId',v_fixture_scope.publication_id,
    'fixtureRunId',v_fixture_scope.run_id,
    'fixtureCount',v_fixture_count,'matchdayCount',v_matchday_count,
    'fixtureTeamCount',v_fixture_team_count,'firstKickoffAt',v_first_kickoff,'lastKickoffAt',v_last_kickoff,
    'fixtureFingerprint',v_fixture_fingerprint,
    'certified',v_existing.id is not null,'certificateId',v_existing.id,
    'bootstrapHash',v_existing.bootstrap_hash
  );
end;
$function$;
revoke all on function public.compute_provider_season_bootstrap_gate_v1(uuid)
from public,anon,authenticated;
grant execute on function public.compute_provider_season_bootstrap_gate_v1(uuid)
to service_role;

create or replace function public.certify_provider_season_bootstrap_v1(
  p_league_id uuid
)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare
  v_gate jsonb;
  v_existing public.provider_season_bootstrap_certificates%rowtype;
  v_certificate_id bigint;
  v_hash text;
  v_payload jsonb;
begin
  if auth.uid() is not null and not(
    public.is_league_admin(p_league_id)
    or exists(select 1 from public.leagues league
      where league.id=p_league_id and league.owner_id=auth.uid())
  ) then
    raise exception 'Solo la Direzione può certificare il bootstrap provider.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'league-season-rollover-lineage:'||p_league_id::text,0));
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'provider-new-season-bootstrap:'||p_league_id::text,0));

  select certificate.* into v_existing
  from public.provider_season_bootstrap_certificates certificate
  where certificate.league_id=p_league_id;
  if found then
    return public.compute_provider_season_bootstrap_gate_v1(p_league_id)
      ||jsonb_build_object('certified',true,'certificateId',v_existing.id,
        'bootstrapHash',v_existing.bootstrap_hash);
  end if;

  v_gate:=public.compute_provider_season_bootstrap_gate_v1(p_league_id);
  if not coalesce((v_gate->>'applicable')::boolean,false) then return v_gate; end if;
  if coalesce(v_gate->>'status','waiting')<>'ready'
    or not coalesce((v_gate->>'catalogReady')::boolean,false)
    or not coalesce((v_gate->>'fixturesReady')::boolean,false)
    or coalesce((v_gate->>'affected')::boolean,false) then
    raise exception 'Bootstrap provider non certificabile [%].',v_gate->>'reasonCode';
  end if;

  v_hash:=public.compute_provider_season_bootstrap_hash_v1(
    p_league_id,(v_gate->>'rolloverCertificateId')::bigint,v_gate->>'provider',
    (v_gate->>'season')::integer,(v_gate->>'catalogHeadId')::uuid,
    (v_gate->>'catalogGeneration')::bigint,
    (v_gate->>'catalogPlayerCount')::integer,
    (v_gate->>'fixtureScopeCertificateId')::uuid,
    (v_gate->>'fixtureCount')::integer,(v_gate->>'matchdayCount')::integer,
    (v_gate->>'fixtureTeamCount')::integer,v_gate->>'fixtureFingerprint'
  );
  v_certificate_id:=pg_catalog.nextval(pg_catalog.pg_get_serial_sequence(
    'public.provider_season_bootstrap_certificates','id')::regclass);
  v_payload:=v_gate||jsonb_build_object(
    'certified',true,'certificateId',v_certificate_id,
    'bootstrapHash',v_hash,'certifiedAt',now()
  );

  perform set_config('leghevo.provider_season_bootstrap_context','on',true);
  insert into public.provider_season_bootstrap_certificates(
    id,league_id,rollover_certificate_id,provider,competition_code,season,
    catalog_head_id,catalog_publication_id,catalog_run_id,catalog_generation,
    catalog_player_count,fixture_scope_certificate_id,fixture_publication_id,
    fixture_run_id,fixture_count,matchday_count,fixture_team_count,
    first_kickoff_at,last_kickoff_at,
    fixture_fingerprint,bootstrap_hash,certified_by,result_payload
  ) values(
    v_certificate_id,p_league_id,(v_gate->>'rolloverCertificateId')::bigint,
    v_gate->>'provider','IT-SA',(v_gate->>'season')::integer,
    (v_gate->>'catalogHeadId')::uuid,(v_gate->>'catalogPublicationId')::uuid,
    (v_gate->>'catalogRunId')::uuid,(v_gate->>'catalogGeneration')::bigint,
    (v_gate->>'catalogPlayerCount')::integer,
    (v_gate->>'fixtureScopeCertificateId')::uuid,
    (v_gate->>'fixturePublicationId')::uuid,(v_gate->>'fixtureRunId')::uuid,
    (v_gate->>'fixtureCount')::integer,(v_gate->>'matchdayCount')::integer,
    (v_gate->>'fixtureTeamCount')::integer,(v_gate->>'firstKickoffAt')::timestamptz,
    (v_gate->>'lastKickoffAt')::timestamptz,
    v_gate->>'fixtureFingerprint',v_hash,auth.uid(),v_payload
  );

  insert into public.provider_season_bootstrap_heads(
    league_id,certificate_id,bootstrap_status,reason_code,observed_season,
    catalog_ready,fixtures_ready,observed_provider,observed_catalog_season,
    observed_catalog_generation,observed_catalog_player_count,
    observed_fixture_count,observed_matchday_count,observed_fixture_team_count,
    observed_fixture_fingerprint,last_assessed_at,updated_at
  ) values(
    p_league_id,v_certificate_id,'ready','provider_bootstrap.certified',
    (v_gate->>'season')::integer,true,true,v_gate->>'provider',
    (v_gate->>'catalogSeason')::integer,(v_gate->>'catalogGeneration')::bigint,
    (v_gate->>'catalogPlayerCount')::integer,(v_gate->>'fixtureCount')::integer,
    (v_gate->>'matchdayCount')::integer,(v_gate->>'fixtureTeamCount')::integer,
    v_gate->>'fixtureFingerprint',now(),now()
  ) on conflict(league_id) do update set
    certificate_id=excluded.certificate_id,bootstrap_status='ready',
    reason_code='provider_bootstrap.certified',catalog_ready=true,
    fixtures_ready=true,observed_provider=excluded.observed_provider,
    observed_catalog_season=excluded.observed_catalog_season,
    observed_catalog_generation=excluded.observed_catalog_generation,
    observed_catalog_player_count=excluded.observed_catalog_player_count,
    observed_fixture_count=excluded.observed_fixture_count,
    observed_matchday_count=excluded.observed_matchday_count,
    observed_fixture_team_count=excluded.observed_fixture_team_count,
    observed_fixture_fingerprint=excluded.observed_fixture_fingerprint,
    affected_at=null,last_assessed_at=now(),updated_at=now();

  insert into public.provider_season_bootstrap_events(
    league_id,certificate_id,event_type,bootstrap_status,reason_code,
    observed_season,catalog_ready,fixtures_ready,observed_catalog_generation,
    observed_catalog_player_count,observed_fixture_count,
    observed_matchday_count,observed_fixture_team_count,
    observed_fixture_fingerprint,event_payload
  ) values(
    p_league_id,v_certificate_id,'certified','ready',
    'provider_bootstrap.certified',(v_gate->>'season')::integer,true,true,
    (v_gate->>'catalogGeneration')::bigint,
    (v_gate->>'catalogPlayerCount')::integer,(v_gate->>'fixtureCount')::integer,
    (v_gate->>'matchdayCount')::integer,(v_gate->>'fixtureTeamCount')::integer,
    v_gate->>'fixtureFingerprint',v_payload
  );
  perform set_config('leghevo.provider_season_bootstrap_context','',true);
  return v_payload;
end;
$function$;
revoke all on function public.certify_provider_season_bootstrap_v1(uuid)
from public,anon;
grant execute on function public.certify_provider_season_bootstrap_v1(uuid)
to authenticated,service_role;

create or replace function public.reconcile_provider_season_bootstrap_v1(
  p_league_id uuid,p_auto_certify boolean default true
)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare
  v_gate jsonb;
  v_head public.provider_season_bootstrap_heads%rowtype;
  v_status text;
  v_reason text;
  v_event_type text;
  v_catalog_ready boolean;
  v_fixtures_ready boolean;
  v_certificate_id bigint;
begin
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'provider-new-season-bootstrap:'||p_league_id::text,0));
  v_gate:=public.compute_provider_season_bootstrap_gate_v1(p_league_id);
  if not coalesce((v_gate->>'applicable')::boolean,false) then return v_gate; end if;

  if p_auto_certify and coalesce(v_gate->>'status','waiting')='ready'
    and not coalesce((v_gate->>'certified')::boolean,false) then
    return public.certify_provider_season_bootstrap_v1(p_league_id);
  end if;

  v_status:=coalesce(v_gate->>'status','waiting');
  v_reason:=coalesce(v_gate->>'reasonCode','provider_bootstrap.waiting');
  v_catalog_ready:=coalesce((v_gate->>'catalogReady')::boolean,false);
  v_fixtures_ready:=coalesce((v_gate->>'fixturesReady')::boolean,false);
  v_certificate_id:=nullif(v_gate->>'certificateId','')::bigint;

  select head.* into v_head from public.provider_season_bootstrap_heads head
  where head.league_id=p_league_id for update;
  if found and v_head.bootstrap_status=v_status
    and v_head.reason_code=v_reason
    and v_head.catalog_ready=v_catalog_ready
    and v_head.fixtures_ready=v_fixtures_ready
    and v_head.observed_catalog_generation is not distinct from
      nullif(v_gate->>'catalogGeneration','')::bigint
    and v_head.observed_fixture_fingerprint is not distinct from
      v_gate->>'fixtureFingerprint' then
    return v_gate;
  end if;

  v_event_type:=case
    when v_status='affected' then 'affected'
    when v_status='ready' and v_certificate_id is not null
      and found and v_head.bootstrap_status='affected' then 'revalidated'
    when v_status='catalog_ready' then 'catalog_ready'
    when v_status='ready' then 'certified'
    else 'waiting' end;

  perform set_config('leghevo.provider_season_bootstrap_context','on',true);
  insert into public.provider_season_bootstrap_heads(
    league_id,certificate_id,bootstrap_status,reason_code,observed_season,
    catalog_ready,fixtures_ready,observed_provider,observed_catalog_season,
    observed_catalog_generation,observed_catalog_player_count,
    observed_fixture_count,observed_matchday_count,observed_fixture_team_count,
    observed_fixture_fingerprint,affected_at,last_assessed_at,updated_at
  ) values(
    p_league_id,v_certificate_id,v_status,v_reason,(v_gate->>'season')::integer,
    v_catalog_ready,v_fixtures_ready,v_gate->>'provider',
    nullif(v_gate->>'catalogSeason','')::integer,
    nullif(v_gate->>'catalogGeneration','')::bigint,
    coalesce(nullif(v_gate->>'catalogPlayerCount','')::integer,0),
    coalesce(nullif(v_gate->>'fixtureCount','')::integer,0),
    coalesce(nullif(v_gate->>'matchdayCount','')::integer,0),
    coalesce(nullif(v_gate->>'fixtureTeamCount','')::integer,0),
    v_gate->>'fixtureFingerprint',case when v_status='affected' then now() end,
    now(),now()
  ) on conflict(league_id) do update set
    certificate_id=coalesce(excluded.certificate_id,
      public.provider_season_bootstrap_heads.certificate_id),
    bootstrap_status=excluded.bootstrap_status,reason_code=excluded.reason_code,
    observed_season=excluded.observed_season,
    catalog_ready=excluded.catalog_ready,fixtures_ready=excluded.fixtures_ready,
    observed_provider=excluded.observed_provider,
    observed_catalog_season=excluded.observed_catalog_season,
    observed_catalog_generation=excluded.observed_catalog_generation,
    observed_catalog_player_count=excluded.observed_catalog_player_count,
    observed_fixture_count=excluded.observed_fixture_count,
    observed_matchday_count=excluded.observed_matchday_count,
    observed_fixture_team_count=excluded.observed_fixture_team_count,
    observed_fixture_fingerprint=excluded.observed_fixture_fingerprint,
    affected_at=case when excluded.bootstrap_status='affected'
      then coalesce(public.provider_season_bootstrap_heads.affected_at,now())
      else null end,last_assessed_at=now(),updated_at=now();

  select head.* into v_head from public.provider_season_bootstrap_heads head
  where head.league_id=p_league_id;
  insert into public.provider_season_bootstrap_events(
    league_id,certificate_id,event_type,bootstrap_status,reason_code,
    observed_season,catalog_ready,fixtures_ready,observed_catalog_generation,
    observed_catalog_player_count,observed_fixture_count,
    observed_matchday_count,observed_fixture_team_count,
    observed_fixture_fingerprint,event_payload
  ) values(
    p_league_id,v_head.certificate_id,v_event_type,v_head.bootstrap_status,
    v_head.reason_code,v_head.observed_season,v_head.catalog_ready,
    v_head.fixtures_ready,v_head.observed_catalog_generation,
    v_head.observed_catalog_player_count,v_head.observed_fixture_count,
    v_head.observed_matchday_count,v_head.observed_fixture_team_count,
    v_head.observed_fixture_fingerprint,
    jsonb_build_object('assessment',v_gate)
  );
  perform set_config('leghevo.provider_season_bootstrap_context','',true);
  return v_gate||jsonb_build_object('certificateId',v_head.certificate_id);
end;
$function$;
revoke all on function public.reconcile_provider_season_bootstrap_v1(uuid,boolean)
from public,anon,authenticated;
grant execute on function public.reconcile_provider_season_bootstrap_v1(uuid,boolean)
to service_role;

create or replace function public.get_league_provider_season_bootstrap_v1(
  p_league_id uuid
)
returns jsonb language plpgsql stable security definer set search_path='' as $function$
declare v_gate jsonb;v_head public.provider_season_bootstrap_heads%rowtype;
begin
  if not(public.is_league_member(p_league_id) or public.is_league_admin(p_league_id)) then
    raise exception 'Non puoi consultare il bootstrap provider di questa lega.';
  end if;
  v_gate:=public.compute_provider_season_bootstrap_gate_v1(p_league_id);
  select head.* into v_head from public.provider_season_bootstrap_heads head
  where head.league_id=p_league_id;
  return v_gate||jsonb_build_object(
    'status',coalesce(v_head.bootstrap_status,v_gate->>'status','waiting'),
    'reasonCode',coalesce(v_head.reason_code,v_gate->>'reasonCode'),
    'catalogReady',coalesce(v_head.catalog_ready,
      (v_gate->>'catalogReady')::boolean,false),
    'fixturesReady',coalesce(v_head.fixtures_ready,
      (v_gate->>'fixturesReady')::boolean,false),
    'certificateId',coalesce(v_head.certificate_id,
      nullif(v_gate->>'certificateId','')::bigint),
    'affectedAt',v_head.affected_at,'lastAssessedAt',v_head.last_assessed_at
  );
end;
$function$;
revoke all on function public.get_league_provider_season_bootstrap_v1(uuid)
from public,anon,service_role;
grant execute on function public.get_league_provider_season_bootstrap_v1(uuid)
to authenticated;

create or replace function public.assert_provider_season_bootstrap_ready_v1(
  p_league_id uuid,p_requirement text
)
returns void language plpgsql security definer set search_path='' as $function$
declare v_gate jsonb;v_requirement text:=lower(trim(coalesce(p_requirement,'')));
begin
  v_gate:=public.compute_provider_season_bootstrap_gate_v1(p_league_id);
  if not coalesce((v_gate->>'applicable')::boolean,false) then return; end if;
  if coalesce((v_gate->>'affected')::boolean,false) then
    raise exception 'Operazione bloccata [%].',v_gate->>'reasonCode';
  end if;
  if v_requirement='catalog' and not coalesce(
    (v_gate->>'catalogReady')::boolean,false) then
    raise exception 'Catalogo provider nuova stagione non pronto [%].',
      v_gate->>'reasonCode';
  elsif v_requirement='fixtures' and not(
    coalesce((v_gate->>'catalogReady')::boolean,false)
    and coalesce((v_gate->>'fixturesReady')::boolean,false)
    and coalesce((v_gate->>'certified')::boolean,false)
  ) then
    raise exception 'Calendario provider nuova stagione non certificato [%].',
      v_gate->>'reasonCode';
  elsif v_requirement not in('catalog','fixtures') then
    raise exception 'Requisito bootstrap provider sconosciuto.';
  end if;
end;
$function$;
revoke all on function public.assert_provider_season_bootstrap_ready_v1(uuid,text)
from public,anon,authenticated;
grant execute on function public.assert_provider_season_bootstrap_ready_v1(uuid,text)
to service_role;

create or replace function public.guard_provider_season_market_write_v1()
returns trigger language plpgsql security definer set search_path='' as $function$
declare v_league_id uuid;
begin
  if tg_table_name='roster_entries' then v_league_id:=new.league_id;
  else select auction.league_id into v_league_id from public.auctions auction
    where auction.id=new.auction_id; end if;
  perform public.assert_provider_season_bootstrap_ready_v1(v_league_id,'catalog');
  return new;
end;
$function$;
revoke all on function public.guard_provider_season_market_write_v1()
from public,anon,authenticated,service_role;

drop trigger if exists provider_season_bootstrap_roster_guard
on public.roster_entries;
create trigger provider_season_bootstrap_roster_guard
before insert on public.roster_entries for each row
execute function public.guard_provider_season_market_write_v1();
alter table public.roster_entries
  enable always trigger provider_season_bootstrap_roster_guard;

drop trigger if exists provider_season_bootstrap_auction_item_guard
on public.auction_items;
create trigger provider_season_bootstrap_auction_item_guard
before insert on public.auction_items for each row
execute function public.guard_provider_season_market_write_v1();
alter table public.auction_items
  enable always trigger provider_season_bootstrap_auction_item_guard;

create or replace function public.guard_provider_season_calendar_write_v1()
returns trigger language plpgsql security definer set search_path='' as $function$
begin
  perform public.assert_provider_season_bootstrap_ready_v1(new.league_id,'fixtures');
  return new;
end;
$function$;
revoke all on function public.guard_provider_season_calendar_write_v1()
from public,anon,authenticated,service_role;

drop trigger if exists provider_season_bootstrap_calendar_guard
on public.fantasy_fixtures;
create trigger provider_season_bootstrap_calendar_guard
before insert on public.fantasy_fixtures for each row
execute function public.guard_provider_season_calendar_write_v1();
alter table public.fantasy_fixtures
  enable always trigger provider_season_bootstrap_calendar_guard;

create or replace function public.reconcile_provider_season_bootstrap_from_provider_v1()
returns trigger language plpgsql security definer set search_path='' as $function$
declare v_league_id uuid;
begin
  for v_league_id in select league.id from public.leagues league
    where league.previous_league_id is not null
      and league.status in('draft','active')
  loop
    perform public.reconcile_provider_season_bootstrap_v1(v_league_id,true);
  end loop;
  return null;
end;
$function$;
revoke all on function public.reconcile_provider_season_bootstrap_from_provider_v1()
from public,anon,authenticated;
grant execute on function public.reconcile_provider_season_bootstrap_from_provider_v1()
to service_role;

drop trigger if exists provider_season_bootstrap_catalog_reconcile
on public.provider_player_catalog_heads;
create trigger provider_season_bootstrap_catalog_reconcile
after insert or update on public.provider_player_catalog_heads
for each statement execute function public.reconcile_provider_season_bootstrap_from_provider_v1();
alter table public.provider_player_catalog_heads
  enable always trigger provider_season_bootstrap_catalog_reconcile;

drop trigger if exists provider_season_bootstrap_scope_reconcile
on public.provider_sync_scope_certificates;
create trigger provider_season_bootstrap_scope_reconcile
after insert or update on public.provider_sync_scope_certificates
for each statement execute function public.reconcile_provider_season_bootstrap_from_provider_v1();
alter table public.provider_sync_scope_certificates
  enable always trigger provider_season_bootstrap_scope_reconcile;

drop trigger if exists provider_season_bootstrap_rollover_reconcile
on public.league_season_rollover_heads;
create trigger provider_season_bootstrap_rollover_reconcile
after insert or update on public.league_season_rollover_heads
for each statement execute function public.reconcile_provider_season_bootstrap_from_provider_v1();
alter table public.league_season_rollover_heads
  enable always trigger provider_season_bootstrap_rollover_reconcile;

create or replace function public.renew_league_season_guarded_v3(
  p_league_id uuid,p_next_season text,p_request_id uuid
)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare v_result jsonb;v_new_league_id uuid;v_bootstrap jsonb;
begin
  v_result:=public.renew_league_season_guarded_v2(
    p_league_id,p_next_season,p_request_id
  );
  v_new_league_id:=nullif(v_result->>'renewedLeagueId','')::uuid;
  if v_new_league_id is not null then
    v_bootstrap:=public.reconcile_provider_season_bootstrap_v1(
      v_new_league_id,true
    );
  end if;
  return v_result||jsonb_build_object('providerSeasonBootstrap',v_bootstrap);
end;
$function$;
revoke all on function public.renew_league_season_guarded_v3(uuid,text,uuid)
from public,anon,service_role;
grant execute on function public.renew_league_season_guarded_v3(uuid,text,uuid)
to authenticated;

create or replace function public.renew_league_season(
  p_league_id uuid,p_next_season text
)
returns uuid language plpgsql security definer set search_path='' as $function$
declare v_result jsonb;
begin
  v_result:=public.renew_league_season_guarded_v3(
    p_league_id,p_next_season,gen_random_uuid()
  );
  return nullif(v_result->>'renewedLeagueId','')::uuid;
end;
$function$;
revoke all on function public.renew_league_season(uuid,text)
from public,anon,service_role;
grant execute on function public.renew_league_season(uuid,text) to authenticated;

create or replace function public.get_league_season_state_v8(p_league_id uuid)
returns jsonb language plpgsql stable security definer set search_path='' as $function$
declare v_state jsonb;v_gate jsonb;
begin
  v_state:=public.get_league_season_state_v7(p_league_id);
  v_gate:=public.compute_provider_season_bootstrap_gate_v1(p_league_id);
  return v_state||jsonb_build_object(
    'providerSeasonBootstrapProtected',true,
    'providerSeasonBootstrapApplicable',
      coalesce((v_gate->>'applicable')::boolean,false),
    'providerSeasonBootstrapHealthy',
      coalesce((v_gate->>'healthy')::boolean,true),
    'providerSeasonBootstrapAffected',
      coalesce((v_gate->>'affected')::boolean,false),
    'providerSeasonBootstrapStatus',coalesce(v_gate->>'status','waiting'),
    'providerSeasonBootstrapReason',v_gate->>'reasonCode',
    'providerSeasonCatalogReady',
      coalesce((v_gate->>'catalogReady')::boolean,false),
    'providerSeasonFixturesReady',
      coalesce((v_gate->>'fixturesReady')::boolean,false),
    'providerSeasonBootstrapCertified',
      coalesce((v_gate->>'certified')::boolean,false),
    'providerSeasonBootstrapCertificateId',
      nullif(v_gate->>'certificateId','')::bigint,
    'providerSeasonBootstrapHash',v_gate->>'bootstrapHash',
    'providerSeasonBootstrap',v_gate
  );
end;
$function$;
revoke all on function public.get_league_season_state_v8(uuid)
from public,anon,service_role;
grant execute on function public.get_league_season_state_v8(uuid)
to authenticated;

create or replace function public.get_league_management_state_v18(p_league_id uuid)
returns jsonb language plpgsql stable security definer set search_path='' as $function$
declare v_state jsonb;v_season jsonb;v_checks jsonb;
begin
  v_state:=public.get_league_management_state_v17(p_league_id);
  v_season:=public.get_league_season_state_v8(p_league_id);
  v_checks:=coalesce(v_state->'checks','{}'::jsonb);
  return v_state||v_season||jsonb_build_object('checks',v_checks||jsonb_build_object(
    'providerSeasonBootstrapProtected',true,
    'providerSeasonCatalogReady',
      coalesce((v_season->>'providerSeasonCatalogReady')::boolean,false),
    'providerSeasonFixturesReady',
      coalesce((v_season->>'providerSeasonFixturesReady')::boolean,false),
    'providerSeasonBootstrapCertified',
      coalesce((v_season->>'providerSeasonBootstrapCertified')::boolean,false),
    'providerSeasonBootstrapHealthy',
      coalesce((v_season->>'providerSeasonBootstrapHealthy')::boolean,true)
  ));
end;
$function$;
revoke all on function public.get_league_management_state_v18(uuid)
from public,anon,service_role;
grant execute on function public.get_league_management_state_v18(uuid)
to authenticated;

create or replace function public.get_league_provider_sync_health_v29(p_league_id uuid)
returns jsonb language plpgsql stable security definer set search_path='' as $function$
declare v_base jsonb;v_gate jsonb;v_healthy boolean;
begin
  v_base:=public.get_league_provider_sync_health_v28(p_league_id);
  v_gate:=public.compute_provider_season_bootstrap_gate_v1(p_league_id);
  v_healthy:=coalesce((v_base->>'healthy')::boolean,false)
    and coalesce((v_gate->>'healthy')::boolean,true)
    and not coalesce((v_gate->>'affected')::boolean,false);
  return v_base||jsonb_build_object(
    'protected',coalesce((v_base->>'protected')::boolean,false)
      and coalesce((v_gate->>'protected')::boolean,false),
    'healthy',v_healthy,
    'status',case when v_healthy then coalesce(v_base->>'status','idle')
      else 'attention' end,
    'providerSeasonBootstrap',v_gate
  );
end;
$function$;
revoke all on function public.get_league_provider_sync_health_v29(uuid)
from public,anon,service_role;
grant execute on function public.get_league_provider_sync_health_v29(uuid)
to authenticated;

-- Backfill non distruttivo: nessuna lega viene modificata o riaperta.
do $backfill$
declare v_league_id uuid;
begin
  for v_league_id in select league.id from public.leagues league
    where league.previous_league_id is not null
  loop
    perform public.reconcile_provider_season_bootstrap_v1(v_league_id,true);
  end loop;
end;
$backfill$;

do $realtime$
begin
  if not exists(select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public'
      and tablename='provider_season_bootstrap_events') then
    alter publication supabase_realtime
      add table public.provider_season_bootstrap_events;
  end if;
end;
$realtime$;

create or replace function public.get_provider_season_bootstrap_integrity_v1()
returns jsonb language plpgsql stable security definer set search_path='' as $function$
declare
  v_certify text:=coalesce(pg_catalog.pg_get_functiondef(
    to_regprocedure('public.certify_provider_season_bootstrap_v1(uuid)')),'');
  v_reconcile text:=coalesce(pg_catalog.pg_get_functiondef(
    to_regprocedure('public.reconcile_provider_season_bootstrap_v1(uuid,boolean)')),'');
  v_assert text:=coalesce(pg_catalog.pg_get_functiondef(
    to_regprocedure('public.assert_provider_season_bootstrap_ready_v1(uuid,text)')),'');
  v_renew text:=coalesce(pg_catalog.pg_get_functiondef(
    to_regprocedure('public.renew_league_season_guarded_v3(uuid,text,uuid)')),'');
  v_legacy text:=coalesce(pg_catalog.pg_get_functiondef(
    to_regprocedure('public.renew_league_season(uuid,text)')),'');
begin
  return jsonb_build_object(
    'predecessor_ready',
      to_regprocedure('public.get_league_season_rollover_integrity_v1()') is not null
      and (select count(*) from jsonb_each(
        public.get_league_season_rollover_integrity_v1()))=20,
    'certificate_table_ready',
      to_regclass('public.provider_season_bootstrap_certificates') is not null,
    'head_table_ready',
      to_regclass('public.provider_season_bootstrap_heads') is not null,
    'event_table_ready',
      to_regclass('public.provider_season_bootstrap_events') is not null,
    'columns_ready',
      (select count(*)=33 from information_schema.columns column_row
       where column_row.table_schema='public'
         and ((column_row.table_name='provider_season_bootstrap_certificates'
           and column_row.column_name in('id','league_id','rollover_certificate_id',
             'provider','competition_code','season','catalog_head_id',
             'catalog_publication_id','catalog_run_id','catalog_generation',
             'catalog_player_count','fixture_scope_certificate_id',
             'fixture_publication_id','fixture_run_id','fixture_count',
             'matchday_count','fixture_team_count','first_kickoff_at','last_kickoff_at',
             'fixture_fingerprint','bootstrap_hash','certified_by',
             'certified_at','result_payload'))
          or (column_row.table_name='provider_season_bootstrap_heads'
           and column_row.column_name in('league_id','certificate_id',
             'bootstrap_status','reason_code','observed_season','catalog_ready',
             'fixtures_ready','observed_catalog_generation',
             'observed_fixture_team_count')))),
    'constraints_ready',
      (select count(*)>=12 from pg_catalog.pg_constraint c
       where c.conrelid in('public.provider_season_bootstrap_certificates'::regclass,
         'public.provider_season_bootstrap_heads'::regclass,
         'public.provider_season_bootstrap_events'::regclass)),
    'indexes_ready',
      to_regclass('public.provider_season_bootstrap_certificates_created_idx') is not null
      and to_regclass('public.provider_season_bootstrap_heads_status_idx') is not null
      and to_regclass('public.provider_season_bootstrap_events_league_idx') is not null,
    'rls_ready',
      coalesce((select relrowsecurity from pg_catalog.pg_class
        where oid='public.provider_season_bootstrap_certificates'::regclass),false)
      and coalesce((select relrowsecurity from pg_catalog.pg_class
        where oid='public.provider_season_bootstrap_heads'::regclass),false)
      and coalesce((select relrowsecurity from pg_catalog.pg_class
        where oid='public.provider_season_bootstrap_events'::regclass),false),
    'direct_write_blocked',
      has_table_privilege('authenticated',
        'public.provider_season_bootstrap_certificates','SELECT')
      and not has_table_privilege('authenticated',
        'public.provider_season_bootstrap_certificates','INSERT')
      and not has_table_privilege('authenticated',
        'public.provider_season_bootstrap_heads','UPDATE')
      and not has_table_privilege('authenticated',
        'public.provider_season_bootstrap_events','DELETE'),
    'immutable_certificate_ready',
      exists(select 1 from pg_catalog.pg_trigger t
        where t.tgrelid='public.provider_season_bootstrap_certificates'::regclass
          and t.tgname='provider_season_bootstrap_certificates_immutable'
          and t.tgenabled='A'),
    'immutable_events_ready',
      exists(select 1 from pg_catalog.pg_trigger t
        where t.tgrelid='public.provider_season_bootstrap_events'::regclass
          and t.tgname='provider_season_bootstrap_events_immutable'
          and t.tgenabled='A'),
    'head_guard_ready',
      exists(select 1 from pg_catalog.pg_trigger t
        where t.tgrelid='public.provider_season_bootstrap_heads'::regclass
          and t.tgname='provider_season_bootstrap_heads_write_guard'
          and t.tgenabled='A'),
    'assessment_rpc_ready',
      to_regprocedure('public.compute_provider_season_bootstrap_gate_v1(uuid)') is not null
      and to_regprocedure('public.compute_provider_season_fixture_fingerprint_v1(text,integer)') is not null,
    'certify_rpc_ready',
      to_regprocedure('public.certify_provider_season_bootstrap_v1(uuid)') is not null
      and position('provider-new-season-bootstrap' in v_certify)>0
      and position('compute_provider_season_bootstrap_hash_v1' in v_certify)>0,
    'reconcile_rpc_ready',
      to_regprocedure('public.reconcile_provider_season_bootstrap_v1(uuid,boolean)') is not null
      and position('provider-new-season-bootstrap' in v_reconcile)>0,
    'market_guard_ready',
      position('catalog' in v_assert)>0
      and exists(select 1 from pg_catalog.pg_trigger t
        where t.tgrelid='public.roster_entries'::regclass
          and t.tgname='provider_season_bootstrap_roster_guard' and t.tgenabled='A')
      and exists(select 1 from pg_catalog.pg_trigger t
        where t.tgrelid='public.auction_items'::regclass
          and t.tgname='provider_season_bootstrap_auction_item_guard' and t.tgenabled='A'),
    'calendar_guard_ready',
      position('fixtures' in v_assert)>0
      and exists(select 1 from pg_catalog.pg_trigger t
        where t.tgrelid='public.fantasy_fixtures'::regclass
          and t.tgname='provider_season_bootstrap_calendar_guard' and t.tgenabled='A'),
    'renewal_v3_ready',
      to_regprocedure('public.renew_league_season_guarded_v3(uuid,text,uuid)') is not null
      and position('reconcile_provider_season_bootstrap_v1' in v_renew)>0
      and position('renew_league_season_guarded_v3' in v_legacy)>0,
    'state_and_health_ready',
      to_regprocedure('public.get_league_season_state_v8(uuid)') is not null
      and to_regprocedure('public.get_league_management_state_v18(uuid)') is not null
      and to_regprocedure('public.get_league_provider_sync_health_v29(uuid)') is not null,
    'backfill_and_realtime_ready',
      not exists(select 1 from public.leagues league
        left join public.provider_season_bootstrap_heads head
          on head.league_id=league.id
        where league.previous_league_id is not null and head.league_id is null)
      and not exists(select 1
        from public.provider_season_bootstrap_certificates certificate
        where certificate.bootstrap_hash<>public.compute_provider_season_bootstrap_hash_v1(
          certificate.league_id,certificate.rollover_certificate_id,
          certificate.provider,certificate.season,certificate.catalog_head_id,
          certificate.catalog_generation,certificate.catalog_player_count,
          certificate.fixture_scope_certificate_id,certificate.fixture_count,
          certificate.matchday_count,certificate.fixture_team_count,
          certificate.fixture_fingerprint
        ))
      and exists(select 1 from pg_publication_tables
        where pubname='supabase_realtime' and schemaname='public'
          and tablename='provider_season_bootstrap_events')
  );
end;
$function$;
revoke all on function public.get_provider_season_bootstrap_integrity_v1()
from public,anon,authenticated;
grant execute on function public.get_provider_season_bootstrap_integrity_v1()
to service_role;

-- Validazione strutturale finale: esattamente 20 booleani true.
do $validation$
declare v_checks jsonb;
begin
  v_checks:=public.get_provider_season_bootstrap_integrity_v1();
  if (select count(*) from jsonb_each(v_checks))<>20
    or exists(select 1 from jsonb_each(v_checks) c
      where jsonb_typeof(c.value) is distinct from 'boolean'
         or c.value is distinct from 'true'::jsonb) then
    raise exception 'Validazione v0.62.30 non superata: %',v_checks;
  end if;
end;
$validation$;

commit;

select
  (public.get_provider_season_bootstrap_integrity_v1()->>'predecessor_ready')::boolean as predecessor_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'certificate_table_ready')::boolean as certificate_table_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'head_table_ready')::boolean as head_table_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'event_table_ready')::boolean as event_table_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'columns_ready')::boolean as columns_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'constraints_ready')::boolean as constraints_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'indexes_ready')::boolean as indexes_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'rls_ready')::boolean as rls_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'direct_write_blocked')::boolean as direct_write_blocked,
  (public.get_provider_season_bootstrap_integrity_v1()->>'immutable_certificate_ready')::boolean as immutable_certificate_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'immutable_events_ready')::boolean as immutable_events_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'head_guard_ready')::boolean as head_guard_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'assessment_rpc_ready')::boolean as assessment_rpc_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'certify_rpc_ready')::boolean as certify_rpc_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'reconcile_rpc_ready')::boolean as reconcile_rpc_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'market_guard_ready')::boolean as market_guard_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'calendar_guard_ready')::boolean as calendar_guard_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'renewal_v3_ready')::boolean as renewal_v3_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'state_and_health_ready')::boolean as state_and_health_ready,
  (public.get_provider_season_bootstrap_integrity_v1()->>'backfill_and_realtime_ready')::boolean as backfill_and_realtime_ready;
